### ISSUE TITLE
Medium Defense Potion and other items not consuming from recent update

### ISSUE THREAD

**Issue by jTynne** [HerculesWS/Hercules#1005]
https://github.com/HerculesWS/Hercules/commit/d79a996b1ecfe2dfdfe0069927f3aa0fbe584c8f

From that commit, it looks like item ID 14611 and a few other items aren't consuming when used in-game. Freshly updated using that commit and the items aren't consuming, just applying the script effects and remaining in the player's inventory.

**Comment by jTynne** [comment]
Also, when using @iteminfo / @ii in-game (for instance, @ii 501) the NPC Buy / Sell / Weight are showing up twice in the chat log.

**Comment by Jedzkie** [comment]
report #1 confirmed.

**Comment by Jedzkie** [comment]
@jTynne number 2 report, i can reproduce it.
