### ISSUE TITLE
Relax

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#1014]
The skill Relax is not working according to the aegis, the icone is disappearing in about 10 seconds what should be up to the player to get up.

source: http://herc.ws/board/tracker/issue-8627-relax/?gopid=24976#entry24976

**Comment by Jedzkie** [comment]
@xBeret please give us info how to reproduce this. Thanks!

**Comment by AnisotropicDefixation** [comment]
The extra regen doesn't work when overweight either when it should.

**Comment by Jedzkie** [comment]
Oh, i see.

Sits the user and triples the HP Recovery rate while the user has no overweight, otherwise this skill allows HP Recovery at regular rate
