### ISSUE TITLE
showevent icon on the mini-map

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#1015]
One of the icons of the showevent command that can be placed on the mini-map is missing

As the officer are 4 colors, that they are:
Yellow
Orange
Green
Purple
To find the yellow icon search data.grf by quest_0.bmp

enum aegis:

```
enum enumQTYPE{
    QTYPE_YELLOW = 0x0,
    QTYPE_ORANG = 0x1,
    QTYPE_GREEN = 0x2,
    QTYPE_PURPLE = 0x3
};
```

Bug Track post:http://herc.ws/board/tracker/issue-8113-showevent-icon-on-the-mini-map/

**Comment by Jedzkie** [comment]
I notice this also, using 2015-05-13

**Comment by Jedzkie** [comment]
@xBeret maybe its a questinfo bug, coz when i create a novice in renewal, i can see the icon on my mini map.

**Comment by Kenpachi2k13** [comment]
The colors have changed at some point.
When passing 0 (yellow) as color code to the packet, no icon appears, but when passing 1 (orange), a yellow icon appears. Green and purple work as intended.
So that's nothing we have a bearing on.
`close();`
