### ISSUE TITLE
Slot premium

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#1017]
Premium Slots are not working as the aegis, being created several slots, to reproduce the problem do the following.

Compile the server with 9 slots, then change the value of character_slots to 3.
The game in the window to select character will appear that there are 15 slots, the correct would be releasing 3 slots and 6 block slots and it's not happening.

This problem occurs because the package is adding the same amount of premium slots for the slots Billing. The slots Billings are another system that is not part of the premium

bug track post: http://herc.ws/board/tracker/issue-8060-slot-premium/

**Comment by Jedzkie** [comment]
@xBeret where i can set the character_slots?

**Comment by xBeret** [comment]
@Jedzkie table login.

https://github.com/HerculesWS/Hercules/blob/master/sql-files/main.sql#L572

**Comment by hemagx** [comment]
sure about this bug ? o-o
while i was messing with character server i saw it would never send more than the hardcoded define in source.
and if it send more it will bug when create character in those i believe. :x:

**Comment by Jedzkie** [comment]
yes @hemagx, i confirmed it now.

**Comment by xBeret** [comment]
@hemagx 

I believe that the problem is here see https://github.com/HerculesWS/Hercules/blob/master/src/char/char.c#L2120

bits packet 0x82d

	/* this+0x4 */ unsigned char NormalSlotNum
	/* this+0x5 */ unsigned char PremiumSlotNum
	/* this+0x6 */ unsigned char BillingSlotNum
	/* this+0x7 */ unsigned char ProducibleSlotNum
	/* this+0x8 */ unsigned char ValidSlotNum

Hercules is using the same variable for slots Billing

**Comment by hemagx** [comment]
possible, assign to self.

**Comment by hemagx** [comment]
okay. wth happened here ? i got 18 slot with 3 in login table.
this really require some investigate

**Comment by hemagx** [comment]
okay results for now.
1- we had some miss understood for packet values
2- the packet not fully sent i guess Ind thought it's fine, but seems like we should supply the whole packet if we want it to work ?

@MishimaHaruna wanna join in this fun mess ? :dancer:
