### ISSUE TITLE
Abracadabra

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1018]
Hercules: Whenever I use the skill Abracadabra, when a skill with a requirement appears (Body Relocation, Ankle Snare etc.), I can still cast it even though I don't have the requirements.

Official: It should be skill has failed because I don't have the requirements

Bug Tracker: http://herc.ws/board/tracker/issue-7729-abracadabra/

**Comment by Kenpachi2k13** [comment]
Fixed in https://github.com/HerculesWS/Hercules/pull/2616/commits/1098b588625774ca2cf4e05527b00fd4d0187919.
`close();`
