### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by admkakaroto** [HerculesWS/Hercules#1020]
Hello good afternoon, I can not compile the latest version of the Linux emulator, following image from mistakes:

http://i.imgur.com/qFqQq8k.png

**Comment by MishimaHaruna** [comment]
Could you try to re-run the  `./configure` script, and check if it fixes the issue?

**Comment by admkakaroto** [comment]
Remade again as follows:

First: http://i.imgur.com/ytjonza.png

After: http://i.imgur.com/fOYX1ly.png

I cleared my previous build to ensure that there were no problems: http://i.imgur.com/Ymy00LG.png

Result: http://i.imgur.com/lfkDcfK.png

**Comment by Smit1237** [comment]
Which os?

2015-12-26 1:23 GMT+03:00 João Filho Matias Silva <notifications@github.com>
:

**Comment by dastgir** [comment]
Probably missing libpcre
Ubuntu/Debian:
apt-get install libpcre3 libpcre3-devel

**Comment by admkakaroto** [comment]
Solve as follows:

yum install libpcre* pcre* -y

Tnks: @dastgir , @Smit1237  and @MishimaHaruna .

**Comment by Smit1237** [comment]
No problem :) I did nothing :)
Next time just use yum whatprovides pcre for example :)

2015-12-26 22:09 GMT+03:00 João Filho Matias Silva <notifications@github.com

**Comment by hemagx** [comment]
Closes as it got solved by user.
