### ISSUE TITLE
NC_SELFDESTRUCTION Damage overflow (Critical)

### ISSUE THREAD

**Issue by tsan79** [HerculesWS/Hercules#1028]
Hercules Version: (Most likely the latest)

Apologize if this was reported previously, but I'd like to point out this issue.
There is an overflow of damage with self destruction when your HP is lower than the total defense of your enemy. This cause you to do do millions of damage.
Here's a little snapshot of what a friend of mine sent me:
![Damage] (http://i5.photobucket.com/albums/y163/ellakitten/selfdestruct_zpstrtf0g17.jpg)

Unfortunately, I cannot give proper proof as my PC is in service but I think it should be caused by this part on line 4078.
[Reference](https://github.com/HerculesWS/Hercules/blob/master/src/map/battle.c#L4078)
````
md.damage += status_get_hp(src) - totaldef;
````
It appears that it prioritise `status_get_hp(src) - totaldef` before adding `md.damage`
So if your HP is lower than your total def, it goes negative, and things break.

I suggest we separate the two factors such as below:
````
md.damage += status_get_hp(src);
md.damage -= totaldef;
````

In addition I have a question regarding line 4076 - which checks for NC_MAINFRAME, it checks for it or return 10. Meanwhile NC_MAINFRAME max level is 4. 
[Reference](https://github.com/HerculesWS/Hercules/blob/master/src/map/battle.c#L4076)
````
md.damage = ( (sd?pc->checkskill(sd,NC_MAINFRAME):10) + 8 ) * ( skill_lv + 1 ) * ( status_get_sp(src) + sstatus->vit );
			RE_LVL_MDMOD(100);
````
shouldn't it be 0? and thus if it doesn't have it, you don't get the bonus. 
If anyone could enlighten me with the correct answers it would be awesome!

Thanks for your time,
-SH

**Comment by AnnieRuru** [comment]
https://github.com/HerculesWS/Hercules/issues/959
