### ISSUE TITLE
[Eden Quest] Wrong equipments given by NPC

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#1033]
Line 2141 should be "Para_Team_Hat"
Line 2142 should be "Para_Team_Manteau"

That's equipment given to player if they complete Level 40 eden training quest
the one Herc's give is for Level 60 eden training quest

Files:
\npc\re\quests\eden\eden_quests.txt

**Comment by dastgir** [comment]
Thanks for reporting.

**Comment by zackdreaver** [comment]
np
