### ISSUE TITLE
RENEWAL EXP

### ISSUE THREAD

**Issue by Desground** [HerculesWS/Hercules#1051]
RENEWAL_EXP not working
experience always give 100% at any level.
revision https://github.com/HerculesWS/Hercules/commit/e95c473c694f4fccb40584f3e6a00323f91e36ee

**Comment by jTynne** [comment]
Confirmed; I literally just posted about this on the Herc forum in source support forum, and came here to see if anyone else had opened an issue, otherwise I would have opened one myself.

http://herc.ws/board/topic/11606-is-renewal-exp-working/#entry68209

**Comment by AnnieRuru** [comment]
erm ... confirm ... and its silly ...

RC_Boss is 11
RC_NonBoss is 12
https://github.com/HerculesWS/Hercules/blob/master/db/const.txt#L676-L677

yet, in our repo, it reads 10 & 11 ??
https://github.com/HerculesWS/Hercules/blob/master/db/re/level_penalty.txt

**Comment by dastgir** [comment]
Seems my mistake https://github.com/HerculesWS/Hercules/commit/46311fe27870f30d287e32703c5ad8cb8a829fa2
I didn't knew this file uses race to identify difference :x

**Comment by dastgir** [comment]
Closing with d83cae0fbd1bed4a10dc2976baf797c297018574
