### ISSUE TITLE
Champion SP bug

### ISSUE THREAD

**Issue by ermanherman** [HerculesWS/Hercules#1054]
Champion SP if level 99 lower then level 98.

On level 99/70 with no skill and default stat (no stat use) max sp is = 552
On level 98/70 with no skill and default stat (no stat use) max sp is = 633

there huge diffrent there.

Git revision 'c033d4f7498e9b136b4f586b521365f835073171' (src) / 
'c033d4f7498e9b136b4f586b521365f835073171' (scripts)

**Comment by dastgir** [comment]
c033d4f7498e9b136b4f586b521365f835073171 doesn't exist in Hercules.
with new hercules, this is the result I got
```

**Comment by dastgir** [comment]
Tried in game:
Here's the Result:
Level 98: (SP 633)
http://imgur.com/N0slTeO
Level 99: (SP 640)
http://imgur.com/FDT12Hu

so maybe update your hercules?
