### ISSUE TITLE
Renewal Base EXP (separate from level penalty file)

### ISSUE THREAD

**Issue by jTynne** [HerculesWS/Hercules#1060]
Currently Base EXP is only awarding half of what it should / half of what it displays in the monsterinfo/mi command. Job EXP is not affected and is awarding the correct amount.

This is a separate issue from the level penalty file, which needs a simple fix (increase the race values by +1).

**Comment by dastgir** [comment]
It does gives correct one as mentioned
if you do @mi MONSTER with atcommand_mobinfo_type as 1, it would show you exact amount that you will receive.

**Comment by dastgir** [comment]
Closing this, as it started working( http://herc.ws/board/topic/11606-is-renewal-exp-working/ )
