### ISSUE TITLE
PvP Msg in Aegis

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#1063]
in Aegis, when entering pvp maps, you will see in your chat box this message 'Nothing found in the selected map.' Line# 1773

**Comment by kyeme** [comment]
Did you test it on kRO? or rwc server

**Comment by Jedzkie** [comment]
RWC

**Comment by hemagx** [comment]
unless there's good reason to emulate a behavior then it will not get emulated.
we're not Aegis clone.

**Comment by Jedzkie** [comment]
This Issue is now closed.
