### ISSUE TITLE
Orc Archer Bow Weapon Level

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1065]
Orc Archer Bow should be a level 3 weapon, but in both pre-re and renewal the ID 1734 version is defined as a level 4 weapon.

The ID 18115 version is already correctly defined as level 3 weapon.

Credits to @Playtester

**Comment by dastgir** [comment]
@Jedzkie

**Comment by Jedzkie** [comment]
In RENEWAL it is set already to 3 but in PRE-RENEWAL its set to 4.

**Comment by Jedzkie** [comment]
Fixed, Thanks!
