### ISSUE TITLE
map server crash if using non-existent script command

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#1073]
VERY NEW BUG https://github.com/HerculesWS/Hercules/commit/d5199cee806fb9f18987dea0c3a20a2d381927ca
after I update to this revision,
```
prontera,155,185,5	script	kjkjsdfksdjf	1_F_MARIA,{
	test .@asdf;
	end;
}
```
just as simple as this can crash map-server
I can't debug custom scripts anymore if it keep crashing
I have to revert that commit

**Comment by 4144** [comment]
Please update atleast to 0772dd0f128aaeb46cb00ccf9ee00721bab90144
because on d5199ce on hooks update and it will may crash server in different cases

**Comment by AnnieRuru** [comment]
yup just pull latest one
no more crash
