### ISSUE TITLE
Map Crash

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#1074]
Herc Version: https://github.com/HerculesWS/Hercules/commit/e3da170660e8c52ec5657c086057085ef20e382f
Mode: `Renewal`

I summon Bangungot (ID#2317), and cast Lord Of Vermillion skill, it shows error `[Error]: map_addblock: bl-prev != NULL` then map-server crash.

**Comment by MishimaHaruna** [comment]
And this appears to be my fault :x 

Introduced in e3eac134b1607cfe78331e298aaa20b260662571 (`1` instead of `count` in the `CREATE` call in `skill_initunitgroup`).
