### ISSUE TITLE
Logging into my character, map server crashes.

### ISSUE THREAD

**Issue by jTynne** [HerculesWS/Hercules#1075]
Current version: https://github.com/HerculesWS/Hercules/commit/e3da170660e8c52ec5657c086057085ef20e382f
Renewal

The following error displays in the console at the time of the crash:
[Error]: map_addblock: bl-prev != NULL

Will collect more data as I continue trying to figure out why it's doing what it's doing.

**Comment by MishimaHaruna** [comment]
Same as #1074
