### ISSUE TITLE
Character position de-synchronization when disguised

### ISSUE THREAD

**Issue by RouganStriker** [HerculesWS/Hercules#1078]
When disguised if the user starts walking away their client shows the player's sprite getting left behind. Users on other client do not see this issue. Looks identical to this [bug](http://herc.ws/board/tracker/issue-7502-disguise-bug).

Client: 2014-02-05 Ragexe
PACKETVER: 20140205
Source: Fork of latest Hercules master branch[2af2132] containing minimal source edits.
Gif of bug: http://i.imgur.com/J0rYXHQ.gifv

**Comment by Lemongrass3110** [comment]
We also have that one here rathena/rathena#856 and fixed it in rathena/rathena@2f471a1 feel free to try that fix and merge it.

**Comment by RouganStriker** [comment]
Thanks @Lemongrass3110 but it didn't work.

What does work is commenting out the following line in the clif_move function. I have no idea why that fixes it and why the disguise command sets bl->id to be negative in the first place.

```
    if (disguised(bl)) {
        //WBUFL(buf,2)=-bl->id;
        clif->send(buf, packet_len(0x86), bl, SELF);
    }
```

**Comment by Lemongrass3110** [comment]
This might be related to this commit, because there all bl->ids get sent plain, without respecting their disguise state.
https://github.com/HerculesWS/Hercules/commit/eb0d0dc677e1d3e584de9202d3140fe6fb6db722

**Comment by vBrenth** [comment]
@MishimaHaruna Please fix this :'(
