### ISSUE TITLE
eden quest can't give job exp to super novice after job level 70

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#1082]
I was playing on my friends server as a super novice, 
and when my super novice gain exp until level 99/71,
this eden quest only gives me 1 job exp
https://drive.google.com/file/d/0B2BM920mmHQgV0lNREV5akl6WUE/view

super novice has max job level at 99
https://github.com/HerculesWS/Hercules/blob/master/db/re/exp.txt#L59
and when I read the script, found out, it doesn't support giving exp after job level 70
https://github.com/HerculesWS/Hercules/blob/master/npc/re/quests/eden/91-99.txt#L213

I wonder is this IRO official bug ? or is this intended ?

**Comment by dastgir** [comment]
```
I wonder is this IRO official bug ?
```
Yes, we might have to change it the condition to >=
