### ISSUE TITLE
eden quest should have 1 day delay on level11-25 , but it is currently repeatable

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#1084]
On Level 11-25 missions, these quest should have a 1 day delay
this is mentioned in the script, and also client side translation

but what really happened was,
**I can redo the grasshopper mission over and over again**
( kill 10 rocker and collect 10 grasshopper leg )
I tested on my own test server and I really reproduce it, along with this error message
`[Error]: quest_add: Character 150000 already has quest 11126.`

**Comment by Jedzkie** [comment]
@AnnieRuru any official information about this?

**Comment by AnnieRuru** [comment]
I don't play iro or having aegis
all I know, is that it print an error message on the map-server
that is definitely script bugs

**Comment by dastgir** [comment]
How you reproduced this @AnnieRuru ?

**Comment by dastgir** [comment]
Fixed c7c956f .
Thanks for reporting
