### ISSUE TITLE
Eden quest  board (Lv 91-99) cannot give job exp to any job lower than 50

### ISSUE THREAD

**Issue by tsan79** [HerculesWS/Hercules#1085]
How to reproduce - Consider the following:
At level between 91 ~ 99 you did a quest board
After completing the hunting, you proceed to the job change to any class e.g. from acolyte 91/50 to priest 91/1
If you return the quest board, and hand in your quest, you won't get any job exp.
as on L185 it says: ```` if (JobLevel > 50 && JobLevel < 56) .@jexp = 67000; ````

**Comment by dastgir** [comment]
Aegis have it like this, probably they didn't thought like this.
Should we give the lowest exp to JobLevel <= 50 and highest one to >= 69

I need opinion
@Jedzkie @MishimaHaruna @hemagx

**Comment by Jedzkie** [comment]
+1 @dastgir

**Comment by MishimaHaruna** [comment]
I'd say that's a sane approach, yes. 67000 is a lot for level 1, though.

**Comment by tsan79** [comment]
@MishimaHaruna If you follow the job exp table, 67,000 gets you to job level 5 ish, that's not too bad
