### ISSUE TITLE
Renewal Spear Quicken

### ISSUE THREAD

**Issue by tsan79** [HerculesWS/Hercules#1094]
Spear Quicken in Renewal meant to add 7 flat aspd, but I think it might be using the prerenewal version. as below it's only giving 5 bonus aspd.
![Proof](https://i.gyazo.com/7ebb6a72d1aaf07b413511f8805461a5.gif)

**Comment by dastgir** [comment]
@Jedzkie can confirm?

**Comment by Jedzkie** [comment]
@dastgir @tsan79 Not only this skill, but also `Two Hand Quicken` `One Hand Quicken` `Mercenary Quicken` `Adrenaline Rush` `Fleet (Homun Skill)`

**Comment by malufett** [comment]
working as intended...
Hercules renewal aspd is stable and has accurate data..
only missing data is about new items and skills aspd bonuses...
the said bonuses is not to be added to the aspd..its supply to the formula..

**Comment by Jedzkie** [comment]
@malufett master :3 <3 <3 <3

**Comment by tsan79** [comment]
So I assume this is one of those gravity derpy description? Just for clarification does that mean it add aspd = x factor of bonus  from other things * 7? 

P.s Thank you for confirming, @jedzkie and Master @malufett :3

**Comment by malufett** [comment]
@tsan79 
yes..well gravity is very consistent about that thing..hahahahaha...
@Jedzkie <3 <3<3

**Comment by Jedzkie** [comment]
@malufett i emailed you in your gmail, and also pm'ed you in facebook, i hope you can help me. thanks!
