### ISSUE TITLE
Strange behaviour of whisper function. Looks like typo.

### ISSUE THREAD

**Issue by Smit1237** [HerculesWS/Hercules#1096]
![error](https://cloud.githubusercontent.com/assets/1930952/12273484/1a9c313c-b977-11e5-808c-8a70523dc710.png)
Herc revision: aad6eaea82053f629cbbe204aa83db5fd4b557a4

**Comment by Rytech2** [comment]
What client did you use?

**Comment by Smit1237** [comment]
2014-02-05eRagexe

**Comment by Rytech2** [comment]
Wonder if it has something to do with a change in how chat messages are handled recently. This is a weird one.

**Comment by Rytech2** [comment]
Almost forgot. What do you have the PACKETVER set to in the mmo.h file and did you compile?

**Comment by kyeme** [comment]
I can confirm on 2015-05-13client

**Comment by dastgir** [comment]
I wonder if it's client side mistake

**Comment by Smit1237** [comment]
#ifndef PACKETVER
        #define PACKETVER 20140205
#endif // PACKETVER

**Comment by jTynne** [comment]
Happens in the May 13th 2015 client as well.

**Comment by dastgir** [comment]
https://github.com/MStr3am/NEMO/pull/112 , its client side, closing this
