### ISSUE TITLE
Potion/healing sound effects missing from effect, but only via itemheal script?

### ISSUE THREAD

**Issue by FreddieFatso** [HerculesWS/Hercules#1099]
See also: [Thread on the forums] (http://herc.ws/board/topic/7443-potion-animation-and-sound-effects/)

Healing item sound effects ranging from 204 to 211 in effect_list.txt seem to only display their graphical effect without any sound for me. That basically means

NOT WORKING are
Red Potion
Red Herb
Condensed Red Potion
...
White Potion
Blue Potion
Yggdrasilberry
Potato
Apple
etc.

BUT
Meat
Honey
Aloe/Hinalle Leaflet
Candy (Cane) 
seem to work perfectly fine, with sound and all.

Applies to both itemheal and percentheal. The client can display the effects if they're sent via @effect 204, 22 and also if the itemscript is changed to misceffect 204 in item_db.txt, such as
Script: <" misceffect 204; percentheal rand(45,65),0; "> for the Red Potion script.

Client: 2012-04-10 (PACKETVER set accordingly)
Sadly I don't have any other clients that work to test it with currently.
Same issue with a 2013 Hercules version, so it can't be anything recent.

If it isn't related to the server at all, I would like to know so I can redirect my search for the cause. But since the client can and does display the effect itself, I am clueless really.

PS: How is the effect triggered by an itemheal script different from the effect sent by @effect? One works and the other doesn't...
I was trying to locate it in the src folders, but I didn't find what I was looking for and am therefore unable to compare them.

**Comment by Jedzkie** [comment]
tested in kRO, maybe they broke the sound of some effects in Newer clients. this is only client side.
