### ISSUE TITLE
Acid Demonstration Damage

### ISSUE THREAD

**Issue by iubantot** [HerculesWS/Hercules#1101]
Why is Acid Demonstration's damage not increased by range damage modifiers like archer skeleton card.? using latest herc.

**Comment by Paoly28** [comment]
![screenbestro008](https://cloud.githubusercontent.com/assets/8035101/12370689/5c6b0558-bc55-11e5-8496-56cacbaf8496.jpg)
![screenbestro005](https://cloud.githubusercontent.com/assets/8035101/12370688/5c5b5eb4-bc55-11e5-967f-36bcc60f9077.jpg)

it does. =)

used +0 main gauche for minimal weapon atk so there's little variance also used 4 AS Card to easily see if Ranged Modifiers work /gawi
