### ISSUE TITLE
Soul Destroyer Range

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#1104]
Reference:
https://github.com/rathena/rathena/issues/905
kRO Renewal Client's = \data\luafiles514\lua files\skillinfoz\skillinfolist.lub

```
    [SKID.ASC_BREAKER] = {
        "ASC_BREAKER",
        SkillName = "Soul Destroyer",
        MaxLv = 10,
        SpAmount = { 20, 20, 20, 20, 20, 30, 30, 30, 30, 30 },
        bSeperateLv = true,
        AttackRange = { 9, 9, 9, 9, 9, 9, 9, 9, 9, 9 },
        _NeedSkillList = {
            { SKID.TF_DOUBLE, 5 },
            { SKID.TF_POISON, 5 },
            { SKID.AS_CLOAKING, 3 },
            { SKID.AS_ENCHANTPOISON, 6 }
        }
    },
```

It's says the range maxed at 9 cells,
but in Herc is 7:

```
379,7,6,1,-1,0x40,0,10,1,yes,0,0,0,misc,0,
```

**Comment by Jedzkie** [comment]
@zackdreaver please confirm also in pre-re

**Comment by hemagx** [comment]
i believe the client uses circles and server-side uses squares ?
can you test if there's actual issue?

**Comment by zackdreaver** [comment]
@Jedzkie 
I don't remember how long in pre-renewal, it's been 6 yers
and i dont have aegis server

**Comment by Playtester** [comment]
I tested on a pre-renewal Aegis server to confirm it's 9 range on pre-renewal, so I'm pretty sure about it.

Also yes, it uses a circle range for players.

**Comment by Michieru** [comment]
Test on renewal and Pre-renewal, both are 10 cell

**Comment by zackdreaver** [comment]
Michi, can't we just stick with 9 cells as stated in skillinfos?
thank you for testing it.

**Comment by Playtester** [comment]
Maybe Hercules has a different implementation for ranges, but rAthena uses Aegis ranges.

Range = 9 means "9 cells in between you and the target if you stand on a linear line"

**Comment by Michieru** [comment]
Range is 10 cells between you and the target as I show on aegis screen.

**Comment by Playtester** [comment]
It's hard to see but that looks like 9 cells and not 10 cells.

**Comment by AnisotropicDefixation** [comment]
It does look like 10 cells to me.

**Comment by Playtester** [comment]
![1452959890-screenmichiro000_cells](https://cloud.githubusercontent.com/assets/3785983/12376558/d90f4880-bcfa-11e5-8cbe-2ae254afbab2.jpg)

9 cells at most.

**Comment by Jedzkie** [comment]
@Playtester does the character position include in the cell count?

**Comment by Playtester** [comment]
Not on Aegis and rAthena for PC ranges. Not sure about Herc.

As said 9 range = 9 cells between caster and target.
