### ISSUE TITLE
Visual Effect Costumes

### ISSUE THREAD

**Issue by tsan79** [HerculesWS/Hercules#1114]
Despite having the setting of "cannot be reset by clearance", 
Visual Effect Costumes aka SC Costumes can be removed by Clearance
![proof](https://i.gyazo.com/0436d3eb2e47329d78923ed89d2733be.gif)

Also tested with dispell, it did not remove the status.
Reference: https://github.com/HerculesWS/Hercules/blob/master/db/sc_config.txt#L476

**Comment by kyeme** [comment]
@Jedzkie

**Comment by Jedzkie** [comment]
@malufett
