### ISSUE TITLE
[Renewal] Nightmare Glastheim and Nightmare Clock Tower

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#1116]
I wonder if herc can add "Nightmare Glastheim" (not Old Glastheim) and "Nightmare Clock Tower"?

[Nightmare Glastheim]
The NPC that teleport you, is present here:
https://code.google.com/p/idathena/source/browse/trunk/npc/re/instances/OldGlastHeim.txt

Maps and mobs info:
http://www.divine-pride.net/database/map/gl_chyard_
http://www.divine-pride.net/database/map/gl_cas02_

[Nightmare Clock Tower]
general info:
http://www.playragnarok.com/news/updatedetail.aspx?id=269

Mobs:
http://www.divine-pride.net/database/map/c_tower2_
http://www.divine-pride.net/database/map/c_tower3_
https://code.google.com/p/idathena/source/browse/trunk/npc/re/mobs/dungeons/c_tower.txt

iRO has impelemented them i believe.

**Comment by Ridley8819** [comment]
Added in 114767c and 88c5a47
