### ISSUE TITLE
CASH FOODS

### ISSUE THREAD

**Issue by iubantot** [HerculesWS/Hercules#1119]
cash foods does not allow you to use all stat cash foods at the same time. 
for example  i use STR Cash food , i have to wait for the STR cash food's time before i can use another. 

using latest rev

**Comment by Jedzkie** [comment]
No, in official servers theres a 1 min dely to use other cash foods.

**Comment by hemagx** [comment]
@Jedzkie he means stack them probably, and yet i don't think this is official too, but i will check as soon as i have some free time :)

**Comment by Jedzkie** [comment]
@hemagx I see, i can test it now in kRO

**Comment by hemagx** [comment]
@Jedzkie ok make sure it's cash and non-cash..

**Comment by Jedzkie** [comment]
@iubantot tested in Aegis Server, i can still use STR Cash Food even i still have the Food effect.

@hemagx i don't have cash item in kRO, its only +5 xD not +10

**Comment by hemagx** [comment]
Will test myself this afternoon
