### ISSUE TITLE
Party item share

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#1120]
Test mode: Pre-renewal
Client: 2010-04-20aRagexeRE
hash: 0ed2d09e9aa88af01698707fd701363bdbd92b4b

If I'm not mistaken (pre-renewal and renewal),
when party item share is set to "shared", only member in "same screen" are affected by this setting,
but in herc, even you're not in same screen, you still get the items from other member that pick the item.

Has this been changed in kRO, so herc use this mechanic?

and one more thing,
so does with the "Kill count", but I haven't tested it in herc.

Thanks

**Comment by Playtester** [comment]
I think for item share it has always been like this. As long as you're on the same map you get the item.

Kill count on the other hand only counts if you are on-screen on officials as far as I remember.

**Comment by zackdreaver** [comment]
I'm used to played "Turn-in" event everyday in iRO,
so it was based on my experiences.

And if the "right" behavior is like this,
people in iRO will get raged by this mechanic (they hate leecher).

**Comment by vBrenth** [comment]
Its always like this, its used be a way of scamming people in official servers.

**Comment by Kenpachi2k13** [comment]
Question was answered. At least it seems like no one is interested in this anymore.
`close();`
