### ISSUE TITLE
Map Server Crash Randomly when Log In

### ISSUE THREAD

**Issue by RandonsRO** [HerculesWS/Hercules#1121]
I don't know what to do....
When someone logs in (but not anyone), the map-server crashes:

GDB->

Program received signal SIGSEGV, Segmentation fault.
skill_unit_timer_sub (key=..., data=0x911be00, ap=0xbffff480 "\a") at skill.c:16650
16650           if( !group->state.guildaura && (DIFF_TICK(tick,group->tick) >= group->limit || DIFF_TICK(tick,group->tick) >= su->limit) ) {
(gdb) bt
#0  skill_unit_timer_sub (key=..., data=0x911be00, ap=0xbffff480 "\a") at skill.c:16650
#1  0x08235fb2 in db_obj_vforeach (self=0x868ea50, func=0x81b6930 <skill_unit_timer_sub>, args=0xbffff478 "\203\365\260\071\a") at db.c:2063
#2  0x08235853 in db_obj_foreach (self=0x868ea50, func=0x81b6930 <skill_unit_timer_sub>) at db.c:2109
#3  0x081b391e in skill_unit_timer (tid=11, tick=31032669571, id=0, data=0) at skill.c:16853
#4  0x08241e06 in do_timer (tick=31032669600) at timer.c:430
#5  0x08245d1c in main (argc=1, argv=0xbffff5f4) at core.c:461
(gdb) bt full
#0  skill_unit_timer_sub (key=..., data=0x911be00, ap=0xbffff480 "\a") at skill.c:16650
        su = 0xb30ee804
        group = 0x333a632e
        tick = 31032669571
        dissonance = <value optimized out>
        bl = 0xb30ee804
#1  0x08235fb2 in db_obj_vforeach (self=0x868ea50, func=0x81b6930 <skill_unit_timer_sub>, args=0xbffff478 "\203\365\260\071\a") at db.c:2063
        argscopy = 0xbffff478 "\203\365\260\071\a"
        db = 0x868ea50
        i = <value optimized out>
        sum = 0
        node = 0x911bdec
        parent = <value optimized out>
#2  0x08235853 in db_obj_foreach (self=0x868ea50, func=0x81b6930 <skill_unit_timer_sub>) at db.c:2109
        args = 0xbffff478 "\203\365\260\071\a"
#3  0x081b391e in skill_unit_timer (tid=11, tick=31032669571, id=0, data=0) at skill.c:16853
No locals.
#4  0x08241e06 in do_timer (tick=31032669600) at timer.c:430
        tid = 11
        diff = -29
        __FUNCTION__ = "do_timer"
#5  0x08245d1c in main (argc=1, argv=0xbffff5f4) at core.c:461
        next = <value optimized out>
        retval = 0

**Comment by dastgir** [comment]
Which hercules revision are you using?
the line
```
if( !group->state.guildaura && (DIFF_TICK(tick,group->tick) >= group->limit || DIFF_TICK(tick,group->tick) >= su->limit) ) {
```
appears to be in 16526, but in yours it shows 16650. maybe some of your mods might be doing it?
