### ISSUE TITLE
Boss scale and HP bar Bug!!

### ISSUE THREAD

**Issue by rotloso** [HerculesWS/Hercules#1122]
Hi , may i know how to fixed boss scale and HP bar.

Boss in Hall of the Abyss scale bug and health bar bug may i know how to fixed

Topic : http://herc.ws/board/topic/11687-boss-scale-bug/

**Comment by AnisotropicDefixation** [comment]
https://github.com/HerculesWS/Hercules/commit/eb0d0dc677e1d3e584de9202d3140fe6fb6db722

This commits needs MD_BOSS exceptions for all blocks handling display and update of HP bars.

**Comment by dastgir** [comment]
About HP, we will be implementing additional config for it.

**Comment by Kenpachi2k13** [comment]
Works fine now. Don't know when this was fixed.
Client: `20190220`
Hercules: https://github.com/HerculesWS/Hercules/commit/c03722679a01e5f181c2138565e95a6b0981a124

`close();`
