### ISSUE TITLE
Compile Error in Clean Debian 8.1 and 7

### ISSUE THREAD

**Issue by inhyositsu** [HerculesWS/Hercules#1127]
I compiled the latest Hercules on Debian and it occur an error.
But It's no problem when compiling on Windows.

> obj_sql/HPMmap.o: In function `HPM_shared_symbols':
/root/Hercules-master/src/map/../common/HPMSymbols.inc.h:401: undefined reference to `npc_chat'
/root/Hercules-master/src/map/../common/HPMSymbols.inc.h:422: undefined reference to `libpcre'
collect2: error: ld returned 1 exit status
Makefile:117: recipe for target '../../map-server' failed
make[1]: *** [../../map-server] Error 1
make[1]: Leaving directory '/root/Hercules-master/src/map'
Makefile:120: recipe for target 'map_sql' failed
make: *** [map_sql] Error 2

**Comment by hemagx** [comment]
please make sure to install libpcre it's a must now.
thank you

**Comment by 4144** [comment]
will be fixed in https://github.com/HerculesWS/Hercules/pull/1108
