### ISSUE TITLE
Can't walk into a FAKE_NPC or HIDDEN_WARP_NPC

### ISSUE THREAD

**Issue by vykimo** [HerculesWS/Hercules#1135]
When I click on a case which a HIDDEN_WARP_NPC is present (invisible) the player search for the closer case near the invisible npc. It's impossible to stay on a case where a npc take place.
I think it's a condition and it's correct for normal npc.
But It's a bit stupid for theses two kind of npc, in this case what's the advantage to make a npc invisible?

If it's official (who people succeded to test it?), make at least player can stay on a case where FAKE_NPC is supposed to stay.

**Comment by dastgir** [comment]
It's stupid for FAKE_NPC, I Agree..
Waiting for @hemagx or @MishimaHaruna reply to this

**Comment by 4144** [comment]
I think for this issue, need skip invisible npc from count in function map_count_oncell

**Comment by vykimo** [comment]
Any fix?

**Comment by vykimo** [comment]
up

**Comment by Emistry** [comment]
Infinite loop for walk
![asdasd](https://cloud.githubusercontent.com/assets/1075099/19020547/903b9784-88de-11e6-93ef-0dd59cf8e0a5.gif)

I think should add normal but "Hidden" NPC into the list to skip too.

**Comment by dhaisuke** [comment]
Hi Guys, 

is there a workaround for this? to walk in to the hidde npc?

**Comment by vykimo** [comment]
Don't count hide npc in map_count_oncell

**Comment by dhaisuke** [comment]
How i can do that? is the **map_count_oncell**  somewhere on the conf file?

**Comment by MishimaHaruna** [comment]
@dastgir can you have a look at the commit I just referenced? It's something I did for my own custom purposes (without Hercules in mind since I'm not sure whether it's a wanted official behavior or not), but if it resolves this issue and introduces an acceptable behavior, it's a good idea to push it here.
