### ISSUE TITLE
Guild Aura bug on "sc_end SC_ALL;"

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1147]
When the Guild Leader uses the "sc_end SC_ALL;" script on a certain cell or point he/she can then have the Guild Aura Effect whenever he/she passes to that certain cell or point.

Video:
https://youtu.be/ZIwp2nKVh9Y

**Comment by kyeme** [comment]
@MishimaHaruna

**Comment by WillTheDoggy** [comment]
Can confirm. 

Also works for resetter NPCs. 

Please test with a lot more skills with aura effects. Maybe songs?
