### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by vBrenth** [HerculesWS/Hercules#1152]
5>d:\desktop\hercws\src\map\mob.c(3640): warning C4244: 'function' : conversion from 'int64' to 'double', possible loss of data
5>d:\desktop\hercws\src\map\mob.c(3640): warning C4244: '=' : conversion from 'double' to 'int64', possible loss of data

Fresh herc.

**Comment by vBrenth** [comment]
1>D:\Desktop\HercWS\src\map/npc.h(30): fatal error C1083: Cannot open include file: 'pcre.h': No such file or directory

**Comment by dastgir** [comment]
Using VS2015?

**Comment by MishimaHaruna** [comment]
I can reproduce the first issue (the warning) on VS2010 and VS2015. I can't reproduce the second one (the error) in either.

**Comment by vBrenth** [comment]
I'm using 2010, and this error shows on my uptodate hercules.

**Comment by kyeme** [comment]
I can confirm, using 2010, windows 7

herc trunk\src\map/npc.h(30): fatal error C1083: Cannot open include file: 'pcre.h': No such file or directory
\herc trunk\src\map\mob.c(3640): warning C4244: 'function' : conversion from 'int64' to 'double', possible loss of data
\herc trunk\src\map\mob.c(3640): warning C4244: '=' : conversion from 'double' to 'int64', possible loss of data

**Comment by MishimaHaruna** [comment]
Did you make any changes to the project files?

**Comment by kyeme** [comment]
@MishimaHaruna
No changes, I'm using clean trunk.

**Comment by MishimaHaruna** [comment]
Can you show that you have this?

(right-click the map-server project, choose Properties, then go to Configuration Properties -> C/C++ -> General, and see the Additional Include Directories setting. It should contain the pcre line that I selected in the following screenshot)

![screen shot 2016-02-09 at 16 00 53 2](https://cloud.githubusercontent.com/assets/4590397/12919891/65b6b75c-cf46-11e5-88d0-428218f67cac.png)

**Comment by kyeme** [comment]
![2](https://cloud.githubusercontent.com/assets/4656578/12920396/6662cf1e-cf83-11e5-998f-1d3864783c57.jpg)

I don't how to open tha box xD but I copy paste Addition Include Directories :
..\src;..\3rdparty;..\3rdparty\mysql\include;..\3rdparty\zlib\include;..\3rdparty\pcre\include;..\3rdparty\msinttypes\include;..\3rdparty\mt19937ar;%(AdditionalIncludeDirectories)

**Comment by MishimaHaruna** [comment]
What if you do this? (From map/npc.h - I right-clicked the `<pcre.h>`)
Does it open the pcre.h file in the editor? If you get an error message, could you show it to me?

![screen shot 2016-02-09 at 16 32 34 2](https://cloud.githubusercontent.com/assets/4590397/12920875/ce4d4192-cf4a-11e5-8278-58c77dfb5dbb.png)

**Comment by kyeme** [comment]
Here:
![3](https://cloud.githubusercontent.com/assets/4656578/12921545/c03fb4ac-cf88-11e5-9b75-def215608a06.jpg)

**Comment by MishimaHaruna** [comment]
A fix is on its way. Thanks to @theultramage for pointing me in the right direction (I was only checking the map-server project, while the problem is in HPMHooking_map)
