### ISSUE TITLE
Itemname Constant Error

### ISSUE THREAD

**Issue by SamuelHercules** [HerculesWS/Hercules#1155]
Upg_Revolver seems can't be read as constant name but read as Player variable name

**Comment by dastgir** [comment]
Any error in map-server?
And which script is causing that?

Maybe you had that variable prior to adding item and thus giving warning?

**Comment by SamuelHercules** [comment]
Well, i'll close this one, that is weird error, because yesterday even if I restart the server it shows the error, but not with newly opened computer, the error is gone. LOL
