### ISSUE TITLE
ModExp, ModDrop, ModDeath const.

### ISSUE THREAD

**Issue by mnjfx** [HerculesWS/Hercules#1158]
after updating I tried and tested but it seems that ModExp, ModDrop and ModDeath doesn't work like it used too, no exp mod was applied, no death penalty was applied. I'll try to get the version where it was working because I have it saved, I'll post it once I got it.

**Comment by mnjfx** [comment]
![image](https://cloud.githubusercontent.com/assets/9565831/13065284/dffdd226-d495-11e5-8fa2-b1fd0d3e0bed.png)

The Version above is where I know its working and the one below is where its no longer working, as to when it stopped I'm not sure.

**Comment by mnjfx** [comment]
well on checking further, exp bonus is applied but when you relog ModDrop and ModDeath reverts back to 100.

**Comment by guilherme-gm** [comment]
It seems to be working fine on 2018.09.23. Tried changing each value, checked that it affected my character and relogging/restarting server also kept the values.

Test Script:
```
prontera,150,150,4	script	TestExpMod	1_M_01,{
	input .@val;
	setparam(ModExp, .@val);
	end;
}

prontera,152,150,4	script	TestDropMod	1_M_01,{
	input .@val;
	setparam(ModDrop, .@val);
	end;
}

prontera,154,150,4	script	TestDeathMod	1_M_01,{
	input .@val;
	setparam(ModDeath, .@val);
	end;
}
```

**Comment by Kenpachi2k13** [comment]
Works fine for me, too.
`close();`
