### ISSUE TITLE
Failed Assertion (Latest Build)

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1163]
I just want to share this error i found in my logs.

(02/18/2016 15:55:17) [ Error ] : --- failed assertion --------------------------------------------

(02/18/2016 15:55:17) [ Error ] : skill.c:172: 'skill_lv > 0' in function `skill_get_range'

(02/18/2016 15:55:17) [ Error ] : ./map-server(assert_report+0x77) [0x627537]

(02/18/2016 15:55:17) [ Error ] : ./map-server(skill_get_range+0xc3) [0x597313]

(02/18/2016 15:55:17) [ Error ] : ./map-server(skill_get_range2+0x5b) [0x5992bb]

(02/18/2016 15:55:17) [ Error ] : ./map-server(clif_devotion+0xc6) [0x4aeb36]

(02/18/2016 15:55:17) [ Error ] : ./map-server(status_change_end_+0x141d) [0x5f04bd]

(02/18/2016 15:55:17) [ Error ] : ./map-server(do_timer+0x1aa) [0x62be6a]

(02/18/2016 15:55:17) [ Error ] : ./map-server(main+0x17b) [0x63017b]

(02/18/2016 15:55:17) [ Error ] : /lib64/libc.so.6(__libc_start_main+0xfd) [0x7f021f8abd5d]

(02/18/2016 15:55:17) [ Error ] : ./map-server() [0x435449]

(02/18/2016 15:55:17) [ Error ] : --- end failed assertion ----------------------------------------

**Comment by hemagx** [comment]
Please include your git last commit hash ~
and any condition when this happen ?
