### ISSUE TITLE
Automatic navigation

### ISSUE THREAD

**Issue by Racaae** [HerculesWS/Hercules#1164]
In KRO Pope' instance the navigation location is set without message link.

Video: https://youtu.be/pMqqefDUums?t=393

**Comment by dastgir** [comment]
I know about it, somehow I was going to add it with doram job, but something happened with me, and all things by me are delayed..
Assigning this to me (unless someone wants to take this one)

**Comment by vykimo** [comment]
It seems to be only one packet to find.

**Comment by Lemongrass3110** [comment]
You can find the required packet in rathena/rathena@4f13007
It seems to have been in the client since the start of the navigation system, we just did not notice...

**Comment by dastgir** [comment]
We do know the packet, I am just busy to push this stuff

**Comment by Ridley8819** [comment]
added in b6690d7bb
