### ISSUE TITLE
Guild Skill Bug

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#1172]
The Cooldown is not reset when i log out.
Setting
// Restart guild skills cooldown by relog? (Note 1)
// When "no", you relog with the same cooldown remaining as from when you
// logged out, "yes" restarts the cooldown upon login to its full duration.
guild_skill_relog_delay: yes

even i set it to no still the same. 
Currently using the latest Git of herc.

**Comment by guilherme-gm** [comment]
I'm not able to reproduce this, tested with Battle Order - 5 mins cooldown
set to `true`, used skill waited some seconds, logged out and back in, 300 seconds (5 min) cooldown again (cooldown reseted to its full duration), setting it to `false` reduced the time I was online from the total

**Comment by dastgirp** [comment]
https://github.com/HerculesWS/Hercules/pull/2005 (https://github.com/HerculesWS/Hercules/commit/57ba23012d78b8bae37953d65831e932d1365283)
This should have fixed it
