### ISSUE TITLE
Issue with char-server disconnecting and in-game making a party with ""

### ISSUE THREAD

**Issue by irugationz** [HerculesWS/Hercules#1185]
Hercules Git Version: 37fefe0d863f74a8229dd57c72a6cef6c1071730

When someone makes a party with /organize "NAME", with the "", and do something that need to check the party (like doing alt + z, or logout), it can not logout (character select menu) and the char-server is disconnected:
[Status]: Char-server 'SERVER' has disconnected.
[Status]: Attempting to connect to Char Server. Please wait.
[Status]: Connecting to 127.0.0.1:6121
[Error]: make_connection: connect failed (socket #6, error 111: Connection refused)!
[Status]: Connecting to 127.0.0.1:6121
[Error]: make_connection: connect failed (socket #6, error 111: Connection refused)!
[...]

**Comment by hemagx** [comment]
This would probably means the character server crashes please check it and provide a core dump either by gdb or whatever compiler or debugger you use

**Comment by irugationz** [comment]
Can you please tell me how to do that? I tryed to follow the "http://herc.ws/wiki/GDB" tutorial, but did not worked. Also, when i recompile the server, i noted that an error shows up a lot of time, like that:

[...]
      CC      nullpo.c
        CC      random.c
        CC      showmsg.c
        CC      strlib.c
strlib.c: In function 'strlib_normalize_name':
strlib.c:193: warning: logical '&&' with non-zero constant will always evaluate as true
strlib.c:203: warning: logical '&&' with non-zero constant will always evaluate as true
strlib.c:210: warning: logical '&&' with non-zero constant will always evaluate as true
strlib.c: In function 'strlib_e_mail_check':
strlib.c:314: warning: logical '&&' with non-zero constant will always evaluate as true
strlib.c: In function 'sv_escape_c':
strlib.c:767: warning: logical '&&' with non-zero constant will always evaluate as true
        CC      sysinfo.c
        CC      thread.c
        CC      timer.c
        CC      utils.c
[...]

Could it be related?

**Comment by Jedzkie** [comment]
Maybe you have custom modifications? Please provide us more info such as your OS

**Comment by irugationz** [comment]
- OS - cat /etc/issue:
CentOS release 6.5 (Final)
Kernel \r on an \m

- OS - cat /proc/version:
Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013

- What i have changed:
1) Get Hercules in my Windows 7 OS, through GitTortoise and made all changes, then uploaded to my host (The CentOS 6.5).

2) put chmod 744 to "athena-start" and "configure".

3) put chmod 744 to "*.sh"

4) copyed my host provider "sysinfogen.sh" and put chmod 755 (my original file was getting error when compiling).

5) got bash errors, so used "dos2unix athena-start" and "dos2unix configure".

6) compiled server (./configure), and showed up those errors.

- Attached files:
1) crashlog.zip: .log file with screen info when the char-server gets disconnected.
2) 20160229 - ReTRO.zip: a .diff file with all my changes in emulator.
3) import - oficial.zip: my import folder (inside /conf),
4) sysinfogen.zip: the sysinfogen.sh provided by the host.

Thanks!


[crashlog.zip](https://github.com/HerculesWS/Hercules/files/160315/crashlog.zip)
[20160229 - ReTRO.zip](https://github.com/HerculesWS/Hercules/files/160316/20160229.-.ReTRO.zip)
[import - oficial.zip](https://github.com/HerculesWS/Hercules/files/160320/import.-.oficial.zip)
[sysinfogen.zip](https://github.com/HerculesWS/Hercules/files/160321/sysinfogen.zip)

**Comment by kubixservice** [comment]
I have the same problem with last GIT.
