### ISSUE TITLE
Unintended Item Duplicate?

### ISSUE THREAD

**Issue by ermanherman** [HerculesWS/Hercules#1191]
Hi there,

Today i just think about to investigate if any duplication may occur either intended by players or by system saving glitch.

Surprisingly i found there is duplication and from my conclusion it's unintended by players, since the item duplicate with same unique_id persists in players account without their acknowledge.

Here i do how to trace the duplicate item with unique_id

```
SELECT unique_id, account_id, nameid, refine
FROM storage 
GROUP BY unique_id
HAVING COUNT( * ) >=2
```

I tested on both my servers, 1 using kinda old hercules about 1 year ago version, and another one with at least 1 month old of hercules version.

Please check this guys and thanks.

Just some extra info the server running with about 300 players avarage.

**Comment by ermanherman** [comment]
UPDATE:

Server not crash, just few hour from my checking there were found about 4407 duplication found and in rising to 4413 without clue...

**Comment by ermanherman** [comment]
UPDATE:

Im tracking latest duplicated unique_item and talk to one of effected char. He said he just store the item and dont realize that item he stored become 2 in quantity although he store it 1.

**Comment by ermanherman** [comment]
@4144 @dastgir @Jedzkie @Michieru

**Comment by dastgir** [comment]
What was that item? Item Id? Was the item bounded? He stored in guild storage or account storage?

**Comment by ermanherman** [comment]
Some screenshot.

![1](https://cloud.githubusercontent.com/assets/9628908/13636710/464c5ab6-e63e-11e5-9c8c-9a33b0a89ec1.jpg)
![2](https://cloud.githubusercontent.com/assets/9628908/13636711/46617522-e63e-11e5-8d90-8f6ddd500f3b.jpg)

**Comment by ermanherman** [comment]
@dastgir mostly equipment. I cant check stack-able item due it dont have unique_id

**Comment by MishimaHaruna** [comment]
Do you know if the server show any error message while running? (mostly interested in the ones tagged as `[Error]` or `[SQL]`).

Just to make sure, do you have more than one map-server connected to the same char-server?

**Comment by ermanherman** [comment]
@MishimaHaruna no error sir, im running single map-server.

**Comment by ermanherman** [comment]
@dastgir look like bound item not affected.

**Comment by kyeme** [comment]
I've experienced this, I'm just not sure if this was a Duplicate Item or there is some bug on UID. I've already sent this matter to @MishimaHaruna but he haven't read my message yet (I've sent a private message last June 2015, so this bug does exist for a long time already.)

**Comment by ermanherman** [comment]
I belive this is item duplication after all i check...

**Comment by ermanherman** [comment]
Thanks for fast action! :)
