### ISSUE TITLE
Compile warning Latest Git 10/3/2016

### ISSUE THREAD

**Issue by ermanherman** [HerculesWS/Hercules#1193]
CC      mob.c
mob.c: In function âmob_defaultsâ:
mob.c:5290:29: warning: assignment from incompatible pointer type [enabled by default]
        CC      npc.c
        CC      npc_chat.c
        CC      party.c
        CC      path.c
        CC      pc.c
        CC      pc_groups.c
        CC      pet.c
        CC      quest.c
        CC      script.c
        CC      searchstore.c
        CC      skill.c
        CC      status.c
        CC      storage.c
storage.c: In function âstorage_guild_storagegetâ:
storage.c:577:2: warning: logical âorâ of collectively exhaustive tests is always true [-Wlogical-op]
storage.c: In function âstorage_guild_storagegettocartâ:
storage.c:649:2: warning: logical âorâ of collectively exhaustive tests is always true [-Wlogical-op]

system DEBIAN 7

**Comment by ermanherman** [comment]
@MishimaHaruna

**Comment by MishimaHaruna** [comment]
> ```
mob.c: In function âmob_defaultsâ:
mob.c:5290:29: warning: assignment from incompatible pointer type [enabled by default]
```

Did you edit the definition of the function `item_dropratio_adjust` without updating the interface?

On a clean hercules it should look like this:

```
// mob.c:3666
void item_dropratio_adjust(int nameid, int mob_id, int *rate_adjust)
// mob.h:511
void (*item_dropratio_adjust) (int nameid, int mob_id, int *rate_adjust);
```

> ```
 storage.c: In function âstorage_guild_storagegetâ:
storage.c:577:2: warning: logical âorâ of collectively exhaustive tests is always true [-Wlogical-op]
storage.c: In function âstorage_guild_storagegettocartâ:
storage.c:649:2: warning: logical âorâ of collectively exhaustive tests is always true [-Wlogical-op]
```

What's the value of `MAX_GUILD_STORAGE`? (hopefully not zero?)
It should be defined in src/common/mmo.h. But I don't see included in in storage.c, which smells fishy.

**Comment by ermanherman** [comment]
Ok sir. Thanks That was from my side.

yeah MAX_GUILD_STORAGE i set 0 as i dont want to enable the features.

**Comment by ermanherman** [comment]
@MishimaHaruna nvm it look like my PLUGIN SRC not updated. Wired...
