### ISSUE TITLE
Enchant Deadly Poison doesn't work

### ISSUE THREAD

**Issue by bangzeed** [HerculesWS/Hercules#1194]
Enchant Deadly Poison can't use with weapon 2 dagger

https://www.youtube.com/watch?v=bSxC6NIIpVc

**Comment by Travesso** [comment]
Is true, doesn't work, please, fix that

**Comment by Jedzkie** [comment]
Before making bug reports, please provide us more informations, so that we can figure it out faster.

**Comment by Travesso** [comment]
Just work with one weapon(jur, one dagger), with two weapon doesnt work( left: main gauche, right: main gauche), i not try with one weapon and shield.

**Comment by Jedzkie** [comment]
RENEWAL or PRE-RENEWAL?

**Comment by Travesso** [comment]
RENEWAL

**Comment by bangzeed** [comment]
so sorry for my informations.

**Comment by Paoly28** [comment]
can you please post at least a photo since the report is pretty vague , i haven't encountered anything like this. considering how many trans server as of now and i didn't encounter this not even once. even at my own test server.

**Comment by bangzeed** [comment]
one weapon can use Skill
[url=http://www.mx7.com/view2/yYccB9RunHsJrQgI][img]http://www.mx7.com/i/1e5/OhvVgK.jpg[/img][/url]

2 weapon can not use Skill

[url=http://www.mx7.com/view2/yYcdfVpUZyKL7Wbc][img]http://www.mx7.com/i/170/BoXrEs.jpg[/img][/url]
[url=http://www.mx7.com/view2/yYccCVKTNDi3zTvH][img]http://www.mx7.com/i/b64/bDowNT.jpg[/img][/url]

**Comment by Travesso** [comment]
*and not hava error in cmds, just doesnt work the skill

**Comment by Jedzkie** [comment]
@bangzeed @Travesso Can't reproduce this bug report, i'm using latest Hercules and Renewal Settings.

http://i.giphy.com/3ornkfLH2SQDTDWu08.gif

**Comment by Travesso** [comment]
you do any modification on emulador before compilation? I try again, using latest hercules, i dont chance nothing, just the PACTEVER for hexed 2015-05-13, downloaded on forum and not working

**Comment by bangzeed** [comment]
ok. I use exe  2015-05-13 too

**Comment by bangzeed** [comment]
@Jedzkie Thank for test

**Comment by Travesso** [comment]
@Jedzkie what client data you use? link please?

@bangzeed now works for you? the new leatest update?

**Comment by Jedzkie** [comment]
@bangzeed 2015-05-13

**Comment by bangzeed** [comment]
@Travesso  last uptade for exe 2015-05-13 not work

@Jedzkie Yep. I use exe 2015-05-13. src last update not work

Src not update Still work.

**Comment by Jedzkie** [comment]
did you use clean Hercules? latest version?

**Comment by bangzeed** [comment]
@Jedzkie Yeah Clean and lastst version

<a href="http://www.mx7.com/view2/yYeiN1Ot7EjUUJnY" target="_blank"><img border="0" src="http://www.mx7.com/i/11a/MILVcP.jpg" /></a>

**Comment by bangzeed** [comment]
@Jedzkie yeah clean and last version

<a href="http://www.mx7.com/view2/yYeiWBeSMdo17c4h" target="_blank"><img border="0" src="http://www.mx7.com/i/d3a/zBTKGy.jpg" /></a>

**Comment by Jedzkie** [comment]
Maybe try to not use custom Sprites.

**Comment by Travesso** [comment]
I

**Comment by Travesso** [comment]
*I dont use custom sprint and doesnt work

**Comment by bangzeed** [comment]
<iframe width="420" height="315" src="https://www.youtube.com/embed/bSxC6NIIpVc" frameborder="0" allowfullscreen></iframe>

**Comment by Paoly28** [comment]
did you have any modifications ? maybe something indirectly affects enchant deadly poison.

**Comment by Travesso** [comment]
Only modification i made was changed PACTEVER for 2015-05-13,  only that

**Comment by Jedzkie** [comment]
Please tell us what is your herc versiin

**Comment by Travesso** [comment]
Maybe problem in compilation? I use Visual Studio 2010, and check map-server, char-server, login-server and mapcache, all realease, Build, 4 sucessed, no error, normal

**Comment by Travesso** [comment]
The lastest version, i download again now, have 10 minutes

**Comment by bangzeed** [comment]
@Travesso me too last version

**Comment by Travesso** [comment]
Still doesnt work here

**Comment by Jedzkie** [comment]
@bangzeed @Travesso try to upgrade your Compiler, i suggest to use 2012 or 2013.

**Comment by Travesso** [comment]
I use de VS2012 and still doesnt work

**Comment by Jedzkie** [comment]
@travesso please add me on skype. so that i can help you with your problem.

Skype: dev.jedz

**Comment by Travesso** [comment]
@Jedzkie Any idea what cause the bug?
