### ISSUE TITLE
Attack Speed Bug

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1198]
Bug: When I used dual dagger, I got 26 attack speed. Don't you think that is too low?

![1](https://cloud.githubusercontent.com/assets/4656578/13747977/c2163946-ea35-11e5-9163-5bce2ebea517.jpg)

Pre-Renewal settings

**Comment by Jedzkie** [comment]
Same issue with #1194

**Comment by kyeme** [comment]
~ Bumps ~

**Comment by Jedzkie** [comment]
@4144 @MishimaHaruna @dastgir @hemagx
