### ISSUE TITLE
Bioethics complete quest checks

### ISSUE THREAD

**Issue by AtlantisRO** [HerculesWS/Hercules#1205]
In commit bd86d05 it was changed the bioethics skill check in [Biochemist#Valkyrie] NPC affecting players with very old accounts, changing:

(Class == Job_Creator && MISC_QUEST & 64 && getskilllv("AM_BIOETHICS") == 0)

to:

if (Class == Job_Creator && bioeth == 13 && getskilllv(AM_BIOETHICS) == 0) {

The MISC_QUEST|64 was the old variable that ends the quest, but it was dropped in commit 4ea6d47 and it has not been used anymore in scripts, but still mentioned in doc\quest_variables.txt.

Even when it would be better to use bit 64 for MISC_QUEST, since this economizes one variable, that would affect newer players. What about adding to NPC [Biochemist#Valkyrie] a check to evaluate if player has one of both variables:

(Class == Job_Creator && (MISC_QUEST & 64 || bioeth == 13) && getskilllv("AM_BIOETHICS") == 0)

This change also applies to NPC [Kellasus#qsk_al]. Also, it would be great to have a merge function for both vars.

**Comment by dastgir** [comment]
It was dropped 8 years ago... Do we still need to support it?
Or just provide a npc which converts old variable into new?

**Comment by HeroGarr** [comment]
Just add conversion to F_ClearGarbage? It's called every kafra call, so will probably hit everyone it needs to.

**Comment by AtlantisRO** [comment]
I totally missed F_ClearGarbage function, thanks a lot!!

This problem has been reported by players with very old accounts two times until now, it would be a nice improvement to servers convert "bioeth == 13" to "MISC_QUEST & 64", since it would economize one variable and also would be helpful to aged servers which followed Hercules.
.
Thanks for the support!!

**Comment by MishimaHaruna** [comment]
Reducing the amount of variables used isn't a priority though. The MISC_QUEST bitmask is kind of confusing, and you need to check which bit means what every time you read or write a script that uses it.

**Comment by AtlantisRO** [comment]
I understand and appreciate the attention. This issue is not really a big deal, so, can be closed. Thanks :)
