### ISSUE TITLE
The name from the named item is not permanent

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1206]
Bug: When you and the owner of the 'Named Item' are on the same map, the 'Named Item' becomes 'Nameless'. But, if the owner of the 'Named Item' is not on your map, the name of the 'Named Item' is as is, nothings change.

![ss1](https://cloud.githubusercontent.com/assets/4656578/13902963/fcbbcd32-ee9e-11e5-99a8-4f7670b4a0e5.jpg)

~ I can't reproduced this bug on old revision (october 2015).

**Comment by kyeme** [comment]
@MishimaHaruna @4144

**Comment by MishimaHaruna** [comment]
Does this happen with a specific client/packetver?

**Comment by kyeme** [comment]
@MishimaHaruna 
Im using 2015-05-13 client. No problem with old Hercules (October 2015).. However when i used it on the latest Hercules that's where the problem starts. I used it with the same exe.

**Comment by hemagx** [comment]
Git revision where it's working ? just saying october 2015 is not that helpful.
also any other settings changed than client date in mmo.h?

2016-03-28 4:56 جرينتش+02:00, kyeme <notifications@github.com>:

**Comment by kyeme** [comment]
Any october revision https://github.com/HerculesWS/Hercules/commits/master?page=18
https://github.com/HerculesWS/Hercules/commit/99cb5b4ae5d703878c421d3dd62ef626a7979130

Changes on mmo.h
#define PACKETVER 20150513

**Comment by kyeme** [comment]
Lol its working fine on https://github.com/HerculesWS/Hercules/commit/c7410453a15110a12d9fffb06b70e9557fb9f73a

**Comment by kyeme** [comment]
Up~ 
The bug still persist and can be done in a different way than before.

Bug: There are chances that a "named item" will replicate the nearest players/mob name

Script:
-	script	asdasd	FAKE_NPC,{
OnPCKillEvent:
	getnameditem Skull_, rid2name( killedrid );
	end;
}

Video:
https://www.youtube.com/watch?v=9LyG7_vQ1fE&feature=youtu.be

Git: https://github.com/HerculesWS/Hercules/commit/c7410453a15110a12d9fffb06b70e9557fb9f73a

**Comment by kyeme** [comment]
~ Bump ~

**Comment by kyeme** [comment]
~ Up ~

**Comment by Emistry** [comment]
I tested in my local server. using this script
```
prontera,155,178,5	script	asd	4_F_KAFRA9,{
	getnameditem( 5001,"Player A" );
	end;
}
```

## Step to Reproduce : 
1. Player A talk to the NPC and get the named item with the name "Player A ".
2. Player A immediately drop the named item on ground.
3. Player B pick up the dropped item, and get a "Nameless" item.
4. Player B get the item with his name on it. (should be remain as "Player A ")
5. Player B relog or change to other map (different map with Player A), item name remain "Player A ".
6. Player B return back to the map where Player A stayed, item name become "Nameless" again.

well, sometime it does look fine... the issue doesn't seem to happen 100% every time.

**Comment by KirieZ** [comment]
Seems like the issue is caused by 436b3b96c868285e0f3743b92d582e104b9d4f03 . It's working fine on d30c30f267dcb26bc7abf3a57627ead5c4f90bec . The name disappears in the moment the player who's name is on the item enters in the item's owner area of view.
Tested by killing another character and getting his skull, using 2014-04-16.

Steps:
1. A kills B and takes his skull (Nameless)
2. A goes to another map (Name is OK)
3. A goes to the same map but out of B's vision (Name is OK)
4. A goes near B (Name disappears)

**Comment by hemagx** [comment]
If you use older client than 20131223 it works fine?

**Comment by KirieZ** [comment]
@hemagx Just tried with 2013-08-07 and it seems to be working fine.

**Comment by hemagx** [comment]
Gonna check it then ^^
