### ISSUE TITLE
@fontcolor buggy

### ISSUE THREAD

**Issue by arvilmena** [HerculesWS/Hercules#1217]
~2 years ago, using 20140115 client http://herc.ws/board/topic/7214-fontcolor-showing-unnecessary-logging-effect/

tried it today, fresh hercules install, 2014-10-22 client, a GM sprite`d player that uses @fontcolor is buggy
1. @fontcolor <color>
2. chat something
3. a GM "shadow" kept in place
4. the "real" GM was invi for 3 secs

related:
http://herc.ws/board/tracker/issue-8502-fontcolor-usage-will-strip-gm-cloth/
http://herc.ws/board/topic/9763-plugin-colored-chat/

**Comment by Asheraf** [comment]
not a bug, the fontcolor disguises the player as his job therefore GM costume and cart disappear, for now nothing can be done about that.
