### ISSUE TITLE
Map-server crashed, happen 3 times a week on my server now

### ISSUE THREAD

**Issue by vBrenth** [HerculesWS/Hercules#1220]
#http://pastebin.com/Cd5ZRZFi

I havent change any src thing for months but this happens.
I don't know what is the scenario is..

**Comment by MishimaHaruna** [comment]
Are you running a very old version of Hercules? This crash can no longer happen since september 2015 (commit 21442a88). The issue isn't fixed (it'd show a backtrace), but if you updated, it wouldn't crash anymore.

**Comment by MishimaHaruna** [comment]
I'll commit a fix that prevents the call altogether, if the sd is NULL.
