### ISSUE TITLE
Warp Facing Direction

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1240]
When respawning from teleport/warp the player should always be facing north.. it looks that way on your screen but on others screen they will see you facing the last direction you were facing before you warped.
(Related to https://github.com/HerculesWS/Hercules/commit/c0c9af6d91be054390b1ab797bc292140f25287c)
Hercules Video:
https://youtu.be/3tIyqgcbHA4

**Comment by MishimaHaruna** [comment]
@Jedzkie please don't close other repositories issues, or I'll have to revoke push rights.

**Comment by Jedzkie** [comment]
Sorry @MishimaHaruna i diudnt noticed it. My bad.
