### ISSUE TITLE
missing packet PACKET_ZC_DEFINE_CHECK

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#1242]
The PACKET_ZC_DEFINE_CHECK packet is not implemented in hercules, saw that it applies in the drop rare items and package items

```
// packet 0x7ff
struct PACKET_ZC_DEFINE_CHECK {
  /* this+0x0 */ short PacketType
  /* this+0x2 */ short PacketLength
  /* this+0x4 */ int Result
}
```

```
// result enumeration
enum PACKET_ZC_DEFINE_CHECK::<unnamed-tag>{
    DEFINE__BROADCASTING_SPECIAL_ITEM_OBTAIN =  0x1,
    DEFINE__RENEWAL_ADD_2 =  0x2,
    DEFINE__CHANNELING_SERVICE =  0x4,
};
```

**Comment by Lemongrass3110** [comment]
What about the dynamic data of it? Any infos?

**Comment by Kenpachi2k13** [comment]
@4144 
Any interests in investigating this? (Since you seem to be our "packet guy". :smile:)

**Comment by 4144** [comment]
This packet was removed in 2011-07-19aRagexeRE and 2011-07-18aRagexe and was never exists in zero.
Probably exists some newer replacement for this packet?

**Comment by Kenpachi2k13** [comment]
Well, I guess this can be closed then...
