### ISSUE TITLE
Attack Motion of Skill - Chain Lightning

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#1247]
Recently getting some reports from players state that when using Chain Lightning with high ASPD char, the attack motion isn't as fast as previous.

The result they have tested.
- Summon ball + release = fast. No problem.
- After learn chain lightning + release. 
with ASPD of 147 and 193 respectively, but the attack motion remain same speed.

Conclusion : 
ASPD should affect magic speed attack ?
Can anyone confirm this in any aegis or official server ?

Video 
https://www.youtube.com/watch?v=fplsHip1WLw&feature=youtu.be

**Comment by malufett** [comment]
working as intended...
in aegis only summon release ball is dependent on the aspd of the caster with its hit interval while chain lightning no matter if it was cast via normal cast or release spell it is still fixed the only affected on the aspd is the first hit
Cast->[aspd based delay]->1st chain->[fixed delay]->2nd chain ... and so on

**Comment by Emistry** [comment]
I see, thx for the info.

because I remember old version (probably a year ago) Hercules still has the ASPD affect the hit interval. Probably a bug that was fixed I guess.
