### ISSUE TITLE
NC_Pilebunker requirements not supported 

### ISSUE THREAD

**Issue by sagunkho** [HerculesWS/Hercules#1250]
in skill_require_db.txt
2257,0,0,50,0,0,0,99,0,0,mado,0,**1549:16030:16031:16032**,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0    //NC_PILEBUNKER#Pile Bunker#

The bold portion probably represents that either one of those IDs that can be used, but source code doesn't allow for checking in such a way, for skill required items.
`
    for( j = 0; j < MAX_SKILL_ITEM_REQUIRE; j++ ) {
        skill->dbs->db[idx].itemid[j] = atoi(split[12+ 2*j]);
        skill->dbs->db[idx].amount[j] = atoi(split[13+ 2*j]);
    }
`

**Comment by Kenpachi2k13** [comment]
If this really was buggy back then, it was fixed when the skill DB was converted to libconfig.
`close();`

**Comment by Asheraf** [comment]
@Kenpachi2k13 this issue was created after the conversion, we still don't have support for `OR` item requirements, please don't close issues without investigating them ╰(*°▽°*)╯

**Comment by Kenpachi2k13** [comment]
Oh. I didn't check this because the old TXT entry was quoted.
You're absolutely right. Sorry. :disappointed:

**Comment by Kenpachi2k13** [comment]
I had a closer look at the skill DB and there are many more issues:
- **FixedCastTime** Missing a note in the entry structure that this field will only be read if `RENEWAL_CAST` is enabled.
- **Requirements**
  * **MaxHPTrigger** Completely missing in the entry structure.
  * **SpiritSphereCost** Doubly read in `skill_read_skilldb`.
  * **State**
    * Entry structure says it can be grouped by levels, which isn't implemented, yet.
    * Possible improvement: Convert states to bitmask to be able to combine them.
  * **Items**
    * Entry structure says it can be grouped by levels, which isn't implemented, yet.
    * No support for "on of these items". (This issue.)
    * No support for item must be equipped. (This issue.) (Maybe use `amount = -1` to achieve this.)
 - **Unit**
   * **Interval** Entry structure says it can be grouped by levels, which isn't implemented, yet.
   * **Target**
     * Missing types in entry structure: NotParty, NotGuild, Self
     * Completely missing types: BCT_GUILDALLY, BCT_NEUTRAL
     * Incorrect assigned types: Guild, SameGuild
     * Types should be combinable, since they bitmask fields.

Well, a lot of work...
