### ISSUE TITLE
Some new weapon not working, don't give atk or mAtk

### ISSUE THREAD

**Issue by Shyne** [HerculesWS/Hercules#1251]
Ex: Death Fire (ATK)
itemdb.conf:
`
{
	Id: 13192
	AegisName: "Death_Fire"
	Name: "Death Fire"
	Type: 5
	Buy: 1250000
	Weight: 2000
	Atk: 400
	Range: 9
	Slots: 1
	Job: {
		Rebellion: true
	}
	Loc: 34
	WeaponLv: 3
	EquipLv: 108
	View: 20
	Script: <"
		bonus bLongAtkRate,5;
		bonus bHit,-50;
		bonus bDelayrate,-10;
	">
},`

![screenfsro547](https://cloud.githubusercontent.com/assets/2038294/14489917/f8a656a0-0199-11e6-8ed8-e480ca40e362.jpg)

Ex: Staff of Geffen (MATK)
itemdb.conf:
`
{
	Id: 2022
	AegisName: "Staff_Of_Geffen"
	Name: "Staff Of Geffen"
	Type: 5
	Buy: 20
	Weight: 1000
	Atk: 100
	Matk: 200
	Slots: 1
	Job: {
		Wizard: true
	}
	Upper: 56
	Loc: 34
	WeaponLv: 1
	EquipLv: 150
	View: 10
	Script: <" bonus bInt,20; ">
},`
![screenfsro548](https://cloud.githubusercontent.com/assets/2038294/14489947/20b5f1fa-019a-11e6-883b-1441be3aeb2a.jpg)

**Comment by ajslashsd** [comment]
Type 5 is for armor. Change them to type 4 and they should work.

**Comment by Shyne** [comment]
Ops, i;m so dumb, thx you
