### ISSUE TITLE
Rachel Sanctuary Quest

### ISSUE THREAD

**Issue by Lilori** [HerculesWS/Hercules#1256]
In official : 
at the few steps to the end of quest, you will pick up a key (near priest Zhed). then you go to bloody room which is in 2nd floor. and stairs had warps for that.

In Herc : 
no warp near stairs to 2nd floor, and no warp to bloody room.

Ref:
http://irowiki.org/wiki/Rachel_Sanctuary_Quest
https://wiki.talonro.com/Rachel_Sanctuary_Entrance_Quest

**Comment by skyleo** [comment]
I'll look into it.

**Comment by skyleo** [comment]
Can you specify a bit more at which steps those warps are not working? Also screenshots would be nice.

**Comment by Ridley8819** [comment]
@skyleo can this be closed?

**Comment by AtlantisRO** [comment]
I have tested it on iRO. Both, iRO and Hercules has the warp portals in the same room:

iRO Screenshot:
http://i64.tinypic.com/w70eh0.jpg

Hercules Screenshot:
http://i68.tinypic.com/2nvb41t.jpg

As a comment, the bloody room is accesible only a few momentos while character gets into the sanctuary by the window and opens the door. After that character cannot come again the bloody map, but the normal one.

**Comment by skyleo** [comment]
I think it can be closed, yes. @Ridley8819
