### ISSUE TITLE
Dequ'ee Message Quest Geffen,

### ISSUE THREAD

**Issue by javierlog08** [HerculesWS/Hercules#1258]
I was just doing the quest of the murder, 

I go to geffen follwing the Quest, Dequ'ee npc just after talk with him, warp me to  wrong location on a map

izlude 35, 78

I got stucked on the water...

![](http://ragemu.org/board/uploads/monthly_2016_04/57170b4821ea1_Sinttulo.png.e0ff85f197f0f0ceaec97a52b5408026.png)

the script is npc/quest/first_class/tu_sword.txt

My emulator is the same copy as hercules  , I havent changed anything, so the emulator is RENEWALL

The wrong line
 

if (RENEWAL)
         warp "izlude",127,100;
 else
         warp "izlude",35,78;
 close;
 

Seems to be avoiding RENEWAL flag...

**Comment by Ridley8819** [comment]
Ehm.. Didn't you report this here? http://ragemu.org/board/bug-tracker/scripts/dequee-message-quest-geffen-r7/#comment-10
Its obviously an issue with ragemu, not Herc
