### ISSUE TITLE
Bug with Swordman Manual

### ISSUE THREAD

**Issue by javierlog08** [HerculesWS/Hercules#1259]
I was doing criatura academy Quest.

Late I went to talk with the swordman "Adri" at second floor, he gave to me a a Swordman manual- 

Late I equiped the manual and I went to swordman house in Izlude, (When I equiped the manual I got Provoke, Bash, and magnum break lvl 1)

Well just late to speak with the "Swordman NPC" in izlule he became to me a swordman,  

but curiosly only magnum break disappeared, the others skills still remain on my skill panel, even If I havent filled the skills.

I leave a screenshot here

![](http://ragemu.org/board/uploads/monthly_2016_04/5716e52523005_Sinttulo.png.91781ea2dac201229f4de678a108b166.png)

**Comment by Ridley8819** [comment]
Report is more than 1 year old, also I wasn't able to reproduce this.
If you still encounter the issue feel free to reopen it.
