### ISSUE TITLE
disguise issues

### ISSUE THREAD

**Issue by Angelmelody** [HerculesWS/Hercules#1268]
```
prontera,156,153,5	script	dmtest	4W_SAILOR,{
	disguise 1650; 
	sleep2 10000; 
	undisguise;
	close;	
}
```
When you disguise as a mob sprite, you can't see the mob appearance effect on yourself 
but others can.It looks like summon a monster not disguise as a monster,and then after 
undisguise ,you can still see the residual image of  that mob sprite.

'玩家01' disguises as a mob sprite
<img width="775" alt="d01" src="https://cloud.githubusercontent.com/assets/2773211/14834466/2b08db2a-0c37-11e6-8e02-9af4f71bd0f1.png">

after 10 sec ,'玩家01' returns to normal character sprite
<img width="770" alt="d02" src="https://cloud.githubusercontent.com/assets/2773211/14834486/402d996e-0c37-11e6-9cb3-d3d26084c456.png">

**Comment by vBrenth** [comment]
Hello, Do this thing and the bug will be fixed.
https://github.com/HerculesWS/Hercules/issues/1078#issuecomment-171530319

**Comment by MishimaHaruna** [comment]
Marking as duplicate of #1078
