### ISSUE TITLE
About NST_MARKET itemid == item_weight

### ISSUE THREAD

**Issue by chatchanunn** [HerculesWS/Hercules#1280]
Hello, dev

from
https://github.com/HerculesWS/Hercules/issues/720

I found some behavier about item weight and shoptype.

If charactor have weight == 0 , max_weight == 4000
and itemid == 501 (Red_Potion) weight 7 (70)

I can buy stuff about 80 ea (max_weight/itemid) not 571 ea for real weight ( max_weight/item_weight )

I try to find sourcecode in npc.c but not found something control that but I think you can do this.

So herc server read weight = itemid not real item weight.

Sometime, I think it may be bug about packet arrangement.

Sorry about my English.

**Comment by chatchanunn** [comment]
Anyone can fix it. goto clif.c line round 18240 in function clif_npc_market_open

`    /* NPC Market (by Ind after an extensive debugging of the packet, only possible thanks to Yommy <3) */
    void clif_npc_market_open(struct map_session_data *sd, struct npc_data *nd) {
    #if PACKETVER >= 20131223
    	struct npc_item_list *shop;
    	unsigned short shop_size, i, c;
     
    	nullpo_retv(sd);
    	nullpo_retv(nd);
    	shop = nd->u.scr.shop->item;
    	shop_size = nd->u.scr.shop->items;
    	npcmarket_open.PacketType = npcmarketopenType;
     
    	for(i = 0, c = 0; i < shop_size; i++) {
    		struct item_data *id = NULL;
    		if (shop[i].nameid && (id = itemdb->exists(shop[i].nameid)) != NULL) {
    			npcmarket_open.list[c].nameid = shop[i].nameid;
    			npcmarket_open.list[c].price  = shop[i].value;
    			npcmarket_open.list[c].qty    = shop[i].qty;
    			npcmarket_open.list[c].type   = itemtype(id->type);
    			// npcmarket_open.list[c].view   = ( id->view_id > 0 ) ? id->view_id : id->nameid; << comment old one
    			npcmarket_open.list[c].view   = itemdb_weight(id->nameid); //<< add new one 
    			c++;
    		}
    	}
     
    	npcmarket_open.PacketLength = 4 + ( sizeof(npcmarket_open.list[0]) * c );
     
    	clif->send(&npcmarket_open,npcmarket_open.PacketLength,&sd->bl,SELF);
    #endif
    }`

**Comment by MishimaHaruna** [comment]
What packetvers was this tested on? Are they all affected, or only after a certain date?

**Comment by chatchanunn** [comment]
I use client 20150916 for test this.

**Comment by kyeme** [comment]
I can confirm on 20160106

**Comment by kyeme** [comment]
https://github.com/HerculesWS/Hercules/issues/1840

**Comment by carloshenrq** [comment]
I can confirm in 20141022 client.

**Comment by AnnieRuru** [comment]
https://github.com/HerculesWS/Hercules/commit/95c8d0751bcf73998c43550ee951014930f334e0#diff-85d990dde8caf2d72d1e2b0f7dcf9786R19893

I think @4144  accidentally fix this ?

**Comment by 4144** [comment]
yes, checked what logic same in weight in market and barter packets

**Comment by Kenpachi2k13** [comment]
Fixed in https://github.com/HerculesWS/Hercules/commit/f1f1ef0ff2c9aa7d879df8b959072a7429d2722a
`close();`
