### ISSUE TITLE
Redundant racial specific entries in item_db

### ISSUE THREAD

**Issue by ajslashsd** [HerculesWS/Hercules#1284]
Currently, some items in the item_db are doubled, assuming use for both for PvP and PvM uses.
Example:
Drooping Alice (or Drooping Alicel) increases damage given to Demihumans by 10%.
`{
	Id: 18630
	AegisName: "Dep_Alice_Hat"
	Name: "Drooping Alice"
	Type: 5
	Buy: 20
	Weight: 500
	Def: 6
	Job: {
		All: true
		Novice: false
	}
	Loc: 256
	EquipLv: 70
	View: 784
	Script: <"
		bonus2 bAddRace,RC_DemiPlayer,10;
		bonus2 bAddRace,RC_Player,10;
		bonus2 bAddRace,RC_Demon,10;
		if(getrefine()>6) {
			autobonus "{ bonus bAspdRate,100; }",10,7000,0,"{ specialeffect2 EF_POTION_BERSERK; }";
		}
	">
},`

bAddRace is both applied for RC_DemiPlayer and RC_Player.
Against monsters, this works as intended, but the effects seem to be doubled against players.

Tested by using this:
`bonus2 bAddRaceTolerance,RC_DemiPlayer,50;
bonus2 bAddRaceTolerance,RC_Player,50;
bonus2 bAddRace,RC_DemiPlayer,300;
bonus2 bAddRace,RC_Player,300;`
Damage from monsters are halved, and attacks from players miss completely when both RC_DemiPlayer and RC_Player are present.
Damage given is also much higher when using both RC_DemiPlayer and RC_Player.
Tested on normal, town and pvp map zones.

I'm not sure if the current scripts supposedly replicate kRO/official behavior, so I'm not sure about making pull requests to fix this.

**Comment by dastgir** [comment]
That bAddRace, RC_PLAYER should be removed.

**Comment by Triedge** [comment]
No, plz!
On my server I have several items that only cause damage bonus against players, but not monsters.
Do not remove the "Player" race, it is useful for those who want to balance certain objects in player vs player maps.

**Comment by dastgir** [comment]
You misunderstood @Triedge
The bonus should be removed from that specific item, because it already have bonus for DemiPlayer (DemiHuman+Player)

**Comment by Triedge** [comment]
ah... is okay (y)

**Comment by Ridley8819** [comment]
Fixed in #1465
