### ISSUE TITLE
input script cmd gets stuck when use next cmd

### ISSUE THREAD

**Issue by Angelmelody** [HerculesWS/Hercules#1285]
When I use 'next' cmd  before or after 'input' cmd , the running script will get stuck...

```
prontera,156,150,5	script	test1234	4W_SAILOR,{
input .@temp$;
next;
mes ""+.@temp$;
close;
}
```

**Comment by dastgir** [comment]
I remember this bug very well, (and maybe it's client side), which needs mes before input
@hemagx could you confirm if its client or server side bug?

**Comment by hemagx** [comment]
it's matter of put next; before mes;
you should always start npc with mes or the client will bug on next

**Comment by 4144** [comment]
This is client side issue
