### ISSUE TITLE
Error and Warning

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1293]
I got this in log/map-msg_log.log. Any idea?

(05/17/2016 15:34:58) [ Error ] : script_set_reg: cannot write instance variable ''ins_nyd2', NPC not in a instance!
(05/17/2016 15:34:58) [ Debug ] : Source (NPC): Yggdrasil Gatekeeper at nyd_dun02 (100,201)
(05/17/2016 15:35:04) [ Error ] : script_set_reg: cannot write instance variable ''ins_nyd2', NPC not in a instance!
(05/17/2016 15:35:04) [ Debug ] : Source (NPC): Yggdrasil Gatekeeper at nyd_dun02 (100,201)
(05/17/2016 15:45:41) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 15:45:41) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 15:45:43) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 15:45:43) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 15:54:32) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 15:54:32) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:04:49) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:04:49) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:04:52) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:04:52) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:06:43) [ Error ] : script_set_reg: cannot write instance variable ''ins_nyd2', NPC not in a instance!
(05/17/2016 16:06:43) [ Debug ] : Source (NPC): Yggdrasil Gatekeeper at nyd_dun02 (100,201)
(05/17/2016 16:06:50) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:06:50) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:21:28) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:21:28) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:21:36) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 16:21:36) [ Warning ] : script_get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
(05/17/2016 17:16:17) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Brilliant Statue#tt3 (id=110009838).

**Comment by Emistry** [comment]
probably your player trying to use the NPC that belong to instance, but the players isn't actually located within the instance map.

make sure your char is located in the instance map, and not the "original map" that used to create instance.

**Comment by iRagno** [comment]
All the npcs inside the instanced maps (1@nyd and 2@nyd in this case) are attached to the instance, but those outside from instance aren't and because of that they can't read instance variables and requires to be manually attached on script to be able to read instance vars.
