### ISSUE TITLE
dispbottom bug

### ISSUE THREAD

**Issue by secretdataz** [HerculesWS/Hercules#1297]
When you pass long message with a colon `:` at the end of the message to `dispbottom` script command, the client that receive the message crashes.

Test case
https://gist.github.com/secretdataz/a935a4f0b956799671fd6c41b6a38dbf

client : 2014-10-22b

**Comment by dastgir** [comment]
This is client specific bug, try upgrading the client and it won't happen. (It happens on most 2014 clients)
Which client are you using?

**Comment by secretdataz** [comment]
@dastgir Sorry, forgot to provide the client date. I was using 2014-10-22b.

**Comment by dastgir** [comment]
As I said above, it happens on most 2014 client, it's client side bug.
Keeping this issue open (if other devs agree to add some preventive measures for this kind of this)

**Comment by Emistry** [comment]
I think they have already fixed it in newer client... seem fine when i test using 2015 clients.

![image](https://cloud.githubusercontent.com/assets/1075099/18412283/1652d4a0-77bd-11e6-8470-4e0fff7d94ea.png)

**Comment by secretdataz** [comment]
Yep, only happen on some specific clients.
