### ISSUE TITLE
Disguise bug with moving Mobs.

### ISSUE THREAD

**Issue by Triedge** [HerculesWS/Hercules#1300]
The disguise, you transform into the monster, but the monster moves, it stays stuck in the ground, use @refresh updates the position of the monster.

**Comment by Paoly28** [comment]
also happens with Kage/Oborou Illusion ( the poring transforming thingy ) very buggy, client thinks you are still a poring and prevents you from changing equipment.

**Comment by Angelmelody** [comment]
I have same issue  reported here https://github.com/HerculesWS/Hercules/issues/1268
hope devs  can fix this bug

**Comment by vBrenth** [comment]
Hello, Do this thing and the bug will be fixed.
https://github.com/HerculesWS/Hercules/issues/1078#issuecomment-171530319

**Comment by vBrenth** [comment]
This thing was related.
https://github.com/HerculesWS/Hercules/issues/1078

I tried to do 2nd of the last comment and it works, but when undisguising the mob still there.
@dastgir  fix please....

**Comment by Ridley8819** [comment]
@MishimaHaruna can you take care of this?

**Comment by MishimaHaruna** [comment]
Marking as duplicate of #1078 (I'll track that one instead)
