### ISSUE TITLE
Awakening potion bug for sinx? With critical status

### ISSUE THREAD

**Issue by ermanherman** [HerculesWS/Hercules#1305]
Hi there,

On battle flag im enable this feathers: show_katar_crit_bonus: yes

The problem start is:

1. When we eat AWAKENING POTION (656) it also give crit status, i belive this potion will have no effect on crit right? ( off course you need to equip weapon katar type.

2. From my player screenshot once the status ended, the crit value can become underflow, mean it will become NEGATIVE value.

hope you guys can fix it asap. From my point of view if we disable  show_katar_crit_bonus the bug still there it just not showing on client sided.

@Michieru @das @4144

**Comment by ermanherman** [comment]
Extra info: To reproduce the other way round.

1. Eat awakening potion.
2. Wear katar type weapon (it will show normal)
3. Die 
4. Extra crit bonus obtained

**Comment by ermanherman** [comment]
@dastgir

**Comment by ermanherman** [comment]
@MishimaHaruna

**Comment by ermanherman** [comment]
this is crtical issue. Not only potion but if u having buff your crit status will ruin till -98342758974

**Comment by dastgir** [comment]
Critical become negative? Can you provide screenshot?

**Comment by dastgir** [comment]
#1459 would fix it

**Comment by dastgir** [comment]
Fixed https://github.com/HerculesWS/Hercules/commit/8f9d06128b6cebc776c87af1a0df736847bd803c
