### ISSUE TITLE
Error on SQL

### ISSUE THREAD

**Issue by Dumnezeu** [HerculesWS/Hercules#1309]
console giving error on SQL at new version of MySQL (>= 5.7),

[SQL]: DB error - Incorrect date value: '0000-00-00' for column 'birthdate' at row 1
[Debug]: at ..\src\login\acount_sql.c:687 - UPDATE 'login' SET 'userid'=id?,'user_pass =?,'sex =?,
email'=?,'group_id'=?,'state'?,'unban_time'=?,'expiration_time' =?,'logincount'=?.'lastlogin'=?,'last_ip'=?,'birthdate'=?,'character_slots'=?,'pincode =?,'pincode_change =? WHERE 'account_id' = '1'

**Comment by MishimaHaruna** [comment]
This should be fixed as of 10660a9 (PR #1344)
