### ISSUE TITLE
Assassin Left-Hand (Dual Wield) Fix.

### ISSUE THREAD

**Issue by zXemnas** [HerculesWS/Hercules#1310]
Hello, if anyone had an issue with Left Hand weapons (the damage could not be reduced) like this:

1.- http://i.imgur.com/JQhzHY4.jpg **105% Resist Against Earth**
2.- http://i.imgur.com/Xs6HgE4.jpg **RH Dagger + LH Axe/Dagger - Damage is 0**
3.- http://i.imgur.com/6oxBDZH.jpg **RH Dagger + LH Sword = Damage bypass Defense**

This is a solution: **Tested on Hercules v2015**

Search: Type 4 (**1h Weapons**).

```
Id: 1101
AegisName: "Sword"
Name: "Sword"
Type: 4 <<< This
```

Change to: 

```
Id: 1101
AegisName: "Sword"
Name: "Sword"
Type: 5 <<< This
```

This goes for all one-handed weapons. **Don't put Type 5 on Dual Hand Weapons!**

Have a good night.

**Comment by MishimaHaruna** [comment]
Why would you ever want to change the type of weapons to 'Armor'? It'll cause all sort of terrible issues if you do.

**Comment by Ridley8819** [comment]
Closing this
