### ISSUE TITLE
Duplicate 'type' in pc_readparam

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#1311]
```
#ifndef RENEWAL_CAST
        case SP_VARCASTRATE:
        ....
        ....
#endif
```

and

```
#ifdef RENEWAL_CAST
        case SP_VARCASTRATE:     val = sd->bonus.varcastrate; break;
        ....
        ....
#endif
```

**Comment by hemagx** [comment]
it's not duplicate, tho i think it's bad code styling (and i believe i did it myself)
as you can notice one is under if renewal enabled and the other if not :)

**Comment by Emistry** [comment]
o-o .. lol .. i actually didnt noticed the `n` within the `ifndef` and `ifdef`
