### ISSUE TITLE
Frenzy's full heal do not heal fully

### ISSUE THREAD

**Issue by xsium** [HerculesWS/Hercules#1312]
Hello everyone, 
i know some  encountered  this  problem  before but i couldn't find a good fix for this.

While  taking damages/attacking, activation of frenzy do not fully  heal the user.

I hope there is someone out there  that have  a solution ^^
Thanks to  anyone  who took a bit of time  for me.

**Comment by Emistry** [comment]
doesnt seem like able to reproduce your issue.

it does fully heal my char when the char use frenzy halfway attacking/attacked by monster.

**Comment by Ridley8819** [comment]
Tested several scenarios but can't reproduce this.
