### ISSUE TITLE
Speed pots and 

### ISSUE THREAD

**Issue by vBrenth** [HerculesWS/Hercules#1314]
SC_MOVHASTE_POTION and SC_MOVHASTE_INFINITY not working (latest hercules)

**Comment by AnisotropicDefixation** [comment]
The statuses were updated to accept values from scripts instead of having fixed bonuses, check a look at the current item_db for examples.

**Comment by vBrenth** [comment]
Well actually i used speed pots on the latest hercules, and it doesnt increase my movement speed.
