### ISSUE TITLE
Iron Fist skill (champion)

### ISSUE THREAD

**Issue by yoongjun** [HerculesWS/Hercules#1327]
Is there an issue with Champion's Iron Fist? Apparently at level 10 it says that it will give +30 ATK if a fist/knuckle is equipped. However on equipping a fist/knuckle the bonus ATK from the skill doesn't seem to show on the Atk status tab.

**Comment by AnisotropicDefixation** [comment]
Masteries don't show in the status window and the bonus is different from normal Weapon/Equipment/Status ATK.
