### ISSUE TITLE
Failed Assertion

### ISSUE THREAD

**Issue by Dumnezeu** [HerculesWS/Hercules#1331]
getting error "Failed Assertion" when using @guild command on the latest revision..
[IMG]http://i65.tinypic.com/fz0jro.png[/IMG]

**Comment by 4144** [comment]
This is issue with emperium deletion.
By creating with at command guild, it try to delete emperium and if not found, removing it in index -1 in inventory. And in new code was added checks for indexes.

This pr should show error in original place: https://github.com/HerculesWS/Hercules/pull/1334

**Comment by 4144** [comment]
Error should be fixed now
