### ISSUE TITLE
Missing .spr and .act files. Missing Sprite that you can't name

### ISSUE THREAD

**Issue by git2jvin** [HerculesWS/Hercules#1332]
#Hello, regarding to this original post http://herc.ws/board/tracker/issue-2288-missing-sprite-that-you-cant-name/

i have the same issue, the client crashed after using @monster 2934 command. the mobID is Arch Angeling, and the error shows up like these: 
![error1](https://cloud.githubusercontent.com/assets/20241776/16520324/008d50a6-3fc2-11e6-83c9-5b72d68b7e6c.png)
![error2](https://cloud.githubusercontent.com/assets/20241776/16520325/00956c50-3fc2-11e6-98f8-b2c038fed811.png)
![error3](https://cloud.githubusercontent.com/assets/20241776/16520326/0098b0ea-3fc2-11e6-8d97-e5162ecb9b34.png)
![error4](https://cloud.githubusercontent.com/assets/20241776/16520327/00aaec10-3fc2-11e6-97f2-c68eeee139ba.png)

please, anyone can help me with this. THANK YOU!

**Comment by HeroGarr** [comment]
This is really not an emulator issue, but a client one. You probably miss the right definitions in lua files.
