### ISSUE TITLE
The writing direction for NPC

### ISSUE THREAD

**Issue by changelets** [HerculesWS/Hercules#1335]
Hi,

It is well-know that in English language we write from left to right. However, in my first language, the writing direction is from right to left.

Therefore, I need to change the writing direction of NPC messages, where can I do that?

Thanks!

**Comment by dastgir** [comment]
Clientside needs to be changed to align line by right,
However RTL still can  be viewed(line aligned to left though), if you write script in any language that is RTL.

**Comment by changelets** [comment]
from where can I change the Clientside
