### ISSUE TITLE
Attack Missed

### ISSUE THREAD

**Issue by dfabsgwapings** [HerculesWS/Hercules#1341]
Does anyone know how to fix this?
My character is experiencing attack missed always when they attacking all monsters physically or using weapons even the monster pupa or ant egg. the char is already wearing god items or powerful items but they cant kill this monster by a single attack. it keeps on doing attack missed before killing the monster.
 
ASPD is 196
ALLSTATS is already at maximum
 
Please help me out thanks

**Comment by Emistry** [comment]
what is your "AllStats" amount? 

check your char status window, it's probably caused by overflow of value.
