### ISSUE TITLE
Clif.c error in updated hercules

### ISSUE THREAD

**Issue by vuluts** [HerculesWS/Hercules#1345]
Hello Hercules Community,
 
I just want to report an error regards with build action in visual studio 2015 using updated git clone of hercules.
 
Previous hercules git clone is working fine without showing any errors when building, but when I try to pull and get updated hercules, it gives me an error.
 
Please check this topic for the screenshot of the error http://herc.ws/board/topic/12994-updated-git-hercules-error/

Thank you in advance.

**Comment by MishimaHaruna** [comment]
Fixed, thank you
