### ISSUE TITLE
Missing Script Commands

### ISSUE THREAD

**Issue by Ridley8819** [HerculesWS/Hercules#1362]
Hercules is missing some script commands which are needed for some of the new instances ( e.g. refined or enchanted but unidentified). But they are in general useful and were requested at forums quite often. I saw there are some versions available, but in my opinion it is a must have anyways. 

---

- [x] `makeitem2 <itemid/name>,<amount>,"<map name>",<X>,<Y>,<identify>,<refine>,<attribute>,<card1>,<card2>,<card3>,<card4>;`

just like  getitem2 you can create an item where you can set  several settings, but like makeitem it is dropped on the floor

---

- [x] setunitdata/getunitdata (setmobdata, setmobdir, call it however you want) :name_badge: 
there was a plugin available and I know Anni was working on implementing it. https://trello.com/c/rxxqfcw5/65-setunitdir-getunitdir
http://herc.ws/board/topic/11097-setmobdata-getmobdata/
Again this is quite important for instances because many of the new instances boss's stats depend on the partysize. Here it is important to avoid those:
https://github.com/rathena/rathena/issues/462
https://github.com/rathena/rathena/issues/516
https://github.com/rathena/rathena/issues/751

I think there was a mobcontroller back in eA, but was removed long ago 

---

- [x] specialeffect3
is simple... special effect on specific mob

```
clif->specialeffect(map->id2bl(script_getnum(st,2)), script_getnum(st,3),AREA);
return true;
```

but I bet you can do it better xP

**Comment by AnisotropicDefixation** [comment]
I use this to call effects on a specified GID:

`BUILDIN(specialeffect3) {
	int type, unit_id;
	struct block_list *bl;
	enum send_target target = script_hasdata(st,3) ? (send_target)script_getnum(st,3) : AREA;

	type = script_getnum(st,2);
	unit_id = script_getnum(st,4);
	bl = map->id2bl(unit_id);

	if (bl != NULL)
		clif->specialeffect(bl, type, target);

	return true;
}`

Regarding new instances and mobdata stuff, Annie's version is mostly fine, though some tweaks would be nice but the current unitwarp doesn't work consistently and is often skipped in blocks calling multiple functions (especially those involving modifying the GID's mob data).

**Comment by Emistry** [comment]
`makeitem2` has been implemented https://github.com/HerculesWS/Hercules/commit/ac6fd81810e6afb1ef60e7f2c7f8fc6e03408724

**Comment by iRagno** [comment]
setunitdata / getunitdata are reviewed on #1584 Implementation of unit controlling script commands.

**Comment by mekolat** [comment]
instead of adding a new command (`specialeffect3`) I'd suggest modifying `specialeffect` so it can take both string and integer. If a string is passed, assume it's a npc and search for it; If an integer is passed, assume it's a GID and use `map->id2bl()`

so you'd have:
* `specialeffect(<effect number>{, <send_target>{, "<NPC Name>"}})`
* `specialeffect(<effect number>{, <send_target>{, <unit id>}})`

**Comment by dastgir** [comment]
specialeffect/specialeffect2/misceffect is there since eAthena times(or jAthena time), that's why there's 3 commands with same output but for other units(npc and player)

**Comment by MishimaHaruna** [comment]
I agree with @mekolat that there's no need to introduce yet another command when the same can be reused, in cases like this where it won't cause ambiguity.
