### ISSUE TITLE
Item Sell History

### ISSUE THREAD

**Issue by changelets** [HerculesWS/Hercules#1384]
Hi!

I noticed that there was a problem in the Item Sell History.

After checking the sold items, the sold prices are always shown 0 zeny in the [Item Sell History]. 

Pics:
![item history](https://cloud.githubusercontent.com/assets/20261844/17275398/2475abfc-56bb-11e6-8aa6-7b6f87643abb.PNG)

After selling:
![item history 2](https://cloud.githubusercontent.com/assets/20261844/17275399/27b2c516-56bb-11e6-9c12-164a30696e07.PNG)

Thanks!

**Comment by hemagx** [comment]
is it new client feature ?

**Comment by changelets** [comment]
it is in the 2014-10-22 Client

**Comment by eyes-like-a-hawk** [comment]
It's also in the 2014-02-05, and the same thing happens there.

**Comment by hemagx** [comment]
umm probably we don't have this coded at all?
is this history thing only for the last buy/sell happened during your online session ?

**Comment by changelets** [comment]
This window history appears immediately when all items in the shop are sold out or after closing the shop.

**Comment by hemagx** [comment]
probably we don't send correct packet/data.
would need more info on this

**Comment by MishimaHaruna** [comment]
This should be fixed as of #1422 (if it isn't, please reopen)

**Comment by changelets** [comment]
Hi guys,
The issue hasn't fixed yet, has it?
