### ISSUE TITLE
Failed Assertion

### ISSUE THREAD

**Issue by Dumnezeu** [HerculesWS/Hercules#1388]
when use Lord Knight's "BERSERK" Skill and step on a Ontouch NPC Healer gives a Failed Assertion error..

**Comment by MishimaHaruna** [comment]
Could you post the assertion details please?

**Comment by Dumnezeu** [comment]
here's my screenshot
[IMG]http://i64.tinypic.com/15d6w5l.png[/IMG]

**Comment by MishimaHaruna** [comment]
What does the healer script do exactly?

**Comment by Dumnezeu** [comment]
it does auto heal , repair, combine rough elu and ori , and also agi up and blessing buffs..
here's the script..
http://pastebin.com/mzKedkA4
