### ISSUE TITLE
Leap/High Jump usable in WoE:SE

### ISSUE THREAD

**Issue by yoongjun** [HerculesWS/Hercules#1391]
Even with the gvg2 zone which restrict tk_highjump, they are still able to use the skill in WoE SE.

**Comment by kyeme** [comment]
Temporary fix:
/npc/woe-se/agit_main_se.txt
after:
`[gvgon strnpcinfo(2);](https://github.com/HerculesWS/Hercules/blob/master/npc/woe-se/agit_main_se.txt#L69)`
add:
setmapflag strnpcinfo(2),mf_zone,"GvG2";

**Comment by kyeme** [comment]
@Ridley8819

**Comment by Asheraf** [comment]
seem like command *gvgon call only map flags for gvg zone  not gvg2 , maybe we need a *gvgon2?

**Comment by Emistry** [comment]
Adding `gvgon2` seem like a redundant, or not necessary.

WOE SE and WOE FE differences  mainly in the skills that can be used in the map.
`gvgon` are just used to turn on the `Guild VS Guild` feature in the said map.

I think should just push this into the main repo.
```
gvgon strnpcinfo(2);
setmapflag strnpcinfo(2),mf_zone,"GvG2";
```

**Comment by Asheraf** [comment]
yeah you're right since its only 1 script.

**Comment by Emistry** [comment]
But it seem fine when I test in my test server, 
any steps to reproduce your issues?
have you checked the mapzone using @mapinfo ?

![](http://i.imgur.com/wkLeCuS.jpg)

**Comment by Asheraf** [comment]
this is the result with me
![Image of mapinfo](http://www.m5zn.com/newuploads/2016/08/19/jpg//84d51ef9f5bf287.jpg)

**Comment by ermanherman** [comment]
you need to add GvG2 zone in your mapflag for WOE2 MAP.
