### ISSUE TITLE
Incorrect Mob's Name Display

### ISSUE THREAD

**Issue by zenghanbiao** [HerculesWS/Hercules#1403]
I'm a Chinese,sorry for my poor english.

For my service:
I used a copy of github Hercules and compiled for these 2 configs in VS2015:
1.src\config\renewal.h:
//#define DISABLE_RENEWAL
2.src\common\mmo.h:
#define PACKETVER 20150513

then I use [ Mob DB converter ](http://haru.ws/hercules/mobdbconverter/) to edit my mob_db.conf.

for example:

> {
> 	Id: 1001
> 	SpriteName: "SCORPION"
> 	Name: "蝎子"
> 	Lv: 24
> 	Hp: 1109
> 	Sp: 0
> 	Exp: 287
> 	JExp: 176
> 	AttackRange: 1
> 	Attack: [80, 135]
> 	Def: 30
> 	Mdef: 0
> 	Stats: {
> 		Str: 1
> 		Agi: 24
> 		Vit: 24
> 		Int: 5
> 		Dex: 52
> 		Luk: 5
> 	}
> 	ViewRange: 10
> 	ChaseRange: 12
> 	Size: "Size_Small"
> 	Race: "RC_Insect"
> 	Element: ("Ele_Fire", 1)
> 	Mode: {
> 		CanMove: true
> 		Aggressive: true
> 		CastSensorIdle: true
> 		CanAttack: true
> 		Detector: true
> 		ChangeTargetMelee: true
> 		ChangeTargetChase: true
> 	}
> 	MoveSpeed: 200
> 	AttackDelay: 1564
> 	AttackMotion: 864
> 	DamageMotion: 576
> 	MvpExp: 0
> 	Drops: {
> 		Boody_Red: 70
> 		Scorpion's_Tail: 5500
> 		Elunium_Stone: 57
> 		Solid_Shell: 210
> 		Fine_Grit: 100
> 		Yellow_Herb: 200
> 		Lusty_Iron: 20
> 		Scorpion_Card: 1
> 	}
> },
> 

then I change the option " override_mob_names: 0 " to 1 or 2 in Monster.conf.

after I start my service and " @monster 1001 " ,the monster's name is still " SCORPION " not " 蝎子 ".

I wonder if is my problem or is a bug.

really confused me.

Thanks for your reading and help!

**Comment by Emistry** [comment]
same settings
- [x] - //#define DISABLE_RENEWAL
- [x] - #define PACKETVER 20150513

seem fine in my test server.

![Image of Yaktocat](http://i.imgur.com/QAD04Pg.png)

Perhaps you didnt reload the mob_db after you edited it ?

**Comment by zenghanbiao** [comment]
Thanks for you help~I take a rest yesterday and re do it just now~It worrks well~
Thanks agagin~:)

**Comment by zenghanbiao** [comment]
I wonder how to close this issue~
Stupid me - -!
