### ISSUE TITLE
Cannot use Chemical Protection ____ if that slot has no equip

### ISSUE THREAD

**Issue by eyes-like-a-hawk** [HerculesWS/Hercules#1406]
Example:

If Player A is not wearing a headgear, one cannot cast Chemical Protection Helm on Player A.
If Player B is not equipped with a shield, one cannot cast Chemical Protection Shield on Player B.

Because of this, if you got stripped, you can't use chemical protection to remove that effect.

**Comment by hemagx** [comment]
It's not a bug, Official behavior :)
