### ISSUE TITLE
Bug Tracker [ char-server.conf ]

### ISSUE THREAD

**Issue by zenghanbiao** [HerculesWS/Hercules#1407]
permission: {
		// Enable or disable creation of new characters.
		enable_char_creation: true

		// Display (New) in the server list.
		display_new: false

		// Maximum users able to connect to the server.
		// Set to 0 to disable users to log-in. (-1 means unlimited)
		max_connect_user: -1

		// Group ID that is allowed to bypass the server limit of users.
		// Default: -1 = nobody (there are no groups with ID < 0)
		// See: conf/groups.conf
		gm_allow_group: -1

		// Type of server.
		// No functional side effects at the moment.
		// Displayed next to the server name in the client.
		// 0=normal, 1=maintenance, 2=over 18, 3=paying, 4=F2P
		server_type: 0

		// Minimum Group ID to join char server when it is on char_server_type 1 (maintenance)
		maintenance_min_group_id: 99
	}

these option
display_new: false

swtich to ture but nothing happens~

**Comment by zenghanbiao** [comment]
true - -

**Comment by MishimaHaruna** [comment]
Confirmed. Working on a fix.
