### ISSUE TITLE
Taekwon Job is not load in RE

### ISSUE THREAD

**Issue by orugari** [HerculesWS/Hercules#1418]
Taekwon job SCRIPT (NPC Phoenix) is not load in RE.

- npc/re/jobs/1-1e/taekwon.txt (Wrong Script Name)
[X] payon_in01,62,10,5	duplicate(**Pheonix**)	Phoenix#TKJobChangeRE	4_M_MONK
[O] payon_in01,62,10,5	duplicate(**Phoenix**)	Phoenix#TKJobChangeRE	4_M_MONK

- npc/re/scripts_jobs.conf
[MISSING] "npc/re/jobs/1-1e/taekwon.txt",

- npc/jobs/1-1e/taekwon.txt

[?] -	script	Phoenix**::TKJobChange**	FAKE_NPC,{

**Comment by Ridley8819** [comment]
Fixed in da4f403
