### ISSUE TITLE
Homunculus Rename Bug

### ISSUE THREAD

**Issue by Ridley8819** [HerculesWS/Hercules#1424]
This bug is quite old, happens if you rename your Homunculus and the setting is to allow rename only once.

Homun Window
https://i.gyazo.com/b59234533d8da31e948e2193b0174603.png
https://i.gyazo.com/79b907c73b4230b78949c5e53a608f18.png

- After renaming it, you should see the new name in green, instead the name and the modify button disappear completely.
https://i.gyazo.com/659f538811c9bb77dad6036c85b95388.png

- Reopening the Homunculus Info will show the new name, but also the modify button is back.
https://i.gyazo.com/006bfc45ac1714ca749a87e0f1b2c8be.png

- You can still edit the name but modifying it again, now the name turns green (and the edit box disappears) but the actual name got not changed (since you can rename it only once)
https://i.gyazo.com/835a96d0fc77ecde638be089919ebc1d.png
https://i.gyazo.com/70f792a9dbbdfd49f937840a842a8999.png

- Relogging will bring back the modify button and also the box for name editing.

It should behave like the pet rename
- Input name, click modify, name turns green and the modify button disappears

**Comment by hemagx** [comment]
Probably Client Side issue, another thing Homunculs was never meant to be renamed so probably gravity never made effort in this.
