### ISSUE TITLE
scripts_removed.conf

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#1425]
[Error]: db_put: Attempted to use non-allowed NULL data for db allocated at map.c:4139

Hi i tried to put an npc path on the conf but it does not work. even for "all" 
here is a screenshots. (This version was only clone yesterday 9/11/2016)

#1 - conf
http://i.imgur.com/gZk5aJN.png
 
#2 - console
http://i.imgur.com/H7eJCtx.png
 
#3 - Ingame
http://i.imgur.com/eNIw1zI.png

**Comment by MishimaHaruna** [comment]
Confirmed. The `deleted_npcs` db in `map_read_npclist()` should have been allocated with the option `DB_OPT_ALLOW_NULL_DATA` but it wasn't. We'll fix this.

**Comment by kyeme** [comment]
Still not fixed.
Npcs are still loaded

`npc_removed_list: (
	"all",
	//"path/to/npc",
) // removed`
