### ISSUE TITLE
Emergency Call Bug

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#1428]
Hi,

Any job can walk while casting a Guild Skill
not so sure why. but i know you cant walk while casting Guild skill right?
My Herc files is latest as of 9/13/2016

Screenshot of walking while casting Ecall
http://imgur.com/a/uAu9c

**Comment by Asheraf** [comment]
make sure your gm permission set to
`all_skill: false`
in conf/groups.conf

**Comment by Mojacko** [comment]
I have not edit any configuration in the battleconf since it was a fresh copy

**Comment by kyeme** [comment]
I can confirmed. @MishimaHaruna  @4144
