### ISSUE TITLE
Can't use skill 

### ISSUE THREAD

**Issue by bangzeed** [HerculesWS/Hercules#1433]
i found error somthing in timer 

When rechar

![image](https://cloud.githubusercontent.com/assets/16998837/18512179/0a22c814-7ab2-11e6-956a-0f61d5c4b72a.png)

and can't use skill

![image](https://cloud.githubusercontent.com/assets/16998837/18512232/4fdbf0b0-7ab2-11e6-8f01-7912dbc7c7f1.png)

hercules last version
exe 2015-05-13aRagexe

**Comment by 4144** [comment]
Before in console was no other errors?

You can explain how to reproduce this error?
Need use some special skills order or move or do something else?

**Comment by bangzeed** [comment]
@4144 

yes. before in console  was normally no error.


I think is a resualt of die between use skill.

**Comment by 4144** [comment]
You get this issue only some times? Or can reproduce it?
If can reproduce, try find exact actions what can trigger issue.

**Comment by bangzeed** [comment]
@4144 

i will try.

**Comment by Ridley8819** [comment]
@bangzeed any infos on this?
