### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1434]
trunk\src\char\int_party.c(320): warning C4018: '<=': signed/unsigned mismatch

Revision: https://github.com/HerculesWS/Hercules/commit/19a06cae9a03ae7c390db18ca95b74bd6033dc4e
OS Version: Windows 7
Compiled with MVC C++ 2015

**Comment by jetkappu** [comment]
have this issue too

**Comment by mkbu95** [comment]
Got this warning as well 451b3fa .
I wonder why `party_share_level` isn't unsigned anyways? @MishimaHaruna

**Comment by hemagx** [comment]
Unsigned integers are not preferred to be used except for bitwise variables.
Signed and unsigned mix that we have currently in Hercules causes many
dangers issues and requires more useless checks
