### ISSUE TITLE
Adopt menu issue

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1440]
Original Topic by Napster: http://herc.ws/board/tracker/issue-8363-adopt-menu-issue/?gopid=23756#entry23756

client date 2014-03-05
when join party (father , mother, baby)
father , mother = base level > 70
baby = base level 1, job novice
item ring = yes , both and equip
when father click right over baby  not show menu adoption

can confirm this, thank you

**Comment by Ridley8819** [comment]
from what we saw this is a client issue itself, and not server side and therefore not fixable for us

**Comment by kyeme** [comment]
Ah ok, thats why rathena implemented .@adopt command

**Comment by Ridley8819** [comment]
At first i thought it's only for the 20140305 client and only for the father, but this is actually missing for both parents and not only in this client. It seems it is missing since ~201308 until now. 
Will investigate this further

**Comment by skyleo** [comment]
Should be fixed by https://github.com/HerculesWS/Hercules/commit/f17e94c77a59af896fa2d230ade105d2b154cc33
