### ISSUE TITLE
show_katar_crit_bonus:

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1442]
i don't know if it supposed to behave like this:

1. set at battle config "show_katar_crit_bonus: true"
2. wear infiltrator
3. buff your self with enchant poison

findings:
- critical will increase by 2x each time you buff.

**Comment by Ridley8819** [comment]
is this also related to #881?

**Comment by dastgir** [comment]
#881 was solved by the PR of Annie, but that introduced a bug of doubling Critical every time status recalculates.
I will update this(and other) PR tomorrow and should be ready to merge then...
