### ISSUE TITLE
Question about Quests carry forward upon Rebirth into Transcendent classes.

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#1445]
1. when player reach max lv 2nd job classes
2. they took a quest
3. then they rebirth into transcendent classes
4. and continue/complete the quest, gain tremendous amount of EXP as reward...
5. and probably reach max level 99/10 Novice (in private server) .. LOL 

does official server behave like this too ?
do they allow carry forward of these quests when they rebirth ?

this method was popular among the private servers.

**Comment by Ridley8819** [comment]
On official servers you can turn in a quest at any time on any level, so yes, this is official behavior :|

**Comment by hemagx** [comment]
^ Correction by default multi-level up is disabled.
@Emistry many in-game scripts is designed to work under Aegis settings and nothing else, so custom Hercules setting may effect some scripts.
