### ISSUE TITLE
Sc_Burning from card no have damage

### ISSUE THREAD

**Issue by bangzeed** [HerculesWS/Hercules#1446]
hi everyone.

I test card Banaspaty Card#4518.
I see enemies no have damage.
but I use dragon breath Sc_Burning is normaly
![image](https://cloud.githubusercontent.com/assets/16998837/18934588/b9e90e90-8604-11e6-80f8-92b249af75e6.png)

hercules last versoin

**Comment by Ridley8819** [comment]
was reported in #663
