### ISSUE TITLE
Test in Aegis

### ISSUE THREAD

**Issue by esu1214** [HerculesWS/Hercules#1449]
I have setup an Aegis Server of EP15.2.
Hope it will be helpful to Herc.
Now, the test way is here:
http://bbs.ro250.com...ewthread&tid=15

I will apply an English patch in a few days.

**Comment by hemagx** [comment]
Interesting, thank you for your effort, i'm pretty sure this can be great help.
can you please contact me on IRC (Rizon network nickname: Ema) or Forum (nickname: hemagx).
 P.S: the link seem like bad shortened by github, it's not valid.

**Comment by esu1214** [comment]
I have post the link on Herc board also.

**Comment by Ridley8819** [comment]
Closing this since it isn't an issue and is available on forums too.
