### ISSUE TITLE
item bonus reduce damage to demihuman not working

### ISSUE THREAD

**Issue by will21** [HerculesWS/Hercules#1455]
Please confirm by testing this 100% reduce damage from DemiHuman

`bonus2 bSubRace,RC_DemiHuman100; bonus2 bSubRace,RC_Player,100;`

not working

**Comment by will21** [comment]
Im using this reviesion https://github.com/HerculesWS/Hercules/tree/0f1d03f505fdc03533122db8ba19fa55f64f11b7

**Comment by dastgir** [comment]
```
bonus2 bSubRace,RC_DemiHuman**,**100; bonus2 bSubRace,RC_Player,100;
```
Did you notice Missing comma between RC_DemiHuman and 100?
(Always see map-server for error)
