### ISSUE TITLE
Differences with dialogues npcs iRO / Hercules

### ISSUE THREAD

**Issue by iRagno** [HerculesWS/Hercules#1467]
I have a question about dialogue differences from iRO npcs with Hercules npcs. Particularly, the Catalogue Magician, he has several minnor differences, but some are relevants.

on iRO he is selling "Window Shopper Catalogue"
on Herc he is selling "Universal Catalog Silver"

The Universal Catalog Silver is the name of the item that can be obtained through this npc, but this npc is a Catalogue Magician who is selling the brand new invention from the Geffen Magic Academy called "Window Shopper Catalogue" (that gives name to those kind of times).

The second relevant difference is when player doesn't have enought Zeny to buy from him.

on iRO he says: "Find some junk to sell or borrow it if you need to."
on Herc he says: "You can sell your equipment to make more money... if you want."

Since the little magician is a shy magician, I don't think that message fits with it's personality.

So, I know this is a very minnor issue, but I'm interested to know what Hercules thinks about iRO official dialogues, if that's something without importance or if should be update to fit with iRO.

**Comment by Mysteries** [comment]
Well technically, iRO dialogue is a "last to go to" type of scenario.

**Comment by Ridley8819** [comment]
As Mystery said here, and as we stated before, iRO dialogues are always the last option. I'm closing this
