### ISSUE TITLE
RG_FLAGGRAFFITI give a warning when used

### ISSUE THREAD

**Issue by macabu** [HerculesWS/Hercules#1482]
I know the skill isn't implemented, but the server throws a misleading warning:
`ShowWarning("skill_castend_pos2: Unknown skill used:%d\n", *skill_id);`

Adding a case for RG_FLAGGRAFFITI removes the warning and does nothing anyways
`case RG_FLAGGRAFFITI: break;`

**Comment by Kenpachi2k13** [comment]
The message exactly points out the issue. The skill isn't implemented so it's unknown for the server.
`close();`
