### ISSUE TITLE
script_removed bug

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#1483]
Hi,
It seems that script_removed.conf disables not only the File you input in the files instead it disable all the files inside the path of the file you wanted to disable.

For example you put
"npc/merchants/renters.txt",
it will disable all the Files in the merchants folder.
tested on the latest hercules git - 10/22/2016

**Comment by MishimaHaruna** [comment]
Confirmed. The DBMap in `map_read_npclist` is using a value too small for its key's max length, causing all files that begin with i.e. `npc/merchants` to be treated the same way.
