### ISSUE TITLE
re / item_db.conf

### ISSUE THREAD

**Issue by recca062** [HerculesWS/Hercules#1484]
I don't know if this was intended, but I was looking around item_db, I saw several weapons in Renewal item_db.conf having "Type: 5". Isn't weapon suppose to be Type: 4 instead ?

**Comment by recca062** [comment]
To be specific, it's these 6 items, 1935, 1936, 1989, 1990, 1991 and 2024.

**Comment by Angelmelody** [comment]
https://github.com/HerculesWS/Hercules/commit/696cf014fc7e662e32f37bf6ffe4a391961db621

https://github.com/HerculesWS/Hercules/commit/8085199aa69e36a46bd14140e40a366d27894cfb

**Comment by Angelmelody** [comment]
db/re/item_db.conf | 80 +++++++++++++++++++++++++++---------------------------
 1 file changed, 40 insertions(+), 40 deletions(-)

diff --git a/db/re/item_db.conf b/db/re/item_db.conf
index 17287fa..0a75788 100644
--- a/db/re/item_db.conf
+++ b/db/re/item_db.conf
@@ -18462,7 +18462,7 @@ item_db: (
 	Id: 1681
 	AegisName: "Short_Foxtail_Staff"
 	Name: "Short Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Atk: 30
 	Range: 1
@@ -18478,7 +18478,7 @@ item_db: (
 	Id: 1683
 	AegisName: "Enriched_Foxtail_Staff"
 	Name: "Enriched Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 200
 	Atk: 50
@@ -18499,7 +18499,7 @@ item_db: (
 	Id: 1684
 	AegisName: "Long_Foxtail_Staff"
 	Name: "Long Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 200
 	Atk: 50
@@ -18521,7 +18521,7 @@ item_db: (
 	Id: 1685
 	AegisName: "Dragonfly_Sitting_Foxtail_Staff"
 	Name: "Dragonfly Sitting Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 300
 	Atk: 70
@@ -18546,7 +18546,7 @@ item_db: (
 	Id: 1686
 	AegisName: "Large_Foxtail_Staff"
 	Name: "Large Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 300
 	Atk: 70
@@ -18570,7 +18570,7 @@ item_db: (
 	Id: 1687
 	AegisName: "Beginner_Foxtail_Staff"
 	Name: "Beginner Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 100
 	Atk: 40
@@ -18591,7 +18591,7 @@ item_db: (
 	Id: 1690
 	AegisName: "Mysterious_Foxtail_Staff"
 	Name: "Mysterious Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 400
 	Atk: 80
@@ -18615,7 +18615,7 @@ item_db: (
 	Id: 1691
 	AegisName: "Strange_God_Foxtail_Staff"
 	Name: "Strange God Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 500
 	Atk: 100
@@ -18646,7 +18646,7 @@ item_db: (
 	Id: 1692
 	AegisName: "Magical_Foxtail_Staff"
 	Name: "Magical Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 600
 	Atk: 120
@@ -18677,7 +18677,7 @@ item_db: (
 	Id: 1693
 	AegisName: "Magical_Yellow_Foxtail_Staff"
 	Name: "Magical Yellow Foxtail Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 700
 	Atk: 140
@@ -18708,7 +18708,7 @@ item_db: (
 	Id: 1694
 	AegisName: "Foxtail_Model"
 	Name: "Foxtail Model"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 300
 	Atk: 150
@@ -18732,7 +18732,7 @@ item_db: (
 	Id: 1695
 	AegisName: "Delicate_Foxtail_Model"
 	Name: "Delicate Foxtail Model"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 300
 	Atk: 195
@@ -18762,7 +18762,7 @@ item_db: (
 	Id: 1696
 	AegisName: "Exquisite_Foxtail_Model"
 	Name: "Exquisite Foxtail Model"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 300
 	Atk: 240
@@ -18792,7 +18792,7 @@ item_db: (
 	Id: 1697
 	AegisName: "Exquisite_Yellow_Foxtail_Model"
 	Name: "Exquisite Yellow Foxtail Model"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 300
 	Atk: 270
@@ -18823,7 +18823,7 @@ item_db: (
 	Id: 1699
 	AegisName: "Paradise_Foxtail_Staff_I"
 	Name: "Eden Group Foxtail I"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Atk: 120
 	Matk: 135
@@ -22314,7 +22314,7 @@ item_db: (
 	Id: 1935
 	AegisName: "Ozs_New_Ukulele"
 	Name: "Oz's New Ukulele"
-	Type: 5
+	Type: 4
 	Buy: 124000
 	Weight: 1000
 	Atk: 160
@@ -22337,7 +22337,7 @@ item_db: (
 	Id: 1936
 	AegisName: "Blue_Violin"
 	Name: "Blue Violin"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 1500
 	Atk: 180
@@ -23347,7 +23347,7 @@ item_db: (
 	Id: 1989
 	AegisName: "Rhythmic_Gymnastics_Ribbon"
 	Name: "Rhythmic Gymnastics Ribbon"
-	Type: 5
+	Type: 4
 	Buy: 124000
 	Weight: 300
 	Atk: 150
@@ -23368,7 +23368,7 @@ item_db: (
 	Id: 1990
 	AegisName: "Bloody_Floral_Decoration_Microphone"
 	Name: "Bloody Floral Decoration Microphone"
-	Type: 5
+	Type: 4
 	Buy: 124000
 	Weight: 1000
 	Atk: 160
@@ -23388,7 +23388,7 @@ item_db: (
 	Id: 1991
 	AegisName: "Blue_Whip"
 	Name: "Blue Whip"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 1500
 	Atk: 180
@@ -24213,7 +24213,7 @@ item_db: (
 	Id: 2024
 	AegisName: "Infinity_Staff"
 	Name: "Infinity Staff"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Weight: 500
 	Atk: 30
@@ -41195,7 +41195,7 @@ item_db: (
 	Id: 2989
 	AegisName: "Bloody_Floral_Decoration_Bracelet"
 	Name: "Bloody Floral Decoration Bracelet"
-	Type: 4
+	Type: 5
 	Buy: 62000
 	Weight: 100
 	Slots: 1
@@ -100685,7 +100685,7 @@ item_db: (
 	Id: 13120
 	AegisName: "Heaven's_Feather_and_Hell's_Fire"
 	Name: "Heaven's_Feather_&_Hell's_Fire"
-	Type: 5
+	Type: 4
 	Buy: 1250000
 	Weight: 800
 	Atk: 150
@@ -100708,7 +100708,7 @@ item_db: (
 	Id: 13122
 	AegisName: "Altea_and_Ares"
 	Name: "Altea & Ares"
-	Type: 5
+	Type: 4
 	Buy: 1450000
 	Weight: 1000
 	Atk: 200
@@ -100730,7 +100730,7 @@ item_db: (
 	Id: 13124
 	AegisName: "Altea_and_Ares_"
 	Name: "Altea & Ares"
-	Type: 5
+	Type: 4
 	Buy: 1450000
 	Weight: 1000
 	Atk: 200
@@ -101774,7 +101774,7 @@ item_db: (
 	Id: 13189
 	AegisName: "Color_Scope"
 	Name: "Color Scope"
-	Type: 5
+	Type: 4
 	Buy: 1350000
 	Weight: 1200
 	Atk: 240
@@ -101796,7 +101796,7 @@ item_db: (
 	Id: 13190
 	AegisName: "RAG203"
 	Name: "RAG203"
-	Type: 5
+	Type: 4
 	Buy: 1800000
 	Weight: 1300
 	Atk: 260
@@ -101819,7 +101819,7 @@ item_db: (
 	Id: 13192
 	AegisName: "Death_Fire"
 	Name: "Death Fire"
-	Type: 5
+	Type: 4
 	Buy: 1250000
 	Weight: 2000
 	Atk: 400
@@ -101842,7 +101842,7 @@ item_db: (
 	Id: 13193
 	AegisName: "Rolling_Thunder"
 	Name: "Rolling Thunder"
-	Type: 5
+	Type: 4
 	Buy: 1350000
 	Weight: 1800
 	Atk: 280
@@ -101865,7 +101865,7 @@ item_db: (
 	Id: 13194
 	AegisName: "Peace_Breaker"
 	Name: "Peace Breaker"
-	Type: 5
+	Type: 4
 	Buy: 1950000
 	Weight: 1400
 	Atk: 250
@@ -101887,7 +101887,7 @@ item_db: (
 	Id: 13195
 	AegisName: "RAG203_"
 	Name: "RAG203"
-	Type: 5
+	Type: 4
 	Buy: 1800000
 	Weight: 1300
 	Atk: 260
@@ -101909,7 +101909,7 @@ item_db: (
 	Id: 13196
 	AegisName: "Peace_Breaker_"
 	Name: "Peace Breaker"
-	Type: 5
+	Type: 4
 	Buy: 1950000
 	Weight: 1400
 	Atk: 250
@@ -101932,7 +101932,7 @@ item_db: (
 	Id: 13197
 	AegisName: "Mini_Mei"
 	Name: "Mini Mei"
-	Type: 5
+	Type: 4
 	Buy: 1600000
 	Weight: 2500
 	Atk: 220
@@ -101951,7 +101951,7 @@ item_db: (
 	Id: 13198
 	AegisName: "Tempest"
 	Name: "Tempest"
-	Type: 5
+	Type: 4
 	Buy: 2200000
 	Weight: 2500
 	Atk: 250
@@ -101974,7 +101974,7 @@ item_db: (
 	Id: 13199
 	AegisName: "Tempest_"
 	Name: "Tempest"
-	Type: 5
+	Type: 4
 	Buy: 2200000
 	Weight: 2500
 	Atk: 250
@@ -124590,7 +124590,7 @@ item_db: (
 	Id: 15150
 	AegisName: "White_Shirt"
 	Name: "White Shirt"
-	Type: 4
+	Type: 5
 	Buy: 20
 	Weight: 50
 	Def: 25
@@ -145451,7 +145451,7 @@ item_db: (
 	Id: 20788
 	AegisName: "Private_Doram_Manteau"
 	Name: "Private Doram Manteau"
-	Type: 4
+	Type: 5
 	Buy: 20
 	Weight: 300
 	Def: 20
@@ -145471,7 +145471,7 @@ item_db: (
 	Id: 20789
 	AegisName: "Luxury_Doram_Manteau"
 	Name: "Luxury Doram Manteau"
-	Type: 4
+	Type: 5
 	Buy: 20
 	Weight: 400
 	Def: 25
@@ -145492,7 +145492,7 @@ item_db: (
 	Id: 20790
 	AegisName: "Elegant_Doram_Manteau"
 	Name: "Elegant Doram Manteau"
-	Type: 4
+	Type: 5
 	Buy: 20
 	Weight: 500
 	Def: 30
@@ -149988,7 +149988,7 @@ item_db: (
 	Id: 26101
 	AegisName: "Paradise_Foxtail_Staff_III"
 	Name: "Eden Group Foxtail Staff III"
-	Type: 5
+	Type: 4
 	Buy: 20
 	Atk: 150
 	Matk: 195

**Comment by dastgir** [comment]
I guess this can be closed now.
Reopen if anything is missed.
