### ISSUE TITLE
skill.c mob bug in juperos

### ISSUE THREAD

**Issue by tangama** [HerculesWS/Hercules#1489]
[Error](skill.c:12176:): --- nullpo info --------------------------------------------

[Error](skill.c:12176:): ./map-server(assert_report+0x81) [0x626b01]

[Error](skill.c:12176:): ./map-server(skill_unit_onplace_timer+0x387) [0x5a75d7]

[Error](skill.c:12176:): ./map-server(skill_unit_timer_sub_onplace+0xb7) [0x5ae267]

[Error](skill.c:12176:): ./map-server() [0x4f31c8]

[Error](skill.c:12176:): ./map-server(map_vforeachinshootrange+0x8f) [0x4fd48f]

[Error](skill.c:12176:): ./map-server(map_foreachinshootrange+0x81) [0x4f2a41]

[Error](skill.c:12176:): ./map-server(skill_unit_timer_sub+0x302) [0x5b7df2]

[Error](skill.c:12176:): ./map-server() [0x61e151]

[Error](skill.c:12176:): ./map-server() [0x61d19c]

[Error](skill.c:12176:): ./map-server(skill_unit_timer+0x36) [0x5ae376]

[Error](skill.c:12176:): --- end nullpo info ----------------------------------------

**Comment by Ridley8819** [comment]
Closing this too. Half a year old and not aware of anyone else having this problem. If it still persists, feel free to open a new issue using the new template in order to gather all informations required to help you
