### ISSUE TITLE
map error

### ISSUE THREAD

**Issue by will21** [HerculesWS/Hercules#1508]
what issue is this? need help here thank you

[Error]: --- failed assertion --------------------------------------------
[Error]: skill.c:198: 'skill_lv > 0' in function `skill_get_blewcount'
[Error]: ./map-server(assert_report+0x7d) [0x6229fd]
[Error]: ./map-server(skill_get_blewcount+0xc3) [0x595593]
[Error]: ./map-server(unit_run_hit+0x156) [0x60d466]
[Error]: ./map-server(unit_run+0x20d) [0x611f2d]
[Error]: ./map-server(status_change_start+0x116c) [0x5feb1c]
[Error]: ./map-server(unit_resume_running+0xb4) [0x60de94]
[Error]: ./map-server(do_timer+0x22a) [0x62781a]
[Error]: ./map-server(main+0x173) [0x436623]
[Error]: /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f1f9134ab15]
[Error]: ./map-server() [0x4366f9]
[Error]: --- end failed assertion ----------------------------------------

**Comment by Ridley8819** [comment]
Closing this too. Half a year old and not aware of anyone else having this problem. If it still persists, feel free to open a new issue using the new template in order to get all informations required to help you
