### ISSUE TITLE
skill.c:12032: 'bst' in function `skill_unit_onplace_timer'

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1510]
my log is full of this error, i was wondering if you can help me.  I can't reproduce as i only see this on the logs:

`(11/12/2016 12:57:14) [ Error ] : skill.c:12032: 'bst' in function `skill_unit_onplace_timer'
(11/12/2016 12:57:14) [ Error ] : ./map-server(assert_report+0x83) [0x629e63]
(11/12/2016 12:57:14) [ Error ] : ./map-server(skill_unit_onplace_timer+0x3cc) [0x5a9a6c]
(11/12/2016 12:57:14) [ Error ] : ./map-server(skill_unit_timer_sub_onplace+0xb8) [0x5b0858]
(11/12/2016 12:57:14) [ Error ] : ./map-server() [0x4f57d8]
(11/12/2016 12:57:14) [ Error ] : ./map-server(map_vforeachinshootrange+0x94) [0x4ff9b4]
(11/12/2016 12:57:14) [ Error ] : ./map-server(map_foreachinshootrange+0x81) [0x4f5041]
(11/12/2016 12:57:14) [ Error ] : ./map-server(skill_unit_timer_sub+0x2b2) [0x5ba4d2]
(11/12/2016 12:57:14) [ Error ] : ./map-server() [0x6212d8]
(11/12/2016 12:57:14) [ Error ] : ./map-server() [0x620350]
(11/12/2016 12:57:14) [ Error ] : ./map-server(skill_unit_timer+0x36) [0x5b0966]
(11/12/2016 12:57:14) [ Error ] : --- end nullpo info ----------------------------------------
`

**Comment by Ridley8819** [comment]
Closing this as already outdated. Feel free to open a new issue following the Template to provide all info needed to help you.
