### ISSUE TITLE
getcharid(CHAR_ID_GUILD) returns value of guild leader's char ID

### ISSUE THREAD

**Issue by eyes-like-a-hawk** [HerculesWS/Hercules#1512]
Hi,

I'm not sure about the other types, but whenever I try to use the script command `getcharid` to return a guild ID, it always returns the wrong number.

Example:
`.@guild_id = getcharid(CHAR_ID_GUILD, "" + strcharinfo(PC_NAME) + "");`
`mes "Your guild ID is " + .@guild_id + ".";`

When the script shows it will say:

> Your guild ID is 150137.

When I check SQL, my guild's ID is 36.
**Update:** It seems `150137` is the value of the guild master's char id. Any reason why this is happening?

**Comment by eyes-like-a-hawk** [comment]
update:

ok so it seems the 150137 is the value of the guild master.
Any reason this is happening?

**Comment by dastgir** [comment]
Seems it's returning char Id.
You can optimize the script as:
```
.@guild_id = getcharid(CHAR_ID_GUILD);
mes "Your guild ID is " + .@guild_id + ".";
```

If it still shows, you can try to add this mes below it and show the output;
```
mes "Constant Value "+ CHAR_ID_GUILD;
```

**Comment by dastgir** [comment]
Also , Be sure there's no mod messing with guild id.

**Comment by eyes-like-a-hawk** [comment]
Constant value came back as 0.
And I tried that - comes back with the same ID.

I don't know of any mods that exist on our server that would cause this.
Tried turning of all plugins, no change.

**Comment by eyes-like-a-hawk** [comment]
Sorry to bother, I just found out when our dev merged to new revision he missed out getcharid in constants.conf. Sorry to bother.

Your answer helped me figure out when constant value returned 0.
