### ISSUE TITLE
Map server issue

### ISSUE THREAD

**Issue by eyes-like-a-hawk** [HerculesWS/Hercules#1516]
Does anybody know what this error is? Just wondering cause it keeps coming up but we can't seem to figure out what is causing it.

```
[Error]: --- nullpo info --------------------------------------------
[Error]: skill.c:12126: 'bst' in function `skill_unit_onplace_timer'
[Error]: ./map-server(assert_report+0x80) [0x645500]
[Error]: ./map-server(skill_unit_onplace_timer+0x419) [0x5c5fa9]
[Error]: ./map-server(skill_unit_timer_sub_onplace+0xc9) [0x5cf5b9]
[Error]: ./map-server() [0x50c1ed]
[Error]: ./map-server(map_vforeachinshootrange+0x99) [0x516ed9]
[Error]: ./map-server(map_foreachinshootrange+0x97) [0x515947]
[Error]: ./map-server(skill_unit_timer_sub+0x2b3) [0x5d3743]
[Error]: ./map-server() [0x63c57a]
[Error]: ./map-server() [0x63bbf2]
[Error]: ./map-server(skill_unit_timer+0x36) [0x5cf6d6]
[Error]: --- end nullpo info ----------------------------------------

```

**Comment by tlacson7** [comment]
somewhat related to my issue
https://github.com/HerculesWS/Hercules/issues/1510

i cant figure out also what causes it, my log is full of that message.

**Comment by dastgir** [comment]
Some plugin is causing it maybe, there's reference to plugin, so try disabling plugin and try, if it does, then there might be slight different message(all stack would have function name), that would be more helpful

**Comment by Ridley8819** [comment]
closing this as well since there was no reply since nearly half a year. Feel free to open a new issue following the new template to provide all info required in order to help you.

**Comment by tlacson7** [comment]
How to recreate error. Im using pre-renewal
1.  Place trap
2.  Use arrow shower on traps.
