### ISSUE TITLE
Chance in Shadow refiner.

### ISSUE THREAD

**Issue by Atemo** [HerculesWS/Hercules#1524]
Githash e1453434af18b30119114077dfc52d27ad196cef

The __double chance__ in the Shadow refiner should only be available for Enrich ore.
https://github.com/HerculesWS/Hercules/blob/master/npc/re/merchants/shadow_refiner.txt#L161

**Comment by hemagx** [comment]
Correct, actually according to the official script it doesn't support enriched at all.
@dastgir @Asheraf @Emistry wanna help?

**Comment by Asheraf** [comment]
I would take it.
