### ISSUE TITLE
Pincode isn't been saved on database.

### ISSUE THREAD

**Issue by gilbertobitt** [HerculesWS/Hercules#1531]
Hercules commit **9795505**
Hexed Version: ** 2016-02-03aRagexeRE**
[SQL]: DB error - Out of range value for column 'pincode_change' at row 1
[Debug]: at account_sql.c:654 - UPDATE `login` SET `userid`=?,`user_pass`=?,`sex`=?,`email`=?,`group_id`=?,`state`=?,`unban_time`=?,`expiration_time`=?,`logincount`=?,`lastlogin`=?,`last_ip`=?,`birthdate`=?,`character_slots`=?,`pincode`=?,`pincode_change`=? WHERE `account_id` = '2000000'
[Info]: Char load request (150000)

**Comment by Asheraf** [comment]
Hercules support only clients  up to 20151216, your client may have differences in the pincode system.

**Comment by gilbertobitt** [comment]
thank's! so i will disable it for now!

**Comment by gilbertobitt** [comment]
@Asheraf  can u give me a link to a 20151216 ragexe Unpacket?

**Comment by Ridley8819** [comment]
Side note:
On kRO the numbers doesnt switch anymore (during Input). I didnt check if this is client or server related or since when it does behave like this

**Comment by leomoyses** [comment]
Same error :(

Can't get it to work even on 2014-10-22 or 2015-05-13

**Comment by MishimaHaruna** [comment]
This might actually be our fault, not the client's. Does anyone know if the pincode feature ever worked at all? (honestly, I'd never use it personally, it looks really annoying)

I see that we're building the query with a parameter of type `SQLDT_LONG`, despite the variable we pass to it is an unsigned int:
https://github.com/HerculesWS/Hercules/blob/master/src/login/account_sql.c#L651
https://github.com/HerculesWS/Hercules/blob/master/src/login/account.h#L55

Now, this was probably written on a windows machine or on a 32 machine, and it seemed to work correctly, but it won't work at all on 64 bit machines running a UNIX-based OS (most common use case of Hercules), where `sizeof(long) != sizeof(unsigned int)`.
Note (for those that aren't aware): when passing a type other than `SQLDT_STRING`, `SQLDT_ENUM` or `SQLDT_BLOB`, the last argument to `SQL->StmtBindParam()` is ignored, so the `sizeof(acc->pincode_change)` won't be considered but the hardcoded size of `SQLDT_LONG` (which evaluates to `sizeof(long)` is considered instead.

It looks like we have various places where this happens. Maybe it's time for improvements to the sql functions, to detect this at runtime.

As a quick fix for this issue, @leomoyses  can you check if everything works by changing the line I mentioned (as well as the matching line in the previous query just a few lines above) to use `MYSQLDT_UINT` instead?

**Comment by dastgir** [comment]
Pincode works on official server and still is used.

**Comment by Ridley8819** [comment]
I used the Pincode before on both, 20141022 and 20150513 without problems, haven't used it in a while tho.

**Comment by leomoyses** [comment]
@MishimaHaruna 

Sorry about the long delay, that fixed it!

Thank you very much ;)

**Comment by MishimaHaruna** [comment]
Thank you for testing, @leomoyses 

Reopening as a self-reminder to push the fix
