### ISSUE TITLE
getstatus() error when reading remaining time with permanent status effect

### ISSUE THREAD

**Issue by iRagno** [HerculesWS/Hercules#1543]
When trying to read the remaining time of status effect with a permanent effect, it shows console error:

> [Error]: --- failed assertion --------------------------------------------
> [Error]: ..\src\common\timer.c:368: 'tid > 0' in function `unknown`
> [Error]: --- end failed assertion ----------------------------------------
> [Error]: script:op_2: invalid data for operator C_ADD
> [Debug]: Data: C_ARG
> [Debug]: Data: string value="Time Left: "
> [Debug]: Source (NPC): Testing1 at prontera (50,50)

NPC for testing:

> prontera,50,50,0	script	Testing1	PORING,{
> 	mes "Time Left: " + getstatus(SC_SUMMER, 5);
> 	close;
> }

Item for test: 2776 - Cool_Towel

Tested with 9795505a14327d5d2603a1d756633485e7e2ba94 version.

**Comment by Emistry** [comment]
you posted a wrong script?
I didnt saw anything that match the error message
`Lefting Time: "`

**Comment by Ragn0** [comment]
It was for bad english, I changed after then. Thanks for notice it ^^;

Anyway, result is the same, it is not string problem, but getstatus() command.

**Comment by dastgir** [comment]
-1 = Infinite Timer, which doesn't even allocate the timer, thus error.
Need to modify the getstatus command to support infinite timers and return -1.

**Comment by Ragn0** [comment]
Wow, thanks a lot @dastgir.
