### ISSUE TITLE
getunitdata on script instance

### ISSUE THREAD

**Issue by rotloso** [HerculesWS/Hercules#1546]
![ggg](https://cloud.githubusercontent.com/assets/15043452/21970871/9114084c-dbdd-11e6-823b-e89d9afba6c6.png)

i follow >>> this link [http://herc.ws/board/topic/11097-setmobdata-getmobdata/](url)
 but i cant fixed it because some code it change,

i follow >>> [http://herc.ws/wiki/Building_HPM_Plugin_for_MSVC](url)
for i need to know how to install plugin but plugin can't compile got error

i cant find this Script >>>
![asdfasd](https://cloud.githubusercontent.com/assets/15043452/21971078/c9f6204e-dbdf-11e6-998a-7a2c3217c28b.png)
i update hercules last version on Github some code it change,

anyone help me fixed or teach me

sorry for my english

**Comment by dastgir** [comment]
This is custom issue not Hercules emulator issue. So closing this. Better ask at forum.
However, the link is of setmobdata and script you use have setunitdata
