### ISSUE TITLE
Map_zone_db.conf Issue

### ISSUE THREAD

**Issue by dfabsgwapings** [HerculesWS/Hercules#1547]
Hi to all developer of herc. I just want to let you all know that there is an issue with the map_zone_db.conf. This file should be able to disable all the items that you will be setting up in it. It seems that it is only working for usable or consumable items like potions and etc but this one seems does not include the file or code that can disable the usage of the equipments. Please fix someone fix this.

**Comment by hemagx** [comment]
The equipment get disabled, well you can wear it, however it's effect disabled.

**Comment by dfabsgwapings** [comment]
From the previous file name itself, noequip meaning that should nlt be able to wear at all. Cause if it does the players will be under the expression that its working. This should totally disable the player equipping the item at all.

**Comment by Emistry** [comment]
https://github.com/HerculesWS/Hercules/blob/master/conf/map/battle/items.conf#L111-L116
you can adjust the settings here.
