### ISSUE TITLE
Abracadabra Skill generating skill IDs that don't exist

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#1550]
Hello,

Recently we have been getting a lot of these in the console:
`[Error]: pc_checkskill: Invalid skill id 16383 (char_id=2159616)`

Lots of messages like above appear. It is abracadabra attempting to generate skill ids that don't exist. We can't figure out why it is doing this.

**Comment by Kenpachi2k13** [comment]
I did a lot of testing with `SA_ABRACADABRA` during the last two weaks and couldn't trigger this.
Additionally no one else reported this within three years.
`close();`
