### ISSUE TITLE
Nydhoggur's Nest second floor (2@nyd) monsters bunched in the middle

### ISSUE THREAD

**Issue by eyes-like-a-hawk** [HerculesWS/Hercules#1551]
Is it normal for all the monsters on 2@nyd to be bunched like such in the middle? 

As seen here: http://i.imgur.com/qFGJdlZ.jpg

**Comment by AnisotropicDefixation** [comment]
Surprised this hasn't been fixed yet, I reported it ages ago myself here:

http://herc.ws/board/tracker/issue-8657-nydhoggs-nest/

Just change all coordinates inside the "ins_nyd2_spawn_mobs" block from 200,92,180,80 to 18,20,381,177.

**Comment by eyes-like-a-hawk** [comment]
Thank you @AnisotropicDefixation. I even searched on rathena, same. Even on old eathena files - same.

**Comment by Mysteries** [comment]
@Ridley8819  @dastgir

**Comment by Ridley8819** [comment]
I once wondered too about that but wasn't aware of the issue. 
The old aegis script really spawns all mobs like that (in that small area part). But as mentioned this doesn't seem correct and looks more like a mistake. Also the 2nd coords are not on walkable gat at all. 
For now I'd just mark the whole area
