### ISSUE TITLE
Removing invisible state with @option on hidden GM

### ISSUE THREAD

**Issue by iRagno** [HerculesWS/Hercules#1556]
This is a minnor issue. In maps with pvp activated, when setting `@option 0` on GM with /hide state and then update it's location, will crash to every player that enters on is area of vision.

How to reproduce it:

1. Use `@pvpon` on a map
2. Use `/hide` command
3. Use `@option 0` command
4. Use `@jump` or a _warp portal_ to reenter the map
5. Every player who walks nearby the gm, will have a client crash

Tested on 2015-05-13aRagexe.

**Comment by Emistry** [comment]
I noticed after `step 3`, the other player can't see the player which already unhidden (using `@option 0`), just like the disguise issue we had currently..
then when jump back to the player `step 4`, confirmed client crashed.

**Comment by 4144** [comment]
in hercules invisible gms is not really invisible. most packets from gms visible for all players. But normal clients ignoring it. Exists pr for fix this, but it may break other "invisible" things not related to gms.

Probably here client issue because it see partial visible gms and crashing.
