### ISSUE TITLE
Compiling new git clone without change anything

### ISSUE THREAD

**Issue by chryxt** [HerculesWS/Hercules#1566]
This error occure when im compiling new git clone without change anything
This i tried 2 times already creating new git clone but same problem. I didnt change anything at map/atcommand.c at all...
`make[1]: Entering directory `/home/trunk/src/map'
        MKDIR   obj_sql
        CC      atcommand.c
{standard input}: Assembler messages:
{standard input}:49982: Warning: end of file not at end of a line; newline inserted
{standard input}:51101: Error: unknown pseudo-op: `.'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[1]: *** [obj_sql/atcommand.o] Error 4
make[1]: Leaving directory `/home/trunk/src/map'
make: *** [map_sql] Error 2`

**Comment by MishimaHaruna** [comment]
What OS and gcc version are you running? Hoe much RAM does the machine have?

**Comment by chryxt** [comment]
im using centOS 7.3 from digitalocean, 512 RAM 
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Ridley8819** [comment]
i can't reproduce this

**Comment by hemagx** [comment]
512MB ram....

**Comment by MishimaHaruna** [comment]
A VPS with 512MB or RAM is enough to compile Hercules with GCC 4.8, but you should try to minimize the amount of other programs running, and minimize the parallel compilation as much as possible (avoid using the `-j` option of make, shutdown SQL servers, web servers, X servers or anything else the VPS might be running).

**Comment by chryxt** [comment]
im installing lamp and mariadb sql on this VPS, cant ya? ill try creating 1 gb then, thanks a lot ya :)

**Comment by anacondaqq** [comment]
> 512MB ram....

I can run Hercules on 128MB ram VPS. It's not a problem.

**Comment by Smokexyz** [comment]
I think this can be closed now as the issue has been addressed.
