### ISSUE TITLE
Chat Room on nochat cells

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#1569]
In a map with no chat cells, there is a way to put chats on them.

1. First player creates chat room on a chat-allowed cell.
2. Second player, who is currently standing on a nochat cell, enters chat room.
3. First player leaves chat room.

Chat room is now on nochat cell.

**Comment by psychonaut04** [comment]
If i remember it's possible to(don't know if it was fixed):
1. Open chat room creation window, put the name but don't create it yet.
2. Start walking to a nochat cell.
3. Create the chat room while walking to the nochat cell but while still in the chat-allowed cell.
Character will move to the nochat cell.
