### ISSUE TITLE
About Training Edition

### ISSUE THREAD

**Issue by Iniciando** [HerculesWS/Hercules#1573]
Topic in Herc with all information: http://herc.ws/board/topic/1442-real-info-about-training-edition/
Open in: Jul 08 2013

From what I realized, there are still a few things missing.
I was browsing through rathena and realized it was just implemented there.
 
https://github.com/r.../commit/7a011ec
 
A lot of information can help us.
Greetings.

**Comment by Asheraf** [comment]
part of #240 could be closed.
