### ISSUE TITLE
Clan System

### ISSUE THREAD

**Issue by Iniciando** [HerculesWS/Hercules#1574]
Topics in Herc with all information: 
http://herc.ws/board/topic/11591-clan-system/page-2?hl=%20clan%20%20system
http://herc.ws/board/blog/1/entry-48-a-peek-on-clans/?st=20#commentsStart
http://herc.ws/board/topic/8340-suggestion-return-to-guilds-system/?hl=%2Bclan+%2Bsystem#entry49667
http://herc.ws/board/topic/4906-request-clan-system/?hl=%2Bclan+%2Bsystem
http://herc.ws/board/topic/3623-clan-system/?hl=%2Bclan+%2Bsystem

Commit in rAthena: https://github.com/rathena/rathena/pull/1511

**Comment by Asheraf** [comment]
this is already a part of issue #241 and it could be closed.

**Comment by Ridley8819** [comment]
one of several duplicates, still, thank you for your interest
