### ISSUE TITLE
Special Characters on character name

### ISSUE THREAD

**Issue by mnjfx** [HerculesWS/Hercules#1576]
Hi All,

I am having trouble with the special characters in game. I've checked everything I can on my end. tried 2 different clients and still no luck.

The thing is, it has no problems on my local ( windows ) server. On our test ( hosted/linux ) server it doesn't show.

When I use the • and ™ whole character name shows up as blank.

[spoiler]

[/spoiler]

char_server.conf

[spoiler]

		// Character name configuration
		name: {
			// Name used for unknown characters
			unknown_char_name: "Unknown"

			// Allow or not identical name for characters but with a different case (upper/lower):
			// example: Test-test-TEST-TesT; Value: 0 not allowed (default), 1 allowed
			name_ignoring_case: false

			// Manage possible letters/symbol in the name of charater. Control character (0x00-0x1f) are never accepted. Possible values are:
			// NOTE: Applies to character, party and guild names.
			// 0: no restriction (default)
			// 1: only letters/symbols in 'name_letters' option.
			// 2: Letters/symbols in 'name_letters' option are forbidden. All others are possibles.
			name_option: 0

			// Set the letters/symbols that you want use with the 'char_name_option' option.
			// Note: Don't add spaces unless you mean to add 'space' to the list.
			name_letters: "abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890~!@#$%^&*()_+`-=[]\{}|;':<>?,./•™"
		}

[/spoiler]

Tried the following clientinfo.xml settings

First

[spoiler]

<?xml version="1.0" encoding="euc-kr" ?>
<clientinfo>
	<desc>Ragnarok Client Information</desc>
	<servicetype>korea</servicetype>
	<servertype>sakray</servertype>
	<connection>
		<display>Server</display>
      		<address></address>
      		<port>6900</port>
      		<version>20</version>
      		<langtype>1</langtype>
		<registrationweb></registrationweb>
        <aid>
            <admin>2000000</admin>
			<admin>2000001</admin>
			<admin>2000002</admin>
			<admin>2000003</admin>
			<admin>2000004</admin>
			<admin>2000005</admin>
			<admin>2000006</admin>
			<admin>2000007</admin>
			<admin>2000008</admin>
			<admin>2000009</admin>
			<admin>2000010</admin>
        </aid>
   	</connection>
</clientinfo>

[/spoiler]

Second

[spoiler]

<?xml version="1.0" encoding="euc-kr" ?>
<clientinfo>
	<desc>Ragnarok Client Information</desc>
	<servicetype>korea</servicetype>
	<servertype>primary</servertype>
	<connection>
		<display>Server</display>
      		<address></address>
      		<port>6900</port>
      		<version>20</version>
      		<langtype>0</langtype>
		<registrationweb></registrationweb>
        <aid>
            <admin>2000000</admin>
			<admin>2000001</admin>
			<admin>2000002</admin>
			<admin>2000003</admin>
			<admin>2000004</admin>
			<admin>2000005</admin>
			<admin>2000006</admin>
			<admin>2000007</admin>
			<admin>2000008</admin>
			<admin>2000009</admin>
			<admin>2000010</admin>
        </aid>
   	</connection>
</clientinfo>

[/spoiler]

Sorry, wrong section, if a mod comes by please move to correct section

**Comment by MishimaHaruna** [comment]
The • and ™ characters aren't part of the ASCII character set. As such, their representation depends on the character set and encoding your editor is using, which should be configured to use the same encoding as the Ragnarok client you use to connect to the server. Likewise, the Ragnarok clients don't support unicode, and still use the legacy Windows character sets, making them very dependent on the settings of the computer they're run on (in other words, what you see as ™ on your client, might have a completely different appearance on someone else's client).

**Comment by Kenpachi2k13** [comment]
Issue not caused by emulator.
`close();`
