### ISSUE TITLE
Special Characters Problem

### ISSUE THREAD

**Issue by mnjfx** [HerculesWS/Hercules#1577]
Hi All,

I am having trouble with the special characters in game. I've checked everything I can on my end. tried 2 different clients and still no luck.

The thing is, it has no problems on my local ( windows ) server. On our test ( hosted/linux ) server it doesn't show.

When I use the • and ™ whole character name shows up as blank.

whole description on this : http://herc.ws/board/topic/14307-special-character-problem/#entry80436

**Comment by Emistry** [comment]
closing this ... duplicate of #1576 .
