### ISSUE TITLE
some bugs skills.

### ISSUE THREAD

**Issue by minneman** [HerculesWS/Hercules#1597]
Skill kunai splash take the element of weapon and no the element of kunai.

Skill Intense Telekinesis dont give triple dmg with ghost element skills, i tested this and  2.2k of dmg up just to 3.6k and no to 6.6k.

dragon breath dont take racial modifiers, bonus long rang atk and element bonus http://irowiki.org/wiki/Dragon_Breath

**Comment by AnisotropicDefixation** [comment]
Yeah all of those are broken but DB is only boosted by ranged damage % modifiers, nothing else.

**Comment by minneman** [comment]
Ok, thanks, you know if the DB is available to miss?

2017-03-02 0:40 GMT-03:00 AnisotropicDefixation <notifications@github.com>:

**Comment by AnisotropicDefixation** [comment]
DB ignores flee.

**Comment by minneman** [comment]
So, also this is wrong, actually db isn't ignore flee on hercules last
version

**Comment by Fraterna** [comment]
just a lil bump for a intense telekinesis fix, it's been a year alreasy...

**Comment by MrKeiKun** [comment]
long range modifiers applies to dragon breath? This seems to be an iRO thing
