### ISSUE TITLE
[minor] skill_reproduce_db dump

### ISSUE THREAD

**Issue by shennetsind** [HerculesWS/Hercules#162]
In the line of thought of #141 

```
bool skill_reproduce_db[MAX_SKILL_DB];
```

soon to become skill->reproduce_db, but could be ducked for the same reasons, regardless, imo, and be put with skill_db. as opposed to #141 there wouldn't be processing improvement though, but there is no reason for it to be separate from skill_db since the amount of memory being spent is the same, it should be easier to browse as well.

**Comment by Asheraf** [comment]
done in 0080d1e4e6ca38074e4493ea6b05884d9b358519
