### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by julinhobrow** [HerculesWS/Hercules#1622]
script.c: In function ‘buildin_classchange’:
script.c:13939:4: error: too many arguments to function ‘clif->class_change’
    clif->class_change(bl, class, type, sd);
    ^
script.c:13942:3: error: too many arguments to function ‘clif->class_change’
   clif->class_change(bl, class, type, NULL);

**Comment by Asheraf** [comment]
Please follow the issue template https://github.com/HerculesWS/Hercules/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by julinhobrow** [comment]
script.c: In function ‘buildin_classchange’:
script.c:13939:4: error: too many arguments to function ‘clif->class_change’
clif->class_change(bl, class, type, sd);
^
script.c:13942:3: error: too many arguments to function ‘clif->class_change’
clif->class_change(bl, class, type, NULL);

**Comment by julinhobrow** [comment]
its all linux

**Comment by 4144** [comment]
@julinhobrow you already got link HOW report issues.
Also this is not at issue in hercules. This is your local code mess.

**Comment by Mysteries** [comment]
Issues should be addressed when you are working with a clean bill of Hercules.

**Comment by julinhobrow** [comment]
a new install whe compile centos 5 centos 6 centos 7  debian 8 ubuntu 14.04 opensuse 10 fedora 25 mandriva and anothers linux in host only hercules has this error i use rathena and compile normally. its when do
git clone and do ./configure make clean make sql without none changes.

**Comment by Emistry** [comment]
you're not using latest/clean Herc.
https://github.com/HerculesWS/Hercules/blob/master/src/map/script.c#L13962-L13969
`clif->class_change(bl, class, type, sd);`
they got 4 parameters, not 3.

even the line number of your error (Line 13939) doesn't match with clean Herc.

**Comment by julinhobrow** [comment]
i update a clean version has 15 min and same error when compile

**Comment by 4144** [comment]
@julinhobrow your error say what you not using clean hercules.
In clean hercules this error impossible.

**Comment by julinhobrow** [comment]
its latest herc and totally clean. im waiting a solution not this wrong answers all give to me, if dont go resolve say nothing.

**Comment by Ridley8819** [comment]
I don't think anyone is saying you're lying, but pointing on the fact that it's not possible to have this error in a clean herc. 
How did you obtain it? Running it locally or on a host? Is it a pre installed ro hosting? You simply need to follow the template and provide all requires informations rather than a random error. I would suggest you to open a new issue and follow the template there.

**Comment by julinhobrow** [comment]
but this error is on a clean herc, when you say but pointing on the fact that it's not possible to have this error in a clean herc. you say im lying. because is a clean herc install
what i do only
git clone https://github.com/HerculesWS/Hercules.git
cd Hercules
./configure
make clean
make sql

and give me
script.c: In function ‘buildin_classchange’:
script.c:13939:4: error: too many arguments to function ‘clif->class_change’
clif->class_change(bl, class, type, sd);
^
script.c:13942:3: error: too many arguments to function ‘clif->class_change’
clif->class_change(bl, class, type, NULL);

i put now a rathena, becauce peoples here dont give a solution.
