### ISSUE TITLE
Command 'opendressroom'

### ISSUE THREAD

**Issue by Likeeit** [HerculesWS/Hercules#1624]
Implement new script command for new clothes Renewal, dressroom, released on JRO.

http://herc.ws/board/topic/3146-new-improved-3rd-job-sprites/
http://herc.ws/board/topic/11531-dress-pack/

https://github.com/rathena/rathena/commit/d70b1734c8bff8a27d8251b2d16d43e7b309cb64

**Comment by Ridley8819** [comment]
Dressroom is pure preview and actually doesn't change anything. You can change appearance using setlook for bodystyle.

**Comment by AnisotropicDefixation** [comment]
The command is still needed though.

**Comment by Ridley8819** [comment]
The command yes, I just wanted to clarify it has nothing to do with the actual change progress

**Comment by Iniciando** [comment]
Correctly. As previously reported, you can change the view via setlook or @bodystyle in script mode. However, for the customer will make a difference, because the dress room will not be opened, and thus impossible an entire preview with a visual aspect.

**Comment by Likeeit** [comment]
Reference 3CeAM.
https://github.com/3CeAM/3CeAM/commit/fe3a1bac7e617ebb9070631a6540c6f3402c2dac
