### ISSUE TITLE
Gentle Touch Change doesnt add damage correctly

### ISSUE THREAD

**Issue by kairu** [HerculesWS/Hercules#1629]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)
I've only modified the source to make gentle touch change viewable from the status window.
### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)
Gentle touch change should add their respected stats right away but it will only add after you've casted asura strike on a target.

### Expected Behavior

[//]: # (Tell us what should happen instead.)
Right after you've casted gentle touch change, stats should already be applied.

### Steps To Reproduce The Issue
This is without editing the viewable src to see the difference.
1. Spawn a Monster/Barricade
2. Use Asura strike and record your damage.
3. Use Finger Offensive and record your damage.
4. Cast gentle touch change
5. Use Asura strike and record your damage.
6. Use Finger Offensive and record your damage.
7. Repeat 5 and 6.

Also Reproduceable by having gentle touch change buffed and relogging.

### Screenshots (Viewable edited)
Without Gentle Touch Change
![a](https://cloud.githubusercontent.com/assets/9050808/23850381/1afe2ee4-081a-11e7-9390-c310bf158f4b.jpg)
With Just Buffed Gentle Touch Change after using Asura strike
![b](https://cloud.githubusercontent.com/assets/9050808/23850382/1b04f364-081a-11e7-8fdc-6872dcc0fef2.jpg)
With Gentle Touch Change right after giving gentle touch's change attack buff from 2nd Asura Strike
![c](https://cloud.githubusercontent.com/assets/9050808/23850383/1b0711f8-081a-11e7-9570-3fd42d2db7dc.jpg)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): '7b4d4fb92603ef1e622b52e777cd5ac1b7f97d55'
[Info]: Git revision (scripts): '7b4d4fb92603ef1e622b52e777cd5ac1b7f97d55'

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by Smokexyz** [comment]
Please mention the git revision hash/commit in your report.

**Comment by kairu** [comment]
Updated

**Comment by AnisotropicDefixation** [comment]
This buff needs SCB_WATK declaration in the initChangeTables block, it's currently missing.

`status->set_sc( SR_GENTLETOUCH_CHANGE    , SC_GENTLETOUCH_CHANGE          , SI_GENTLETOUCH_CHANGE    , SCB_ASPD|SCB_MDEF|SCB_MAXHP );`
