### ISSUE TITLE
Script Command "input".

### ISSUE THREAD

**Issue by gcbucci** [HerculesWS/Hercules#1640]
Git Hash: 137d985
PACKETVER 20151104

Script command "input". The last letter is always missing, example: if input "Hercules", the script only input "Hercule". The last letter is always missed by the script / emulator.

@4144 

Thx

**Comment by 4144** [comment]
Look like need port some changes from hercules forks...

**Comment by 4144** [comment]
I will create pr tomorrow

**Comment by 4144** [comment]
@gcbucci see pull request
