### ISSUE TITLE
WoE Party Skill behavior is wrong

### ISSUE THREAD

**Issue by skyleo** [HerculesWS/Hercules#1647]
## Issue Prelude
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

## Description
The party skill behavior of WoE is not correct concerning the kind of players it should target, as in allies, enemies and guildmates.

### Current Behavior
You can only devote your own guildmates.
You can only Angelus/Gloria/Magnificat your own guildmates.

*The main problem about this behavior is that you can't target your allies with all party-based buffs.*

### Expected Behavior
You should be able to devote **anyone** inside your party, no matter if they are your guildmate, ally or enemy.
You should be able to Angelus/Gloria/Magnificat/etc anyone inside your party, as stated above.

I have tested the above expected behavior on iRO Classic at War of Emperium together with @phaicm .
Check this video out if you want to see for yourself:
http://skyleo.de/herc/testing_session_party_cut.mp4
(Actual testing starts at 1:30, first minute is preparation)

*Enemies inside your party can attack you, this is correct behavior. As well being able to attack an enemy that you devoted and getting the damage yourself. This includes skills like Provoke, Mindbreaker as well.*

### Steps To Reproduce The Issue
Can be reproduced with any Hercules version since this change:
http://herc.ws/board/tracker/issue-7336-gvg-noparty-is-missing/

**Branch(es):**
- [x] master
- [ ] other

[Info]: Hercules 64-bit for Linux
[Info]: Git revision (src): '01c0080be70d93cd57389b1b01ec694eadf926d2'
[Info]: Git revision (scripts): '7ae9186ff6efac28047180ba836f480e8b158cc9'

### Operating System
Debian GNU/Linux 8.6 (jessie) [x86_64]

**Comment by Asheraf** [comment]
fixed in cb4297e6eb734c60825ebfa13f32989fa3a470eb
