### ISSUE TITLE
Item Sell History (2)

### ISSUE THREAD

**Issue by changelets** [HerculesWS/Hercules#1658]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

Hello guys, 

I have submitted this issue around 7 months ago (Issue #1384), and it was supposed to be fixed as of #1422, however, I think it is still not fixed. I hope you guys reopen the issue in order to fix it.

Friendly reminder: 
> Hi!
>I noticed that there was a problem in the Item Sell History.
>After checking the sold items, the sold prices are always shown 0 zeny in the [Item Sell History]. 
>Pics:
![item history](https://cloud.githubusercontent.com/assets/20261844/17275398/2475abfc-56bb-11e6-8aa6-7b6f87643abb.PNG)
>After selling:
![item history 2](https://cloud.githubusercontent.com/assets/20261844/17275399/27b2c516-56bb-11e6-9c12-164a30696e07.PNG)
>Thanks!

**Comment by Ridley8819** [comment]
Hum when I tested it, it worked, can't remember what client I used. Which one you used?

**Comment by changelets** [comment]
Hi Ridely,

The one I used was 2015-05-11.
I was wondering if you could tell me the one you used. I would appreciate that deeply!

Thanks!

**Comment by changelets** [comment]
You are right! The problem was already solved!

Thank you so much guys ^_^!
