### ISSUE TITLE
[Critical] Walk after IC Skill cast or NPC interaction

### ISSUE THREAD

**Issue by guippiccoli** [HerculesWS/Hercules#1668]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
**Before anything: It bodered me that no one has talked about that before. The NPC bug is anoying at most, but the Skill bug is game breaking. Thats FAR from official interaction and impossible to run a serious server with that.**

Unwanted player movement after NPC or Skill interaction. Tested with rAthena also, same bug. Characters is moving to the mouse location after cast an instant skill or talk with an npc that has no mes() function.

## Prints of the two bugs
- [NPC Bug](https://media.giphy.com/media/xUPGck4N4wytK97GLu/giphy.gif)
![NPC Bug](https://media.giphy.com/media/xUPGck4N4wytK97GLu/giphy.gif)
- [Skill Bug](https://media.giphy.com/media/xUPGcr7rZkvrxZWRJC/giphy.gif)
![Skill Bug](https://media.giphy.com/media/3ohzdX8zORtTbbK7Is/giphy.gif)

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior
- **When clicking a NPC that have no mes() function**: The npc click event is triggered but the player also walks to the mouse position.
- **When using intant casts skill (150 dex SG, arrow shower, etc) (only one click)**: The skill is evoked but the player also walks to the mouse position

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior
- **When clicking a NPC that have no mes() function**: Trigger the NPC and not move the character.
- **When using intant casts skill (150 dex SG, arrow shower, etc) (only one click)**: Evoke the skill and not move after cast.

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

**Skill Bug:**
1. Download Hercules -> Compile
2. Cast an instant skill (usualy preRE since RE has fixed cast formula)
3. The character will cast the skill then walk to the mouse location as if the skill cast click had also the interaction of a normal click (walk). See the pictures of test for yourself to understand better.

**Skill Bug:**
1. Download Hercules -> Compile
2. Script an NPC with no mes() function, like a healer that can heal with one click.
```
prt_fild01,280,144,5	script	empty_npc	4W_SAILOR,{
	heal(100,100);
	end;
}
```
3. The character will be healed and then walk to the mouse position, as if the click of the npc also triggered the normal mouse click (walk). (same problem as the skill bug, but different situation)

**Branch(es):**
- [x] master

**Hercules rev. hash/commit:** 
Git revision src: 083ed4ad7a30bdc3172b3ef2a66bb257c0c0e70f
`[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): '1af6b6c61fe266f1477754767d7551bdfc6dd1b0'
[Info]: Git revision (scripts): '1af6b6c61fe266f1477754767d7551bdfc6dd1b0'
[Info]: OS version: 'Windows 8 Professional (build 9200) [x86_64]'`

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Tested clients
- 2014-02-05bRagexe
- 2015-05-13aRagexe
- 2015-11-04aRagexe

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by MishimaHaruna** [comment]
The 2013-08-07 Ragexe seems to be unaffected:

![](https://cl.ly/2U2N3k2r1G21/Screen%20Recording%202017-04-09%20at%2015.36.gif)

I'm unable to test it on newer clients, but it does seem a clientside problem. Is anyone else experiencing this with 2014 clients or newer?

**Comment by Ridley8819** [comment]
read it a few times in forums and in github, but i couldn't reproduce, using different 2013/14/15/16 and 17 clients

**Comment by Asheraf** [comment]
Tested on those clients but can't reproduce on anyone:
* 2012-04-10
* 2013-08-07
* 2015-05-13
* 2017-01-25

**Comment by guippiccoli** [comment]
A client patch maybe? Tried with several clients and with rAthena, always same results. I heard of other people having the same issue too, I'm impressed that no one here was able to reproduce. Wierd.

Here's the profile.log of nemo (basicly the recommended patches)
`2 Chat Flood Allow
8 Custom Window Title
9 Disable 1rag1 type parameters (Recommended)
13 Disable Ragexe Filename Check (Recommended)
16 Disable Swear Filter
18 Skip Service Selection Screen
19 Enable Title Bar Menu
20 Extend Chat Box
21 Extend Chat Room Box
22 Extend PM Box
23 Enable /who command (Recommended)
24 Fix Camera Angles (Recommended)
29 Disable Game Guard (Recommended)
30 Increase Zoom Out 50%
33 Always Call SelectKoreaClientInfo() (Recommended)
34 Enable /showname (Recommended)
35 Read Data Folder First
36 Read msgstringtable.txt (Recommended)
37 Read questid2display.txt (Recommended)
38 Remove Gravity Ads (Recommended)
39 Remove Gravity Logo (Recommended)
40 Restore Login Window (Recommended)
41 Disable Nagle Algorithm (Recommended)
44 Translate Client (Recommended)
46 Use Normal Guild Brackets (Recommended)
48 Use Plain Text Descriptions (Recommended)
49 Enable Multiple GRFs (Recommended)
50 Skip License Screen
53 Use Ascii on All LangTypes (Recommended)
64 @ Bug Fix (Recommended)
65 Load Custom lua file instead of iteminfo*.lub (Recommended)
73 Remove Hourly Announce (Recommended)
74 Increase Screenshot Quality
75 Enable Flag Emoticons
84 Remove Serial Display (Recommended)
88 Allow space in guild name
90 Enable DNS Support (Recommended)
91 Disconnect to Login Window
97 Cancel to Login Window (Recommended)
204 Increase Attack Display
213 Disable Help Message on Login (Recommended)
215 Increase Map Quality
216 Hide Cash Shop
219 Always Show Resurrection Button
227 Change Walk To Delay.
`

**Comment by dastgir** [comment]
"Change walk delay"
Remove that, and everything will be fine.

**Comment by Murilo-BiO** [comment]
dastgir is right, I was having the same problem, with the same client I patched it again and removed change walk to delay and it was fixed

**Comment by guippiccoli** [comment]
Awesome! Will try and post here the result.

**Comment by guippiccoli** [comment]
Yep, it was "Change Walk To Delay". All good without it.
