### ISSUE TITLE
Recompile Error with latest rev (4/14/17) GMT+8 12:16 AM

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#1681]
clif.c: In function 'clif_item_equip':
clif.c:2572: error: 'i' undeclared (first use in this function)
clif.c:2572: error: (Each undeclared identifier is reported only once
clif.c:2572: error: for each function it appears in.)
make[1]: *** [obj_sql/clif.o] Error 1
make[1]: Leaving directory `/root/Desktop/trunk/src/map'

**Comment by Mojacko** [comment]
just needed to add A "T" after the i
i think they forgot that line

**Comment by Asheraf** [comment]
Fixed in 14288431a07b3f699e62f94a2d81b66d8779d20a
