### ISSUE TITLE
SC_SUMMER2

### ISSUE THREAD

**Issue by Likeeit** [HerculesWS/Hercules#1683]
We do not yet have the ability to use the second summer clothing. As can be seen in the following post.

http://herc.ws/board/topic/6818-summer-2-costume-job/?hl=oktoberfest

**Comment by Asheraf** [comment]
Added in c22bc45868e8ea2b7ef904848d178caeaa6b379c

**Comment by Likeeit** [comment]
Thanks @Jedzkie ! 👍
