### ISSUE TITLE
An Issue with Items Descriptions While Selling Them in Store

### ISSUE THREAD

**Issue by changelets** [HerculesWS/Hercules#1685]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

Hi Hercules team!

Here is the issue description. After opening a store using "vending" skill, I tried to check the item description by right click. The description appears with extra FALSE information. This issue happens ONLY when items in your store. 

Please look at the picture below:
<img src="https://image.ibb.co/m6tFt5/issue.png" alt="issue" border="0"></a>

I hope this issue can be fixed. 

Thanks!

**Comment by Asheraf** [comment]
Please provide some extra informations:
- git hash
- client date
- the item originally does not have random option and it show wrong data?

**Comment by changelets** [comment]
The problem happens with weapons and armors even though they don't have random options.
Client date is 2015-05-13

Thanks for the quick reply!

**Comment by MishimaHaruna** [comment]
This should now be fixed (through #1673)
