### ISSUE TITLE
sql.c warning

### ISSUE THREAD

**Issue by lelouch22** [HerculesWS/Hercules#1687]
> sql.c: In function 'SqlStmt_BindParam':
sql.c:680: warning: cast discards qualifiers from pointer target type

Git revision: 5802b22439441be1914ae9024d6ce06d51c0210f

**Comment by 4144** [comment]
What compiler you using?

**Comment by lelouch22** [comment]
Im using CentOS 64-bit

**Comment by Smokexyz** [comment]
@lelouch22 if in your console you could type gcc -v and paste the output here.

**Comment by MishimaHaruna** [comment]
If you're running an old version of CentOS (6 or older), you'll need to update your devtoolset as recommended in https://github.com/HerculesWS/Hercules/wiki/Supported-Platforms#centos-and-red-hat-enterprise-linux 

For details on how to do it, please see my comment in issue #1262
