### ISSUE TITLE
Change Cart 2 Skill Is Not Working!

### ISSUE THREAD

**Issue by changelets** [HerculesWS/Hercules#1702]
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

Hi Hercules Team,

When I use change cart 2 skill, no window appears to select the cart shape! 
The client I used: 2015-05-13
Server mode: Pre-renewal

Hope to see the issue fixed soon!

Thanks,

**Comment by Jedzkie** [comment]
This is invalid, 2015-08-05aRagexeRE onwards supports this feature.
