### ISSUE TITLE
Tip of Today Window Features Are Not Working

### ISSUE THREAD

**Issue by changelets** [HerculesWS/Hercules#1707]
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Hi Hercules team,

I noticed that the Tip of Today window features are not working. When I write /tip, the window appears, but it doesn't display any text even though I made sure that I have all required txt files.  Also, the check option in the window is not working, I mean the one that makes the tip window appear each time you log in.

Hope to see Tip of Today window work in Hercules!

Client Used: 2015-05-13

**Comment by Ridley8819** [comment]
this is a client side issue and needs some hexing to fix.

Edit: in Nemo Beta branch there is a fix for it

**Comment by changelets** [comment]
@Ridley8819 I wasn't able to find the Nemo Beta branch, where is it located ?

**Comment by 4144** [comment]
@changelets for now look like up to date only one nemo fork.
https://gitlab.com/4144/Nemo

**Comment by changelets** [comment]
@4144 I tried the version you gave me, but there is no option for Tip of Today?

Is there a special title for that?
