### ISSUE TITLE
Recently merged prevent-logout PR needs a follow-up bug fix.

### ISSUE THREAD

**Issue by secretdataz** [HerculesWS/Hercules#1714]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)
PR #1697 causes rathena/rathena#1877 to occur.  
rAthena added rathena/rathena@f5c4332 to fix the issue.  

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)
Bug rathena/rathena#1877 should occur, preventing players from logging out in some cases.

### Expected Behavior
Players can log out.  

[//]: # (Tell us what should happen instead.)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 1bc4994

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System
Irrelevant  

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by MishimaHaruna** [comment]
Has this been tested?

From the look of it, it doesn't seem like we should be affected, our `DIFF_TICK()` differs from rAthena's.
The rAthena bug occurs because their `gettick()` is unsigned, and in `DIFF_TICK()` they subtract (risking underflows), then cast to a signed 32 bit int (risking overflows).

Our `gettick()`, instead, is a 64 bit signed integer, which is reasonably safe to subtract without underflows. Our `DIFF_TICK()` doesn't do any typecasts, and uses the result as is (int64), without underflows/overflows.

Here's an example with arbitrarily chosen values to demonstrate the bug:

```
battle_config.prevent_logout = 10000; // default value
sd->canlog_tick = 0; // This is the value it takes on login, if it's not otherwise set
// let's assume the current tick is a number larger than INT_MAX, smaller than UINT_MAX:
assert(gettick() == INT_MAX + 1);

// Line of code that's buggy in rAthena, works well in Hercules:
(!battle_config.prevent_logout || DIFF_TICK(gettick(), sd->canlog_tick) > battle_config.prevent_logout)
```

Let's replace it with values (Hercules version)

```
(!(int)10000 || DIFF_TICK((int64)(INT_MAX + 1), (int64)0) > (int)10000)
// becomes:
(false || ((int64)(INT_MAX + 1) - (int64)0) > (int)10000)
// then:
((int64)(INT_MAX + 1) > (int)10000)
// evaluates to:
(true)
```

Now the rAthena version

```
(!(int)10000 || DIFF_TICK((unsigned int)(INT_MAX + 1), (unsigned int)0) > (int)10000)
// becomes:
(false || ((int)((unsigned int)(INT_MAX + 1) - (unsigned int)0)) > (int)10000)
// then:
((int)((unsigned int)(INT_MAX + 1)) > (int)10000)
// overflows (note: this operation has undefined behavior by the C standard, but commonly produces this result):
((int)(INT_MIN) > (int)10000)
// which evaluates to:
(false)
```

This is part of a series on why using unsigned integers is a bad idea, and why they're always inappropriate (as opposed to using a larger signed integer type) if the goal is to increase the range.
