### ISSUE TITLE
custom atcommands and group permissions

### ISSUE THREAD

**Issue by mekolat** [HerculesWS/Hercules#1726]
`bindatcmd()` uses the deprecated GM level system instead of using permission groups.

A solution could be to add a new buildin to dynamically change permissions, so you'd do for example:
```c
bindatcmd("foobar", "NPC::OnUseCommand"); // register @foobar
add_group_command("foobar", 2, true, false); // allow group id 2 to use @foobar
add_group_command("foobar", 5, true, true); // allow group id 5 to use @foobar and #foobar
```

thoughts?

**Comment by VMGlab** [comment]
Isn't it the same with <group level> and <group level char> on the current bindatcmd?
*bindatcmd("command", "<NPC object name>::<event label>"{, <group level>, <group level char>, <log>})
but for better and easier and cleaner way, I'll second this.

**Comment by mekolat** [comment]
on bindatcmd the parameters are min level for @ and min level for # but that's minimum level, not an array of group IDs, so it basically forces you to give group X and up the permission

**Comment by MishimaHaruna** [comment]
Great idea, I second it

There's one use-case that it doesn't cover (but it might be unnecessary, if it's not a very common case). Assuming that if a group inherits another, the command availability is also inherited, groups.conf allows to exclude an inherited command by setting it to false in the child.
The only way I can think to support that would be to use 1, 0, -1 instead of true/false, but that's a bit ugly.

**Comment by mekolat** [comment]
@MishimaHaruna the initial idea was to make `add_group_command()` bypass inheritance, so you can explicitly set true or false for each group. If you do want to keep the inheritance in place though, it could still work:

let's say `<group b>` and `<group c>` both inherit from `<group a>`, you could do the following:
```c
bindatcmd("foobar", "NPC::OnUseCommand"); // register @foobar
add_group_command("foobar", <group a>, true, false); // allow <group a> to use @foobar, and implicitly allow <group b> and <group c> since they inherit
add_group_command("foobar", <group b>, false, false); // explicitly forbid <group b>
```
which would yield this permission tree:
* `<group a>` is `true`
    * `<group b>` is `false`
    * `<group c>` is `true`

**Comment by mekolat** [comment]
@MishimaHaruna here's an implementation that disregards inheritance: https://github.com/HerculesWS/Hercules/pull/1736

**Comment by MishimaHaruna** [comment]
Ok, ignoring inheritance sounds fine and simplifies things immensely, as long as the documentation clearly says so. I'd personally expect it to honor it if nothing is mentioned (because when I make a group inherit from another, I expect it to behave exactly like the other)

**Comment by mekolat** [comment]
merged
