### ISSUE TITLE
Pre-renewal WZ_STORMGUST freezing chance

### ISSUE THREAD

**Issue by MishimaHaruna** [HerculesWS/Hercules#173]
Commits to consider:
- 5f59e50f462873f9607ffd233550bb2e68f6d38f: - Fixed success chance of Storm Gust's freeze status change in pre-renewal, iROwiki says 150% and feedback from official server players confirmed that it is indeed 150%

**Comment by Mysteries** [comment]
Is this still relevant @MishimaHaruna

**Comment by MishimaHaruna** [comment]
It's not, it was merged as part of commit 51fd6b4d. Closing.
