### ISSUE TITLE
getmonsterinfo() sends debug warning on fail

### ISSUE THREAD

**Issue by Wolfie-Blackout** [HerculesWS/Hercules#1735]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [ ] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

Script command `getmonsterinfo` prints a 'Debug' in the map-server console.

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

In a script, when using getmonsterinfo() like such...
```
		input(.@mob);
		if (getmonsterinfo(.@mob, MOB_LV) < 0 || getmonsterinfo(.@mob, MOB_NAME) == "Dummy")
		{
			do this
		}
```

It will print warnings in the map-server console.
`[Debug]: Source (NPC): NPC at prontera (150,150)`
I tried commenting the `ShowWarning` line in script.c. The error messages go away, but the debug still appears.

### Expected Behavior

[//]: # (Tell us what should happen instead.)

doc\scriptcommands.txt tells us it should return -1. You would think -1 would be a natural response, therefore no errors. However, I still receive these debugs.

### Steps To Reproduce The Issue

Check Current Behavior script provided.

**Branch(es):**
- [ ] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Linux )
[//]: # ( [Info]: Git revision src: '0f09fc750487f712b81e1421f26016fe403c99d0' )
[//]: # ( [Info]: Git revision scripts: '0f09fc750487f712b81e1421f26016fe403c99d0' )

### Operating System

[//]: # (CentOS 7.something 64-bit)
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by mekolat** [comment]
This is on purpose, so that you can't by mistake use a mob id that doesn't exist.
It will still return `-1` but tells you in the console that there's an error with your script (it expects a mob that doesn't exist)

**Comment by dastgir** [comment]
You can use strmobinfo if you want to check if monster exist or not
