### ISSUE TITLE
Ghenirhemin in wrong position?

### ISSUE THREAD

**Issue by Wolfie-Blackout** [HerculesWS/Hercules#1737]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

In `npc/quests/newgears/2006_headgears.txt`, the NPC Ghenirhemin may have the wrong coordinates.

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

Ghenirhemin is located at `hugel,147,103` in Hercules, however, on ratemyserver.net he is located at `hugel,147,130`. I'm not sure which one is the correct one. It seems a typo has been made one way or the other.

### Expected Behavior

[//]: # (Tell us what should happen instead.)

N/A

### Steps To Reproduce The Issue

N/A

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by Jedzkie** [comment]
ratemyserver's info is incorrect. Our coordinate is correct. This is the coordinate in my Aegis.

`npc "hugel" "Ghenirhemin" 4_M_HUGRANFA 147 103 3 0 0`
