### ISSUE TITLE
variable freezing

### ISSUE THREAD

**Issue by mekolat** [HerculesWS/Hercules#1738]
Would it be desirable to have a variable freezing system? The idea would be to make it work like Ruby's [#freeze](https://apidock.com/ruby/Object/freeze) so a variable cannot be modified after freezing, which would turn it into a pseudo-constant.

```c
@var = 5;
freeze(@var);
@var = 4; // Error: can't modify frozen variables
```

**Comment by dastgir** [comment]
Any use case for having this system?

**Comment by mekolat** [comment]
I believe @MishimaHaruna was planning to have a way to create constants from scripts
