### ISSUE TITLE
like one solution for this compile error

### ISSUE THREAD

**Issue by julinhobrow** [HerculesWS/Hercules#1740]
{standard input}: Assembler messages:
{standard input}:108860: Warning: end of file not at end of a line; newline inserted
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[1]: *** [obj_sql/clif.o] Error 4
make[1]: Leaving directory `/home/ragnarok/Hercules/src/map'
make: *** [map_sql] Error 2

its in a new copy.

**Comment by dastgir** [comment]
You might be using old compiler, which uses much ram to compile hpmhook(1-2gb)
Update your compiler and you should be good.

**Comment by julinhobrow** [comment]
You might be using old compiler, which uses much ram to compile hpmhook(1-2gb)
Update your compiler and you should be good. what? if gcc 5.3 is old what can i use?

**Comment by dastgir** [comment]
Well, that error means, your machine got out of ram, maybe you have less ram in machine?

**Comment by julinhobrow** [comment]
8gb of ram

**Comment by MishimaHaruna** [comment]
This ticket is missing the basic information requested by the issue template. Please update it. Specifically, we can't help you if we don't know the version of the OS and the compiler you're using, as well as the flags you're compiling with and the command you're running.

Even if some parts aren't yet compiled, the login server is likely to be already functional, so you can obtain most of the information you need through `./login-server --version`.

**Comment by julinhobrow** [comment]
ok unique solution i reinstall OS to one more old change from centos 7 to centos 6 and work normal.
