### ISSUE TITLE
disabled_commands not recognized in custom map_zone_db.conf

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#1744]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [ ] I have not modified the source prior to reproducing this issue.
-  [ ] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

I am using pre-renewal, however, with source mods, so cannot testify if it is the same in fresh herc.
I have created custom Map Zones, defined in `map.h` and `db\pre-re\map_zone_db.conf`

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

Anything specified in
```
	disabled_commands: {
	}
```
will not be recognized and the commands can be used as normal. Every other setting works as normal, such as disabled items, disabled skills and mapflags.

### Expected Behavior

[//]: # (Tell us what should happen instead.)

Should be able to disable commands in custom zones.

### Steps To Reproduce The Issue

Here is a zone I set up. Everything works fine except @kill can be used by anybody. I tried disabling it in one of the default zones and @kill is unable to be used then.

```
{
	name: "My Zone 1"

	disabled_skills: {
		GD_EMERGENCYCALL: "PLAYER"
		AL_TELEPORT: "PLAYER"
		AL_WARP: "PLAYER"
		WZ_ICEWALL: "PLAYER"
	}

	disabled_items: {
		Yggdrasilberry: true
		Seed_Of_Yggdrasil: true
	}

	mapflags: (
		"nobranch",
		"noknockback",
		"nomemo",
		"nopenalty",
		"noreturn",
		"nosave	SavePoint",
		"noteleport",
		"novending",
		"nowarp",
		"nowarpto",
	)

	disabled_commands: {
		kill: 30
	}
},
```

**Branch(es):**
- [ ] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by mekolat** [comment]
Are you 100% sure that the group of the character you tested with does not have the use_all_commands permission?

**Comment by Wolfie-Blackout** [comment]
This is how I tested:
- My account is 99 admin
- Went to map with this zone.
- Used @adjgroup 0 to make me a player.

@kill can be used.

2nd test:
- Same as above, but include the disabled command in a different zone (say all zone)

@kill cannot be used.

**Comment by mekolat** [comment]
Did you add the `zone` mapflag to the target map? (`/npc/mapflag/zone.txt`)

**Comment by EyesOfAHawk** [comment]
Yes I added the zone. I can tell it worked because the items are disabled and all the mapflags were added.

One other thing, is actually the map is also using the mapflag `battleground 2`. Do you think this is conflicting with it?

**Comment by MishimaHaruna** [comment]
If `map_name mapflag battleground 2` is parsed *after* you set your custom zone, it will overwrite it completely.
To make this work, you have to make sure that you set the custom zone in a script that gets loaded after the battleground flag is set. That way it'll be merged with, rather than replaced by, the Battlegrounds zone.

**Comment by EyesOfAHawk** [comment]
Thanks for the clarification.
