### ISSUE TITLE
Error Skill.c

### ISSUE THREAD

**Issue by ragnasound** [HerculesWS/Hercules#1748]
(05/27/2017 22:33:01) [ Error ] : skill.c:16842: 'ud' in function `skill_clear_unitgroup'
(05/27/2017 22:33:01) [ Error ] : ./map-server(assert_report+0x80) [0x64fd90]
(05/27/2017 22:33:01) [ Error ] : ./map-server(skill_clear_unitgroup+0x77) [0x5dac47]
(05/27/2017 22:33:01) [ Error ] : ./map-server(pc_setpos+0x3d9) [0x54d8b9]
(05/27/2017 22:33:01) [ Error ] : plugins/hBG.so(skill_castend_nodamage_id_pre+0x608) [0x7f65543a12b8]
(05/27/2017 22:33:01) [ Error ] : plugins/HPMHooking_map.so(HP_skill_castend_nodamage_id+0xad) [0x7f65546a91dd]
(05/27/2017 22:33:01) [ Error ] : ./map-server(skill_castend_id+0x12b5) [0x5ca2f5]
(05/27/2017 22:33:01) [ Error ] : ./map-server(do_timer+0x1a9) [0x654959]
(05/27/2017 22:33:01) [ Error ] : ./map-server(main+0x193) [0x658b83]
(05/27/2017 22:33:01) [ Error ] : /lib64/libc.so.6(__libc_start_main+0xfd) [0x7f6556c64d1d]
(05/27/2017 22:33:01) [ Error ] : ./map-server() [0x436ec9]

**Comment by Asheraf** [comment]
Hello there, apparently this is related with the Hercules Battleground plugin so please report it in the proper place http://herc.ws/board/topic/14083-hercules-battlegrounds
