### ISSUE TITLE
SC_DANCING is missing

### ISSUE THREAD

**Issue by ragnasound** [HerculesWS/Hercules#1749]
(05/27/2017 22:40:21) [ Debug ] : status_change_end: SC_DANCING is missing skill unit group (val1=655681, val2=404775, val3=50, val4=0, timer=197, tid=-1, char_id=150914, map=lighthalzen, x=157, y=94, prev=<none>:0, from=unit.c:2449). Please report this! (#3504)

**Comment by Asheraf** [comment]
Hello there, please follow the issue template and reopen this otherwise we cant help.
