### ISSUE TITLE
Storage and teleporting

### ISSUE THREAD

**Issue by Asheraf** [HerculesWS/Hercules#1762]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Current Behavior
Using teleportation skill while storage is open wont close it.

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior
Test on kRO shows that the storage got closed when the player uses teleportation skill

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. Open storage.
2. use teleport skill.

**Branch(es):**
- [x] master

```
[Info]: Hercules 64-bit for Linux
[Info]: Git revision (src): '10cb83a30cc50d757e05924fb29c11fc68abda49'
[Info]: Git revision (scripts): '10cb83a30cc50d757e05924fb29c11fc68abda49'
[Info]: OS version: 'Ubuntu 14.04.5 LTS [x86_64]'
[Info]: CPU: 'Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz [4]'
[Info]: Compiled with GCC v4.8.4
[Info]: Compile Flags: -g -O2 -pipe -ffast-math -Wall -Wextra -Wno-sign-compare -std=c99 -Wno-unused-parameter -Wno-clobbered -Wempty-body -Winit-self -Wpointer-arith -Wformat-security -Wformat -Wformat-y2k -Wsuggest-attribute=noreturn -Wundef -Wnested-externs -Wold-style-definition -Woverlength-strings -Wredundant-decls -Wcast-qual -Wno-format-nonliteral -Wno-switch -Wno-missing-field-initializers -Wno-suggest-attribute=format -Wshadow -fno-strict-aliasing -g -fno-omit-frame-pointer -DHAVE_EXECINFO -DMAXCONN=16384 -I../common -DHAS_TLS -DHAVE_SETRLIMIT -DHAVE_STRNLEN -DDEBUG -DHAVE_MONOTONIC_CLOCK
```

**Comment by MishimaHaruna** [comment]
The current behavior (that I don't really like, it sounds like a bug to me) was implemented in commit 31486a8c3340a8ca8a8b1e5dd9084c2c07ec8614 as described at http://herc.ws/board/tracker/issue-8027-when-the-storage-is-open-you-can-use-self-skills

**Comment by kyeme** [comment]
Does KRO made some changes in its behavior ?
Based on my aegis screenshot you'll notice that storage does not close when teleport skill has been used.
http://i.imgur.com/CGhTMLP.jpg

**Comment by Asheraf** [comment]
@kyeme the storage closes after you teleport not when you use the skill.

**Comment by Asheraf** [comment]
- Current Hercules behaviour

https://drive.google.com/open?id=0B8s-sa51NSkgWjV5cFJWb2dqSzA

- kRO Sakray

https://drive.google.com/open?id=0B8s-sa51NSkgUDZ6cmI1WnJMa0k
