### ISSUE TITLE
Guild Skill Cool down

### ISSUE THREAD

**Issue by GMVyLow** [HerculesWS/Hercules#1774]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Emergency Cool Down Behaviour

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior
Currenty behaviour in herc, all guild skill cd stop when you logout or character select

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior
Guild skill cool down should continue even after logging out or character select

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. Use Emergency guild skill
2. logout for 5 minutes
3. relogin and try using the emergency call again

**Branch(es):**
- [x] master
- [x] other

**Hercules rev. hash/commit:** 

Git revision src:
b22380aaeaa429e90df47a7f645a22a64a5ac952

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System
Centos 6
[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by Emistry** [comment]
check your settings?
https://github.com/HerculesWS/Hercules/blob/master/conf/map/battle/guild.conf#L42-L45

**Comment by GMVyLow** [comment]
That would make emergency call usable again after relogin, the current issue here is to continue its timer even after logging out or character select. Meaning if you logout with 4 minutes cd remaining and relogin after a minute, cd for guildskill will be 3 minutes.

**Comment by moguri85** [comment]
AFAIK this is the intended behaviour :/

**Comment by GMVyLow** [comment]
ive been playing as a Guild Master in pRO for almost 10 years and this is not what ive encountered on pRO days. Guild skill cd continues even when i logout

**Comment by kyeme** [comment]
I think we should have a config which continues the cool down timer of emergency call when logged out.

**Comment by GMVyLow** [comment]
totally agree with you kyeme
