### ISSUE TITLE
Dynamic Shop Sell Crash

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1783]
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
trying that doc/sample/npc_dynamic_shop.txt
when you sell , server will crash.

`#0  0x00000000005959d9 in set_reg (st=0x0, sd=0x1d64e00, num=6448784, name=0x7fffffffdd20 "@slot_opt_idx1", value=0x0, ref=0x0) at script.c:3486
        val = 0
        prefix = 64 '@'
        ref = 0x0
        value = 0x0
        name = 0x7fffffffdd20 "@slot_opt_idx1"
        num = 6448784
        sd = 0x1d64e00
        st = 0x0`

`#1  0x0000000000593744 in script_setarray_pc (sd=0x1d64e00, varname=<optimized out>, idx=<optimized out>, value=0x0, refcache=0x7fffffffdcc0) at script.c:4891`

`#2  0x0000000000516f4d in npc_selllist_sub (sd=0x1d64e00, item_list=0x7fffffffdde0, nd=0x7ffff2cab59c) at npc.c:2152
        opt_idx = <optimized out>
        opt_value = 0
        nameid = <optimized out>
        amount = <optimized out>
        identify = <optimized out>
        entry = <optimized out>
        item = <optimized out>
        refine = <optimized out>
        attribute = <optimized out>
        npc_ev = '\000' <repeats 50 times>
        card_slot = "@sold_card4\000\000\000\000\000LK@\000\000\000\000"
        opt_index_str = "@slot_opt_idx1\000\000\000\000\001\000\000\000\000"
        opt_value_str = '\000' <repeats 23 times>
        i = 0
        j = 0
        key_nameid = 18826
        key_amount = 18827
        key_refine = 18861
        key_attribute = 18862
        key_identify = 18863
        key_card = {18864, 18865, 18866, 18867}
        key_opt_idx = {6448784, 0, -8736, 32767, -8976}
        key_opt_value = {30821888, 0, 38, 0, -8752}
        __func__ = "npc_selllist_sub"`

`#3  0x000000000048e3da in clif_parse_NpcSellListSend (fd=<optimized out>, sd=0x1d64e00) at clif.c:10786
        item_list = {_max_ = 1, _len_ = 1, _data_ = 0x7ffff2d9fe2c}
        i = <optimized out>
        fail = 0
        n = <optimized out>
        __func__ = "clif_parse_NpcSellListSend"`

`#4  0x000000000048a582 in clif_parse (fd=11) at clif.c:19227
        parse_cmd_func = <optimized out>
        cmd = 201
        packet_len = 8
        sd = 0x1d64e00
        pnum = 0`

`#5  0x000000000063d71e in do_sockets (next=<optimized out>) at socket.c:1026
        rfd = {fds_bits = {2048, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 75307}
---Type <return> to continue, or q <return> to quit---`

**Comment by dastgir** [comment]
Similar to #1772 
Fix proposed in #1782
