### ISSUE TITLE
Suggestion: Add alive() script command

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#1784]
This is a suggestion that we should add the **alive()** script command to Hercules. It functions same as the @alive atcommand, but you can trigger through script engine without having to use `atcommand("@alive")`
The reason for this is sometimes you need to resurrect a character through script, but don't want to display the @alive msgs.

Maybe you can even add optional param for Account ID or Char ID.

```
// *alive(<account id>{, <char id>})
// This function revives the specified character of the
// account id specified. You can also pass the char_id
// to check for both account and char id. Returns true
// on success, false on failure.
BUILDIN(alive)
{
	struct map_session_data *sd = map->id2sd(script_getnum(st, 2));

	if (script_hasdata(st, 3) && sd != NULL
	 && sd->status.char_id != script_getnum(st, 3))
		sd = NULL;

	if (sd == NULL)
	{
		script_pushint(st, 0);
		return false;
	}

	if (!status->revive(&sd->bl, 100, 100))
		return false;

	clif->skill_nodamage(&sd->bl, &sd->bl, ALL_RESURRECTION, 4, 1);
	script_pushint(st, 1);
	return true;
}

BUILDIN_DEF(alive,"i?"),
```

I tested on my own server using `alive(getcharid(CHAR_ID_ACCOUNT))` it seems to work okay.

**Comment by EyesOfAHawk** [comment]
I also suggest the same for the @size command -> size()

**Comment by Emistry** [comment]
submit a PR would be better  :D

**Comment by EyesOfAHawk** [comment]
i dont know how

**Comment by Emistry** [comment]
The easy way ...

1. Fork latest Herc
2. Create branch from your forked Herc
3. Add in all the new changes to the branch
4. Commit to your branch
5. Visit your branch Github website
6. Click the "Compare & Create PR" button
7. Fill in all the relevant message for the commit, and done.

**Comment by EyesOfAHawk** [comment]
o wow I don't understand this github jargon, 'fork', 'branch'. I guess I will leave this here and maybe someone will pick it up one day.

**Comment by mekolat** [comment]
@EyesOfAHawk is this ok? https://github.com/HerculesWS/Hercules/issues/1784

**Comment by VMGlab** [comment]
@mekolat wrong reference above, i guess?

**Comment by mekolat** [comment]
oh, right, I meant #1786 ... changed it

**Comment by EyesOfAHawk** [comment]
yea that is really cool. more imaginative than i could have thought. very nice,
