### ISSUE TITLE
ARM Compile time error

### ISSUE THREAD

**Issue by Habilya** [HerculesWS/Hercules#1793]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
Not Building on Raspberry Pi 3.
ARM architecture, maybe others affected.

[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

On building of /Hercules/src/map/script.c
I'm getting Compiletime error

```
script.c: In function ‘buildin_recovery’:
script.c:15051:5: error: incompatible type for argument 2 of ‘script->buildin_recovery_pc_sub’
     script->buildin_recovery_pc_sub(sd, NULL);
     ^
script.c:15051:5: note: expected ‘va_list’ but argument is of type ‘void *’
Makefile:144: recipe for target 'obj_sql/script.o' failed
make[1]: *** [obj_sql/script.o] Error 1
make[1]: Leaving directory '/home/[user]/Hercules/src/map'
Makefile:120: recipe for target 'map_sql' failed
make: *** [map_sql] Error 2
```

gcc version 4.9.2 (Raspbian 4.9.2-10)

### Expected Behavior

[//]: # (Tell us what should happen instead.)
Expected to build compile... like before

### Steps To Reproduce The Issue

1. Step 1
Freshly clonned Hercules from the GIT repo.
2. Step 2
Did steps just like multiple times before
`./configure --enable-packetver=YYYYMMDD --disable-renewal`
3. Step 3
`make clean`
`make sql`

**Branch(es):**
- [X] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 44afefff8c3b09d47f7d1a7a3d386e83f8b2dcbd

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System
Raspbian GNU/Linux 8 (jessie) (4.4.50-v7+)
on
ARMv7 Processor rev 4 (v7l)

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by MishimaHaruna** [comment]
This is indeed a bug, a `va_list` isn't guaranteed to be a pointer, and as such, passing NULL to it is wrong. I already fixed a similar issue the last time I compiled Hercules on a Pi (5fd40de233d3a897284f771338cbf8e657182261)

**Comment by mekolat** [comment]
Sorry about that... Still weird that my gcc (`5.4.0`), and appveyor and travis didn't catch that
