### ISSUE TITLE
Nidhoggur's Nest Cannot Re-enter After going to 2nd level

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#1796]
After entering the portal to take you to 2@nyd, if you die and need to come back, you cannot re-enter the instance.
```if ('ins_nyd2 == 3 || 'ins_nyd2 == 4) {```
Need to remove `ins_nyd2 == 3`. Sorry for not following format.

**Comment by Asheraf** [comment]
According to iRO/fRO Aegis scripts the current behaviour is correct feel free to reopen this if you can prove the opposite in official server.

```
//== has entered the dungeon ==
elseif ((entered == 1) & (entered2 == 1))
	//== still within 4 hour time limit ==
	if ((4hourcheck == 1) & (3daycheck == 1))
		if ((v[ins_nyd2] == 3) | (v[ins_nyd2] == 4))
			dialog "[Yggdrasil Gatekeeper]"
			dialog "Nidhoggur's Shadow has been defeated."
			dialog "If he regains his power your strength may still be needed at a later time."
			close
			return
		endif
```
