### ISSUE TITLE
Suggestion: Add ismute() script command

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#1798]
Suggestion to add the `ismute()` script command. I am currently using this in scripts to check if a player is muted, and it is very useful. Works same as issit(), where no specification = current RID, if char name specified that one.

```
BUILDIN(ismute)
{
	struct map_session_data *sd = NULL;

	if (script_hasdata(st, 2))
		sd = script->nick2sd(st, script_getstr(st, 2));
	else
		sd = script->rid2sd(st);

	if (sd == NULL)
		return true;

	if (pc_ismuted(&sd->sc, MANNER_NOCOMMAND))
		script_pushint(st, 1);
	else
		script_pushint(st, 0);
	return true;
}
```

**Comment by mekolat** [comment]
any use case? also rather than a new buildin this could just be a param

**Comment by Asheraf** [comment]
could be used for example to deny a player from joining events if muted but this could be checked using `SC_NOCHAT` or `Manner`.

https://github.com/HerculesWS/Hercules/blob/master/doc/script_commands.txt#L5762-L5765

**Comment by mekolat** [comment]
if it can already be checked then let's close this issue
