### ISSUE TITLE
int_char.c Warning

### ISSUE THREAD

**Issue by Saekkori** [HerculesWS/Hercules#1799]
warning C4018: <=: Non-conformity of types with and without sign (..\src\char\int_party.c)	...src\char\int_party.c	320	1	char-server

I'm Downloaded Last Version of Hercules. 
Compiled by VS 2012 Express

**Comment by Asheraf** [comment]
Hello there, Please follow the issue template when you open a new issue without enough informations we cannot help you.

**Comment by Saekkori** [comment]
What other information should I provide?
I showed the result of the construction on Visual Studio 2012 Express
warning C4018: <=: Non-conformity of types with and without sign (..\src\char\int_party.c) ...src\char\int_party.c 320 1 char-server

Warning in this Code:
// Returns whether this party can keep having exp share or not.
int inter_party_check_exp_share(struct party_data *const p)
{
	nullpo_ret(p);
	return (p->party.count < 2 || p->max_lv - p->min_lv <= party_share_level);
}

I have not touched anything yet. I just compiled the server to run it

**Comment by Asheraf** [comment]
You get the template by default when you open a new issue but here it is https://github.com/HerculesWS/Hercules/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Asheraf** [comment]
also this is a duplication of #1434
