### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by will21** [HerculesWS/Hercules#1803]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"CL.exe" exited with code -1073741515.	plugin-HPMHooking_login	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6006	"CL.exe" exited with code -1073741515.	login-server	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6006	"CL.exe" exited with code -1073741515.	char-server	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6006	"CL.exe" exited with code -1073741515.	mapcache	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6006	"CL.exe" exited with code -1073741515.	plugin-sample	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6006	"CL.exe" exited with code -1073741515.	map-server	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6006	"CL.exe" exited with code -1073741515.	plugin-HPMHooking_char	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6006	"CL.exe" exited with code -1073741515.	plugin-HPMHooking_map	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358

**Comment by Asheraf** [comment]
Hello there, please fill the issue template when you open a new issue and give enough informations so we can help, you'll get the template by default when you open a new issue or you can copy it from here https://github.com/HerculesWS/Hercules/blob/master/.github/ISSUE_TEMPLATE.md

also from the error message you gave i can see you are using Visual Studio 2017 to compile hercules which is not yet supported by hercules for more informations on supported platforms check this link https://github.com/HerculesWS/Hercules/wiki/Supported-Platforms

Closing this - please feel free to reopen once you filled the template.
