### ISSUE TITLE
Snap_dodge yes / no not working

### ISSUE THREAD

**Issue by Sixte44** [HerculesWS/Hercules#1808]
[
Hello, so as you may know, there is a way to switch between Snap dodge bug ON and OFF on Rathena ( and hercules too ? )

the thing is, it works on Rathena emulator, but not on Hercules Apparently, can someone give it a try ? 

thank you

**Comment by Asheraf** [comment]
Its `true/false` instead of `yes/no` in hercules.

https://github.com/HerculesWS/Hercules/blob/master/conf/map/battle/battle.conf#L180

**Comment by Asheraf** [comment]
if this is a bug then its duplicate of #638
closing this one.
