### ISSUE TITLE
Incomplete Checkidle

### ISSUE THREAD

**Issue by MrKeiKun** [HerculesWS/Hercules#181]
Remove Idle when
- [x] Equip/Unequip
- [x] Sit/Stand
- [x] Chat
- [x] Change of X&Y(except when recall by someone and EMERGENCY_CALL)
- [x] Next/Close Script
- [x] Buying
- [x] while on Window(Buying or selling NPC Shop)
- [x] dori and bing/bang
- [x] Use of Skill
- [x] Item Use
- [ ] on Window Open/Close

**Comment by AnnieRuru** [comment]
open these window ? 
```
// Be mindful that the more options used, the easier it becomes to cheat features that rely on idletime (e.g. checkidle()).
```
heck, no, not going to do that XD

other than vending/chat window,
I don't think server can detect players open skill window, status/party/guild/equipment/inventory ...

**Comment by dastgirp** [comment]
Server can detect some new window open/close like bank, roulette, bargain shop, etc..

Though I don't think that would be useful for checkidle
