### ISSUE TITLE
Unanswered issues.

### ISSUE THREAD

**Issue by Likeeit** [HerculesWS/Hercules#1814]
I did a survey of my open issues and realized that much of it is open to good time and has so far received no opinion.

```
Add cell_pvp or cell_pk
#1654 opened on 26 Mar by Likeeit 

Command 'opendressroom'
#1624 opened on 12 Mar by Likeeit 

Guild Configs & Script Commands component:core:scriptengine
#1616 opened on 7 Mar by Likeeit 0 of 7

Add db file job_noenter_map.txt with format: JobID,FlagZone,GroupLevelBypass.
#1604 opened on 3 Mar by Likeeit 

Implement New skill GD
#1572 opened on 10 Feb by Likeeit 
```

**Comment by Asheraf** [comment]
Hello there, this is a pointless issue.. if you want to bump an issue just add a comment and do not open new one. closing this.

**Comment by mekolat** [comment]
@Likeeit if you want to get stuff done feel free to contribute. This project is open source, which means nobody is getting paid and all the work we do is done on a voluntary basis. If it is missing some features that you desire then please wait until someone is interested to add them, or learn to code and do it yourself. No one here is your slave, but we can work together if you want to help. You must also understand that we each have different priorities and more pressing issues to tackle first.

If you absolutely need something and cannot do it yourself then feel free to hire someone that can do it for you
