### ISSUE TITLE
NST_MARKET shop reporting over weight

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#1840]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)
Trying to buy many of an item in NST_MARKET shop is causing an 'Overweight' message to occur.

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)
I had 8k White Slim Pots [547] in the store. It only let me select 10 at a time. It kept telling me I was overweight if I tried to choose 20+, even though I have 500 STR.

### Expected Behavior

[//]: # (Tell us what should happen instead.)
Better detection of weight needed.

**Comment by EyesOfAHawk** [comment]
Bump this issue still outstanding. Makes it so you can only sell singular amounts of items and not bulk ones.

**Comment by Kenpachi2k13** [comment]
Fixed in https://github.com/HerculesWS/Hercules/commit/f1f1ef0ff2c9aa7d879df8b959072a7429d2722a
`close();`
