### ISSUE TITLE
Warning while compiling with latest hercules revision

### ISSUE THREAD

**Issue by xtreamprince** [HerculesWS/Hercules#1845]
Warning while compiling with latest hercules revision

![untitled](https://user-images.githubusercontent.com/22543759/30773330-4b790c14-a08c-11e7-84c2-463d470ca1cf.jpg)

**Comment by 4144** [comment]
I not have visual studio. And all this warnings non critical.

**Comment by MishimaHaruna** [comment]
This should be fixed as of #1870 (if it isn't, please reopen)
