### ISSUE TITLE
Script Engine 'true' should mean anything above 0

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#1856]
### Issue Prelude

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
When checking 'istrue' in scripts using `if (variable == true)`, true can only mean 1. I'm not experienced at any type of programming or anything, but shouldn't
False = `val <= 0` 
True = `val >= 1`
So if `variable = 3`, variable is true.

### Expected Behavior

I should be able to do `if (variable == true)` for anything above 0, instead of having to go `if (variable >= true)`

**Comment by Asheraf** [comment]
True and False are used for boolean only I don't see the point why you want to check a non bool var using true and false.

**Comment by MishimaHaruna** [comment]
FWIW, the appropriate to check a boolean is never `if (foo == true)`. You can pick one of the following safe variants:

True:

- `if (foo)`
- `if (foo != false)`

False:

- `if (!foo)`
- `if (foo == false)`

This is similar to what happens in C and many C-derived languages (see for example the [C FAQ](http://c-faq.com/bool/bool2.html).

**Note**: using the `if (foo)` or `if (!foo)` checks on a variable that is not meant to be a boolean is _bad style_ and should be avoided at all costs. If it's a number, check it against numbers; if it's a boolean, check it like a boolean.

**Comment by EyesOfAHawk** [comment]
thx guys
