### ISSUE TITLE
warpparty() and warpguild() are checking for nowarp mapflag

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#1861]
### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

`BUILDIN(warpparty)` and `BUILDIN(warpguild)` are checking for the `nowarp` and `noreturn` mapflags.

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)
These script commands cannot be used to warp guilds/parties around on nowarp mapflags.

### Expected Behavior

[//]: # (Tell us what should happen instead.)
Just like the regular `warp()` command, you should be able to warp regardless.

**Branch(es):**
- [x] master
- [ ] other

**Comment by mekolat** [comment]
I believe it would be a better idea to just add an extra parameter to `warp()` so it can take a GID, and then deprecate `warpparty()` and `warpguild()` since `getunits()` makes them obsolete. It will also help avoid having yet more warp commands when we merge the Clan system

**Comment by psychonaut04** [comment]
I did something just to test.

https://github.com/HerculesWS/Hercules/compare/stable...psychonaut04:patch-2

Deprecated warpparty and warpguild, just with a warning(it still works).
Warp using switch, a char change it to warpguild, can change it somehow still to add more.

Just a code testing(i did for fun only) to give .
