### ISSUE TITLE
Compile Warnings on latest version

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#1867]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

![test](https://user-images.githubusercontent.com/4826387/31851840-76b15556-b6a0-11e7-90dd-21422a9b3ff3.PNG)

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

**Branch(es):**
- [x] master
- [x] stable
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)
Windows 10 Pro 64bit Version: 1709
Compiled using Microsoft Visual Studio Community 2017

**Comment by mekolat** [comment]
https://github.com/HerculesWS/Hercules/commit/c11f17020732d96e6830deadb8272f66c9af623b

**Comment by Jedzkie** [comment]
@mekolat I already have this changes, but still got error, i'm using latest herc, and nothing is modified.

**Comment by mekolat** [comment]
I meant the warnings were induced by this commit

**Comment by MishimaHaruna** [comment]
@Jedzkie could you please check if they're all gone now that #1859 is merged to the master branch (not on stable yet) - I don't have VS2017 readily available

**Comment by Jedzkie** [comment]
Sure @MishimaHaruna

**Comment by Jedzkie** [comment]
@MishimaHaruna still not fixed.

![image](https://user-images.githubusercontent.com/4826387/31854445-112ce7be-b6cc-11e7-9149-4a03c691b12e.png)

![image](https://user-images.githubusercontent.com/4826387/31854448-1d3837e8-b6cc-11e7-86f4-347cf188ae50.png)

**Comment by MishimaHaruna** [comment]
@Jedzkie is #1870 of any help?

**Comment by Jedzkie** [comment]
Ill try manual patch it later

**Comment by Jedzkie** [comment]
It's fixed now, thanks @mekolat and @MishimaHaruna
