### ISSUE TITLE
getiteminfo - ViewSprite

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1895]
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

getiteminfo(2226,14); // Will not return ViewSprite ID.  This might be the issue.

https://github.com/HerculesWS/Hercules/blob/00624f157bdee3bd438bd7d9ecd4aed03815c23e/src/map/itemdb.c#L2208

**Comment by EyesOfAHawk** [comment]
i believe you have to use type 11 in getiteminfo. im not even sure what 14 is for ⭕️

**Comment by tlacson7** [comment]
its here:  https://github.com/HerculesWS/Hercules/blob/00624f157bdee3bd438bd7d9ecd4aed03815c23e/doc/script_commands.txt#L3189

I tried this test script and it cant display any ViewSprite of any headgears:
https://github.com/HerculesWS/Hercules/blob/stable/doc/sample/getiteminfo.txt
