### ISSUE TITLE
strcharinfo(PC_NAME, GID) 

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1899]
[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [ x ] I have not modified the source prior to reproducing this issue.
-  [ x ] I am using the latest version of Hercules.
-  [ x ] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

Script Issue:
`*strcharinfo(<type>{, <default value>{, <GID>}})

This function will return either the name, party name or guild name for
the invoking character. Whatever it returns is determined by type.
(0) PC_NAME		- Character's name.
(1) PC_PARTY	- The name of the party they're in if any.
(2) PC_GUILD	- The name of the guild they're in if any.
(3) PC_MAP		- The name of the map the character is in.

If <GID> is passed, it will return the value of the specified player instead
the attached player. If the player is not found, it will return
<default value>, if any, or else return an empty string.
`
strcharinfo(PC_NAME,150001);  // did not show 150001 char name but the invoker's name.

**Comment by dastgir** [comment]
GID = Account ID, not Character ID.

**Comment by tlacson7** [comment]
using strcharinfo(PC_NAME,200003);  // still same result

**Comment by MishimaHaruna** [comment]
that doesn't look like a valid account ID (`200,003` vs `2,000,003`)

**Comment by tlacson7** [comment]
@MishimaHaruna   sorry Haru, its just an example.  but i cant get the PC_NAME giving the aid or cid

**Comment by 4144** [comment]
documentation look like wrong. strcharinfo return information for attached player only

**Comment by 4144** [comment]
If you want use more than one parameter, you must give default value. this is second parameter
some thing like:
```
mes strcharinfo(PC_NAME, "bad", 20003);
```
it will return "bad" if player id is wrong

**Comment by 4144** [comment]
See documentation about strcharinfo.
copy paste from doc: *strcharinfo(<type>{, <default value>{, <GID>}})

**Comment by Asheraf** [comment]
Closing this, you're using wrong syntax AID is 3rd argument.
