### ISSUE TITLE
resetlvl with baby not resetting stats

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#1907]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

Sorry I don't have much time just need to file quick report. resetlvl() script command, im using resetlvl(1) on a Job_Baby, and my Status Point aren't being reset. E.g., I'm lvl 99 and i use resetlvl(1) on my baby, it will retain all the Status Points it has sorry for bad rescription im in a hurry

**Comment by dastgir** [comment]
The description seems wrong.
resetlvl(1) is like rebirth, it gives 100 status point, only if you are High Novice.
You can use resetstatus(); after resetlvl to trigger status point reset

**Comment by EyesOfAHawk** [comment]
Ah okay, but shouldn't resetlvl(1) fix your status points?
After using it, my baby char had all its stats (str, luk, etc.) reset to 1, but then it had double 'StatusPoint'

**Comment by Jeybla** [comment]
Related:
https://github.com/HerculesWS/Hercules/blob/stable/doc/script_commands.txt#L5753
https://github.com/HerculesWS/Hercules/blob/stable/npc/custom/jobmaster.txt#L161
