### ISSUE TITLE
Items missing in rodex mail

### ISSUE THREAD

**Issue by Nurkz** [HerculesWS/Hercules#1912]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

-  [ ] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Steps To Reproduce The Issue

1. Try to send item via Rodex Mail
2. Reciever can't properly take item.
3. Profit

**Branch(es):**
- [x] master
- [x] stable
- [ ] other

**Comment by Nurkz** [comment]
@4144 check out for sql stmt query in `inter_rodex_fromsql` (`src/char/int_rodex.c`)

**Comment by Asheraf** [comment]
confirming this on 6300a7b1dc2b09541274f46beea844ba8ecc5507 using 20171101
