### ISSUE TITLE
Mobs not cached

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#1915]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

In pre-re mode it is showing that 14 monstos are not cached. are some monsters from lhz_dun03, starting at the following:

https://github.com/HerculesWS/Hercules/blob/stable/npc/pre-re/mobs/dungeons/lhz_dun.txt#L110

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 6300a7b1dc2b09541274f46beea844ba8ecc5507
Git revision scripts: 6300a7b1dc2b09541274f46beea844ba8ecc5507

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by xBeret** [comment]
@dastgir

**Comment by dastgir** [comment]
There can be only 100 spawn entries per map(MAX_MOB_LIST_PER_MAP).
For lhz_dun03, it's more than 100, so all of those cannot be cached.
I suggest increasing the Max Mob List to 115
@MishimaHaruna

**Comment by 4144** [comment]
probably better switch to VECTOR and set limit to some much bigger value

**Comment by Kenpachi2k13** [comment]
In my opinion, increasing `MAX_MOB_LIST_PER_MAP` to 115 in pre-RE mode, is okay for now.
The `spawn_data` `struct` is not that large, so memory wasting should not be an argument here.

Switching to `VECTOR` should be a separate task for all memory-intensive arrays.
