### ISSUE TITLE
FAKE_NPC having a sprite

### ISSUE THREAD

**Issue by Skeec** [HerculesWS/Hercules#1916]
### Issue Prelude
-  [X] I have not modified the source prior to reproducing this issue.
-  [X] I am using the latest version of Hercules.
-  [X] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

The FAKE_NPC is having a sprite with the latest stable version.
This can be seen here

![image](https://user-images.githubusercontent.com/20649209/33242514-817a74f2-d2d6-11e7-8324-617f750378d3.png)

![image](https://user-images.githubusercontent.com/20649209/33242535-d3c512da-d2d6-11e7-89a6-437753e629df.png)

### Operating System
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by dastgir** [comment]
Related PR: https://github.com/HerculesWS/Hercules/pull/1893 
@4144

**Comment by dastgir** [comment]
Suggested fix:
npc_refresh
```c
if (map->list[nd->bl.m].users) {
```
To
```c
if (map->list[nd->bl.m].users && nd->class != FAKE_NPC) {
```

**Comment by 4144** [comment]
@dastgir if this fixed issue, can you create pr?

**Comment by EyesOfAHawk** [comment]
how come fake_npc has sprite of female novice to begin with @_@

**Comment by MishimaHaruna** [comment]
Suggested fix:

```
diff --git i/src/map/npc.c w/src/map/npc.c
index 10ff4ebf2..9e1414f9c 100644
--- i/src/map/npc.c
+++ w/src/map/npc.c
@@ -2708,7 +2708,7 @@ struct npc_data *npc_create_npc(enum npc_subtype subtype, int m, int x, int y, u
 	nd->area_size = AREA_SIZE + 1;
 	nd->class_ = class_;
 	nd->speed = 200;
-	nd->vd.class = 0;
+	nd->vd.class = INVISIBLE_CLASS;
 
 	return nd;
 }
```
