### ISSUE TITLE
MAGIC_REFLECTION_TYPE causes sstatus to be unused variable

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#1920]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)
I think this compiler warning explains it best:
```
skill.c: In function ‘skill_attack’:
skill.c:2744:22: warning: variable ‘sstatus’ set but not used [-Wunused-but-set-variable]
  struct status_data *sstatus, *tstatus;
```
It happens due to `MAGIC_REFLECTION_TYPE` being set to 0 in `src/config/classes/general.h`.
I think a simple `#if MAGIC_REFLECTION_TYPE` check before allowing sstatus to be defined and set would suffice to fix the compiler warning.

Thanks

**Branch(es):**
- [x] master
- [ ] other

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

CentOS7

**Comment by mekolat** [comment]
closed by #2175
