### ISSUE TITLE
Trap Visibility (Renewal)

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1927]
### Current Behavior
Traps are visible to everyone.

### Expected Behavior
Official:
Hunter traps are only visible to the caster or his/her party/guildmates/alliance in all maps.
Official Video: https://www.youtube.com/watch?v=lSDfPb905-w&feature=youtu.be
Official Video with party: https://youtu.be/fdWpcQirGuo?t=124
 
I suggest to make a settings like:
// Trap Settings
// 1: Only hunters can see the traps.
// 2: Only the Hunter and his/her party can see the trap. (Official - Renewal)
// 3: All traps are visible to everyone (pre-renewal).
trap_visible: 2

**Branch(es):**
- [x ] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[/x/]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[/x/]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

*edit* Only the Hunter and his/her party can see the trap on official.

**Comment by kyeme** [comment]
Up

**Comment by kyeme** [comment]
Up~

**Comment by Normynator** [comment]
WIP
