### ISSUE TITLE
failed assertion error

### ISSUE THREAD

**Issue by xtreamprince** [HerculesWS/Hercules#1932]
Recently updated emulator to latest version and got this error on login and char select.
![untitled](https://user-images.githubusercontent.com/22543759/33997019-0c3fd420-e109-11e7-8a30-bc4b4f766ab3.jpg)

**Comment by xtreamprince** [comment]
it's causing by plugin Smoke Battleground Plugin.

**Comment by Asheraf** [comment]
for plugin related issues contact the author or ask for help in the forums, the bug tracker is for emulator related bugs only.
