### ISSUE TITLE
RODEX maximum Email

### ISSUE THREAD

**Issue by kairu** [HerculesWS/Hercules#1933]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [  ] I have not modified the source prior to reproducing this issue.
-  [  ] I am using the latest version of Hercules.
-  [ x ] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Rodex should have a config or atleast a warning that only 8 tabs of mails are allowed.
[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior
It will send errors to the terminal when you've exceeded the maximum number of mails on your inbox.
[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior
Should send/check the players inbox if it is able to be sendable? or a config for max emails of the player.
[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. Step 1: Send email to player2 a maximum of 8 tabs of mails.
2. Step 2: Sending the next mail to make the 9th tab of mail will cause error on terminal.
3. Step 3: Mail on player2 will now have an empty mail and cannot recieve any(not tested when the mail expired)

**Branch(es):**
- [ x ] master
- [ ] other
Extra Info:
 While im not using the latest branch of herc i still think this will happen as there hasnt been any updates to rodex by then.
**Hercules rev. hash/commit:** 
Screenshot:
https://i.imgur.com/r2EYbj8.jpg

**Comment by 4144** [comment]
look like error check is wrong. it compare total messages with messages in one packet.
