### ISSUE TITLE
Quest Umbala - Ore Downgrading - delitem() after getitem() (Dupe Bug)

### ISSUE THREAD

**Issue by epicrov4tech** [HerculesWS/Hercules#1934]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

It's possible on NPC Puchuchartan to dupe items with RoDex while NPC Dialog.
You can select your Ore which you want to downgrade. Select yes and send while you are in Dialog the downgrading Ore to another Char of you.

The npc will not check for amount after devides. He will give you the downgraded ores and tries to delete the selected ore - No ore detected, server receives "tried to delete non existent item from char" error. And player have divided ores and ore in RoDex Mailbox.

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

NPC don't check for existing ores before getitem()

### Expected Behavior

NPC should say "Whoo, there are some items missing."

[//]: # (Tell us what should happen instead.)

**Branch(es):**
- [ x ] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

 				
```c
 				switch(.@divide) {

 				case 994:

+					if (countitem(.@divide) < .@input) close;

 					if (checkweight(Boody_Red, .@shaman_max)) {

 						getitem Boody_Red,.@shaman_max;

 					} else {

 					}

 					break;

 				case 995:

+					if (countitem(.@divide) < .@input) close;

 					if (checkweight(Crystal_Blue, .@shaman_max)) {

 						getitem Crystal_Blue,.@shaman_max;

 					} else {

 					}

 					break;

 				case 996:

+					if (countitem(.@divide) < .@input) close;

 					if (checkweight(Wind_Of_Verdure, .@shaman_max)) {

 						getitem Wind_Of_Verdure,.@shaman_max;

 					} else {

 					}

 					break;

 				case 997:

+					if (countitem(.@divide) < .@input) close;

 					if (checkweight(Yellow_Live, .@shaman_max)) {

 						getitem Yellow_Live,.@shaman_max;

 					} else {
```

**Comment by tlacson7** [comment]
that is a very bad bug for live server. i suggest enable rodex in town only just like the regular mail.

**Comment by 4144** [comment]
bug not in rodex but in wrong scripts.
Exists different ways to use script bugs, and rodex is only one simplest.

**Comment by Emistry** [comment]
this issue can be closed since this PR https://github.com/HerculesWS/Hercules/pull/1936 solved it?

**Comment by AnnieRuru** [comment]
hmm ... 

1. Alt+Z, open a party/friend window
2. right-click, select `Send a mail`, your send mail window is open
3. click on a npc, you get `Please close the Mail compose window`
4. close the mail window, you get stuck ...

I think this should be a new issue lol,
but yeah, I can't send items anymore with mailbox open while in npc dialog
