### ISSUE TITLE
Perfect Dodge not showing in player stats tab

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#1938]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [ ] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
Decription: Perfect dodge of any item is not showing in stats of player.
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)
bonus bflee2 seems not to be working but i'm not so sure if its working just not showing in the player stats.
### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior

[//]: # (Tell us what should happen instead.)
exptected behavior it should show on player status from Flee row: flee+perfect dodge.
### Steps To Reproduce The Issue

1. wear any item with bonus bflee2 script
2. alt+q (i'm using 2012 04 10 client)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)
![untitled](https://user-images.githubusercontent.com/7709489/34302661-d29bc354-e76c-11e7-8248-55abdc2a6f46.png)

**Comment by tlacson7** [comment]
working fine using 2015 client
![ac1](https://user-images.githubusercontent.com/8176150/34317156-5f89b7be-e7e3-11e7-8445-82537017d45e.JPG)
![ac2](https://user-images.githubusercontent.com/8176150/34317158-63d76c26-e7e3-11e7-8012-220b857bd57f.JPG)

**Comment by Mojacko** [comment]
I'm using 2012 client

**Comment by guilherme-gm** [comment]
It's working fine on my 2012-04-10
![flee](https://user-images.githubusercontent.com/10552039/36935601-869b9260-1ed8-11e8-99bb-5cc36346985f.jpg)

**Comment by Aruar** [comment]
I'm also having the same error, I use client 2017

**Comment by Emistry** [comment]
seem okay for me, using client `20180620`, git https://github.com/HerculesWS/Hercules/commit/0edf2360b185f0e1c68bb6ddbbbe3720af5651b3

![preview](https://i.imgur.com/pD1aOai.png)

**Comment by Kenpachi2k13** [comment]
Unable to reproduce, too.
Client: `20180418`
Hercules: https://github.com/HerculesWS/Hercules/commit/c03722679a01e5f181c2138565e95a6b0981a124

`close();`
