### ISSUE TITLE
Mushroom Event not working properly

### ISSUE THREAD

**Issue by xtreamprince** [HerculesWS/Hercules#1955]
hello i got problems with mushroom event
![untitled](https://user-images.githubusercontent.com/22543759/34990434-176f4928-faec-11e7-92fc-fb6af0098546.jpg)

after all mushroom killed, it should end the event.

**Comment by xtreamprince** [comment]
Look like i'm using old version of script.

**Comment by xtreamprince** [comment]
same problem with latest version of script

**Comment by guilherme-gm** [comment]
Can you check if this is still happening? It's working fine here (latest master)

**Comment by Emistry** [comment]
checked and work fine 
![img](https://i.imgur.com/GVmLy45.png)

**Comment by xtreamprince** [comment]
Well it start to work fine after reload script, after some time when no one playing this event, it got stuck & says 0 mushroom left.

**Comment by Emistry** [comment]
hmm, I think I found the issue.
you are probably did `@killmonster` during the event. 
with this trick, only I able to duplicate the similar scenario that you show above.

![pic](https://i.imgur.com/J5tuh7X.png)
