### ISSUE TITLE
Not able to connect, using 2013-12-23c ragexe

### ISSUE THREAD

**Issue by xtreamprince** [HerculesWS/Hercules#1956]
I just updated my Emulator to latest revision, since then i'm not able to login through my client, showing following error.
![packet](https://user-images.githubusercontent.com/22543759/35054015-ac888b88-fbd1-11e7-81ea-6c38424ac64d.jpg)

I try to disable/enable Packet_obs feature.
I'm using 2013-12-23c ragexe

**Comment by dastgir** [comment]
Enable the packet obfuscation server side.
The error shows encrypted packet been received from client. But server have that disabled.

**Comment by 4144** [comment]
Just tested 2013-12-23cragexe, works fine.
This mean issue or in patches or in server configuration.
Remember what old server configuration had encryption mode auto detection and it not always works. Now default mode is enabled obfuscation always.

See in conf/map/battle/client.conf
packet_obfuscation: 2

**Comment by xtreamprince** [comment]
Well, i tested with setting
packet_obfuscation: 2
but no luk
I will try patching client again with new keys and post result.

**Comment by 4144** [comment]
dont change keys in client at all. default keys will works fine

**Comment by 4144** [comment]
Also if you change packetversion in server, you must rebuild server from scratch.
```
make clean
./configure
make
```

**Comment by xtreamprince** [comment]
well i use visual studio 2015 for build server and using windows 7 professional.

I tested with custom keys, disabling packet_obs, also patching client without keys, but no luk.
where should i add my keys? packet_keys.h?
i also tested adding keys on packet_keys_main.h

Is there is something new? which i'm missing?

I will test with different client and post results.

**Comment by 4144** [comment]
client and server works without any keys changes. why you changing it?

windows is pain...
If you really want change working keys, add own keys at end of packets_keys_main.h

and rebuild all if you do any changes like this.

**Comment by Murilo-BiO** [comment]
sometimes I can't connect with `packet_obfuscation: 2` but when I change to `1` it works...

**Comment by 4144** [comment]
@Murilo-BiO this probably mean client with removed encryption keys.
Mode 1 works good always for clients without keys, but for clients with keys it some times failed.

**Comment by xtreamprince** [comment]
@4144 i tested with 2013-08-07aRagexe and i'm able to connect to the server without any problem.

can u share patched 2013-12-23c client

btw when i patch client without custom keys, i got this error
![packet](https://user-images.githubusercontent.com/22543759/35150817-d62e337c-fd41-11e7-8898-b7d17f3c00f5.jpg)

**Comment by 4144** [comment]
ah, sorry i had server with keys enabled and client with keys disabled. and it worked.
This mean client keys looks broken. some where was lists with clients with bad keys.
not sure is set custom keys fix this issue.
But bad key here mean client encrypt packets in some strange way or existing tools cant extract correct keys.

So one workaround for 2013-12-23c client. In server disable or not keys, should works both.
in client disable keys.

**Comment by 4144** [comment]
And here patches list:
```
9 Disable 1rag1 type parameters (Recommended)
13 Disable Ragexe Filename Check (Recommended)
15 Disable HShield (Recommended)
23 Enable /who command (Recommended)
24 Fix Camera Angles (Recommended)
33 Always Call SelectKoreaClientInfo() (Recommended)
34 Enable /showname (Recommended)
35 Read Data Folder First
36 Read msgstringtable.txt (Recommended)
37 Read questid2display.txt (Recommended)
38 Remove Gravity Ads (Recommended)
39 Remove Gravity Logo (Recommended)
40 Restore Login Window (Recommended)
41 Disable Nagle Algorithm (Recommended)
44 Translate Client (Recommended)
46 Use Normal Guild Brackets (Recommended)
48 Use Plain Text Descriptions (Recommended)
49 Enable Multiple GRFs (Recommended)
53 Use Ascii on All LangTypes (Recommended)
61 Disable Packet Encryption
64 @ Bug Fix (Recommended)
73 Remove Hourly Announce (Recommended)
84 Remove Serial Display (Recommended)
90 Enable DNS Support (Recommended)
97 Cancel to Login Window (Recommended)
213 Disable Help Message on Login (Recommended)
```

**Comment by xtreamprince** [comment]
@4144 i tested with patches u provide, still not working. Look like i have to revert this update or switch to other client.

**Comment by 4144** [comment]
Look like this is not keys issue, but some kind of conflicting versions ragexe and ragexeRE
for old client like 2013-12-23, you can do small change to remove new shuffle packets.

Quick fix:
in file clif.c find line:
```
#include "packets_shuffle_main.h"
```
and change to:
```
//#include "packets_shuffle_main.h"
```
In this change you will remove support for most new clients, but for old clients will be used old packets.

**Comment by 4144** [comment]
Or without manual changes you can try this pull request https://github.com/HerculesWS/Hercules/pull/1957

**Comment by xtreamprince** [comment]
//#include "packets_shuffle_main.h"

Not i can connect using 20131223 client, thank you for your support.
