### ISSUE TITLE
Rental Expiration Date in Item Description Not Displaying

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#1958]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

Maybe this is a client issue and not one with Hercules, unsure. Thought it was best to report, in case another person is also experiencing this. Long ago (1yr+) it worked fine. In the item description for rentals, it would be displayed correctly as the date. Now, it literally displays as '%s'.

**Before:** Expiration Date: yyyy-mm-dd hh:mm:ss (I can't remember the format, but it displayed correctly)
**Now:** Expiration Date: %s

This is in the item's description, as in when you right click it and its flavor text from itemInfo.lub displays.
I tried a few clients, with an array of (NEMO) diffs, ranging from custom ones to only the recommended, and they all seemed to return the same result.

**Comment by 4144** [comment]
this more look like translation bug
you checked clean client without grf changes and translations?

**Comment by dastgir** [comment]
Please mention the client date you tested with.

**Comment by EyesOfAHawk** [comment]
tested on 20141022 and 20151029. I haven't test with clean client, no grf changes, translations, etc. It read correctly from msgstringtable, as if I change something on that particular line, it will change the output of the text.

**Comment by EyesOfAHawk** [comment]
I downloaded Zackreaver's client translation and made a new grf with it. Same result.
[https://i.imgur.com/biJKQPl.png](url)

**Comment by Emistry** [comment]
did you changed `langtype` ? it does affect the display of rental duration too.

**Comment by EyesOfAHawk** [comment]
This issue is caused by langtype as Emistry said. I was using langtype 10.
