### ISSUE TITLE
Ragnarok Zero's quest system is unloaded.

### ISSUE THREAD

**Issue by idamonli** [HerculesWS/Hercules#1960]
The client can't received any information about the tasks from the server。

The client task file confirms the relevant description of the task.

using 2017-12-06 Zero .exe   and   2017-12-12 Zero .exe

KRO:
![newquestui gif 2437c0bcccbccebee73d0815e678bca6](https://user-images.githubusercontent.com/13962741/35377775-72ef029c-01eb-11e8-9019-613b6978acbc.jpg)

 HERC:
![34912514-80e607e0-f91e-11e7-9cc4-05b4f8fe7cfc](https://user-images.githubusercontent.com/13962741/35377785-7c10e796-01eb-11e8-8b9c-959796bacb8b.png)

**Comment by Asheraf** [comment]
confirmed, zero clients dropped the use of the old packets after the quest ui update.. #1111 should fix this.

**Comment by idamonli** [comment]
KRO 2018-01-17aRagexeRE Is Normal。
![iv_ nzopf7fmdoy 0 3tls](https://user-images.githubusercontent.com/13962741/35859285-6d504506-0b7a-11e8-97af-4545191d7426.png)

That seems to be the case only with the zero version.
