### ISSUE TITLE
Failed Assertion in pc bonus

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#1962]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

When adding a 4039 card to some equipment and equipping this equipment receives a failed assertion error.

I think the problem is bonus2 bResEff for cards.

![test](https://user-images.githubusercontent.com/8175669/35525257-1e40ecf6-050b-11e8-94c9-90759a9907bb.png)

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. Get a head equipment.
2. Add the 4039 card
3. Equip item and you receive failed assertion

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 5808b1363619a4d1ece4e89a464c0f48225f3a23

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by xBeret** [comment]
@4144 @MishimaHaruna @dastgir

**Comment by Asheraf** [comment]
unable to reproduce, the value of `bResEff` is `1013` in the other side the error in your picture shows `2061` so you're probably trying to use `bAddRaceTolerance` in pre-re build which doesnt exist.

**Comment by xBeret** [comment]
@Asheraf I forgot to mention I tested using item 18755, could you test with the item?

**Comment by Asheraf** [comment]
@xBeret this issue happens only if you're using `bAddRaceTolerance` in pre-re build, it doesn't really need testing.

**Comment by xBeret** [comment]
@Asheraf  sorry, I forgot bAddRaceTolerance only works on renewal.
