### ISSUE TITLE
fakename stops guild/party names from showing

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#1966]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

When you have a fakename from using **@fakename**, your guild and party names and guild positions won't be shown.

In the function `clif_charnameack`, I was able to resolve this issue. I'm unsure if it has side effects, but seems to work okay so far!

Find:
```
			if (ssd->fakename[0] != '\0') {
				WBUFW(buf, 0) = cmd = 0x195;
				memcpy(WBUFP(buf,6), ssd->fakename, NAME_LENGTH);
				WBUFB(buf,30) = WBUFB(buf,54) = WBUFB(buf,78) = 0;
- 				break;
			}
+			else
- 			memcpy(WBUFP(buf,6), ssd->status.name, NAME_LENGTH);
+ 				memcpy(WBUFP(buf,6), ssd->status.name, NAME_LENGTH);
```

Also, this is not a bug, rather an undesired feature. I will try to figure out how PR works to see if I can do it myself.

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by Emistry** [comment]
perhaps add a new parameter to toggle for both party/guild names?

hiding guild/party name under  certain condition are good, especially during GM host event where the GM disguised as other player who doesnt have party/guild, or maybe a monster.

something like
```
@fakename <option>
0 - default, hide both guild/party name
1 - only hide party name
2 - only hide guild name
3 - hide both party and guild
```

**Comment by EyesOfAHawk** [comment]
nice idea emistry. what do you think of my PR? I made it like @fakename, @fakename2, etc.
https://github.com/HerculesWS/Hercules/pull/1967

**Comment by Kenpachi2k13** [comment]
When using RE client (I used 2019-02-20aRagexeRE), every character info vanishes.
Even the fake name won't show up.
