### ISSUE TITLE
nullpo rodex

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#1977]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

The Rodex system is occurring nullpo error when deleting, but need to do some steps to get the error.

![sem titulo](https://user-images.githubusercontent.com/8175669/36357109-f1486f1c-14d7-11e8-8ba7-1e9cb46c474f.png)

**Client:** 2018-01-24bRagexeRE

The NPC used for testing is just below

```c
prontera,150,150,4	script	Rodex Mail	1_M_01,{
	rodex_sendmail(
		getcharid(CHAR_ID_CHAR), "Rodex Test", "Rodex Test1", "Hello World, How are You?",
		1000,
		Red_Potion, 5
	);
	end;
}
```

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)
### Steps To Reproduce The Issue

**1.** Talk to the NPC and get the reward, open rodex and pick up the items and zeny, but do not remove the email yet

**2.** Talk to the NPC again, take the items and Zeny, do not remove message yet

**3.** Close the Rodex and open again, select the two messages and try to remove only one will be removed, and the other will cause nullpo error. Relog and try to remove the message, and now it is possible to remove.

**Note:** Sometimes it is removed correctly, try until you get nullpo error 

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 59f02f1d406a1238f90d072949ac07279a90e9ea

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by xBeret** [comment]
@4144 @Asheraf

**Comment by guilherme-gm** [comment]
I'm working on it! I've found the cause already, but it'll take a couple days before a PR is ready
