### ISSUE TITLE
--db2sql breaks with segmentation fault

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1984]
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
 ./map-server --db2sql  breaks with segmentation fault

**Comment by 4144** [comment]
can you show call stack?

**Comment by tlacson7** [comment]
i cant use gdb ./map-server --db2sql
how to generate call stack?

**Comment by 4144** [comment]
run like this:
```
gdb --args ./map-server --db2sql
```
also crash probably because you loaded all default plugins?

**Comment by tlacson7** [comment]
the only loaded plugins was db2sql.

http://tinypic.com/r/2mxetjt/9

**Comment by tlacson7** [comment]
http://tinypic.com/r/2yn5jeh/9

**Comment by 4144** [comment]
look like you have local modifications or using outdated hercules
can you say last commit id?

also try do same on clean hercules.

**Comment by tlacson7** [comment]
yes new Herc, im using:
svn checkout   https://github.com/HerculesWS/Hercules/trunk ~/Hercules
- Plugin Loaded: db2sql
./configure && make clean && make sql && make plugins

**Comment by tlacson7** [comment]
please check on this @4144 thanks sir

**Comment by 4144** [comment]
hercules not using svn and never used.

you not gave commit id, and not said what you changed in hercules code.
can you show crash stack from clean hercules and without other plugins?  and better as text and not as image.

**Comment by tlacson7** [comment]
im sorry but if svn is no longer supported in Hercules. I think its better to revise this guide:

http://herc.ws/board/topic/152-obtaining-hercules/

Git Revision: 59f02f1
- latest revision
- disable renewal
- only db2sql plugin is loaded.
- no other changes on db script or source.
