### ISSUE TITLE
Incorrect whisper packet

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#1993]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

Whisper packet is incorrect in hercules, in 2013 it has been updated, here is the result of zone_server.

```c
// packet 0x9DE
struct PACKET_ZC_WHISPER_V2 {
  short PacketID;
  short PacketLength;
  unsigned long GID;
  char senderName[24];
  char msg[];
};
```
```c
// packet 0x9DF
struct PACKET_ZC_ACK_WHISPER_V2 {
  short PacketID;
  unsigned char result;
  unsigned long GID;;
};
```

`p.unknown = 0;` is incorrect change to `p.GID = sd->status.char_id`

https://github.com/HerculesWS/Hercules/blob/d89690fbdbaa5dc78f98d96ee91403e329c12af1/src/map/clif.c#L6082-L6084

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: d89690fbdbaa5dc78f98d96ee91403e329c12af1

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by xBeret** [comment]
@4144

**Comment by 4144** [comment]
This packets look like too old.
Atleast packet 0x9de wrong for 2017 clients.
Probably it was changed after 2013.

**Comment by Kenpachi2k13** [comment]
Fixed in https://github.com/HerculesWS/Hercules/pull/2176.
`close();`
