### ISSUE TITLE
 make_connection: connect failed (socket #6, error 111: Connection refused

### ISSUE THREAD

**Issue by yashin16** [HerculesWS/Hercules#1999]
I set up a server with Hercules. It worked normal offline on my pc, but when I put it in the host and configured it with the correct ips, the emulator loads everything but at the end of this error message and does not connect. I tried using the same emulator without my modifications and continued the error in the end when putting online. can you help me?

![connection error](https://user-images.githubusercontent.com/31966843/37879428-56570228-304f-11e8-8755-d88c56d1d0e8.png)

**Comment by 4144** [comment]
close ports or incorrect configured ips.
how configure server better ask in forums or irc or discord.
bug tracker for bugs.

**Comment by yashin16** [comment]
Incorrect. The ip is configured with the ip that I was already using before on my old server and also so the ports are not closed because it is an online host and be standard ports for ragnarok
