### ISSUE TITLE
script-checker.bat always throw missing map file

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2013]
-  [ ] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.

I think I have modify the mapcache a little bit ?
but can somebody confirm this ?

when I try to execute **Hercules\script-checker.bat**
and throw in WHATEVER file ... ANY file will do
```
[Warning]: map_readfromcache: Could not open the mapcache file for map 'poring_c01' at path 'maps/re/poring_c01.mcache'.
[Warning]: map_readfromcache: Could not open the mapcache file for map 'poring_c02' at path 'maps/re/poring_c02.mcache'.
```
yup ~ like this ~
![script-checker](https://raw.githubusercontent.com/AnnieRuru/customs/master/screenshots/script_checker.png)

but my map_server.exe runs just fine
```
[Status]: Loading maps using map cache files...
[Info]: Successfully loaded '880' maps.
[Status]: Done reading '62' command aliases in 'conf/atcommand.conf'.
[Status]: Done reading '4' channels in 'conf/channels.conf'.
......
```

**Comment by dastgirp** [comment]
If we run script checker, it runs map-server with minimal settings (minimal settings ignore maps.conf, which does not have poring_c01 map), however it still considers map_index.txt.
Definitely a bug, I suppose possible fix:
1) Remove poring_c01/02 from map_index.txt and
2) show warning on map-server without minimal settings too

**Comment by AnnieRuru** [comment]
curious ... is there any difference with poring_c01 and poring_w01 ?
I think ... they are similar ...

maybe gravity changed their map name from poring_c01 into poring_w01 ... or something

**Comment by AnnieRuru** [comment]
just test again, this has been fixed
