### ISSUE TITLE
Cast time of Renewal MG_FIREBOLT and MG_LIGHTNINGBOLT level 7 seems wrong.

### ISSUE THREAD

**Issue by BrOgBr** [HerculesWS/Hercules#2016]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

https://github.com/HerculesWS/Hercules/blob/stable/db/re/skill_db.conf

> CastTime: {
>         Lv1: 640
>         Lv2: 960
>         Lv3: 1280
>         Lv4: 1600
>         Lv5: 1920
>         Lv6: 2100
>         **Lv7: 1560**
>         Lv8: 2880
>         Lv9: 3200
>         Lv10: 3520

level 7 lower then 6,5 and 4?
I can't confirm the official information, but it seems wrong.

rathena/rathena/issues/3042

Sorry, I don't know how to report properly issues in herc, trying to help only. :)

 ##

**Branch(es):**
- [x] master
- [ ] other

**Comment by kyeme** [comment]
It's typo. The correct is 2560

**Comment by Asheraf** [comment]
according to aegis what we have is correct.

https://github.com/skyiing/Aegis/blob/master/ZoneServer/skill/SkillCastStatDelay.txt#L74
