### ISSUE TITLE
Effects does not reset the counter when relogin character

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#2018]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

Today I was testing some things in the kRO when I noticed that when the relogin character the time counter of the effects was not reset.

the bar continued from where it stopped, in hercules when you relogin character or close emulator open again the time loading bar of effects starts from the beginning again.

The bar I say is that of the effect time the one of white color and turns red when 1 min is missing.

![sem titulo](https://user-images.githubusercontent.com/8175669/38883970-bef93114-4244-11e8-9bdc-f76b5d93140b.png)

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Expected Behavior

[//]: # (Tell us what should happen instead.)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 7b097da8b433ea3b768b6c306c12801f7ddef0a5

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by xBeret** [comment]
Can anyone confirm? @Asheraf

**Comment by Jedzkie** [comment]
maybe this can help?

https://github.com/3CeAM/3CeAM/commit/e94e138c0bebcada7ee058a797dbb6174010e813
