### ISSUE TITLE
Monster transform

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#2035]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

When this system was implemented only the part of the scrolls were made, however there is the bonus part of applying damage and receiving damage.

Aegis uses another effect called `EFST_ACTIVE_MONSTER_TRANSFORM`, this effect was not applied in Hercules.

Several items use this effect, here some videos about this bonus.

This effect there is a **rate** and **time** that keeps the player transformed

https://youtu.be/UkVmNCXdnFY?t=1m
https://www.youtube.com/watch?v=sFOc7W5QY1Q&feature=share

![2zya8a8](https://user-images.githubusercontent.com/8175669/39715901-1ad09c6e-5205-11e8-949f-61003af91441.jpg)

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

**Branch(es):**
- [x] Stable
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 5c9056c183421df41b546dc3031d251ee6c963b5

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by xBeret** [comment]
@Asheraf You can confirm that

**Comment by Asheraf** [comment]
Isn't this done via `autobonus` + `montransform`

example:
```
Script: <" autobonus2 "{ bonus bStr, 200; bonus2 bHPLossRate, 500, 1000; montransform BIGFOOT, 5000; }", 20, 5000, BF_WEAPON, "{ specialeffect(EF_POTION_BERSERK, AREA, playerattached()); showscript \"?!!!!\"; }"; ">
```

I'm not sure how this works in aegis but i don't see any differences in how the items work in Hercules and kRO.

**Comment by xBeret** [comment]
@Asheraf 

There are 2 effects that are them:

EFST_MONSTER_TRANSFORM is used for scrolls.

EFST_ACTIVE_MONSTER_TRANSFORM is used for activation transformations where in the official you need to apply damage or receive damage to activate the transformation for a few seconds

Some items. 

https://www.divine-pride.net/database/item/18856
https://www.divine-pride.net/database/item/18756
https://www.divine-pride.net/database/item/4875

iRO

**Comment by Asheraf** [comment]
A script example from Aegis:
```
	event OnActiveWeapon:							
		ShowEffect "" EF_POTION_BERSERK						
		ShowScript "" "Human can show up, or get out of here Goast!!"						
		Active_Montransform DULLAHAN						
		SetIgnoreDEFClass CLASS_Normal						
		SetIgnoreDEFClass CLASS_Boss						
	return							
	event OnDeactiveWeapon:							
		ShowScript "" "Apple's yummy!"						
		DeActive_Montransform DULLAHAN						
		ResetIgnoreDEFClass CLASS_Normal						
		ResetIgnoreDEFClass CLASS_Boss						
	return	
```

again this is same as we do it only different seems to be gravity using separate status for no reason..

**Comment by xBeret** [comment]
@Asheraf There is 2 state effect because if you are on the effect of a scrolling effect of the change it will not be removed.

In other words, if I am on the scroll effect I will turn into another and when that activation effect time ends I go back to the effect of scroll.

Did you understand?

**Comment by AnnieRuru** [comment]
yeah, when beret ask questions in my PM box, I also have to ask back a few times to really understand what he means

how about I ask you back a few questions since I also don't really understand what you are trying to say

1. do you mean IF I wear item ID 4875, `Bears_Power` and use the scroll ID 11592, `Trance_Candy_R`, the effect doesn't stack ?
and it trigger separately ?
if I really understand what you are trying to say, the scroll effect takes priority ? or the equipment effect takes priority ?

2. then what is the behavior in Aegis if I do like example 1 ?
and what is the current behavior in Hercules ?


like I said, you are the kind of member that can't explain yourself properly

**Comment by xBeret** [comment]
@AnnieRuru you looked at the video before you ask? 

Because you posted without even looking at the videos and still think I can't explain, is hard to explain if you have no concept of the system.

But I'll try to explain again.

Just look at the current code of hercules the montransform script command. This command when you run it removes the effect and applies a new effect, that is correct for the scrolls.

Now there is a transformation that applies to items, this transformation cannot use the same effect of the scrolls. If the player is with the scroll effect he's going to lose.

At aegis if the player is with the effect of transformation of the scroll and activate the item transformation, the transformation of the scroll cannot be removed.

Just look at the video.

**Comment by Asheraf** [comment]
To be fair the initial post you made (which is what i read from my email) had only one video that didn't show anything useful, anyways yes this now makes sense the effect should be stackable while currently we over write them.

**Comment by xBeret** [comment]
@Asheraf Is that I found only the first video and ended up posting only it. Then I found the second that showed the mechanics and edited the post.

Anyway thank you Asheraf for the confirmation

**Comment by marcosbucarte** [comment]
@Asheraf @dastgirp @hemagx @Emistry 

anything about it? is an old feature that missed this part of implementation.

**Comment by marcosbucarte** [comment]
@Emistry something about it?
