### ISSUE TITLE
MvP no Slaves

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2044]
-  [x ] I have not modified the source prior to reproducing this issue.
-  [ x] I am using the latest version of Hercules.
-  [ x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

Using Pre-RE and latest fresh GIT.  Please confirm.
MvP does not summon its slaves.

**Comment by AnnieRuru** [comment]
https://github.com/HerculesWS/Hercules/pull/2042
have you try this pull request ?
