### ISSUE TITLE
Pin Code

### ISSUE THREAD

**Issue by marcosbucarte** [HerculesWS/Hercules#2046]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

If the player sets their PIN code for the first time an error happens.

When entering with character on the server maps you receive the message `rejected from server`.

is incorrect as it currently works, on the official servers when you set your PIN for the first time a window asking for confirmation of the pin opens soon after.

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 5c9056c183421df41b546dc3031d251ee6c963b5

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by marcosbucarte** [comment]
@Jedzkie @4144

**Comment by Jedzkie** [comment]
@marcosbucarte I never encountered this error, what client you're using?

**Comment by Jedzkie** [comment]
Okay i confirmed this issue, and i currently working for a fix. Thanks for the report.

**Comment by marcosbucarte** [comment]
Something about it ? @Jedzkie

**Comment by Jedzkie** [comment]
@marcosbucarte Sorry for the delay, I already made a fix. Please check it. Thanks
