### ISSUE TITLE
pvp_nocalcrank mapflag doesn't function properly

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2056]
### Issue Prelude
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
although a map has `pvp_nocalcrank` mapflag turn on,
but it still shows the pvp ranking and timer on as shown below

### Steps To Reproduce The Issue
```prontera	mapflag	pvp_nocalcrank```
1. type `@pvpon` in chat as executing atcommand
2. you'll see the timer running on top and players remaining at down-right corner
3. type `@refresh` somehow, the pvp ranking is gone

### Current Behavior
currently if the map has `pvp_nocalcrank` mapflag,
while the players IN THE MAP and execute these commands
`*setmapflag` `*pvpon` script command or `@pvpon` atcommand
will show the pvp ranking and timer

### Expected Behavior
`pvp_nocalcrank` mapflag should never show pvp ranking in any way
as long as the map has `pvp_nocalcrank` 

### Additional Information
`pvp_nocalcrank` mapflag I think its use for pk server,
this only execute if the server already has pk_mode turn on
so when players load the map, it doesn't shows the pvp ranking or timer and still able to pk

and nobody actually play with this mapflag ... anyways ...

### Branch(es):
- [x] master
- [x] stable
this bug has been exist for as long as I could remember, back in eathena days

### Hercules rev. hash/commit: & Operating System
```
[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): 'fc175850efdb4dd258dd8bbab4b01be8f1c327fa'
[Info]: Git revision (scripts): 'fc175850efdb4dd258dd8bbab4b01be8f1c327fa'
[Info]: OS version: 'Windows 7 Ultimate Service Pack 1 (build 7601) [x86]'
[Info]: CPU: 'x86 CPU, Family 6, Model 23, Stepping 10 [2]'
[Info]: Compiled with Microsoft Visual C++ 2015 (v1900)
```

**Comment by 4144** [comment]
@AnnieRuru can you check is this pr works? https://github.com/HerculesWS/Hercules/pull/2057
