### ISSUE TITLE
*showdigit will continue to countdown if the player logout

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2058]
### Issue Prelude
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
there is no known way to remove a `*showdigit` if player logout while the timer is running

### Steps To Reproduce The Issue
```
prontera,155,185,5	script	kjdfksjdf	1_F_MARIA,{
	showdigit 0, 1;
//	showdigit 1, 3;
//	showdigit ~10, 2;
	end;
OnPCLogoutEvent: // doesn't work
	showdigit 0, 0;
//	showdigit 1, 3;
	end;
}
```
1. click on the npc, it shows you the timer counting down
2. press Esc, choose [Character Select]
3. login back, the timer still runs !

### Current Behavior
`*showdigit` will continue run the timer if the player logout by character select
even you use Player A to run the timer, logout,
then choose Player B in the same account, the timer still runs !

### Expected Behavior
there should be some script command that can remove this countdown timer

### Branch(es):
- [x] master
- [x] stable

### Hercules rev. hash/commit: & Operating System
```
[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): 'c81fee18c0d5ed70f8717679ee16cebe5e591c58'
[Info]: Git revision (scripts): 'c81fee18c0d5ed70f8717679ee16cebe5e591c58'
[Info]: OS version: 'Windows 7 Ultimate Service Pack 1 (build 7601) [x86]'
[Info]: CPU: 'x86 CPU, Family 6, Model 23, Stepping 10 [2]'
[Info]: Compiled with Microsoft Visual C++ 2015 (v1900)
```
client version 2017-05-17

**Comment by dastgirp** [comment]
It seems it is client side bug.
we don't save anything in server. we just send the packet 0x1b1 to the client, and client handles the rest.

**Comment by AnnieRuru** [comment]
yeah `ZC_SHOWDIGIT` ...

I guess have no choice but to do like adding [`bug_showdigit`](http://upaste.me/1b3249619f23c7755#LC188) player variable then
```
prontera,155,185,5	script	kjdfksjdf	1_F_MARIA,{
	showdigit 0, 1;
	bug_showdigit = true;
	end;
OnPCLoginEvent:
	if ( bug_showdigit ) {
		showdigit 0, 3;
		bug_showdigit = false;
	}
	end;
}
```
