### ISSUE TITLE
doc\map_cache.txt is outdated

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2060]
https://github.com/HerculesWS/Hercules/blob/stable/doc/map_cache.txt

somebody has to update this file,
many members are confuse how the new map_cache system works

**Comment by dastgirp** [comment]
Guide: http://herc.ws/board/topic/15868-guide-mapcache-generation-2018/,
anyone willing to do this, needs to do it in Markdown syntax

**Comment by jvastbinder** [comment]
I can do this
