### ISSUE TITLE
New exp_db causing map-server crash

### ISSUE THREAD

**Issue by marcosbucarte** [HerculesWS/Hercules#2070]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
If the job and base exp group of some class in job_db.conf is not present in the file, crash occurs on the map server when reading db.

In Novice job comment the exp groups.

```
 //BaseExpGroup: "FirstClasses"
 //JobExpGroup: "Novice"
```

Test performed on windows
![imgerr](https://user-images.githubusercontent.com/38480564/41081126-fe431b72-69ff-11e8-968b-f865e886e185.png)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 81d02447f733ff802614c338cecfd88adad76ace

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by marcosbucarte** [comment]
@Asheraf

**Comment by EyesOfAHawk** [comment]
i thought this was intentional lol so i didnt report. silly me.
