### ISSUE TITLE
HP_chr_make_new_char_sql out of date

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#2096]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

I'm looking at in **HPMHooking_char_Hooks.inc** and it has the following struct:
`int HP_chr_make_new_char_sql(struct char_session_data *sd, const char *name_, int str, int agi, int vit, int int_, int dex, int luk, int slot, int hair_color, int hair_style, short starting_job, uint8 sex)`

Whereas in our current `src/char/char.c` it is
`int char_make_new_char_sql(struct char_session_data *sd, const char *name_, int str, int agi, int vit, int int_, int dex, int luk, int slot, int hair_color, int hair_style, int16 starting_class, uint8 sex)`

As you can see, using `short starting_job` instead of new `int16 starting_class`.

Either way, I can't get my plugin to work. (stops people from using 'GM' in their character name)
```
int chr_make_new_char_sql_pre(struct char_session_data **sd, const char **name_, int *str, int *agi, int *vit, int *int_, int *dex, int *luk, int *slot, int *hair_color, int *hair_style, short *starting_job, uint8 *sex)
{
	char name[NAME_LENGTH];
	char esc_name[NAME_LENGTH * 2 + 1];
	int flag;

	nullpo_retr(-2, *name_);
	safestrncpy(name, *name_, NAME_LENGTH);
	normalize_name(name, TRIM_CHARS);
	SQL->EscapeStringLen(inter->sql_handle, esc_name, name, strnlen(name, NAME_LENGTH));

	flag = chr->check_char_name(name, esc_name);
	if (flag < 0)
		return flag;

	if (stristr(name, "GM")) {
		if (stristr(name, "GM-") || stristr(name, "-GM") || stristr(name, " GM") ||
			stristr(name, "GM.") || stristr(name, ".GM") || stristr(name, "~GM") ||
			stristr(name, "GM~") || stristr(name, "_GM") || stristr(name, "GM_") ||
			stristr(name, ",GM") || stristr(name, "GM,") || stristr(name, "`GM") ||
			stristr(name, "GM`") || stristr(name, "GM'") || stristr(name, "'GM") ||
			stristr(name, "*GM") || stristr(name, "GM*") || stristr(name, "(GM") ||
			stristr(name, "GM)") || stristr(name, "[GM") || stristr(name, "GM]") ||
			stristr(name, " GM") || stristr(name, "GM ")) {
				hookStop();
				return -3;
			}
	}
	return -1;
}


/* run when server starts */
HPExport void plugin_init (void)
{
	if (SERVER_TYPE == SERVER_TYPE_CHAR) {
		// Pre-Hooks
		addHookPre(chr, make_new_char_sql, chr_make_new_char_sql_pre);
	}
}
```

**Branch(es):**
- [x] master
- [x] stable

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

CentOS 7

**Comment by 4144** [comment]
This is not HPM issue. in .c and in .h used different type names. But they reallase same
``int8`` is ``short int``. This is actually error, but it not affect code on probably all systems where hercules can works.

About your bug in plugin, look like you using ``stristr`` in wrong way

**Comment by EyesOfAHawk** [comment]
it work good when i try it directly in src. the hook is not happening at all. I tested by doing a `ShowInfo` at the start of the hook.
