### ISSUE TITLE
Bug when using hide with disguise

### ISSUE THREAD

**Issue by SombraRO** [HerculesWS/Hercules#2104]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

When the character is on the **disguise effect** and enter the **state of hide** and exit the state hide sometimes your character is in permanent hide mode, so you can exit hide state need to use command **refresh**.

**Hexed: 2018-05-02**

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 81d02447f733ff802614c338cecfd88adad76ace

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by SombraRO** [comment]
@4144

**Comment by Lemongrass3110** [comment]
rathena/rathena#1370 just for references.

**Comment by SombraRO** [comment]
@Kenpachi2k13 any idea about that?

**Comment by Kenpachi2k13** [comment]
@SombraRO
I didn't notice this issue before. I'll have a look at it over the next few days.

**Comment by Kenpachi2k13** [comment]
@SombraRO  Some questions:
 * Which client are you using? (There are 3 from 2018-05-02 -> 2018-05-02bRagexe, 2018-05-02bRagexeRE, 2018-05-02dRagexeRE)
 * Can you list all patches your client contains?
 * Did you notice this bug with other clients?
 * Did you notice this bug with a newer version of Hercules than 81d0244?
 * Is your server running in RE or pre-RE mode?
 * When saying "hide", do you mean GM hide (@<span></span>hide) or something else?
 * Did you notice any other circumstances which may trigger that bug?

**Comment by SombraRO** [comment]
@Kenpachi2k13 I will test again tomorrow and give you an answer.

**Comment by SombraRO** [comment]
@Kenpachi2k13 I tested again on the latest version of hercules and the problem still occurs.

- I am using client **2018-05-02bRagexe** also tested with latest **2020** client
- I don't have the patches applied anymore, but I only tested with the basic activated
- Tested in PRE-RE mode

**How to reproduce this problem**

- Use the **@disguise poring** command
- Then use the command (@hide)
- use the @hide command again and the problem occurs the character does not appear

**Comment by Kenpachi2k13** [comment]
Thank you. Finally I'm able to reproduce this.
