### ISSUE TITLE
Mobs (visually) reappear after death under certain circumstances

### ISSUE THREAD

**Issue by drdaxxy** [HerculesWS/Hercules#2109]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

Under some circumstances, e.g. with certain skills causing knockback like *Magnum Break*, players may see mobs that have died reappear with 0 HP in an idle animation.

### Current Behavior

Hercules may send `ZC_NOTIFY_MOVEENTRYn` packets concerning units that have already died. If the client has already removed the unit from its state before receiving that packet, it will recreate it, thus displaying a stuck mob with 0 HP to the player until they relog. (I believe this is not a client bug as this packet type may also be used to notify clients of units they have legitimately not seen before.)

A fairly consistent the problem manifests is when mobs whose movement speed has changed through *Increase AGI* die to some knockback skills. In these cases, the offending packet is sent at https://github.com/HerculesWS/Hercules/blob/c419726752ebd1b532f487e5683f63232a6c237b/src/map/clif.c#L1866 However, this is not necessarily the *only* place that can send it. I'm aware of MvP slaves sometimes displaying the glitch after their master dies on a live server (with source modifications), however I've not been able to reproduce that on unmodified Hercules, personally.

Lowering the unit removal notification delay in https://github.com/HerculesWS/Hercules/blob/c419726752ebd1b532f487e5683f63232a6c237b/src/map/mob.c#L2728 makes the issue occur more frequently but is not required.

Issue has been reproduced on `2018-06-21aRagexeRE` and `2018-04-04cRagexeRE` but most likely affects clients many years older as well.

### Expected Behavior

`ZC_NOTIFY_MOVEENTRYn` packets, as crafted in https://github.com/HerculesWS/Hercules/blob/c419726752ebd1b532f487e5683f63232a6c237b/src/map/clif.c#L1303 should never be sent after `ZC_NOTIFY_VANISH` (unless the mob is intended to be recreated on client).

### Steps To Reproduce The Issue

1. Log on with a *Swordsman* that can kill *Orc Lady* in 2-3 *Magnum Breaks*
2. Mob *Orc Ladies*, wait for a few to use *Increase AGI*
3. Kill them with *Magnum Break*

It's not 100% consistent, but a few iterations of this should cause at least one *Orc Lady* to reappear with 0 HP.

**Branch(es):**
- [x] master
- [x] stable

**Hercules rev. hash/commit:** 

Git revision src: 'c419726752ebd1b532f487e5683f63232a6c237b'

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by AnisotropicDefixation** [comment]
Yeah that's a very old issue.

I believe that [this](https://github.com/HerculesWS/Hercules/issues/2047) could be also related as all those cases exhibit visual "movement" of units that shouldn't be moving.

**Comment by guilherme-gm** [comment]
Can you try manually patching #2088 and see if it the problem persists? I made this pull request to fix a similar issue. In my case we found out that it was happening when the monster got out of area range (14 cells far) during the 250ms after its death because those clients didn't receive the dead packet.

**Comment by drdaxxy** [comment]
I should clarify that it *is* legitimate to send `ZC_NOTIFY_MOVEENTRYn` while a mob is dying (serverside, HP = 0), but *before* sending `ZC_NOTIFY_VANISH`. I believe some lethal attacks like Bolt skills will in fact do that, but I haven't had time to confirm.

Hence, mobs should be flagged "death packet sent, do not send `ZC_NOTIFY_MOVEENTRYn` etc." after `clif_clearunit_area` has been run on them with `CLR_DEAD`. That function may not be the cleanest place to do that, but care must be taken to set this after the packets have been sent out, not right after they're *scheduled* with `clif_clearunit_delayed`.

Unless of course there's ever a reason to "revive" a mob. `NPC_REBIRTH` shouldn't be one as that doesn't trigger a unit clear in the first place but I can't guarantee there aren't others I'm forgetting about. See  https://github.com/HerculesWS/Hercules/blob/eed4e9bb3a466cfe32bdb72df12c7ad2ceb0dd79/src/map/mob.c#L2742

@guilherme-gm That's not quite the same issue. In the one this thread is about, the server does correctly deliver `ZC_NOTIFY_VANISH` for the dying mob, causing the death animation to play and the mob to disappear - but sends another `ZC_NOTIFY_MOVEENTRYn` for that mob afterwards, causing the client to *recreate* it.

@AnisotropicDefixation While the effects seem related, I don't think there's a common root cause for these bugs. Here we have a race condition, #1578 is state not being reset correctly (presumably on the server side - I seem to recall this happening to Ant Eggs right after I walk onto the map for the first time, so the client's never seen the previously hatched mobile mobs)...

**Comment by AnisotropicDefixation** [comment]
The easiest way to recreate this issue is killing monsters with skills that knockback, root/stun, or a combination of those, and the issue #2047 involves monsters appearing as "walking" under the same conditions, and it happens much in the same way. The sprite of a monster that's supposed to be dead or unable to move, "walks" for some distance then stops and rubberbands back to its original spot once the status ends and it's still alive, if it's dead then doing a refresh fixes the position.
Maybe there are different causes but some of them might be involved in both issues.
