### ISSUE TITLE
Sea-Otter Card not increasing effectiveness of Sushi

### ISSUE THREAD

**Issue by HansLowell** [HerculesWS/Hercules#2116]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [ ] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)

Sea-Otter card is not increasing effectiveness of sushi will using the card.
It is only increasing the effectiveness of raw fish.

[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

The problem is in the scripts
https://raw.githubusercontent.com/HerculesWS/Hercules/stable/db/pre-re/item_db.conf

It is written this:
Script: <"
		bonus2 bAddItemHealRate,Sushi,50;
		bonus2 bAddItemHealRate,Fish_Slice,50;
		bonus3 bAddMonsterDropItem,551,RC_Fish,300;
		bonus3 bAddMonsterDropItem,544,RC_Fish,300;

But the Aegis name of sushi is Shusi:

Id: 551
	AegisName: "Shusi"
	Name: "Sushi"
	Type: "IT_HEALING"
	Buy: 1
	Weight: 50
	BuyingStore: true
	Script: <" itemheal rand(50,60),0; ">

### Current Behavior

While sea-otter card is equiped raw-fish heal more than sushi, 
and there is no difference on heal with or without sea-otter card while using sushi

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior

Heal from sushi should be more than raw fish on average and there should be a difference with and without the acessory equiped.

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. Step 1 Equip an acessory with sea-otter card
2. Step 2 use multiple sushi
3. Step 3 use multiple raw-fish
4. Step4: compare values

**Branch(es):**
- [x] master

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

Windows 7

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by Jedzkie** [comment]
Are there errors on console? Please show it.

**Comment by skyleo** [comment]
@Jedzkie There's no error, since a non-existant constant is just a character variable :)
And since the character variable Sushi doesn't exist, it evaluates to 0.

**Comment by AnnieRuru** [comment]
I think we should have item ID check in the source code
same with monster ID ...
so it print an error ... invalid ItemID or something...
