### ISSUE TITLE
SI_Postdelay never dissappears

### ISSUE THREAD

**Issue by Shizuke** [HerculesWS/Hercules#2118]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)
SI_postdelay not hiding after time is up.

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)
SI_POSTDELAY icon is shown but it never dissapears.

### Expected Behavior

[//]: # (Tell us what should happen instead.)
SI_POSTDELAY should dissappear after postdelay is done. For example when using 190 aspd double strafe the timer should be 200ms.

### Steps To Reproduce The Issue

1. Put [EFST_IDs.EFST_POSTDELAY] on stateiconimginfo.lub
2. Use any skill.

**Branch(es):**
- [x] master

**Comment by Shizuke** [comment]
bump?

**Comment by Emistry** [comment]
Maybe one of the reason it wasn't displayed originally, are because of the short duration?
status icon duration that less than 1 seconds to display at the client, sound like not needed?

maybe need to create a timer that trigger after 200ms to remove it
![sample](https://i.imgur.com/rOz6Olb.png)

**Comment by Kenpachi2k13** [comment]
It's not a server-related issue, if the client needs modification to trigger this behaviour...
`close();`
