### ISSUE TITLE
Roulette not working correctly

### ISSUE THREAD

**Issue by SombraRO** [HerculesWS/Hercules#2120]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

When the roulette is open the items are not in the correct position, also when you play the roulette and lose you are not able to pick up the coin.

The bonus tab also does not work on hercules, in the official it works normal.

In the video you can see that there are items in the bonus tab

https://www.youtube.com/watch?v=n76720cG1ac

**Client: 20180621**

![rl](https://user-images.githubusercontent.com/39016868/42287801-42ccfbac-7f8e-11e8-8d50-c8e504ca2b65.png)

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: eed4e9bb3a466cfe32bdb72df12c7ad2ceb0dd79

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

**Comment by SombraRO** [comment]
@4144 @Asheraf

**Comment by dastgirp** [comment]
Open if not solved
