### ISSUE TITLE
** Guild Mismatch ** (Critical)

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2122]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [ x] I have not modified the source prior to reproducing this issue.
-  [x ] I am using the latest version of Hercules.
-  [ x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Can't invite to guild
     Pre-Re, client 20151029
      Error: [Info]: int_guild: guild withdraw (1 - 2000001: join - ** Guild Mismatch **)

**Branch(es):**
- [x ] master
- [ ] other

**Hercules rev. hash/commit:** 
latest pull

**Comment by EyesOfAHawk** [comment]
Check your SQL for the character id being invited. Maybe some error they already got guild idk.
```
static struct map_session_data *guild_sd_check(int guild_id, int account_id, int char_id)
{
	struct map_session_data *sd = map->id2sd(account_id);

	if (!(sd && sd->status.char_id == char_id))
		return NULL;

	if (sd->status.guild_id != guild_id) {
		//If player belongs to a different guild, kick him out.
		intif->guild_leave(guild_id,account_id,char_id,0,"** Guild Mismatch **");
		return NULL;
	}

	return sd;
}
```

**Comment by tlacson7** [comment]
i tied this in new database..2 accounts only

**Comment by marcosbucarte** [comment]
The same thing happened to me.

@4144 @MishimaHaruna Could anyone look at this?

**Comment by tlacson7** [comment]
no, i did not
1. download new herc
2. add new database and 2 account
3. 1st account make guild
4. invite 2nd account.
that is what i did. no modification on source. only:
- clientver
-prere

**Comment by MishimaHaruna** [comment]
Confirmed, I can reproduce this, I'll review the mapif-related changes from #2108

**Comment by MishimaHaruna** [comment]
Found the issue, the order of operations in `mapif_parse_GuildAddMember` / `inter_guild_add_member` changed. A patch that restores the previous order is on its way.

**Comment by MishimaHaruna** [comment]
The fix has been merged to the stable branch
