### ISSUE TITLE
Pets egg bug

### ISSUE THREAD

**Issue by Helheim90X** [HerculesWS/Hercules#2135]
[x]: # (**********************************)
[x]: # (** Fill in the following fields **)
[x]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Pets are not dissapearing its own eggs after you hatch them using an incubator.

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior

Any pet egg is working like this... they remain in the inventory as an unknown item... which is not normal. At the beginning the egg disappears, but if you do refresh command, the egg will show up in your inventory. If using a magnifier it will detect the egg as an unknown item.

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior

The egg should disappear after hatching the pet, and it shouldn't come back in your inventory unless you return the pet to the egg... But in this case  is detecting the egg as an existing item that returns as soon as you walk through a warp or use @refresh command...

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. Catch a pet or Make an egg... for example: @item 9055
2. Hatch it using a pet incubator.
3. change the map, warp or @refresh... Pet egg will appear in your inventory as an Unknown item

**Branch(es):**
- [x] master
- [x] Stable

**Hercules rev. hash/commit:** 
Latest Stable and Master

### Operating System

CentOS
(Sorry i don't know how to fill the checklist, but i have not modified anything from the src)

**Comment by tlacson7** [comment]
i receive report about this in my server. i will try to reproduce
