### ISSUE TITLE
local functions can be called as events

### ISSUE THREAD

**Issue by Helianthella** [HerculesWS/Hercules#2137]
since local function names and labels are both stored in the same strdb it is possible to call a local function as if it were an event when it has a name that begins with `On`
```c
// define a function in MyNPC
function OnMyFunction {
	debugmes("hello!");
	return;
}

// then it can be called from anywhere:
donpcevent("MyNPC::OnMyFunction");
```

```ini
[Debug]: script debug : 0 110000354 : hello!
[Warning]: script:run_func: return without callfunc or callsub!
```
This affects not just custom events but rather every single event calls (oninit, onlogin, mob death, timers, clock, woe, …) since they all use the same functions

<br>

---
We should either make it illegal or officially support it, which would be a great idea as we could get rid of most labels and use functions everywhere. As syntax for the event string we could use
```c++
MyNPC::MyFunction()
```
so if parentheses are found it is a function call, else it is a normal label call

**Comment by AnnieRuru** [comment]
at this moment we can use a floating npc then donpcevent
not really urgent to implement this ...

**Comment by mekolat** [comment]
this is far from urgent, I just put severity 3 because it is [defined](https://github.com/HerculesWS/Hercules/wiki/Bugtracker-Labels#severitymedium-incorrect-mechanics-or-behavior
) as `Script command not behaving accordingly to what's expected`
