### ISSUE TITLE
failed assertion

### ISSUE THREAD

**Issue by greatjon1** [HerculesWS/Hercules#2140]
![hercultim](https://user-images.githubusercontent.com/37519296/43038652-b0d3f480-8cf3-11e8-9f73-7e1483baeae8.PNG)

This happens when the player uses @mobinfo + ID.
shows error on the atcommand.c line below:

`Assert_retr("??", msg_number >= 0 && msg_number < MAX_MSG && atcommand->msg_table[0][msg_number] != NULL);`

**Comment by 4144** [comment]
look like you have not updated messages.conf or modded/old hercules

**Comment by greatjon1** [comment]
That's right! But I still do not understand I downloaded it in the Hercules repository does not have a month or even changed the messages.conf
I deleted that I was running the emulator I downloaded and replaced it right. Thank you!
