### ISSUE TITLE
failed assertion SC_BERSERK

### ISSUE THREAD

**Issue by greatjon1** [HerculesWS/Hercules#2145]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

![](https://i.imgur.com/bU37oeB.png)
When the script uses sc_end SC_BERSERK; show this error on the map
### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)
I put an anti bot, at the end of the script it uses a sc_end SC_BERSERK + SC_FREEZE.
When defrosting SC_FREEZE does not show any error, SC_BERSERK already shows.
Both work in the script, so the SC_BERSERK shows error.

### Expected Behavior

[//]: # (Tell us what should happen instead.)
Upon receiving sc_end SC_BERSERK; do not show error.

### Steps To Reproduce The Issue

1. I put an anti bot script on the server. I went to test it. In the last part she gave an error in SC_BERSERK.
2. I also created a simple script to test the problem:
prontera,155,172,5	script	Kappa	4_M_KY_HEAD,{
	sc_end SC_BERSERK;
	end;
}
3. Clicking it does not show an error, but activating the LK_BERSERK skill and clicking on the NPC generates the error.

**Branch(es):**
- [x] master
- [x] stable

Downloaded this month

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )
Hercules 32-bit for Windows
Exported revision (src): 'Unknown'
Exported revision (scripts): 'Unknown'

### Operating System 

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)
Windows 7 32-bit

**Comment by carloshenrq** [comment]
I think this is a duplicate from issue #1388
