### ISSUE TITLE
Stylist UI not opening

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#2174]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Stylist UI not opening in client 2016-01-06aRagexe.
Client problem or missing packets?

**Comment by EyesOfAHawk** [comment]
i got this issue too. 2016-01-13

**Comment by Jedzkie** [comment]
@kyeme @EyesOfAHawk can't reproduce on 2016-03-16aRagexeRE

**Comment by Asheraf** [comment]
The stylist UI didn't get implemented in Ragexe until 2016-01-27, any previous versions does not have the code to actually display it.
