### ISSUE TITLE
Scripts with countitem2 not working correctly

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#2187]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
This kind of a two part problem. So in quests like 'the_sign_quest', there is one part where the `countitem2()` script command is used. 
`.@sign3 = .@signid & 65535;` -> this value is supposed to be `card2` in the SQL. However, it is not working. What is actually in card2 is the char_id of the signed item. It really should just be `.@sign3 = .@signid`, as that is what is actually in the sql.

My issue is which should it be? Should the script be fixed or should the SQL format be fixed? I.e. card0-card4 can only display 32767, despite char id being higher than that.

**Branch(es):**
- [x] master
- [x] stable

**Comment by 4144** [comment]
card0 to card4 can have values from 0 to 2147483648 in new clients, or 65535 in old clients.

countitem2 not run any sql queries. Probably you mean quest script putting wrong values into countitem2 parameters?

**Comment by 4144** [comment]
ah yes, card field size in sql is wrong. but this is unrelated issue to script

**Comment by dastgirp** [comment]
As item id can already go upto 2bil, it's safe to increase card field to INT

**Comment by 4144** [comment]
yes i forgot to update cards fields in db. all items/cards fields must be int field types
