### ISSUE TITLE
Variable 'Zeny' is not recognize (CRITICAL)

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2200]
[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [X ] I have not modified the source prior to reproducing this issue.
-  [ X] I am using the latest version of Hercules.
-  [X ] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Using #define PACKETVER 20151029
RENEWAL

Talking to NPC using Zeny variable will give error
`[Error]: script:set_reg: not a variable! 'Zeny'`
like talking to Kafra for Storage or Warp.

**Comment by dastgirp** [comment]
Happens with all character?

**Comment by Helianthella** [comment]
my bad, I'm releasing a patch ASAP

**Comment by Helianthella** [comment]
@tlacson7 please upgrade to v2018.08.26+1, and thanks for the bug report
