### ISSUE TITLE
turn the global conf documentation into markdown

### ISSUE THREAD

**Issue by Helianthella** [HerculesWS/Hercules#2216]
`doc/global_configuration.txt` should be rewritten in markdown for easier reading in the browser and better organization.

proposed syntax:

``` markdown
# Global configuration reference

## What is global configuration?
…

## How does it work?
…

. . . 
```

**Comment by JuanCrg90** [comment]
I'll work on this 😄

**Comment by Helianthella** [comment]
@JuanCrg90 this already being tackled by @linton-dawson
feel free to pick another issue though

Happy hacking :jack_o_lantern:

**Comment by Jakehoffman22** [comment]
Yay
