### ISSUE TITLE
Map-server crash when using @reloadscript if PK Mode is enabled.

### ISSUE THREAD

**Issue by shadow-mo0n** [HerculesWS/Hercules#2242]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [ ] I have not modified the source prior to reproducing this issue.
-  [ ] I am using the latest version of Hercules.
-  [ ] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Map-server is crashing when using @reloadscript if PK Mode is enabled.
For GDB trace see this topic: http://herc.ws/board/topic/16348-map-server-crash-when-using-reloadscript/

**Hercules rev. hash/commit:** 

Git revision src: 852c13305f67948531bd0277eb1922dbd02b1f26
Git revision scripts: 852c13305f67948531bd0277eb1922dbd02b1f26

### Operating System

OS version: 'Windows 8 Professional (build 9200) [x86_64]'
CPU: 'x86_64 CPU, Family 6, Model 60, Stepping 3 [4]'
Compiled with Microsoft Visual C++ 2015 (v1900)

**Comment by dastgirp** [comment]
@Helianthella 
Probably this is causing it: https://github.com/HerculesWS/Hercules/pull/2162/commits/3a8705a28c5c9577e5a86584224d6252d0620ed8

**Comment by Helianthella** [comment]
@shadow-mo0n could you check if https://github.com/HerculesWS/Hercules/pull/2247 fixes the issue for you?

**Comment by shadow-mo0n** [comment]
@Helianthella Thank you. This fix the issue.

**Comment by tlacson7** [comment]
https://github.com/HerculesWS/Hercules/pull/2247 this fixed zone issue after @reloadscript.  without this fix, when you  do @reloadscript, zone like PvP is all off, you need to go each map and do @pvpon

**Comment by dastgirp** [comment]
Issue is fixed (#2247), closing it.
If anything occurs, please comment and open it or create new issue
