### ISSUE TITLE
MSC_MYSTATUSOFF

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#2299]
Since it isn't used by anything it seems like this went ignored for a long time.

It takes the "lack of status x" condition quite literally and the skill will be used regardless of that specific status being applied at any point at all, it's basically the same as MSC_ALWAYS.

**Comment by Kenpachi2k13** [comment]
Works fine in latest release.

For testing I added this skill to `PORING`:
```
AL_HEAL: {
	SkillState: "MSS_ANY"
	SkillLevel: 1
	Rate: 10000
	Delay: 1000
	SkillTarget: "MST_SELF"
	CastCondition: "MSC_MYSTATUSOFF"
	ConditionData: "SC_DEC_AGI"
}
```
Result:
Poring is spamming Heal until Decrease AGI is cast on it and resume spamming Heal when Decrease AGI ends.

`close();`
