### ISSUE TITLE
Storage Item Missing

### ISSUE THREAD

**Issue by ermanherman** [HerculesWS/Hercules#2300]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [/ ] I have not modified the source prior to reproducing this issue.
-  [ ] I am using the latest version of Hercules.
-  [ /] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # Some of players reporting thier item in storage gone missing.
[//]: # Most of them reporting once they put item in storage then they go offline or do char select sometime items gone missing.

i do check their items and log when they storage, and yes the item gone missing due i cant find any item unique id any longer.

**Hercules rev. hash/commit:** 

Git revision src:

 (Copy the first 3 lines of the login-server, char-server or map-server startup.)
( [Info]: Hercules 64-bit for DEBIAN )
 ( [Info]: Git revision src: '7f7b8060cba8f0aba60f43cf343bdf3f773f3438' )
( [Info]: Git revision scripts: '7f7b8060cba8f0aba60f43cf343bdf3f773f3438 )

### Operating System

 (DEBIAN 7])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by ermanherman** [comment]
@Asheraf  @4144

**Comment by 4144** [comment]
you have any mods as gepard or plugins?

**Comment by dastgirp** [comment]
@ermanherman any more information? Are you using clean hercules?

**Comment by dastgirp** [comment]
Closed, please open with any additional information
