### ISSUE TITLE
Homunculus 10% EXP from master

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2313]
**Describe the bug**
I believe Gravity removed that custom AI for homunculus on newer clients but added Homunculus receives n 10% of master's experience.   This is not implemented here I think.

**System specs (please complete the following information):**
 - OS: [e.g. windows 10 version 1809, macOS 10.14]
 - Hercules Version [e.g. v2018.10.21]
 - Mode: [pre-renewal]
 - Packet version: [20180404]

**Comment by kubixservice** [comment]
I think it's should be a feature request not bug?

**Comment by dastgirp** [comment]
Any video showing  homunculus received 10% of exp?

**Comment by tlacson7** [comment]
oh sorry it should be in feature request :D
@dastgirp here is a screenshot
https://pasteboard.co/HL0bJX4Y.png
