### ISSUE TITLE
"Import" folder not working

### ISSUE THREAD

**Issue by agenciah1code** [HerculesWS/Hercules#2317]
**Describe the bug**

I am not able to put data inside the "char-server.conf" and "map-server.conf" files that are inside the "/ conf / import" folder.

I'm trying to put settings directly inside this file so it reads inside the originals that are in "/ conf / char" and "/ conf / map", but the information inserted there does not work.

I tried to find it in the documentation but I did not find it, could you help me?

**Comment by kyeme** [comment]
Show your settings inside import folder

**Comment by agenciah1code** [comment]
@kyeme I have tried in every possible way, the last ones I tried were these:

```
char_configuration: {
         login_ip: "122.122.122.122"
         char_ip: "122.122.122.122"
}

login_ip: "122.122.122.122"
char_ip: "122.122.122.122"
```

Both inside and outside the brackets

**Comment by agenciah1code** [comment]
@4144 and @kyeme 

I understood what you wanted to say, I did some tests over here and it seems that it worked, I think I'm used to the old emulators, which did not have these directives, anyway, I'll perform some more detailed tests tomorrow with time and I'll return the contact. Thank you in advance for your attention!
