### ISSUE TITLE
Error creating instance for character

### ISSUE THREAD

**Issue by SombraRO** [HerculesWS/Hercules#2326]
**Describe the bug**

When creating an instance using **CHAR_ID_CHAR** and character relogin the instance window does not appear, but the instance is already created, if you make use of **CHAR_ID_PARTY** when relogin character appears the window normally.

This bug causes a big problem because it is possible for a player to generate multiple instances because when the character does relogin it is not possible to enter the instance, it needs to generate another, and the one that was previously opened continues

**To Reproduce**
Earth Tower Test:
1. change `.@party_id = getcharid(CHAR_ID_PARTY);`
2. to `.@party_id = getcharid(CHAR_ID_CHAR);`
3. change `.@instance = instance_create(.@md_name$, .@party_id);`
4. to `.@instance = instance_create(.@md_name$, .@party_id, IOT_CHAR);`
5. Now run the emulator and create the instance and relogin character

**Expected behavior**

The correct one would be to show the instance window with the remaining time.

![test](https://user-images.githubusercontent.com/39016868/48667031-730c5100-eab4-11e8-9032-86d0b99937b6.png)

**System specs (please complete the following information):**
 - OS: [windows 8]
 - Hercules Version [v2018.10.21]
 - Mode: [pre-renewal]
 - Packet version: [20181017]
 - Client type: [main]

**Plugins used or source modifications**
None

**Additional context**
None

**Comment by carloshenrq** [comment]
I can confirm but i think it's not a bug.
It's a doc mismatch.

    /*--------------------------------------
     * name : instance name
     * Return value could be
     * -4 = already exists | -3 = no free instances | -2 = owner not found | -1 = invalid type
     * On success return instance_id
     *--------------------------------------*/
    static int instance_create(int owner_id, const char *name, enum instance_owner_type type)
    {
        struct map_session_data *sd = NULL;
        unsigned short *icptr = NULL;
        struct party_data *p = NULL;
        struct guild *g = NULL;
        short *iptr = NULL;
        int i;

        nullpo_retr(-1, name);
        switch ( type ) {
            case IOT_NONE:
                break;
            case IOT_CHAR:
                if( ( sd = map->id2sd(owner_id) ) == NULL ) {
                    ShowError("instance_create: character %d not found for instance '%s'.\n", owner_id, name);
                    return -2;
                }
                iptr = sd->instance;
                icptr = &sd->instances;
                break;


The `map->id2sd` uses account_id not char_id.

Try to use CHAR_ID_ACCOUNT insteads of CHAR_ID_CHAR for getcharid()

Works like a charm here. =]

**Comment by marcosbucarte** [comment]
@dastgirp, @Emistry something about it?

**Comment by carloshenrq** [comment]
@marcosbucarte Change `.@party_id = getcharid(CHAR_ID_CHAR);` to `.@party_id = getcharid(CHAR_ID_ACCOUNT);`
