### ISSUE TITLE
[Critical Bug] Still Dead after respawn after when death.

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2328]
**Describe the bug**
Please validate, when I die and return to save point, I was still dead. ^--^

**To Reproduce**
1. Just kill mob and let mob kill you.
2. Return to savepoint.
3. Visually you are alive, but try to kill mob, you can't attack because you are still dead.
4. type @alive and you can attack again

**System specs (please complete the following information):**
 - OS: [Centos 7]
 - Hercules Version [e.g. v2018.11.10]
 - Mode: [pre-renewal]
 - Packet version: [20151029]

**Comment by Emistry** [comment]
> Return to savepoint.

did you returned to the save point using atcommand like `@warp` `@load`? or warp by script `warp()`?
these ways of return, doesn't revive the char if its dead.

**Comment by Jedzkie** [comment]
Its already fixed. https://github.com/HerculesWS/Hercules/commit/c34871cb3f65412db663a4793df6f055663e16fa
