### ISSUE TITLE
Characters die but still have hp. Causes issues sometimes.

### ISSUE THREAD

**Issue by EyesOfAHawk** [HerculesWS/Hercules#2333]
**Describe the bug**
When you die, your HP does not get reduced to 0. Can cause abnormal behavior such as not warping away when you use `@die` in GvG maps or becoming unkillable as you are 'alive' with 0 hp.

**To Reproduce**
1. Use the `@kill` command or `NPC_SUICIDE` (175) skill.
2. Click 'Return to Save Point'.
3. Try things like getting resurrected, using healing items and returning to save point.
4. Try above again on different types of 'vs' maps such as bg, gvg, etc.

**Screenshots**
- https://i.imgur.com/bkqm8z5.png: As you can see, I died using `@kill`, but I still have some hp. The value of hp you get is based on your `restart_hp_rate` battleconf (player.conf).
- https://i.imgur.com/orAft1O.png: 0 hp, aggressive mob can't attack me, I can't attack it. Once I used a healing item, I got 'resurrected' effect and it was normal again.

**Comment by dastgirp** [comment]
This might be the reason behind it: https://github.com/HerculesWS/Hercules/pull/1215

**Comment by Jedzkie** [comment]
@MishimaHaruna

**Comment by dastgirp** [comment]
Is this fixed @EyesOfAHawk ?
