### ISSUE TITLE
Assert error while creating character

### ISSUE THREAD

**Issue by SombraRO** [HerculesWS/Hercules#2334]
**Describe the bug**

When creating a character assert error occurs on the char server

```[Error]: Reserved too small packet buffer for packet 0x006D with size 152, but must be size 157
[Error]: --- failed assertion --------------------------------------------
[Error]: socket.c:2138: '0' in function `socket_validateWfifo'
[Error]: ./char-server() [0x447788]
[Error]: ./char-server() [0x45b8ee]
[Error]: ./char-server() [0x40ace0]
[Error]: ./char-server() [0x40eb01]
[Error]: ./char-server() [0x45afcb]
[Error]: ./char-server(main+0x2ba) [0x4073ba]
[Error]: /lib64/libc.so.6(__libc_start_main+0xea) [0x7f46cc60ef6a]
[Error]: ./char-server(_start+0x2a) [0x40748a]
[Error]: --- end failed assertion ----------------------------------------
```

**To Reproduce**
1. Create character
2. look at the char server

**Screenshots**
none

**System specs (please complete the following information):**
 - OS: [windows 10 ]
 - Hercules Version v2018.11.18+1 
 - Mode: [renewal]
 - Packet version: [20181017]
 - Client type: [main]

**Plugins used or source modifications**
none

**Additional context**
none

**Comment by SombraRO** [comment]
@4144

**Comment by 4144** [comment]
can you show actual assertion text?
it showed some lines before you copy/pasted text. because you show error place, but not error itself

**Comment by SombraRO** [comment]
> can you show actual assertion text?
> it showed some lines before you copy/pasted text. because you show error place, but not error itself

`Reserved too small packet buffer for packet 0x006D with size 152, but must be size 157`

**Comment by 4144** [comment]
ah this is known issue. should be already fixed in my pr

**Comment by dastgirp** [comment]
#2324 Merged, Please open it again if problem still exists
