### ISSUE TITLE
mysql 8 throw error on varchar(255) table creation on myisam engine

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2349]
**Describe the bug**
mysql 8 doesn't allow table creation with varchar(255) on myisam engine
https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes
https://stackoverflow.com/questions/20014106/how-to-create-this-table-1071-specified-key-was-too-long-max-key-length-is/42497309

**To Reproduce**
1. install mysql 8
2. run sql-files/main.sql

**Expected behavior**
.........

**Screenshots**
![mysql8](https://raw.githubusercontent.com/AnnieRuru/customs/master/screenshots/mysql8.png)

**System specs (please complete the following information):**
 - OS: [e.g. windows 7, 64-bit]
 - Hercules Version [e.g. v2019.01.01]
 - Mode: [renewal]
 - Packet version: _still setting up test server_
 - Client type: _still setting up test server_

**Plugins used or source modifications**
_still setting up test server_

**Additional context**
https://github.com/rathena/rathena/issues/3093

**Comment by dastgirp** [comment]
@4144 @Helianthella
