### ISSUE TITLE
Stylist - needs to update

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2356]
Hercules has implement Stylist UI, but when I look into db\stylist_db.conf,
it seems every Hair Style ID, every Hair Color ID needs to be added manually
so my **Question No.1** is,
if the server has over 100 hair styles and over 100 hair color, I have to add 200 configurations
or does it actually crash the client ?
http://herc.ws/board/topic/16515-874-incomplete-styling-shop-support/

https://rathena.org/board/topic/118030-help-restriction-stylist-npc/
**Suggestion No.2**, I think hercules stylist needs an update
currently this script can throw error on player's client if player using summoner class
or maybe not if the Stylist UI can handle lots of ID ?

**Question No.3** Hairstyle 0 can crash client ...?
when I test it doesn't crash my client
so I'm not sure Euphy actually start the ID with 1 because his client crash ?

**Comment by 4144** [comment]
This about stylist client feature.
I think stylist db copy all official features. For some clients it can be too old or too new.
In client side exists same configuration. For add custom styles need change client config too.
Rytech speak about this feature.

Also probably exists npc with custom stylist script, here i not sure how it works.
In rathena topic look like they speaking about custom script.

**Comment by AnnieRuru** [comment]
>For add custom styles need change client config too

interested ... its inside a lua/lub file where we can edit, or we have to hex it ?

>In rathena topic look like they speaking about custom script.

no, its inside Hercules as well
https://github.com/HerculesWS/Hercules/blob/stable/npc/custom/stylist.txt
this script is seriously outdated, some of our members has made changes to it
http://herc.ws/board/files/file/405-stylist-with-doram-limit-hair-style-and-hair-color/

btw hairstyle 0 can crash client ? my test doesn't crash
and clothing with ID 0 has different color than ID 1 ... so I am not so sure about it

**Comment by 4144** [comment]
For builtin stylist i think related this lua file stylingshopinfo.lub
For show builtin stylist window need use this script command openstylist (supported from 20150128)
But in herc look like it unused, probably you can create script for using it?

**Comment by AnnieRuru** [comment]
> For builtin stylist i think related this lua file stylingshopinfo.lub.

yeah this is the info I need, time to add custom stuffs inside

> But in herc look like it unused, probably you can create script for using it?

that's we are discussing in rathena forum right now, as we have similar script commands for stylist
