### ISSUE TITLE
client crash when select Member tab from Guild Window

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2384]
**Describe the bug**
client crash when `Member` tab from Guild Window

**To Reproduce**
1. Alt+G
2. Click `Member` tab

**Expected behavior**
I tried with rAthena test server, this bug doesn't happen on rAthena

**Screenshots**
![](https://raw.githubusercontent.com/AnnieRuru/customs/master/screenshots/screen2019rAthena013.jpg)
this screenshot is taken with rAthena test server,
Hercules will crash

**System specs (please complete the following information):**
 - OS: Windows 7 Service Pack 1 Ultimate
 - Hercules Version: latest
 - Packet version: 20180620
 - Mode: Renewal
 - Client type: [2018-06-20eRagexeRE](https://rathena.org/board/topic/117168-packetver-20180620-client-release-2018-06-20eragexere/)

**Plugins used or source modifications**
<none> unload everything

**Additional context**

**Comment by 4144** [comment]
using official kro data and grf?

**Comment by 4144** [comment]
i not tested now, but in past i think this version works fine with official data

**Comment by 4144** [comment]
also what packet version and type you used?
in rathena you can use only packet version, in herc must use client type too

**Comment by AnnieRuru** [comment]
well, using same hexed client ...
* throw error on Hercules
* works fine on rAthena

its obviously not client side error anymore

I use KRO from https://rathena.org/board/topic/106413-kro-full-client-2018-08-13-includes-bgm-rsu/
20180803

> also what packet version and type you used?
in rathena you can use only packet version, in herc must use client type too

hmm ? I only know edit from common/mmo.h

**Comment by 4144** [comment]
http://nemo.herc.ws/clients/2018-06-20eRagexeRE/#build-hercules

**Comment by 4144** [comment]
tested and it works fine on herc. but i tested 2018-06-21
20 look like had some issues and gravity released new one version

**Comment by AnnieRuru** [comment]
I use Github Log to backtrack my repo to this revision
https://github.com/HerculesWS/Hercules/tree/5182ecdd2649f43644a2e8767ad8f016e62bd8f7
doesn't throw error anymore on Hercules (same hexed client)

this must mean within this 23 days, some commit broke it

**Comment by 4144** [comment]
herc also had some issue just after release, and was fixed in next day. may be you have this broken version?

**Comment by 4144** [comment]
anyway try build for correct packet version and type and check. if client still crash, collect packets with wireshark or use packet logger plugin

**Comment by AnnieRuru** [comment]
what a weird turn out,
I redownload fresh Hercules, setup/import/compile Hercules again, error gone

**Comment by 4144** [comment]
and better use client 2018-06-21 and not 2018-06-20 rathena and herc should works with both. but with second probably less bugs
