### ISSUE TITLE
problem Start loading tables  mob_skill_db.sql

### ISSUE THREAD

**Issue by louisplag** [HerculesWS/Hercules#2405]
I started loading tables ( mob_skill_db.sql) and an error occurred 
`ERROR 1064 (42000) at line 1416: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Nine Tails@NPC_EMOTION','idle',197,1,2000,0,5000,'yes','self','always',NULL,22,N' at line 1
`
This is my first mistake and I don't know what additional information to give you.I did not find similar topics.
p.s. .... so sorry my english

**Comment by AnnieRuru** [comment]
```sql
REPLACE INTO `mob_skill_db` VALUES (1307,'Cat o' Nine Tails@AL_TELEPORT','idle',26,1,10000,0,0,'yes','self','rudeattacked',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `mob_skill_db` VALUES (1307,'Cat o' Nine Tails@MC_MAMMONITE','attack',42,9,500,800,5000,'no','target','always',NULL,NULL,NULL,NULL,NULL,NULL,'8',NULL);
REPLACE INTO `mob_skill_db` VALUES (1307,'Cat o' Nine Tails@NPC_EMOTION','idle',197,1,2000,0,5000,'yes','self','always',NULL,22,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `mob_skill_db` VALUES (1307,'Cat o' Nine Tails@NPC_GUIDEDATTACK','attack',172,2,500,1000,20000,'no','target','always',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `mob_skill_db` VALUES (1307,'Cat o' Nine Tails@NPC_SUMMONSLAVE','idle',196,2,10000,2000,60000,'no','self','slavele',NULL,1180,NULL,NULL,NULL,NULL,NULL,NULL);
```
confirmed, the Apostrophe symbol `'` should be escape by left slash symbol `\`
`'Cat o' Nine Tails@NPC_SUMMONSLAVE'`

**Comment by louisplag** [comment]
found an error in the table mob_skill_db_re.sql

**Comment by AnnieRuru** [comment]
fixed in https://github.com/HerculesWS/Hercules/pull/2416
