### ISSUE TITLE
signed items should loop value by unsigned short, proved by <ITEML>

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2409]
**Describe the bug**
I always knew something was wrong when we increase ItemID limitation
[it has broken signed item and pet ID generation](https://github.com/HerculesWS/Hercules/pull/2359#issuecomment-458770637)
[Myriad's server pet items are broken too](http://herc.ws/board/topic/11275-getitemname2/?do=findComment&comment=90313)

**To Reproduce**
```c
prontera,158,180,5	script	test	1_F_MARIA,{
	getnameditem 501, getcharid(CHAR_ID_CHAR);
	input .@a$;
	dispbottom .@a$;
	debugmes .@a$;
	end;
}
```
get a name item, then shift-click the item in the input box
you'll get something like 
```
[Debug]: script debug : 2000000 110000094 : <ITEML>00000085&00(46(00(4Vi(02</ITEML>
```
46 is 254
4Vi is 18928
02 is ... well ... 2

<details>
<summary>can get the value into base 10 with this script</summary>

```c
prontera,150,185,3	script	base62tobase10	1_F_MARIA,{
	input .@a$;
	for ( .@i = 0; getstrlen(.@a$); ++.@i ) {
		.@value += 62 ** .@i * callsub( S_base10, charat( .@a$, getstrlen(.@a$) -1 ) );
		.@a$ = delchar( .@a$, getstrlen(.@a$) -1 );
	}
	dispbottom .@a$ +" = "+ .@value;
	end;
S_base10:
	if ( getarg(0) == "0" ) return 0;
	if ( getarg(0) == "1" ) return 1;
	if ( getarg(0) == "2" ) return 2;
	if ( getarg(0) == "3" ) return 3;
	if ( getarg(0) == "4" ) return 4;
	if ( getarg(0) == "5" ) return 5;
	if ( getarg(0) == "6" ) return 6;
	if ( getarg(0) == "7" ) return 7;
	if ( getarg(0) == "8" ) return 8;
	if ( getarg(0) == "9" ) return 9;
	if ( getarg(0) == "a" ) return 10;
	if ( getarg(0) == "b" ) return 11;
	if ( getarg(0) == "c" ) return 12;
	if ( getarg(0) == "d" ) return 13;
	if ( getarg(0) == "e" ) return 14;
	if ( getarg(0) == "f" ) return 15;
	if ( getarg(0) == "g" ) return 16;
	if ( getarg(0) == "h" ) return 17;
	if ( getarg(0) == "i" ) return 18;
	if ( getarg(0) == "j" ) return 19;
	if ( getarg(0) == "k" ) return 20;
	if ( getarg(0) == "l" ) return 21;
	if ( getarg(0) == "m" ) return 22;
	if ( getarg(0) == "n" ) return 23;
	if ( getarg(0) == "o" ) return 24;
	if ( getarg(0) == "p" ) return 25;
	if ( getarg(0) == "q" ) return 26;
	if ( getarg(0) == "r" ) return 27;
	if ( getarg(0) == "s" ) return 28;
	if ( getarg(0) == "t" ) return 29;
	if ( getarg(0) == "u" ) return 30;
	if ( getarg(0) == "v" ) return 31;
	if ( getarg(0) == "w" ) return 32;
	if ( getarg(0) == "x" ) return 33;
	if ( getarg(0) == "y" ) return 34;
	if ( getarg(0) == "z" ) return 35;
	if ( getarg(0) == "A" ) return 36;
	if ( getarg(0) == "B" ) return 37;
	if ( getarg(0) == "C" ) return 38;
	if ( getarg(0) == "D" ) return 39;
	if ( getarg(0) == "E" ) return 40;
	if ( getarg(0) == "F" ) return 41;
	if ( getarg(0) == "G" ) return 42;
	if ( getarg(0) == "H" ) return 43;
	if ( getarg(0) == "I" ) return 44;
	if ( getarg(0) == "J" ) return 45;
	if ( getarg(0) == "K" ) return 46;
	if ( getarg(0) == "L" ) return 47;
	if ( getarg(0) == "M" ) return 48;
	if ( getarg(0) == "N" ) return 49;
	if ( getarg(0) == "O" ) return 50;
	if ( getarg(0) == "P" ) return 51;
	if ( getarg(0) == "Q" ) return 52;
	if ( getarg(0) == "R" ) return 53;
	if ( getarg(0) == "S" ) return 54;
	if ( getarg(0) == "T" ) return 55;
	if ( getarg(0) == "U" ) return 56;
	if ( getarg(0) == "V" ) return 57;
	if ( getarg(0) == "W" ) return 58;
	if ( getarg(0) == "X" ) return 59;
	if ( getarg(0) == "Y" ) return 60;
	if ( getarg(0) == "Z" ) return 61;
	return -1;
}
```

</details>

but hercules getnameditem has the card3 field same as char_id
254 0 150000 2

char_id | hercules' `*getnameditem` | `<ITEML>` convert into base10
-- | -- | --
150000 | 254 0 150000 2 | 254 0 18928 2
160001 | 254 0 160001 2 | 254 0 28929 2
170001 | 254 0 170001 2 | 254 0 38929 2
200001 | 254 0 200001 3 | 254 0 3393 3

**Expected behavior**
even if the ItemID can be int(11), but signed items' card field should loop with unsigned short
this has been proven with client side feature `<ITEML>`

**Screenshots**
none

**System specs (please complete the following information):**
 - OS: Windows 7 Service Pack 1 Ultimate
 - Hercules Version: 2019-2-11
 - Packet version: 20180620
 - Mode: Renewal
 - Client type: [2018-06-20eRagexeRE](https://rathena.org/board/topic/117168-packetver-20180620-client-release-2018-06-20eragexere/)

**Plugins used or source modifications**
none

**Additional context**
http://herc.ws/board/topic/16648-iteml-function/

**Comment by 4144** [comment]
you checking on very outdated client
from new clients all item id is 4 bytes aka int32. and card is item too this mean 4 bytes

**Comment by 4144** [comment]
and in links client may have bugs even new versions, because gravity not often using hight items for now

**Comment by 4144** [comment]
another with pet eggs look like all fine, probably was issue in opened eggs before server update.
but for new eggs should be fine

**Comment by AnnieRuru** [comment]
> you checking on very outdated client
from new clients all item id is 4 bytes aka int32. and card is item too this mean 4 bytes

with the large number of hercules community here using outdated client version,
I think we should provide a fix for those people still using outdated client version ...

> and in links client may have bugs even new versions, because gravity not often using hight items for now

I can test it a little bit then

> another with pet eggs look like all fine, probably was issue in opened eggs before server update.
but for new eggs should be fine

yes it broke when people update their server without providing a proper sql-update fix from our side

ima thinking can do this with 
```sql
UPDATE inventory SET card3 = card3 & 65535 where card1 = 255 || card1 = 254;
UPDATE cart_inventory SET card3 = card3 & 65535 where card1 = 255 || card1 = 254;
UPDATE storage SET card3 = card3 & 65535 where card1 = 255 || card1 = 254;
UPDATE guild_storage SET card3 = card3 & 65535 where card1 = 255 || card1 = 254;
UPDATE mail SET card3 = card3 & 65535 where card1 = 255 || card1 = 254;
```

**Comment by Megasantos** [comment]
The use of `<ITEML>` requires support for a script command. Because it can be used on the rodex, some official aegis systems like the **Offline Store** make use of `<ITEML>`, I made an implementation in my emulator.

![Sem título](https://user-images.githubusercontent.com/2119520/55042791-f533f580-5011-11e9-8f90-5f623f6d5bb8.png)

**Comment by AnnieRuru** [comment]
again I thought it is custom ...
I made F_ITEML function on the forum
and rathena has itemlink script command in source release 

so what is the official script command name for `<ITEML>` use in Aegis ?

**Comment by hemagx** [comment]
@AnnieRuru please try the code at my PR #2425
