### ISSUE TITLE
HPM Hooks generator is not able to parse pointed variables

### ISSUE THREAD

**Issue by hemagx** [HerculesWS/Hercules#2423]
**Describe the bug**
HPM Hooks generator is not able to parse pointed variables.
Error produced:
```
Error: unable to parse 'char(* atcommand_interface::atcmd_output)[(255+1)]'
Error: unable to parse 'char(* atcommand_interface::atcmd_player_name)[(23+1)]'
```

**To Reproduce**
1. Execute `make hooks`

**Expected behavior**
To no parse errors to appear.

**System specs (please complete the following information):**
 - OS: windows 10
 - Hercules Version 2019-04-07
 - Mode: All
 - Packet version: None-applicable.
 - Client type: None-applicable.

**Plugins used or source modifications**
Non-applicable.

**Comment by MishimaHaruna** [comment]
This was fixed in #2467
