### ISSUE TITLE
pets after evolve by pet evolution are acting like monsters

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2434]
**Describe the bug**
pets after evolve by pet evolution are acting like monsters

**To Reproduce**
1. `@makeegg 1002` create a poring egg
2. `@hatch` hatch the poring egg
3. `@petfriendly 1000` intimacy to max
4. `@item Leaf_Of_Yggdrasil 10` `@item Unripe_Apple 3` and select pet evolution to Mastering
5. `@hatch` the mastering egg
-> now your mastering is uncontrollable

**Expected behavior**
this mastering pet should behave like poring

**Screenshots**
none

**System specs (please complete the following information):**
 - OS: Windows 7 Service Pack 1 Ultimate
 - Hercules Version: 2019-04-07
 - Packet version: 20180620
 - Mode: Renewal
 - Client type: ~[2018-06-20eRagexeRE](https://rathena.org/board/topic/117168-packetver-20180620-client-release-2018-06-20eragexere/)~ [2019-02-20aRagexeRE](http://nemo.herc.ws/clients/2019-02-20aRagexeRE/) tested both

**Plugins used or source modifications**
none

**Additional context**
_Originally posted by @AnnieRuru in https://github.com/HerculesWS/Hercules/pull/2428#issuecomment-482582880_

**Comment by Jedzkie** [comment]
Additional information, when you return the pet to egg state, the egg turns broken. And you can't see the egg in you inventory. You can see the broken egg only by using `Pet Incubator` or `@hatch` command

![image](https://user-images.githubusercontent.com/4826387/56075001-12c4d580-5dee-11e9-8398-bb3bc1993002.png)

**Comment by Asheraf** [comment]
Re-posting my comment from pr#2428

> the bug you're reporting is related to missing pet info in the database, basically mastering have a HungerDelay value of 0 which means once you obtain it it loses all the hunger and loyalty and its gone. due to missing infos about these new pets nothing was added to their values.

**Comment by Zarbony** [comment]
Got this issue too.
If i use @petfriendly 1000 after the per acting like mob, it snapping from another place to near of the master like macro using body relocation

**Comment by Zarbony** [comment]
Found out what this Issue was called.
one Look at the pet_db.conf and i see that some Evolve Pets dont have any infos, like this:
`{
	Id: 1090
	SpriteName: "MASTERING"
	Name: "Mastering"
	EggItem: "Mastering_Egg"
	AutoFeed: true
	Evolve: {
		Angeling_Egg: {
			Yellow_Potion: 20
			Spirit_Chain: 1
			White_Herb: 50
			Jellopy: 200
		}
	}
},
`

Just add some basic Infos from mastering, looks like this:
`{
	Id: 1090
	SpriteName: "MASTERING"
	Name: "Mastering"
	EggItem: "Mastering_Egg"
	AutoFeed: true
	Evolve: {
		Angeling_Egg: {
			Yellow_Potion: 20
			Spirit_Chain: 1
			White_Herb: 50
			Jellopy: 200
		}
	}
	FoodEffectiveness: 80
	HungerDelay: 60
	Intimacy: {
		Initial: 250
		FeedIncrement: 50
		OverFeedDecrement: 100
		OwnerDeathDecrement: 20
	}
	CaptureRate: 2000
	Speed: 150
	SpecialPerformance: true
	AttackRate: 350
	DefendRate: 400
	ChangeTargetRate: 800
	PetScript: <" petloot(10); ">
	EquipScript: <"
		bonus(bLuk, 2);
		bonus(bCritical, 1);
	">

},
`

and the Pet works.

**Comment by Kenpachi2k13** [comment]
I'll work on that. Additionally some pet bonuses needs to be updated.
