### ISSUE TITLE
pre-renewal compile fails when --enable-packetver=20120410 is used @ char.c:59

### ISSUE THREAD

**Issue by aerodyn4mic** [HerculesWS/Hercules#2438]
**Describe the bug**
make sql compile fails if option "--enable-packetver=20120410" is specified during configuration.

>> however, It works successfully if this option is left out.

**To Reproduce**
1. Pull master branch (04/13/2019) on Debian 64bit, GCC version 6.3

2. Configure Hercules using:
**./configure --disable-renewal --enable-packetver=20120410
make clean
make sql**

3. The result is 'make sql' compile fails at char.c:59:0 as shown with error below:

make[1]: Leaving directory '/home/aero/Hercules/src/login'
	MAKE	char_sql
make[1]: Entering directory '/home/aero/Hercules/src/char'
	MKDIR	obj_sql
	CC	char.c
In file included from char.c:59:0:
char.c: In function ‘char_send_HC_ACK_CHARINFO_PER_PAGE_tail’:
char.c:2156:23: error: invalid application of ‘sizeof’ to incomplete type ‘struct PACKET_HC_ACK_CHARINFO_PER_PAGE’
  WFIFOHEAD(fd, sizeof(struct PACKET_HC_ACK_CHARINFO_PER_PAGE));
                       ^
../common/socket.h:44:50: note: in definition of macro ‘WFIFOHEAD’
 #define WFIFOHEAD(fd, size) sockt->wfifohead(fd, size)
                                                  ^~~~
char.c:2158:3: error: dereferencing pointer to incomplete type ‘struct PACKET_HC_ACK_CHARINFO_PER_PAGE’
  p->packetId = HEADER_HC_ACK_CHARINFO_PER_PAGE;
   ^~
char.c:2158:16: error: ‘HEADER_HC_ACK_CHARINFO_PER_PAGE’ undeclared (first use in this function)
  p->packetId = HEADER_HC_ACK_CHARINFO_PER_PAGE;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
char.c:2158:16: note: each undeclared identifier is reported only once for each function it appears in
char.c:2159:24: error: invalid application of ‘sizeof’ to incomplete type ‘struct PACKET_HC_ACK_CHARINFO_PER_PAGE’
  p->packetLen = sizeof(struct PACKET_HC_ACK_CHARINFO_PER_PAGE);
                        ^~~~~~
make[1]: *** [Makefile:139: obj_sql/char.o] Error 1
make[1]: Leaving directory '/home/aero/Hercules/src/char'
make: *** [Makefile:116: char_sql] Error 2 

**Expected behavior**
Expectation is the server to be able to compile in pre-renewal mode with the packetver option specified without errors

**System specs (please complete the following information):**
 - OS: Debian 10? (Buster) 64bit 
 - Hercules Version v2019.04.13  ... latest commit as of 04/13/2019
 - Mode: pre-renewal
 - Packet version: 20120410
 - Client type: kRO renewal

**Plugins used or source modifications**
 None used

**Additional context**
have not gathered crash logs or logging, willing to if instructed on specifics.

**Comment by 4144** [comment]
Thanks for report,
Try commit https://github.com/HerculesWS/Hercules/pull/2432/commits/c01c3570ef614c45d2cf6b71bb127d23a7cbaf51
or use this pr https://github.com/HerculesWS/Hercules/pull/2432

**Comment by aerodyn4mic** [comment]
Much appreciation for the time and work you guys put into this project. Thank you for pointing me in the right direction.
