### ISSUE TITLE
SA_CREATECON Not Work

### ISSUE THREAD

**Issue by sdbezerra** [HerculesWS/Hercules#2445]
SA_CREATECON Not work. 

Items required:
1 Blank Scroll, 3 Scorpion Tail
1 Blank Scroll, 3 Snail's Shell
1 Blank Scroll, 3 Horn
1 Blank Scroll, 3 Rainbow Shell

Client:
2019-01-09aRagexe.exe
http://nemo.herc.ws/clients/2019-01-09aRagexe/

Using the Skill, but Elemental Converters cannot be created.
![screenFênix021](https://user-images.githubusercontent.com/6790026/56257456-a45c6d80-60a2-11e9-9889-7e8c1fa0bf2a.jpg)

**Comment by lllaaazzz** [comment]
https://ibb.co/CV2Zn1G
works fine for me
check your item info lua in your system folder 

Unless they changed something in the code in the past few days . . . I dont see why itd be an issue in the src . . . . 

If not then idk

**Comment by Kenpachi2k13** [comment]
For fine for me, too. Client issue...
`Close();`
