### ISSUE TITLE
Pet Issue when armor is equip.

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2448]
PRE-RE 
PACKETVER 20151029

Pet sprite is broken, it was maybe of the speed of pet when equip with armor.

**To Reproduce**
1. Equip pet armor
2. See error
`https://pasteboard.co/IaIJYLM.jpg`

**Comment by bWolfie** [comment]
tried on 20160113 no problem when i equipped Poring with Backpack
