### ISSUE TITLE
npc/custom/card_remover.txt is bugged.

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#2469]
**Describe the bug**
If you manage to get to the part of code
```
if(.@failchance < 10) {
	next;
	failedremovecards .@part,3;
	mes "[Card Remover]";
	mes "I have failed to remove the cards. Luckily, however, both the item and the cards are still okay.";
	close;
}
```

While it won't break any item or card. it would read the current equipment as "no card" while there is still a card inside it. so you won't be able to remove the card permanently. what's worse is that you CAN ADD 1 MORE CARD. making it 2 Slot ...

**Screenshots**
![img](https://i.imgur.com/UNSjqyY.png)

**To Reproduce**
1. Enable the npc
2. just remove item until you get that message it fail but no item were destroy
3. try adding cards or even try again talking to the npc and she will say that it doesnt have any card in it.

**Expected behavior**
It should leave the failed attempt as normal items with compounded card.

**System specs (please complete the following information):**
 - OS: centos 6
 - Hercules Version [Release v2019.05.05+3]
 - Mode: [pre-renewal?]
 - Packet version: 2018-04-18bRagexeRE
 - Client type: RE

**Plugins used or source modifications**
If you are using any plugins besides the ones that come bundled with Hercules,
please enumerate them here.

**Additional context**
There is no warning/error message when this happens

**Comment by Emistry** [comment]
hmm ... the NPC doesn't help you add a card into the item. You're only able to manually compound a card into an item.

Do you meant after the process of removing card failed, but the item compounded (duplicated?) a new card into the other slot? 

Have you check your item_db that it has how many slots?

**Comment by Mojacko** [comment]
Hi,
Yes the process of removing card failed. but the item is still compounded. but no new card on my inventory. 
then if i try to use the card remover again and choose the same item it says it doesnt contain any card. 
also i can add another card to the item. 
Im 100% sure that the slot is only 1 because this image i upload is my 5th test and not just on this briss it happen it also happen to mink coat.

**Comment by Emistry** [comment]
I think something is wrong with the `*failedremovecards(...)` script command.

```
prontera,155,181,5	script	sample	4_F_KAFRA1,{
	failedremovecards EQI_ARMOR,3;
	mes "[Card Remover]";
	mes "I have failed to remove the cards. Luckily, however, both the item and the cards are still okay.";
	close;
}
```

![img](https://i.imgur.com/gBWmR3t.png)
-

from [doc/script_command.txt](https://github.com/HerculesWS/Hercules/blob/stable/doc/script_commands.txt)
```
 0 - will destroy both the item and the cards.
 1 - will keep the item, but destroy the cards.
 2 - will keep the cards, but destroy the item.
```
but current result 
```
 0 - wrong, currently it lose both items
 1 - correct, will keep the item, but destroy the cards.
 2 - wrong, currently it lose both items
```
other value - execute fine, but item remain same, but once unequip the item, we able to compound cards to other slot which are not defined in item_db.
