### ISSUE TITLE
Random Option on Monsters

### ISSUE THREAD

**Issue by Vaans** [HerculesWS/Hercules#2484]
**Describe the bug**
The system isn't working at expected. When i try to configure an option drop in an item, this item isn't dropped with the option.
Actually the console show no errors or warning, but when you add some map with the mapcache, the error appear.

**To Reproduce**
1. Add the following in option_drop_group_db.conf:
```
option_drop_group_db: (
{
MYITEM_M: (
	{ // Option Slot 1
		Rate: 10000 // It has 100% of chance of being filled

		// This slot may have one of the following options:
		WEAPON_ATTR_WIND: 5,                // WEAPON_ATTR_WIND Lv5 (33.33%)
		WEAPON_ATTR_GROUND: [2, 4]          // WEAPON_ATTR_GROUND Lv 2~4 (33.33%)
		WEAPON_ATTR_POISON: [1, 4, 8000]    // WEAPON_ATTR_POISON Lv 1~4 (80%)
	},
	{ // Option Slot 2
		Rate: 5000 // It has 50% of chance of being filled

		// If filled, may have one of the following options:
		WEAPON_ATTR_WATER: 4     // WEAPON_ATTR_WATER Lv4 (100%)
	},
)

		}
			)
```

2. Add the Group in an item:

```
{
	Id: 1002
	SpriteName: "PORING"
	Name: "Poring"
	Lv: 1
	Hp: 50
	Sp: 0
	Exp: 2
	JExp: 1
	AttackRange: 1
	Attack: [7, 10]
	Def: 0
	Mdef: 5
	Stats: {
		Str: 1
		Agi: 1
		Vit: 1
		Int: 0
		Dex: 6
		Luk: 30
	}
	ViewRange: 10
	ChaseRange: 12
	Size: "Size_Medium"
	Race: "RC_Plant"
	Element: ("Ele_Water", 1)
	Mode: {
		CanMove: true
		Looter: true
		CanAttack: true
	}
	MoveSpeed: 400
	AttackDelay: 1872
	AttackMotion: 672
	DamageMotion: 480
	MvpExp: 0
	Drops: {
		Jellopy: 7000
		Knife_: (100, "MYITEM_M")
		Sticky_Mucus: 400
		Apple: 1000
		Empty_Bottle: 1500
		Apple: 150
		Unripe_Apple: 20
		Poring_Card: 1
	}
},
```

3. See the console, show no errors or warning.

4. Try to obtain the item.

5. Add a map with mapcache, for example:` ./map-server --load-plugin mapcache --map izlude`
6. See the error in the console:
`[Error]: mob_read_db_optdrops: Invalid option drop group "MYITEM_M" on item "Knife_" in monster 1002, does this group really exists? Skipping...`

**Expected behavior**
The item dropped with the option group.

**Screenshots**
-

**System specs (please complete the following information):**
 - OS: [CentOS Linux release 7.4.1708 (Core)]
 - Hercules Version [Release v2019.05.05+4]
 - Mode: [pre-renewal]
 - Packet version: [e.g. 20181226]
 - Client type: [Rag]

**Comment by guilherme-gm** [comment]
I just tested it and I got the error when running mapcache, but after it adds the map (and kills map-server) starting up the server works fine, no errors and the drops **does** contain the options. Tested on both re and pre-re. Is this the issue you've found? Your description sounds like it doesn't work after adding the map, so please, confirm if what I described is the real issue.

This error doesn't affect the server itself, it just shows up during mapcache execution (and doesn't affect its result).

I'll work on fixing it in the coming days.

**Comment by Vaans** [comment]
> 
> 
> I just tested it and I got the error when running mapcache, but after it adds the map (and kills map-server) starting up the server works fine, no errors and the drops **does** contain the options. Tested on both re and pre-re. Is this the issue you've found? Your description sounds like it doesn't work after adding the map, so please, confirm if what I described is the real issue.
> 
> This error doesn't affect the server itself, it just shows up during mapcache execution (and doesn't affect its result).
> 
> I'll work on fixing it in the coming days.

Uhm weird, i do the same that you do. But the item is not dropped with the options. I thought it was a problem with the rate, but I spawned 50 poring, and none gave me the knife with options.

it's something that i need to enable to perform drops with options?
Can you please post what do you have?

**Comment by guilherme-gm** [comment]
I posted a diff on herc board with my settings: https://herc.ws/board/topic/17079-random-options-on-monster-drops/?tab=comments#comment-91927

No, you don't have to enable anything else.

**Comment by Vaans** [comment]
hmm,i have the same things that you have. i don't know why isn't working for me.

**Comment by Vaans** [comment]
The problem was with a NPC who identify all the item. If you do by the command @identfy or with a magnifier the option appear
