### ISSUE TITLE
Guild Skill Cooldown Delay

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#2488]
**Describe the bug**
Either you set the guild_skill_relog_delay: 0/1 you will always have a 5 mins cooldown

**To Reproduce**
1. set guild_skill_relog_delay: 1 and reload
2. use emergency call and then relog
3. after relog emergency call will still have 5mins cd

**Expected behavior**
it should reset the cooldown after relog

**Screenshots**

**System specs (please complete the following information):**
 - OS: [centos 7 x64]
 - Hercules Version [e.g. v2019.05.05]
 - Mode: [pre-renewal]
 - Packet version: [e.g. 20180620]
 - Client type: [RE]

**Plugins used or source modifications**
If you are using any plugins besides the ones that come bundled with Hercules,
please enumerate them here.

**Additional context**
Add any other context about the problem here. If the bug report is about a
crash, please attach the core/stack-dump or crash-log, if any.

**Comment by guilherme-gm** [comment]
Hmm, I think it is correct, the description says:
```
// How guild skills cooldown works?
// 0 - you relog with the same cooldown remaining as from when you logged out
// 1 - restarts the cooldown upon login to its full duration.
// 2 - like 1, but your logged off time is also decreased from the remaining cooldown (Aegis)
```
For 1:
1 - restarts the cooldown upon login to its **full duration**.

So this means it goes back to 5min

**Comment by Mojacko** [comment]
I thought it should be like removing the cooldown? like the old eathena
