### ISSUE TITLE
Cash Food + Normal Food Stacks

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#2489]
**Describe the bug**
The normal foods will stack with cash foods when you died.

**To Reproduce**
1. Use normal food (eg. str+10) first then use the cash food (str + 10)
2. At first it will have no effect (your str is still +10).
3. After you die you can use the normal food and will give you additional +10 (resulting to +20str)

**Expected behavior**
It should not stack.

**Screenshots**
https://imgur.com/jlJXYHC

**System specs (please complete the following information):**
 - OS: [centos 7 x64]
 - Hercules Version [e.g. v2019.05.05+3]
 - Mode: [pre-renewal]
 - Packet version: [e.g. 20180620]
 - Client type: [RE]

**Plugins used or source modifications**
If you are using any plugins besides the ones that come bundled with Hercules,
please enumerate them here.

**Additional context**
Add any other context about the problem here. If the bug report is about a
crash, please attach the core/stack-dump or crash-log, if any.

**Comment by Jedzkie** [comment]
In official server, does normal food and cash food stacks?
