### ISSUE TITLE
@autoloot

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2493]
**Describe the bug**
https://herc.ws/board/topic/1516-autoloot-not-working-properly/?do=findComment&comment=92152

**To Reproduce**
1. Create wiz
2. Warp to mag_dun01
3. SG on many mobs (autoloot is OK when kill only 1 mob but if many. #4.)
4. Still some loots on ground.

**Comment by tlacson7** [comment]
after checking the code, the problem is here:
**idle_no_autoloot: 1**  <- enabling this will make @autoloot not looting everything in the ground even you are not idle.

**Comment by carloshenrq** [comment]
Please read the configuration about this one.

```
// Idle characters can receive autoloot?
// Set to the time in seconds where an idle character will stop receiving
// items from Autoloot (0: disabled).
idle_no_autoloot: 0
```

If you put 1, means: if you stay 1 second idle, you won't autoloot.
Try with higher value, 30 or even 60.

**Comment by tlacson7** [comment]
Damn i thought its a logical thing. Thanks for the info.
