### ISSUE TITLE
Cannot overwrite monster name when spawn

### ISSUE THREAD

**Issue by Vietlubu** [HerculesWS/Hercules#2495]
**Describe the bug**
Cannot overwrite monster name when spawn

**To Reproduce**
1. Write down a script to spawn a monster
```
prontera,155,185,0,0	monster	New poring	1002,1,0,0,0
```
2. Start the server
3. Check the new monster on game
4. Get the monster's name is keep **Poring** not **New poring**

**Expected behavior**
Can see a poring with name is **New Poring**

**System specs (please complete the following information):**
 - OS: I'm test on MacOS 10.14.1 and Ubuntu 16.04
```
[Info]: Hercules 64-bit for Mac OS X
[Info]: Git revision (src): 'bd4c28934cc1b9701757669cd20f929bc6e54404'
[Info]: Git revision (scripts): 'bd4c28934cc1b9701757669cd20f929bc6e54404'
[Info]: OS version: 'Mac OS X 10.14.4 18E226 [x86_64]'
```
```
[Info]: Hercules 64-bit for Linux
[Info]: Git revision (src): 'bd4c28934cc1b9701757669cd20f929bc6e54404'
[Info]: Git revision (scripts): 'bd4c28934cc1b9701757669cd20f929bc6e54404'
[Info]: OS version: 'Ubuntu 16.04.3 LTS [x86_64]'
```
 - Packet version: 20190228
 - Client type: kRO

**Plugins used or source modifications**
Do not use any plugin

**Comment by dastgirp** [comment]
Commit at fault: https://github.com/HerculesWS/Hercules/commit/1ba4beaff4/
Can you check #2496 ?

**Comment by dastgirp** [comment]
😄, seems like @4144 and I were doing this at same time :)

**Comment by Vietlubu** [comment]
```
[Info]: Hercules 64-bit for Mac OS X
[Info]: Git revision (src): '6f4c95bd75ff75a961c0822bc5845187bf92a2aa'
[Info]: Git revision (scripts): '6f4c95bd75ff75a961c0822bc5845187bf92a2aa'
[Info]: OS version: 'Mac OS X 10.14.4 18E226 [x86_64]'
```
@dastgirp, I tested on you commit, that fixed my issues. Thank you, Hope it will be added on next relase.
