### ISSUE TITLE
Ignition Break Skill Animation

### ISSUE THREAD

**Issue by bruno199** [HerculesWS/Hercules#2511]
Hercules Version: Last Version

Client Date: 20190703

Server Mode: Renewal

Description of Issue:
Ignition Break not showing skill animation on using new clients. (2018-06-20 and to 2019-07-03)

Modifications that may affect results: None

**Comment by Zarbony** [comment]
This one affects Jack Frost and some other skills too.

**Comment by bruno199** [comment]
What More skill this affects?

**Comment by MishimaHaruna** [comment]
Closing this since the original issue was addressed. Please open a new one for any other skills with the same problem
