### ISSUE TITLE
slaveclone bug and last permanently when triggered using autobonus

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#2531]
**Describe the bug**
only first clone will behave correctly, will auto attack
any other clones after the first one will only stand there like a statue, and doesn't attack.
however, all the clones doesn't vanish after 1minute if i recall correctly they should have 1 minute lifespan by default.
`@slaveclone` become not usable anymore.

**To Reproduce**
1. add this script for any equipment (I was using this in a costume equipments)
```
	Script: <"
		autobonus "{ atcommand \"@slaveclone \"+strcharinfo(0); }",1000,60000;
	">
```
2. equip the item, then summon alot monster to kills.
3. when the clones start attacking monster, keep switch equipment so that the `autobonus` get triggered again whenever you re-equip any other equipments.
4. the item bonus keep triggered and keep spawn clones.
5. player can no longer use `@slaveclone` since it hit the slave limit and it doesn't reduce over time.

**Expected behavior**
Clone shouldn't standstill like a statue
Clone should vanish after 1 minute by default if not mistaken
`@slaveclone` shouldn't fail since it should recover the clone limit over time.

**Screenshots**
![img](https://i.imgur.com/7wAITgQ.jpg)
re-equip any kind of equipments will allow the `autobonus` to re-triggers again and again.

**System specs (please complete the following information):**
 - OS: [e.g. windows 10 version 1809, macOS 10.14]
 - Hercules Version [e.g. v2018.08.25]
 - Mode: [renewal]
 - Packet version: [e.g. 20180624]
 - Client type: [e.g. RE]

**Comment by Kenpachi2k13** [comment]
Actually this is not a bug, but misuse of @slaveclone in `autobonus()`.
@clone/@slaveclone/@evilclone will spawn a clone with unlimited duration.
Instead of `atcommand("@slaveclone");` you should use `clone();` script command and define a duration.
