### ISSUE TITLE
incorrect interaction between status reco and evil druid armor

### ISSUE THREAD

**Issue by Xelliekins** [HerculesWS/Hercules#2558]
**Describe the bug**
Using status recovery on an evil druid armor user in pvp/woe succeeds and also applies the blind status 

**To Reproduce**
1. Go to pvp/woe
2.  Apply sleep status to player
3. Use status recovery on sleeping ally with evil druid equipped

**Expected behavior**
Status recovery should simply fail. No recovery of status or application of blind should happen

**Screenshots**
Here is a video demonstrating the official behaviour on iRO Classic (aegis) 
https://youtu.be/LCQZUIF_naU

**System specs (please complete the following information):**
 - OS: Debian GNU/Linux 8.11 (jessie) [x86_64]
 - Hercules Version [v2019.09.22]
 - Mode: pre-renewal
 - Packet version: [20130807]
 - Client type: [RE]

**Comment by Kenpachi2k13** [comment]
Partially confirmed.
The _Sleep_ status won't be cured when _Evil Druid Card_ is equipped, but the application of _Blind_ status is possible.
https://www.youtube.com/watch?v=7xBtw29_kho
