### ISSUE TITLE
Incorrect Lex Aeterna Interactions

### ISSUE THREAD

**Issue by Xelliekins** [HerculesWS/Hercules#2559]
**Describe the bug**
Lex Aeterna remains applied to the player after Freeze or Stone curse Status are applied. 

**To Reproduce**
1. Go to PVP
2. use Lex Aeterna on target
3. Stone curse or freeze target (with frost joker)
4. Lex Aeterna remains applied to target

**Expected behavior**
Lex Aeterna should be cancelled by the application of the status effects freeze and stone curse. 
video from iRO Classic: 
stone curse: https://youtu.be/vmsVHo_jUK0
Freeze: https://youtu.be/ZyZB2I9iey0

**Screenshots**
https://i.imgur.com/UzZEvrW.jpg
https://i.imgur.com/JsHKbaA.jpg

**System specs (please complete the following information):**
   OS: Debian GNU/Linux 8.11 (jessie) [x86_64]
    Hercules Version [v2019.09.222]
    Mode: pre-renewal
    Packet version: [20130807 ]
    Client type: [RE]

**Comment by Kenpachi2k13** [comment]
Sadly the videos does not show what happens when Freeze/Stone status ends.
Does Lex Aeterna stay removed or is it re-applied?

**Comment by Xelliekins** [comment]
it stays gone, iirc. I will try to research that further.

**Comment by hemagx** [comment]
Aegis doesn't seem to do any additional handling after lex has ended, so probably doesn't re-apply it, changing it to confirmed.
