### ISSUE TITLE
skills/hit miss on *clone/@evilclone summons

### ISSUE THREAD

**Issue by worstgamedev** [HerculesWS/Hercules#2607]
**Describe the bug**
Using clone script command and @evilclone in game to summon a clone of a player, it can attack, hit but others can't hit it with skills and normal attacks. It will either go miss or dodged.

**To Reproduce**
1. This is script used
`prontera,155,95,5	script	Shroud#001	4_M_REBELLION,{

	$@clonegid = clone("prontera",158,84,"Shroud#001::OnTrigger",getcharid(0));
 	setunitdata $@clonegid,UDT_HAIRCOLOR,rand(1,10);
 	setunitdata $@clonegid,UDT_ATKRANGE,10;
 	setunitdata $@clonegid,UDT_AI,2;
 	setunitdata $@clonegid,UDT_CLASS,2110;
 	setunitdata $@clonegid,UDT_HIT,500;
 	setunitdata $@clonegid,UDT_FLEE,0;

 	announce($@clonegid,bc_all);

 	.@atkrange = getunitdata($@clonegid,UDT_ATKRANGE);
 	announce(.@atkrange,bc_all);

 	.@udthcolor = getunitdata($@clonegid,UDT_HAIRCOLOR);
 	announce(.@udthcolor,bc_all);

 	.@udtai = getunitdata($@clonegid,UDT_AI);
 	announce(.@udtai,bc_all);

	.@udtclass = getunitdata($@clonegid,UDT_CLASS);
 	announce(.@udtclass,bc_all);

 	.@udthit = getunitdata($@clonegid,UDT_HIT);
 	announce(.@udthit,bc_all);

	.@udtflee = getunitdata($@clonegid,UDT_FLEE);
 	announce(.@udtflee,bc_all);
	end;

	OnTrigger:
		announce($@clonegid + " clone died.", bc_all);

	OnNPCKillEvent:
		announce(killedrid + " died in a miserable way.", bc_blue|bc_all);

}`

**Expected behavior**
Summon a clone which can attack players and other clones and also pickup items.
Player and other clones could also attack and damage them.

**Screenshots**
![misss](https://user-images.githubusercontent.com/51965638/72013208-6b9b9e80-3298-11ea-97ab-b74f6b3ec000.gif)

**System specs (please complete the following information):**
 - OS: [Windows 10 version 1909]
 - Hercules Version [Release v2019.12.15]
 - Mode: [pre-renewal]
 - Packet version: [20151104]
 - Client type: [2015-11-04aRagexe]

**Plugins used or source modifications**
None, fresh compile from git. NEMO patch for client.

**Additional context**
So when I summon clones and attack them with skills or basic attack, it will result to miss, dodge
or no damage at all. I tried to use setunitdata for def mdef flee dodge to lowest number possible to but still not working. I also tried different ai and modes to see if that is the problem still not works.
Im new to scripting and I want to make an event where I summon clone if player is not enough in a room.

**Comment by Kenpachi2k13** [comment]
This is caused by `mob_clone_spawn()` creating an empty `struct mob_db` without assigning a value to `dmg_taken_rate`. Thus `dmg_taken_rate` is `0` and makes the clone invulnerable.

**Comment by Emistry** [comment]
if i recall correctly, this issue happen way before the DamageTakenRate was implemented.

**Comment by Kenpachi2k13** [comment]
I don't know, but this is definitively the issue.
`battle_weapon_attack()` applies this rate:
```
	if (target->type == BL_MOB) {
		struct mob_data *md = BL_CAST(BL_MOB, target);
		if (md != NULL) {
			if (md->db->dmg_taken_rate != 100) {
				if (wd.damage > 0)
					wd.damage = apply_percentrate64(wd.damage, md->db->dmg_taken_rate, 100);
				if (wd.damage2 > 0)
					wd.damage2 = apply_percentrate64(wd.damage2, md->db->dmg_taken_rate, 100);
			}
		}
	}
```
Since `dmg_taken_rate` is `0` here, the damage becomes `0`, too...
