### ISSUE TITLE
Wug Riding skill bug

### ISSUE THREAD

**Issue by ghost** [HerculesWS/Hercules#2611]
**Describe the bug**
Dual wug.

**To Reproduce**
1. Use @job 4062
2. Use @allskill
3. Use skill 'Wug Mastery'
4. Use skill 'Wug Riding'
5. Use skill 'Wug Mastery'
you can seen problem.

**Screenshots**

![image](https://user-images.githubusercontent.com/45366675/72277212-22669880-3664-11ea-9707-9053bec06b3b.png)

**System specs:**
 - OS: windows 10, debian 10
 - Hercules v2020.01.12
 - Mode: renewal
 - Packet version: 2018-09-19, 2019-02-28, 2020-01-08
 - Client type: Main, RE, Zero

**Plugins used or source modifications**
None

**Comment by Kenpachi2k13** [comment]
Can'r reproduce with `Hercules v2020.01.12` and `2018-04-18bRagexeRE`.

**Comment by X-EcutiOnner** [comment]
confirm, this problem can reproduce only when you enable "skill_unconditional: true"

**Comment by Kenpachi2k13** [comment]
> confirm, this problem can reproduce only when you enable "skill_unconditional: true"

So this is expected behaviour and not a bug.
`close();`
