### ISSUE TITLE
IPban table size is less than length of IP

### ISSUE THREAD

**Issue by dastgirp** [HerculesWS/Hercules#2631]
**Describe the bug**
https://github.com/HerculesWS/Hercules/pull/2583#issuecomment-586376498 (Copied Question below by @pazkero) 

> some custom plugins which I've saw on the forums add a command called "@ipban", for example, which is a non-automatic way of adding IP Bans.
> 
> An IP official length is 15 or 16 (xxx.xxx.xxx.xxx). Wouldn't this cause issues when IP bans are not done automatically? (Also, in some rather specific cases, it might be a desired behavior to ban only the specific IP. Yes, I am aware of how dynamic IP works and why we usually use a star.)
> 
> TL;DR Doesn't this causes issues or SQL errors if there are IP Bans of length 15?
> 
> PS. Feel free to open an issue about it, if you think it relevant. I'm just curious.

**Expected behavior**
IP should be stored even if length is 15.

**Additional context**
We changed the IP length in SQL to 13 in IP Ban Table. Reference PR: #2583

**Comment by Kenpachi2k13** [comment]
Maybe we should expand the column length not just to 15, but even to 39, to enable custom code to insert IPv6 addresses.
Just a suggestion...

**Comment by dastgirp** [comment]
Afaik,  client doesn't support IPv6, but, Yes, maybe we can change it to 39
