### ISSUE TITLE
Critical Explosion Broken

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2635]
**Describe the bug**
Using PRE-RE 20151029 latest git

When Critical Explosion, Abrasive STATUS activate. Then not able to assura.

**Comment by Vaans** [comment]
i can confirm this bug.

**Comment by Svald** [comment]
I posted about an issue related to this skill a couple of days ago with more details:
https://herc.ws/board/topic/17879-critical-explosion-brings-up-a-merchants-cart/

**Comment by hemagx** [comment]
Closed in favor of #2636
