### ISSUE TITLE
How To Change Max Job Level ?

### ISSUE THREAD

**Issue by kelvinharleyy** [HerculesWS/Hercules#2640]
How to change max job level ?

I am using Renewal Server
Already tried edit Max level to 120  job_exp_group_db  at db\re\exp_group_db.conf 

My 3rd job level stuck at 60

**Comment by Kenpachi2k13** [comment]
Changing the maximum job level in db/(pre-)re/exp_group_db.conf works fine.
If you need additional support, please open a thread in the forum.

Also please use the provided template when creating an issue.

`close();`
