### ISSUE TITLE
Error compiling with packetver 20100730 on Ubuntu

### ISSUE THREAD

**Issue by joaogardenberg** [HerculesWS/Hercules#2669]
**Describe the bug**
Error compiling with packetver 20100730 on Ubuntu.

**To Reproduce**
1. Use Ubuntu
2. Get source from latest stable (as of 2020-03-27)
3. Follow the [installation instructions](https://github.com/HerculesWS/Hercules/wiki/Installation-(Debian))
4. Instead of `./configure`, use `./configure --enable-packetver=20100730 --disable-renewal`
5. Run `make clean && make sql`

**Expected behavior**
Compiles successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/6900749/77812854-03807b80-7083-11ea-935f-76a0d38b6416.png)

**System specs (please complete the following information):**
 - OS: Ubuntu 18.04
 - Hercules Version: v2020.03.08+2
 - Mode: Pre-renewal
 - Packet version: 20100730
 - Client type: Not applicable

**Plugins used or source modifications**
Nothing.

**Additional context**
Running Ubuntu from docker image "ubuntu", on Windows 10.

**Note**
It works fine without `--enable-packetver=20100730`.

**Comment by 4144** [comment]
This pull request should fix your issue https://github.com/HerculesWS/Hercules/pull/2663

**Comment by joaogardenberg** [comment]
Thanks! Is there any way to know when it's gonna be merged?

**Comment by joaogardenberg** [comment]
@4144 I get this error on your branch:

![image](https://user-images.githubusercontent.com/6900749/77816379-14d88080-70a1-11ea-802f-838d6097f47f.png)

**Comment by 4144** [comment]
oh yes left some other things...

**Comment by 4144** [comment]
now should be fine.
about merge, at next hercules release. near one week left for new release.

**Comment by joaogardenberg** [comment]
Okay, now worked successfully. Thank you very much!
