### ISSUE TITLE
Skill index/tree calculation broken

### ISSUE THREAD

**Issue by Kenpachi2k13** [HerculesWS/Hercules#2670]
**Describe the bug**
A user reported via Discord that the calculation for skill index/tree is broken:

> hey. i just want to ask you, do you know about problem with new skill indexes & bard/dancer linked skills?
> Is server side problem
> Check pc_calc_skilltree
> There must be i+8, cause indexes are reversed now
> actually somehow it affects all this function
> we just revert this PR (https://github.com/HerculesWS/Hercules/pull/2596) on our server until you will fix all these indexes, it's not only affects bard/dancer linked skill, it also affects skill reset, tree calculation and etc.
![unknown](https://user-images.githubusercontent.com/3476227/77814947-18c2cd80-70b6-11ea-9ccf-b567e650138d.png)

**Comment by MishimaHaruna** [comment]
I have a draft to fix this part in an index-independent way (doing that kind of arithmetic on an index is just plain wrong anyway...)
