### ISSUE TITLE
Hatch Egg Bug

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2683]
**Describe the bug**
When hatching some egg it gives this error. Pet did not come out.
[Error]: pet_recv_petdata: Hatching pet (0:Poring) aborted, couldn't find egg in inventory for removal!
**System specs (please complete the following information):**
 - OS: Centos 7 x64
 - Hercules Version v2020.04.05
 - Mode: PreRE
 - Packet version:20151029
 - Client type: main

**Plugins used or source modifications**
none

**Comment by MishimaHaruna** [comment]
Fixed in the v2020.04.05+1 release
