### ISSUE TITLE
UnknownStatusChange

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2684]
**Describe the bug** 
while attacking a mob in dungeon, this error floods the console.
[Error]: UnknownStatusChange [271]
[Error]: UnknownStatusChange [271]
[Error]: UnknownStatusChange [271]
[Error]: UnknownStatusChange [271]

**To Reproduce**
change  ksprotection: 10000

**System specs (please complete the following information):**
 - OS: Centos7
 - Hercules Version  v2020.04.05
 - Mode: PRERE
 - Packet version: 20151029
 - Client type: main

**Plugins used or source modifications**
none

**Comment by Zarbony** [comment]
I got this error with [Error]: UnknownStatusChange [583] when using WM_SEVERE_RAINSTORM (Skill ID: 2418)
