### ISSUE TITLE
OnPCLoginEvent looping!

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2688]
**Describe the bug**
dispbottom is looping when you have duplicate NPC.
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello

**To Reproduce**
`-	script	mybrokenbones	HIDDEN_NPC,{
	mes "Mic test hello";
	close;

OnPCLoginEvent:
	dispbottom "Hello";
	end;
}

payon,74,124,0	duplicate(mybrokenbones)	mybrokenbones#pay	1_F_ORIENT_02
prontera,114,100,4	duplicate(mybrokenbones)	mybrokenbones#prt	1_F_ORIENT_02
prt_fild05,294,224,4	duplicate(mybrokenbones)	mybrokenbones#prt2	1_F_ORIENT_02
izlude,121,92,4	duplicate(mybrokenbones)	mybrokenbones#izl	1_F_ORIENT_02
alberta,106,65,4	duplicate(mybrokenbones)	mybrokenbones#alb2	1_F_ORIENT_02
alberta,31,242,4	duplicate(mybrokenbones)	mybrokenbones#alb	1_F_ORIENT_02
amatsu,99,157,4	duplicate(mybrokenbones)	mybrokenbones#ama	1_F_ORIENT_02
gonryun,174,105,4	duplicate(mybrokenbones)	mybrokenbones#gon	1_F_ORIENT_02
`
**System specs (please complete the following information):**
 - OS: Centos7
 - Hercules Version latest
 - Mode: pre-re
 - Packet version: 20151029
 - Client type: main

**Plugins used or source modifications**
non

**Comment by Emistry** [comment]
that's because you duplicated theNPC that consists of `OnPCLoginEvent` event.
