### ISSUE TITLE
Attendance System

### ISSUE THREAD

**Issue by PixelBr** [HerculesWS/Hercules#2704]
The Attendance System is not working as it is on official servers.

The reward is per character, and not on account as it should be, and when the player is eligible to receive the reward he must open the window automatically, which is not happening either.

I performed the test on Kro and iRO.

**Comment by GilbertoBitt** [comment]
the reward system i think can be easily changed to happen on the account and on the windows automatically open I think it is fixable using a simple NPC timer.
