### ISSUE TITLE
@refresh issue.

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2706]
Using @refresh STATUS AILMENT?  How to prevent/fix not to remoe ailment?

**Comment by Kenpachi2k13** [comment]
@tlacson7 
Could please provide more details? I don't really get your point.

**Comment by MrKeiKun** [comment]
I can confirm.
just get affected by `SC_BLIND` then do `@refresh`. the visual effect of `SC_BLIND` wont get showed back yet the tick is still counting until the end.
