### ISSUE TITLE
Fly Wing, Butterfly Wing

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2709]
**Describe the bug**
There are instance these items dont work. It consumed item but did not function.

**To Reproduce**
I cant but some player had these issue. Not all times but some times.

**System specs (please complete the following information):**
 - OS: centos 7 x64
 - Hercules Version latest
 - Mode: pre-re
 - Packet version: 20151029
 - Client type: main

**Comment by Jedzkie** [comment]
Closing this issue. Already fixed in PR#2699

**Comment by Kenpachi2k13** [comment]
Are you sure about that, @Jedzkie?
Would be nice if @tlacson7 could confirm it...
