### ISSUE TITLE
Break Weapon not affecting Subtype Mace

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#2711]
**Describe the bug**
Tested with bBreakWeaponRate only. all weapon that has W_MACE subtype is not affected or does not get broken... tested on a clean copy of hercules

**To Reproduce**
1. use a item with 100% bBreakWeaponRate 
2. player b will equip a mace type weapon
3. it won't break 
4. No error or any kind of message... But other weapons such as dagger still break.

**Expected behavior**
W_MACE type should also be affected by bBreakWeaponRate  or break status

**Screenshots**

**System specs (please complete the following information):**
 - OS: [Ubuntu 19]
 - Hercules Version [v2020.05.03] (fresh copy upon submitting this)
 - Mode: [pre-renewal]
 - Packet version: [2016-02-03]
 - Client type: [RE]

**Plugins used or source modifications**
NO PLUGIN USED

**Additional context**
Seems that even melt down can't break mace type.

**Comment by kyeme** [comment]
Maces are unbreakable
https://irowiki.org/wiki/Mace

**Comment by Mojacko** [comment]
> Mace and axe weapons are unbreakable
> https://irowiki.org/wiki/Mace

Thank you
