### ISSUE TITLE
Map-Server Crashing with GDB debug

### ISSUE THREAD

**Issue by ean2020** [HerculesWS/Hercules#2719]
**Describe the bug**
- This map-server would crash randomly throughout the day and this was the debug of the first crash - https://pastebin.com/g8az1tTv  and afterwhich 4144 in the Discord suggested to try to update to this Pull Request (https://github.com/HerculesWS/Hercules/pull/2713) which I did and make clean and re-compiled.

After few hours the map server is crashing again with the debug code - http://www.pastebin.com/AZXpWkZF

Appreciate if anyone could provide a permanent fix to this crash.

**Expected behavior**

**Screenshots**

**System specs (please complete the following information):**
 - OS: [e.g. windows 10 version 1809, macOS 10.14] - Debian 10
 - Hercules Version [e.g. v2018.09.22] - Latest
 - Mode: [renewal or pre-renewal?] - Renewal
 - Packet version: [e.g. 20101130] - 2018-4-18

**Plugins used or source modifications**
If you are using any plugins besides the ones that come bundled with Hercules,
please enumerate them here.

- No modifications on the source nor plugins were use

**Additional context**
Add any other context about the problem here. If the bug report is about a
crash, please attach the core/stack-dump or crash-log, if any.

**Comment by bWolfie** [comment]
any pattern to this crash? or you can't find info on it yet?

Previously I had an issue where a malformed reg value caused map server crashes whenever a player with one of the malformed values logged out. This was caused by set(getvariableofpc()), but that bug was fixes years ago AFAIK.

**Comment by 4144** [comment]
i think issue isolated. Soon in given pr should be fix.

**Comment by 4144** [comment]
now it should be fixed in pr #2713

**Comment by ean2020** [comment]
I can confirmed this is fixed as I no longer experiencing crashing as of now.
