### ISSUE TITLE
**CRITICAL BUG** Player consume ITMCHAIN_ORE when die in dungeon or fields.

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2722]
**Describe the bug**
Player consume ITMCHAIN_ORE when die in dungeon or fields.

**To Reproduce**
Go to dungeon or fields with any of ITMCHAIN_ORE's in your inventory. Type @die or get killed by mob and you lose 1 item.

I discovered that at /db/pre-re/item_chain.conf 
placing ITMCHAIN_SIEGFRIED on the top of the line will fix it.

**System specs (please complete the following information):**
 - OS: Centos7 x64
 - Hercules Version LATEST
 - Mode: PRE-RE
 - Packet version: 20151029
 - Client type :MAIN

**Comment by Kenpachi2k13** [comment]
I tried this with 20 Coal in inventory as a level 1/1 Novice and could not reproduce the issue.
I tried dungeons and fields, using `@die` and being killed by monster, pre-RE and RE mode. Always the same result: No item lost.

**Comment by tlacson7** [comment]
@Kenpachi2k13  oh i forgot to include.
remove this group and try again sir.
```
ITMCHAIN_NEO_INSURANCE: {
	New_Insurance: 1
}

```

**Comment by Kenpachi2k13** [comment]
@tlacson7 
Any new information?

**Comment by Kenpachi2k13** [comment]
No new input and irreproducible.
`close();`
