### ISSUE TITLE
1st classes's skills update

### ISSUE THREAD

**Issue by haurenburu** [HerculesWS/Hercules#2725]
***Skills balance contents***
1st classes
- [x] Swordsman
- [x] Merchant
- [x] Magician
- [x] Acolyte

https://www.divine-pride.net/forum/index.php?/topic/3453-kro-mass-skills-balance-1st-2nd-and-transcendent-classes-skills/

repo: https://github.com/haurenburu/Hercules/tree/update-1st-classes
pr: #2726

**Comment by MishimaHaruna** [comment]
This is available in the rebalance branch (and the 2024.03-rebalance pre-release: https://github.com/HerculesWS/Hercules/releases/tag/v2024.03-rebalance)
