### ISSUE TITLE
2nd classes's skills update

### ISSUE THREAD

**Issue by haurenburu** [HerculesWS/Hercules#2727]
***Skills balance contents***
2nd classes
- [x] Knight (still need to confirm some formulas)
- [x] Blacksmith
- [x] Assassin
- [x] Wizard (i`m not sure about vermilion hits)
- [x] Priest
- [x] Hunter
- [x] Crusader
- [x] Alchemist
- [x] Rogue
- [x] Sage
- [x] Monk (missing double damage on GF i dont know how to do it :[ )
- [x] Bard & Dancer

https://www.divine-pride.net/forum/index.php?/topic/3453-kro-mass-skills-balance-1st-2nd-and-transcendent-classes-skills/

**Comment by neverfoldaq** [comment]
hey, do you have any progress here?

**Comment by MishimaHaruna** [comment]
The 2nd class skills rebalance is now available for testing on the rebalance branch (see v2024.06-rebalance pre-release)
