### ISSUE TITLE
exp_group_db max number error

### ISSUE THREAD

**Issue by LiMoon** [HerculesWS/Hercules#2738]
Git revision (src): 'ec0584ac41434766e528b25730812da22ff31fc5'

**Describe the bug**
exp_group_db.conf set ThirdClasses MaxLevel to 185, but 182 exp is `2426009129`, map-server error is `mismatched element type in array`, then change 182 exp to `2147483647` is working.

**Comment by Kenpachi2k13** [comment]
This is not a bug.
The required experience points per level are stored in an integer variable and thus the maximum possible value is `2147483647`.

**Comment by 4144** [comment]
for very big numbers need add ``L`` at end.
also if ``L`` added into one value in list, need add `L` value to all items in list.

**Comment by LiMoon** [comment]
add `L` at end, is working, thank @4144
