### ISSUE TITLE
Unable to trade or open chatroom when dead

### ISSUE THREAD

**Issue by zgmfx20b** [HerculesWS/Hercules#2740]
**Describe the bug**
Unable to trade or create chatroom when dead

**To Reproduce**
1. Kill your self @die 
2. Try to Open chat room or perform trade to other player

**Expected behavior**
Players should be able to trade or create chatroom even dead.

**Screenshots**

**System specs (please complete the following information):**
 - OS: CentOS
 - Hercules Version: Latest
 - Mode: Pre-renewal (Did not test in renewal)
 - Packet version: 20151029
 - Client type: main

**Comment by tlacson7** [comment]
Its a bug i think, player complain they cant ask trade drasil leaf or bluegem  to other player to resu them.

**Comment by pazkero** [comment]
Introduced in commit 6629dfd05f4ebef7862cd2d499b7330acc8d82ac

```c
static void clif_parse_TradeRequest(int fd, struct map_session_data *sd)
{
	struct map_session_data *t_sd;
	if (sd->state.trading || pc_isdead(sd) || pc_isvending(sd))
		return;
```
...

**Comment by Jedzkie** [comment]
If this is an official behavior, then we can make an option to enable/disable this behavior.
