### ISSUE TITLE
Renamed Pets don't have an Egg with "Beloved" prefix

### ISSUE THREAD

**Issue by alisonrag** [HerculesWS/Hercules#2743]
**Describe the bug**
Renamed Pets don't have an Egg with "Beloved" prefix

**To Reproduce**
1 - Create a pet with  `petegg` or capture a pet
2 - Hatch the egg
3 - Rename the pet
4 - Return pet to the egg

**Expected behavior**
Renamed Pets when they back to the Egg, the egg must have the "Beloved" prefix

**Official Information**
Unofficial: https://www.novaragnarok.com/wiki/Pet_System#Overview
Official: https://browiki.org/wiki/Mascotes#Alterar_Nome

**Screenshots**

**System specs (please complete the following information):**
 - OS: Windows 10
 - Hercules Version  Release v2020.05.03 
 - Mode: renewal 
 - Packet version: 20180418
 - Client type: RE

**Plugins used or source modifications**
N/A

**Additional context**
Need to check if emulator is saving 1 in card[3] when the pet is renamed

Generated a "Beloved" egg using the following code:
in `clif.c` function `clif_addcards`:
```
if (item->card[0] == CARD0_PET) { //pet eggs
        buf->card[0] = 1;
        buf->card[1] = 2;
        buf->card[2] = 0;
        buf->card[3] = 1; //Pet renamed flag.
        return;
    }
```
using openkore as base (data parsed from bRO and iRO): 
`buf->card[0] ` must be equals to 1 when EGG
`buf->card[1] + buf->card[2]` must be equals to the PET unique ID (pet table)
`buf->card[3] ` must be equal to 1 if pet is renamed

print of expected result:
![image](https://user-images.githubusercontent.com/10372732/83060254-89905280-a031-11ea-84ad-1ff44be08161.png)

**Comment by Kenpachi2k13** [comment]
Confirmed. This happens due to the missing saving of the pet's rename flag when return it to the egg.
