### ISSUE TITLE
rodex_sendmail_acc

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2749]
**Describe the bug**
Mail notification is received but no msg on mail.

**To Reproduce**
prontera,150,150,4	script	Rodex Mail	1_M_01,{
	// Sends a messsage to attached player "Account Box" from "Rodex Test", with title "Rodex Test3",
	// with message "Hello World, How are You?", 1000 Zenies and 5 Red Potions attached
	rodex_sendmail_acc(
		getcharid(CHAR_ID_ACCOUNT), "Rodex Test", "Rodex Test3", "Hello World, How are You?",
		1000,
		Red_Potion, 5
	);
	end;
}

**System specs (please complete the following information):**
 - OS: Centos 7x64
 - Hercules Version latest
 - Mode: Prere
 - Packet version: 20151029
 - Client type: main

**Comment by guilherme-gm** [comment]
Your client version is too old to support account mails. Hercules did make it and sent the mail alert, but your client is not able to request for account mails, so you don't see them.

I made a PR (#3263) adding warnings when using it in unsupported clients so people can know why it is not working. not exactly a "solution" but I think this is the best that can be done in this case :)

There was a discussion in the past whether we should redirect account mails to the main box, but was decided not to. Maybe a plugin could be made to support this.
