### ISSUE TITLE
Fly Wing / Butterfly Wing not working on PC_ALL_RIDING and Falcon

### ISSUE THREAD

**Issue by nosfantasy** [HerculesWS/Hercules#2750]
**Describe the bug**
I'm use Release April 05 2020 PATCH 1  mode Pre-Renewal

When i'm job Hunter and use item Boarding Halter & have Falcon item Butterfly Wing and Fly wing not working but item decrease.

**Comment by tlacson7** [comment]
it is related to the report #2709 .  Does it happen always?

**Comment by Jedzkie** [comment]
This issues is already been addressed, here's the link of the PR and test it if it helps fixing the issue.
https://github.com/HerculesWS/Hercules/pull/2699

**Comment by tlacson7** [comment]
@Jedzkie i was already using that #2699 PR but still persist. bwing, butterfly sometimes don't work but deducts in number.

**Comment by Kenpachi2k13** [comment]
I added a new commit (468c81a) to #2699 which fixes this particular issue.
