### ISSUE TITLE
Megaphone Behaviors

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#2751]
**Describe the bug**
Original issue reported by kyeme - https://herc.ws/oldboard/tracker/issue-7065-megaphone-behavior-minor-bug/?fbclid=IwAR2DLAJB0rjd3dNn9vsJFAMe3ausg3ybY-Zs0B3DjX0-lvYKkuVWQ980wEE

**To Reproduce**
1. When someone shouts and i double clicked his name in General Message it won't automatically register his name in my chat.

**Expected behavior**
1. in Official, if you double click his name in General Message, it will automatically register the name in the chat.

Additional Info:
if the message input is open.
 - You can walk
 - You can use skill
 - You can use item
 - The message should still be broadcast even thought you died. (Here in hercules when you're going to broadcast a message using a megaphone and suddenly you die the message you were going to send is cancelled.)

**Screenshots**
https://youtu.be/5WVNc_haDqo

**System specs (please complete the following information):**
 - OS: Windows 10 18363
 - Hercules Version: v2020.05.03
 - Mode: Pre-Renewal
 - Packet version: 2016-03-16
 - Client type: RE

**Plugins used or source modifications**

**Additional context**

**Comment by Kenpachi2k13** [comment]
@MishimaHaruna 
#2758 fixed only the part where double clicking the shouters name had no effect.

*reopen*
