### ISSUE TITLE
Allow use of contants in mob_skill_db

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#2768]
**Is your feature request related to a problem? Please describe.**
Currently in the mob_db, we have used mob ids from 2500-3999. This is obviously an issue, as with more and more updates, these need to be moved to new Mob IDs.

The big issue comes from mob_skill_db. In it, you cannot reference constants in the data. E.g. here on summon slave, we would have to go through every entry like below and correct these to new IDs.
```
		NPC_SUMMONSLAVE: {
			SkillState: "MSS_BERSERK"
			SkillLevel: 5
			Rate: 10000
			CastTime: 700
			Delay: 60000
			SkillTarget: "MST_SELF"
			CastCondition: "MSC_SLAVELE"
			ConditionData: 3
			val0: 2501
			val1: 2502
			Emotion: 0
		}
```

**Describe the solution you'd like**
It'd be much easier if we could reference skill, item, mobs and whatever other data we can in the mob_skill_db.

E.g.
`val0: "ANCIENT_MIMIC"`
`ConditionData: "WZ_STORMGUST"`

This means if the ID of the above ever changed, it won't need to be updated in the mob_skill_db.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Kenpachi2k13** [comment]
> Currently in the mob_db, we have used mob ids from 2500-3999.

That's not right. The first monster ID is 1001 (`SCORPION`). Furthermore you can use IDs up to 21000 (`#define MAX_MOB_DB 22000`) excluding the IDs reserved for job classes (4001 to 4048).


> This means if the ID of the above ever changed, it won't need to be updated in the mob_skill_db.

The IDs never have changed and will never change.

-----------------------------

To be honest I don't see a real benefit or reason to implement this request.

**Comment by bWolfie** [comment]
@Kenpachi2k13 I meant mob_db2. "We" refers to ME. People who use those ID ranges 2500-3999 and other mob ids that are used in Renewal updates have to update their mob_skill_db2 accordingly. This could create problems.

**Comment by Kenpachi2k13** [comment]
Ah, now I get it.
I'll work on that, but be aware that it won't have top priority. :wink:

**Comment by Emistry** [comment]
It's a QoL changes.
Just like `item_combo` file which use the constants and not item ID.
It would be useful for other server that has alot of custom changes on mob_db, especially new/custom mob id.
Changing the ID of a mob required to update `mob_skill_db`, if we use constant in `mob_skill_db`, then we wouldn't need to worry about updating `mob_skill_db` since it use constant rather than ID.
