### ISSUE TITLE
Skill DB loading errors in script-checker/minimal mode

### ISSUE THREAD

**Issue by MishimaHaruna** [HerculesWS/Hercules#2776]
**Describe the bug**

When running the server in minimal mode (for example through the script-checker script), several errors are printed similar to the following:

```
[Warning]: skill_validate_sp_cost: Invalid SP cost 8 specified in level 1 for skill ID 5 in db/pre-re/skill_db.conf! Minimum is 0, maximum is 0. Defaulting to 0... 
[Warning]: skill_validate_sp_cost: Invalid SP cost 8 specified in level 2 for skill ID 5 in db/pre-re/skill_db.conf! Minimum is 0, maximum is 0. Defaulting to 0... 
[Warning]: skill_validate_sp_cost: Invalid SP cost 8 specified in level 3 for skill ID 5 in db/pre-re/skill_db.conf! Minimum is 0, maximum is 0. Defaulting to 0... 
[Warning]: skill_validate_sp_cost: Invalid SP cost 8 specified in level 4 for skill ID 5 in db/pre-re/skill_db.conf! Minimum is 0, maximum is 0. Defaulting to 0... 
[Warning]: skill_validate_sp_cost: Invalid SP cost 8 specified in level 5 for skill ID 5 in db/pre-re/skill_db.conf! Minimum is 0, maximum is 0. Defaulting to 0... 
```

This is happening because in minimal mode, the battle config isn't loaded, but the skill DB validation code requires it (see battle.c:21918):

```
 if (sp_cost >= 0 && sp_cost <= battle_config.max_sp)
```

A possible fix is to load the battle config in minimal mode (by moving the call to `battle->config_read()` outside the `if (!minimal)` block in `do_init()` of map.c. This needs to be tested as to whether there are other unexpected interactions with the minimal mode.

**To Reproduce**
1. Compile Hercules
2. Run the script `./script-checker npc/dev/test.txt` (or the equivalent command `./map-server --script-checker --load-script npc/dev/test.txt`)
3. See several warnings printed to the output

**Expected behavior**

No errors or warnings are printed

**System specs (please complete the following information):**
 - OS: Debian GNU/Linux 9.11 (stretch) [x86_64]
 - Hercules Version v2020.05.31+1
 - Mode: both renewal and pre-renewal
 - Packet version: any (default)
 - Client type: n/a, the error is reproducible in the server running in minimal mode

**Plugins used or source modifications**
None

**Additional context**
The error can also be seen on https://haru.ws/scriptchecker/

**Comment by Jedzkie** [comment]
Getting warning also when using mapcache.

**Comment by 4144** [comment]
should be fixed in ci pr soon.
