### ISSUE TITLE
Kaizel revive causes cart to be removed

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#2777]
**Describe the bug**
If you get revived via SC_KAIZEL, your cart is removed.

**To Reproduce**
1. Use Soul Linker skill 'Kaizel' on any player with a cart.
2. Player with cart dies.
3. Cart is gone if revived via Kaizel.

**Expected behavior**
Cart should not be affected by Kaizel.

**Screenshots**

**System specs (please complete the following information):**
 - OS: [CentOS 7]
 - Hercules Version [e.g. v2020.01.12]
 - Mode: [pre-renewal]
 - Packet version: [e.g. 20160113]
 - Client type: [main]

**Plugins used or source modifications**

**Additional context**

**Comment by 4144** [comment]
why you closed issue?

**Comment by bWolfie** [comment]
Bad report. I didn't test on vanilla Hercules. I didn't realise I had custom code affecting Kaizel.
