### ISSUE TITLE
gettimetick(0) returns negative value

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#2779]
**Describe the bug**
gettimetick(0) should only return positive integers.

**To Reproduce**
Create a script to test values, then run the script.
```
.@tick = gettimetick(0);
consolemes(CONSOLEMES_DEBUG, "tick = %u, tick = %u", gettimetick(0), .@tick);
```

In my example, it produced
```[Jun/16 10:09:42][Debug]: consolemes: tick = 3775957166, tick = 3775950043```

But since these values exceed INT_MAX, they become negative according to the script engine.

**Expected behavior**
We shouldn't allow the value to exceed INT_MAX since script engine doesn't support it.

**Comment by Emistry** [comment]
What should be the value if it capped at `INT_MAX`, always return `INT_MAX`? seem not appropriate.

Perhaps we can consider to trim the millisecond? since these millisecond value are hardly used (never really seen anyone using it). 
That way we could have more buffer to use?
