### ISSUE TITLE
If you sell items sending you over INT_MAX, deal fails, lose items, don't get zeny

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#2780]
**Describe the bug**
When you sell items that would send you over INT_MAX, you get the message "**The deal has failed.**", the items you sold get removed, but you don't receive any of the zeny.

In `npc_selllist()`, this check should be done **before** we delete the items. At the moment, the items get deleted, then we check if the deal can fail due to bad zeny count.
```
	if (z + sd->status.zeny > MAX_ZENY && nd->master_nd == NULL)
		return 1;
```

**To Reproduce**
1. Have some big amount of Zeny already (let's say 400m).
2. Sell 2b worth of items (e.g. 12k Treasure Boxes (7444)).
3. You will get deal is failed, items are gone, 

**Expected behavior**
The items should not be deleted if the deal failed.

**Video**
As you can see in the video, I actually sold too many items resulting in the value being negative. However, if I only sold an amount where the value was still positive (assuming current Zeny + new zeny > INT_MAX), the same result would happen.
https://streamable.com/yc4ehe

**System specs (please complete the following information):**
 - OS: [CentOS 7]
 - Hercules Version [e.g. v2020.01.12
 - Mode: [pre-re]
 - Packet version: [e.g. 20160113]
 - Client type: [main]

**Comment by Jedzkie** [comment]
@Kenpachi2k13
