### ISSUE TITLE
Herc don't have bonus2 bDropAddRace,r,x;

### ISSUE THREAD

**Issue by nosfantasy** [HerculesWS/Hercules#2787]
I want to increase drop rate percent to item_db but  bonus2 bDropAddRace,r,x; don't have, Tell me pls or have another way to same it.

**Comment by Kenpachi2k13** [comment]
Is this bonus required for any official item?
If not, I'd like to refer you to the forum's [Source Requests](https://herc.ws/board/forum/25-source-requests/) or [Plugin Requests](https://herc.ws/board/forum/143-plugin-requests/) section.

**Comment by nosfantasy** [comment]
Oh sorry, this required is not have in official item. i want for use in my private server.

**Comment by Jedzkie** [comment]
@nosfantasy going to close this.
