### ISSUE TITLE
can't move when go to change job in academy f2

### ISSUE THREAD

**Issue by comdevx** [HerculesWS/Hercules#2809]
I am test 2 player and bug 2 player. when select to player and select player again. it move to random position.
![image](https://user-images.githubusercontent.com/8242229/89714774-67b93180-d9cb-11ea-84d2-cda55401edc4.png)

**Comment by 4144** [comment]
this mean client map not same with server side map.
try use mapcache plugin for regenerate server maps from client maps.

**Comment by comdevx** [comment]
thx i will try.

**Comment by Leonein** [comment]
> thx i will try.

How did you fixed the issue? I'm new here, I just started my RO Offline.
