### ISSUE TITLE
Soul Link Dancer

### ISSUE THREAD

**Issue by Samuel23** [HerculesWS/Hercules#2815]
**Describe the bug**
Dancer with soul link doesn't get the bard skills counterpart

**To Reproduce**
1. Make a Dancer with all skills (tried even not using @skillall, manual leveling and skill adding)
2. Soul Link Buff for Bard/Dancer
3. Check Skill tree
4. No additional skills added

**Expected behavior**
Dancer with soul link should get the bard skills counterpart

**Screenshots**
https://imgur.com/v6RzuUF

https://imgur.com/OYKbaWB

https://imgur.com/pIz7A4Q

https://imgur.com/Z0gqqpB

**System specs (please complete the following information):**
 - OS: [windows 10]
 - Hercules Version [Release v2020.07.26]
 - Mode: [renewal or pre-renewal?] - tried both
 - Packet version: [e.g. 20190322]
 - Client type: [Main]

**Plugins used or source modifications**
No source modifications
Tried with some of my made plugins
Tried as well to disable all plugins

**Additional context**
No crash error, no console error

**Comment by AnnieRuru** [comment]
confirm, someone on discord also tell me this issue

**Comment by AnnieRuru** [comment]
blame https://github.com/HerculesWS/Hercules/commit/bfa423fea55aa5659506cf85e6c418346804ac89
@Samuel23 that's wrong fix, in fact haru also wrong, why bard copy the correct skill index but dancer did the other way round ?

```
	pc->calc_skilltree_clear(sd);
ShowDebug ("SkillActualID : %d %d %d %d\n", BA_WHISTLE, BA_APPLEIDUN, DC_HUMMING, DC_SERVICEFORYOU);
ShowDebug ("Skillindex : %d %d %d %d\n", skill->get_index(BA_WHISTLE), skill->get_index(BA_APPLEIDUN), skill->get_index(DC_HUMMING), skill->get_index(DC_SERVICEFORYOU));
	for (int i = 0; i < MAX_SKILL_DB; i++) {
		if (sd->status.skill[i].flag == SKILL_FLAG_TEMPORARY || sd->status.skill[i].flag >= SKILL_FLAG_REPLACED_LV_0) {
			// Restore original level of skills after deleting earned skills.
			sd->status.skill[i].lv = (sd->status.skill[i].flag == SKILL_FLAG_TEMPORARY) ? 0 : sd->status.skill[i].flag - SKILL_FLAG_REPLACED_LV_0;
			sd->status.skill[i].flag = SKILL_FLAG_PERMANENT;
			ShowWarning ("run 3 continue\n"); // bard never reach here, but dancer CAN reach here
		}
```
I think the actual problem is because the skill index of dancer is lower than bard,
when it continue the loop it hit the `SKILL_FLAG_REPLACED_LV_0` check condition and set the skill level into 0
