### ISSUE TITLE
Possible bug at MD_LOOTER check in status.c file

### ISSUE THREAD

**Issue by EPuncker** [HerculesWS/Hercules#2834]
**Describe the bug**
monster_loot_type setting not working

**To Reproduce**
1. Go to your battle/monster.conf file and change **monster_loot_type** setting to 1
2. Create a few porings or any other monster that "eat" items from the ground
3. Throw any item in the ground
4. See error, poring will consume it regardless of this setting being set to 0 or 1

**Expected behavior**
Monster shouldn't loot the item regardless of his MD_LOOTER mode when setting is set to 1

**System specs:**
 - OS: Windows 10
 - Hercules Version latest
 - Mode: pre-renewal
 - Packet version: 20190322
 - Client type: main

**Comment by skyleo** [comment]
Will fix, this is broken since 2004 btw.
