### ISSUE TITLE
the reason why all pull request return [X] <-- built failed

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2853]
```
	CC	itemdb.c
	CC	log.c
	CC	mail.c
	CC	map.c
	CC	mapreg_sql.c
	CC	mercenary.c
	CC	mob.c
map.c: In function ‘map_cell2gat’:
map.c:3010:12: note: parameter passing for argument of type ‘struct mapcell’ changed in GCC 9.1
 3010 | static int map_cell2gat(struct mapcell cell)
      |            ^~~~~~~~~~~~
	CC	npc.c
	CC	npc_chat.c
	CC	party.c
	CC	path.c
	CC	pc.c
	CC	pc_groups.c
	CC	pet.c
	CC	quest.c
	CC	refine.c
	CC	rodex.c
	CC	script.c
In file included from HPMHooking.c:234:
HPMHooking/HPMHooking_map.Hooks.inc: In function ‘HP_map_cell2gat’:
HPMHooking/HPMHooking_map.Hooks.inc:49114:5: note: parameter passing for argument of type ‘struct mapcell’ changed in GCC 9.1
49114 | int HP_map_cell2gat(struct mapcell cell) {
      |     ^~~~~~~~~~~~~~~
	CC	searchstore.c
	CC	skill.c
	CC	status.c
	CC	storage.c
	CC	stylist.c
	CC	trade.c
	CC	unit.c
```
someone needs to look into this, I'm not familiar how travis works

**Comment by AnnieRuru** [comment]
https://github.com/HerculesWS/Hercules/blob/1354b01c7a24e9ffd9ea570cbaec668721fc2a6c/src/map/map.c#L3010-L3019
wait, isn't the struct should have asterisk on it ?

```
static int map_cell2gat(struct mapcell *cell)
```

**Comment by 4144** [comment]
where you get this warning? ci not reporting it

**Comment by AnnieRuru** [comment]
1. click pull request section, a lot of them built failed
![](https://raw.githubusercontent.com/AnnieRuru/customs/master/screenshots/travis-ci_gcc%201.png)

2. check my PR, I saw the Travis CI said built failed
![](https://raw.githubusercontent.com/AnnieRuru/customs/master/screenshots/travis-ci_gcc%202.png)

3. click on the details, one of them said built failed
![](https://raw.githubusercontent.com/AnnieRuru/customs/master/screenshots/travis-ci_gcc%203.png)

4. scroll down and I found this
![](https://raw.githubusercontent.com/AnnieRuru/customs/master/screenshots/travis-ci_gcc%204.png)

**Comment by 4144** [comment]
many pull requests need rebase

**Comment by 4144** [comment]
you see in cpu type ``arm``? this cpu some times slow and need press retry. error timeout not related to any warnings or errors in code

and what you show on code, this is even not warning. it said for example if build server with one compiler, and plugin with different compiler version, plugin may not works in this method

**Comment by 4144** [comment]
this mean issue invalid
