### ISSUE TITLE
`Fruit Pom Spider` without the CARD name

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2896]
**Describe the bug**
try to list out all the orbs in hercules `item_db` database and found ...

**To Reproduce**
```sql
select * from item_db where type = 6 and right(name_japanese, 4) != 'card';
```

**Expected behavior**
```
{
	Id: 4670
	AegisName: "Fruit_Pom_Spider_Card"
	Name: "Fruit Pom Spider"
	Type: "IT_CARD"
	Buy: 20
	Weight: 10
	Loc: "EQP_WEAPON"
	Script: <"
		bonus2 bMagicAddEle,Ele_Fire,3;
		if (getrefine() > 6) bonus2 bMagicAddEle,Ele_Fire,5;
		if (getrefine() > 8) bonus2 bMagicAddEle,Ele_Fire,7;
	">
},
```
shouldn't the `Name:` field should be `"Fruit Pom Spider Card"` ?

**System specs (please complete the following information):**
 - OS: Windows 10 pro 64-bit
 - Hercules Version: latest (always pull latest git)
 - Packet version: 20190530
 - Mode: Renewal
 - Client type: [2019-05-30aRagexeRE](http://nemo.herc.ws/downloads/2019-05-30aRagexeRE/)
 - Branch: Main

**Plugins used or source modifications**
this is a database bug nothing to concern about plugin isn't it ?

**Additional context**

**Comment by Kenpachi2k13** [comment]
Confirmed. The "Card" suffix ist missing.
