### ISSUE TITLE
*rodex_sendmail script command attach with 0 item amount can't delete mail

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2897]
**Describe the bug**
when using script command `*rodex_sendmail`, send with item amount 0,
will cause the mail cannot retrieve the item or delete the mail

```sql
SELECT * FROM rodex_items;
delete from rodex_items where amount = 0 and id > -1;
```
I have to manually remove like this

**To Reproduce**
```c
prontera,155,185,5	script	kjsdfhks	1_F_MARIA,{
	rodex_sendmail getcharid(CHAR_ID_CHAR), "someone", "title", "body\r leg", 0, Apple, 0;
}
```

**Expected behavior**
this script command should put some check with item amount with 0

**System specs (please complete the following information):**
 - OS: Windows 10 pro 64-bit
 - Hercules Version: latest (always pull latest git)
 - Packet version: 20190530
 - Mode: Renewal
 - Client type: [2019-05-30aRagexeRE](http://nemo.herc.ws/downloads/2019-05-30aRagexeRE/)
 - Branch: Main

**Plugins used or source modifications**
.... nothing concern here

**Additional context**

**Comment by Kenpachi2k13** [comment]
Well... Again missing data evaluation.
Neither `BUILDIN(rodex_sendmail)` nor `BUILDIN(rodex_sendmail2)` checks the passed item amount for validity.
