### ISSUE TITLE
Problem on the display of monster HP, especially on the emperium and guardians

### ISSUE THREAD

**Issue by Daraen1** [HerculesWS/Hercules#2912]
In the server conf, especially here conf / map /battle/monster.conf on line 194 there is:
```
// Display some mob info next to their name? (Note 3)
// (does not works on guardian or Emperium)
// 1: Display mob HP (Hp / MaxHp format)
// 2: Display mob HP (Percent of full life format)
// 4: Display mob's level
show_mob_info: 2

```
It seems that the conf does not hide the hp of the emperium. I did not test for Guardians but I can already state that it does not work on the emperium, so I assume that it is the same for Guardians
**To Reproduce**

1. Go to 'conf / map /battle/monster.conf on line 194'
2. Change 'show_mob_info: 0'to 'show_mob_info: 2'
3. Use '@reloadbattleconf'and '@refresh' commands

**Screenshots**
![emperium](https://user-images.githubusercontent.com/75265726/101288737-750aef00-37f8-11eb-8b7a-eea1dc1cb6c1.png)
![conf](https://user-images.githubusercontent.com/75265726/101288749-8653fb80-37f8-11eb-9160-9cebe1d14269.png)

**System specs (please complete the following information):**
 - Hercules Version [e.g. v2018.04.18]
 - Mode: [pre-renewal]
 - Packet version: [20180418]
 - Client type: [2018-04-18bRagexeRE]((http://nemo.herc.ws/clients/2018-04-18bRagexeRE/))

**Additional context**
the problem is on the forum, but dev needs to take a look
https://herc.ws/board/topic/19184-how-to-remove-emperium-hp-job3_arch03
The expected behavior is that it hides the hp of the emperium despite the conf configured on 2

**Comment by AnnieRuru** [comment]
https://github.com/HerculesWS/Hercules/pull/2821

this one got stuck for a long time because we messed up a lot of code on differentiate MVP, boss monster and guardians etc
in short, the code on how to differentiate MVP, boss monster and guardians etc should be revamp completely

yeah, the code are mess up

**Comment by MrKeiKun** [comment]
For now https://github.com/HerculesWS/Hercules/pull/2821 has been merged.

**Comment by dastgirp** [comment]
Closing this, as per @MrKeiKun , this is merged and working fine now.
