### ISSUE TITLE
GTB blocks status effects if applied physically (stone curse, silence and coma)

### ISSUE THREAD

**Issue by patrickkuhlmann** [HerculesWS/Hercules#2913]
**Describe the bug**
Tarot Card "Death" doesnt work on someone using a GTB.
Metaller Card doesn't silence on someone using a GTB.
Stone Arrow + Earth Bow doesn't stone curse someone using a GTB.
Pest Card doesn't Stone Curse you when wearing GTB.

**Expected behavior**
it should work verified with aegis.

**Comment by Playtester** [comment]
Yeah, actually the way we implemented GTB on both rAthena and Herc is completely wrong. The only thing that's in Aegis (pre-re) is that if you are magic immune and the source skill is "magic" then you are immune to Freeze and Stone. No other status change has a basic immunity from GTB at all.

It could of course be that immunity is checked for specific skills, but we put everything in the status change code where we no longer have any info about the skill being used (we can't even check if the source is magic).

**Comment by Noooil** [comment]
yeah I saw this already so the easiest way would be remove gtb from status handling and check skills whichs status should be blocked by gtb so we have it all in one place in skill.c?

**Comment by Playtester** [comment]
Yes either this, or we do it like Aegis does for Freeze and Stone and push the information "isSpell" (on our emulator that would be type==magic) into sc_start.

We just need one spot where we have both the status change information and the type of skill and then could implement that properly.

**Comment by Playtester** [comment]
There are three skills that need to be verified:

256,9,6,16,0,0x1,0,5,1,yes,0,0x200,0,none,0,0x0,    CR_PROVIDENCE,Resistant Souls
383,0,6,4,0,0x3,-1,10,1,yes,0,0,0,weapon,0,0x0,    SN_WINDWALK,Wind Walker
2350,0,6,4,0,0x3,7:8:9:10:11,5,1,yes,0,0,0,none,0,0x0,    WA_SWING_DANCE,Swing Dance

If anyone could test these on Aegis (or official servers if you have a GTB card) that would be much appreciated.

If these skills are blocked by GTB they should probably be Magic skills.

**Comment by Playtester** [comment]
Fixed it on rAthena now: https://github.com/rathena/rathena/issues/5682

**Comment by skyleo** [comment]
This should be fixed since https://github.com/HerculesWS/Hercules/pull/3155
