### ISSUE TITLE
Tarot Card "The Chariot" ignores Chemical Protections

### ISSUE THREAD

**Issue by Noooil** [HerculesWS/Hercules#2914]
**Describe the bug**
Tarot Card "The Chariot" ignores Chemical Protections.

**To Reproduce**
1. FCP yourself
2. put some basic gears
3. cast tarot until chariot
4. see equip breaking

**Expected behavior**
Equip shouldn't break.

**Additional context**
Verified in aegis.

**Comment by Playtester** [comment]
Just a guess, but maybe you did get High Priestess before? It does remove FCP (verified on official servers).

**Comment by skyleo** [comment]
Confirmed the correct behavior for pre-Renewal aegis.

**Comment by Noooil** [comment]
Couldnt verify that it ignores it in latest herc thus gonna close this issue
