### ISSUE TITLE
Decarding not working properly

### ISSUE THREAD

**Issue by darhylism** [HerculesWS/Hercules#2922]
**Describe the bug**
Decarding the item does not trigger the Card OnUnequipScript & does not re-equip the said item after decard.

**To Reproduce**
1. Equip Eddga Card on any footgear
2. Decard the footgear with eddga card using Card Remover NPC
3. The Endure Status will NOT be removed and the shoes will not re-equip itself

**Expected behavior**
1. The Endure Status should be removed or any Card script on OnUnequipScript will trigger.
2. the decarded equipment should re-equip itself.

**System specs (please complete the following information):**
-OS: Windows 10 pro 64-bit
-Hercules Version: Release v2020.12.14 (latest)
-Packet version: 20190530
-Mode: Tested on both Renewal & Pre-renewal
-Client type: 2019-05-30aRagexeRE
-Branch: Main

**Plugins used or source modifications**
none

**Additional context**
none

**Comment by Daraen1** [comment]
I have the opposite problem, the ENDURE effect remained but I can equip the shoes.
I am using the latest version of hercules and EXE 2018-04-18bRagexeRE.
Even when I disconnect and reconnect, the endure effect remains active.
I own well `OnUnequipScript: <" sc_end SC_ENDURE; ">`
![eddga](https://user-images.githubusercontent.com/75265726/103309135-8d93b100-4a14-11eb-9bb2-49122c3d1a84.png)
![endure](https://user-images.githubusercontent.com/75265726/103309136-8e2c4780-4a14-11eb-80d0-89ab528086c6.png)

**Comment by darhylism** [comment]
> I have the opposite problem, the ENDURE effect remained but I can equip the shoes.
> I am using the latest version of hercules and EXE 2018-04-18bRagexeRE.
> Even when I disconnect and reconnect, the endure effect remains active.
> I own well `OnUnequipScript: <" sc_end SC_ENDURE; ">`
> ![eddga](https://user-images.githubusercontent.com/75265726/103309135-8d93b100-4a14-11eb-9bb2-49122c3d1a84.png)
> ![endure](https://user-images.githubusercontent.com/75265726/103309136-8e2c4780-4a14-11eb-80d0-89ab528086c6.png)
> 
> EDIT:
> To remove the endure effect, I have to put Eddga's card back in the shoes, equip them to my character and a unequip. Proceed like this, the OnUnequipScript is triggered.

ohh i typoed, my Endure Effect is also remaining after decarding & it does not auto re-equip the shoes as intended

**Comment by Daraen1** [comment]
It is normal that the script does not reattach the shoes, you must re-equipp them yourself after removing the card.

**Comment by Samuel23** [comment]
this commit: b946a096c2ef9dd660910ee4e391ec9fdf8c0dbf

card value is set to 0 before unequipping the item thus card unequip script was not run

**Comment by Daraen1** [comment]
@Samuel23 I already have this commit but the error is indeed the one we describe.

**Comment by Daraen1** [comment]
@Samuel23 I just tested and confirm that it works as expected now! Thanks for fixing the problem!
I validate your commit
