### ISSUE TITLE
Map Server Crash

### ISSUE THREAD

**Issue by Elijah0219** [HerculesWS/Hercules#2923]
**Describe the bug**
after updating the server to latest, Well map server is just crashing

**To Reproduce**
None, i just let players login and after some time it will crash

**Expected behavior**

**Screenshots**
Here's the gdb:
https://pasteboard.co/JGprNOQ.jpg

**System specs (please complete the following information):**
 - OS: [e.g. linux debian 9]
 - Hercules Version [e.g. v2020.12.14]
 - Mode: [pre-renewal?]
 - Packet version: [e.g. 20190322]
 - Client type: [e.g. main]

**Plugins used or source modifications**
disabled all plugins and still same

**Additional context**

**Comment by skyleo** [comment]
https://github.com/HerculesWS/Hercules/pull/2924
try applying that change to your repo and check if it fixes it.
