### ISSUE TITLE
Skill Weapon Type Bug

### ISSUE THREAD

**Issue by MrKeiKun** [HerculesWS/Hercules#2960]
**Describe the bug**
Skill fails when wearing Shadow Weapon and after removing it, it still fails unless requip weapon

**To Reproduce**
1. Use Guillotine Cross Job
2. Wear Angra Manyu
3. Use EDP Skill = Success
4. Wear Shadow Weapon(E.g: `S_Promotion_Weapon `)
5. Use EDP Skill = Fail
6. Remove Shadow Weapon(`S_Promotion_Weapon `)
7.  Use EDP Skill = Fail
8. Remove Angra Manyu
9. Use EDP Skill = Fail

Another Scenario
1. Use Guillotine Cross Job
2. Wear Angra Manyu
3. Use EDP Skill = Success
4. Wear Shadow Weapon(E.g: `S_Promotion_Weapon `)
5. Use EDP Skill = Fail
6. Remove Angra Manyu
7.  Use EDP Skill = Fail
8. Wear Angra Manyu again
9. Use EDP Skill = Success

**System specs (please complete the following information):**
 - OS: Windows 10 version 2004
 - Hercules Version: January 2021 Release
 - Mode: Renewal
 - Packet version: 2018 04 18
 - Client type: RE

**Comment by MrKeiKun** [comment]
Duplicate of https://github.com/HerculesWS/Hercules/issues/547

**Comment by johnlincon** [comment]
i have this issue,  is there a solution for it?
