### ISSUE TITLE
HT_ANKLESNARE stopped working after v2021.03.08 update

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2964]
**Describe the bug**
After update HT_ANKLESNARE breaks
- it does not hold or trap a mob.

**To Reproduce**
1. Just place a trap
2. Lure the monster to that trap

**System specs (please complete the following information):**
 - OS: [Centos 7x64]
 - Hercules Version [e.g. v2021.03.08]
 - Mode: [ pre-renewal ]
 - Packet version: [e.g. 20151029]
 - Client type: [main]

**Plugins used or source modifications**
none

**Comment by olsonpm** [comment]
`git revert "d1aeaaf43638b71e41ddd8180ffdb25e5667dd99^..6f43f6a23b0f2f5aab309eb3a4c230f440cec171"`

fixed the issue for me which reverts  PR #2942
