### ISSUE TITLE
Support for newer client's Guild Emblem and Rebellion Skill

### ISSUE THREAD

**Issue by aero012** [HerculesWS/Hercules#2974]
**Is your feature request related to a problem? Please describe.**
It's already been many years but Hercules still doesn't have Skill for Rebellion. 
Guild emblem doesn't work for 2019 clients or later.

**Describe the solution you'd like**
Guild emblem implementation for late 2019 clients or later, it would be good if Hercules will support it too just like rAthena.

**Describe alternatives you've considered**
Currently just letting players know the server doesn't have rebellion skill, and still its frustrating the class have everything but still no skills throughout the years. Alternative for guild emblem is to use 2018 clients which is currently good choice, but it would be better if can support the later clients as nowadays server tend to switch now to 2020 clients.

**Additional context**
Reference for guild emblem implementation for 2019 or later clients: https://github.com/rathena/rathena/pull/5144
Latest pull - https://github.com/rathena/rathena/pull/5731

**Comment by tlacson7** [comment]
this emu is slowly dying with less and less development seen.  Developers are gone busy with personal life maybe. So let's be patient and there is nothing we can do but to wait until they have time to look on things.

**Comment by aero012** [comment]
Yes, as for other missing contents I'm manually adding them or converting from rAthena to Hercules.

**Comment by 4144** [comment]
@tlacson7 all ro is slowly dying.

most https services already implemented but not public yet.
rathena sample look like incomplete implementation of emblems.

**Comment by Zarbony** [comment]
I would be happy too if it will implemented,,,
the rebellion class is so long broken...

and the emblem thing...
i had an conversation with 4144 about this :D

**Comment by MrKeiKun** [comment]
Whats left now with this issue is the HTTP Service part since I already merged Rebellion Skills.

**Comment by guilherme-gm** [comment]
I think this issue is now solved? we have got HTTP emblems and other HTTP features (not all of them, but this issue speaks specifically of guild emblems)

**Comment by guilherme-gm** [comment]
Closing this issue since we have Rebel changes (as keikun mentioned) and also have HTTP emblem support for a while now, if something is still missing in this part, please open a new issue detailing what is still missing.
