### ISSUE TITLE
Buff skills not applying when casted. 

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#2977]
**Describe the bug**
Almost all buff skill of acolyte doesnt work. the skill will be casted but no status change or animation/icon show

**To Reproduce**
1. Create a acolyte/priest
2. Use for example Blessing
3. It will cast but no actual change

**Expected behavior**
Should have animation/icon and change in status

**Screenshots**

**System specs (please complete the following information):**
 - OS: Ubuntu 18
 - Hercules Version: 202104050
 - Mode: Prere
 - Packet version: [e.g. 20160203]
 - Client type: Re

**Plugins used or source modifications**
Fresh Copy of Hercules

**Comment by Vaans** [comment]
Can confirm this, having the same result

**Comment by 4144** [comment]
issue confirmed
we working on fix

**Comment by MishimaHaruna** [comment]
This was fixed in #2979
