### ISSUE TITLE
item_rate_adddrop doesn't effect chain items

### ISSUE THREAD

**Issue by olsonpm** [HerculesWS/Hercules#2982]
**Describe the bug**
Cards which grant drops via `bAddMonsterDropChainItem` aren't affected by rates

**To Reproduce**
1. In `conf/map/battle/drops.conf` set `item_rate_adddrop` to 5000 (50x)
2. In `db/pre-re/item_chain.conf` set `ITMCHAIN_GEM` to 

```txt
ITMCHAIN_GEM: {
  Dark_Red_Jewel: 200
}
```

this will reduce the variability in the test where the base rate for Dark_Red_Jewel should be 2%

3. Set @autoloot, equip Jewel_Sword and kill a few porings.

**Expected behavior**
Dark_Red_Jewel should be gained 100% of the time

**System specs (please complete the following information):**
- OS: windows 10 version 10.0.18363 Build 18363
- Hercules Version v2021.03.08
- Mode: pre-renewal
- Packet version: 20200902
- Client type: sak

**Plugins used or source modifications**
n/a

**Additional context**
rates in `db/pre-re/item_chain.conf` are unaffected by item_rate_adddrop.  Personally I feel the configuration should be modified to encompass all rates via `src/map/itemdb.c -> itemdb_read_chains`.  This would mean the comment in `conf/map/battle/drops.conf` should be updated

current docs
```txt
// The rate adjustment for card-granted item drops.
```

suggested docs
```txt
// The rate adjustment for skill and script-granted extra drop bonuses
```

I'm willing to open a PR if that solution sounds good to you

**Comment by Jedzkie** [comment]
@olsonpm sure go ahead. Go make a PR for this issue.

**Comment by olsonpm** [comment]
thanks will do
