### ISSUE TITLE
Monster Ticket has no trade restrictions

### ISSUE THREAD

**Issue by olsonpm** [HerculesWS/Hercules#2985]
**Describe the bug**
Monster Ticket has no trade restrictions

**To Reproduce**
1. give yourself a ticket
```txt
@item Monster_Ticket
```

2. view the item in your inventory to confirm the client "item moves description" shows that you cannot trade, drop, etc

3. confirm you are able to drop the item

**Expected behavior**
You should not be able to drop a monster ticket

**System specs (please complete the following information):**
- OS: windows 10 version 10.0.18363 Build 18363
- Hercules Version v2021.03.08
- Mode: pre-renewal
- Packet version: 20200902
- Client type: sak

**Plugins used or source modifications**
n/a

**Additional context**
the bug is in item_db.conf, both re/pre-re I believe it's supposed to have the same "Trade" block as the prize medal

e.g.
```js
Trade: {
  nodrop: true
  notrade: true
  nocart: true
  nostorage: true
  nogstorage: true
  nomail: true
  noauction: true
}
```

**Comment by dastgirp** [comment]
The message depends on clientside itemmoveinfov5.txt.

**Comment by olsonpm** [comment]
The issue isn't the client file, it's the server settings.  That item is not supposed to be trade'able etc.

**Comment by dastgirp** [comment]
> The issue isn't the client file, it's the server settings. That item is not supposed to be trade'able etc.

Yes, but your issue is based on what client shows. The question is, are you using kro files? As that would have updated trade restrictions. If you base this issue on custom clientside (translation , etc), then it's possible that they might be old/skewed.

**Comment by olsonpm** [comment]
No my issue is based off the server settings.  To reproduce I show that the server settings are not in sync with the client.  The file in use is from data.grf from a recent update of the kro client.  The client file is correct

**Comment by dastgirp** [comment]
> No my issue is based off the server settings. To reproduce I show that the server settings are not in sync with the client. The file in use is from data.grf from a recent update of the kro client. The client file is correct

Ok, that's what I meant to ask, if you are using recent update or not.
Thank you for confirming you are using recent client.
