### ISSUE TITLE
Add two new npc shop types ZENY_BUY and ZENY_SELL

### ISSUE THREAD

**Issue by olsonpm** [HerculesWS/Hercules#2988]
**Is your feature request related to a problem? Please describe.**
I personally dislike the buy/sell dialog popping up every time I go to a trader npc since I assume most private servers have a lot of convenience traders right next to each other.  There is no reason for that dialog to pop up every time

**Describe the solution you'd like**
Two new npc shop types ZENY_BUY and ZENY_SELL.  In my implementation I have these from the perspective of the npc shops, e.g. BUY means the npc buys goods from the users.  When you set the type like `tradertype(NST_ZENY_SELL);`, this avoids the buy/sell prompt and goes straight to the selling list.

**Describe alternatives you've considered**
I did not consider any alternatives as this seems like a very straight forward solution and implementation

**Additional context**
I'm wondering whether this would be considered for a PR.  I have an implementation on my server but it doesn't follow the hercules styleguide and could be cleaned up.

I understand adding features has a long term maintenance cost associated and am totally fine with a simple "no thanks" heh

**Comment by olsonpm** [comment]
Somehow I forgot plugins existed.  Sorry for the noise.  If I want to share the implementation I will go that route instead.

**Comment by dastgirp** [comment]
@olsonpm just check callshop command.

**Comment by olsonpm** [comment]
I did see that but it felt weird to need a script npc separate from a trader, unless I misunderstood how that worked
