### ISSUE TITLE
wd.damage2 not applying targetside calculations / resists

### ISSUE THREAD

**Issue by muujiza** [HerculesWS/Hercules#3011]
**Describe the bug**
Unintended Offhand Pure Damage on SinX / Target Side card fix not applying to weapon damage 2

**To Reproduce**
1. Create a SinX and target character
2. @skillall on SinX
3. Equip 2x weapon on SinX
4. Unequip Main Weapon
5. On the target character, wear any kind of resist
6. Attack the target character, and notice that resist are not applying

**Expected behavior**
Resist should apply similar on how it is done on main hand attack

**Screenshots**
Actual behavior: https://youtu.be/OVG-PbnvEi0
Expected behavior: https://youtu.be/LaYLo5hzkjo

**System specs (please complete the following information):**
 - Hercules Version - April 2021 Release (no fix applied on June Release as well)
 - Mode: pre renewal
 - Packet version: HERCULES_VERSION 202011160

**Plugins used or source modifications**
N/A

**Additional context**
Actual behavior: https://youtu.be/OVG-PbnvEi0
Expected behavior: https://youtu.be/LaYLo5hzkjo

**Comment by muujiza** [comment]
simple code fix will fix the issue:

src\map\battle.c (line# 5733)

from
`     if ( tsd ) { //if player on player then it was already measured above`
`          wd.damage = battle->calc_cardfix(BF_WEAPON, src, target, nk, s_ele, s_ele_, wd.damage, (flag.lh ? 1 : 0), wd.flag);`
`     }`
to
`     if ( tsd ) { //if player on player then it was already measured above`
`          wd.damage = battle->calc_cardfix(BF_WEAPON, src, target, nk, s_ele, s_ele_, wd.damage, (flag.lh ? 1 : 0), wd.flag);`
`          if (flag.lh)`
`               wd.damage2 = battle->calc_elefix(src, target, skill_id, skill_lv, wd.damage2, nk, n_ele, s_ele, s_ele_, true, flag.arrow);`
`     }`

**Comment by muujiza** [comment]
simple code change will fix the issue:

src/map/battle.c (line # 5733)

```
	//Card Fix, tsd side
	if (tsd) { //if player on player then it was already measured above
		wd.damage = battle->calc_cardfix(BF_WEAPON, src, target, nk, s_ele, s_ele_, wd.damage, (flag.lh ? 1 : 0), wd.flag);
	}
```


to 

```
	//Card Fix, tsd side
	if (tsd) { //if player on player then it was already measured above
		wd.damage = battle->calc_cardfix(BF_WEAPON, src, target, nk, s_ele, s_ele_, wd.damage, (flag.lh ? 1 : 0), wd.flag);
		if (flag.lh)
			wd.damage2 = battle->calc_cardfix(BF_WEAPON, src, target, nk, s_ele, s_ele_, wd.damage2, (flag.lh ? 1 : 0), wd.flag);
	}
```

**Comment by skyleo** [comment]
shouldn't it be even:
```c
	//Card Fix, tsd side
	if (tsd) { //if player on player then it was already measured above
		wd.damage = battle->calc_cardfix(BF_WEAPON, src, target, nk, s_ele, s_ele_, wd.damage, 0, wd.flag);
		if (flag.lh)
			wd.damage2 = battle->calc_cardfix(BF_WEAPON, src, target, nk, s_ele, s_ele_, wd.damage2, (flag.lh ? 1 : 0), wd.flag);
	}
```
