### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Apidwalin** [HerculesWS/Hercules#3020]
**Describe the bug**

**To Reproduce**
[CODE_OF_CONDUCT.md](https://github.com/HerculesWS/Hercules/files/6871347/CODE_OF_CONDUCT.md)
[CONTRIBUTING.md](https://github.com/HerculesWS/Hercules/files/6871348/CONTRIBUTING.md)
[LICENSE.txt](https://github.com/HerculesWS/Hercules/files/6871349/LICENSE.txt)
[notices.md](https://github.com/HerculesWS/Hercules/files/6871350/notices.md)
[README.md](https://github.com/HerculesWS/Hercules/files/6871351/README.md)
[topics-todo.md](https://github.com/HerculesWS/Hercules/files/6871352/topics-todo.md)

3. Use skill '....'

**Expected behavior**

**Screenshots**

**System specs (please complete the following information):**
 - OS: [e.g. windows 10 version 1809, macOS 10.14]
 - Hercules Version [e.g. v2018.09.22]
 - Mode: [renewal or pre-renewal?]
 - Packet version: [e.g. 20101130]
 - Client type: [e.g. main, RE, zero, sak, ad]

**Plugins used or source modifications**
If you are using any plugins besides the ones that come bundled with Hercules,
please enumerate them here.

**Additional context**
Add any other context about the problem here. If the bug report is about a
crash, please attach the core/stack-dump or crash-log, if any.

**Comment by dastgirp** [comment]
Closing this issue. Please provide bug details if you experience any bugs
