### ISSUE TITLE
rodex_sendmail amount val stored from variable

### ISSUE THREAD

**Issue by MrKeiKun** [HerculesWS/Hercules#3027]
**Describe the bug**
PR #2901 seem to broke `rodex_sendmail` with the `amount` parameter. When you use a variable with a int value, it doesn't read the value on it.

**To Reproduce**
1. Create a basic script
2. Let's say `set(.@amt, 1);`
3. Use `rodex_sendmail` and add all parameters until item1's id/aegis name
4. Let's say item1's amount is `.@amt`
5.  Check map-server console

**Expected behavior**
it should allow usage of variable with int number stored in it

**Logs**
```
script:rodex_sendmail: Passed amount for item 1 is not a number!
```

**Test Script**
```
guild_vs3,54,56,3	script	RodEx Test	4_M_DWARF,{
	set(.@amount, 1);
	rodex_sendmail(
		getcharid(CHAR_ID_CHAR),
		"RodEx People",
		"RodEx Test Mail",
		"This is a RodEx Test Mail.",
		0,
		501, 
		.@amount
	);
	end;
}
```

**System specs (please complete the following information):**
 - OS: Win10 21H1
 - Hercules Version: latest
 - Mode: renewal
 - Packet version: 2019-05-30
 - Client type: main

**Comment by Mojacko** [comment]
The fix did not include rodex_sendmail2
