### ISSUE TITLE
Increase MAX_MOB_DB to support newest mobs w/ID 3,000+

### ISSUE THREAD

**Issue by jTynne** [HerculesWS/Hercules#303]
Because the last thousand entries to MAX_MOB_DB are reserved for clones, requesting src/map/mob.h to be increased at least to 5,000 rather than the current:
# define MAX_MOB_DB 4000

... to support mobs with ID range of 3,000-4,000 (Jitterbug, Faceworm Queen, etc).

**Comment by dastgir** [comment]
@MishimaHaruna

**Comment by jTynne** [comment]
I do wonder about this. Any progress?

**Comment by MishimaHaruna** [comment]
Queued in my list of things to do :x

**Comment by dastgir** [comment]
@jTynne 
This was done in https://github.com/HerculesWS/Hercules/commit/228a826dfdde3581f8e5d757ec458119d6079524

However, I keep this issue open as that causes serious problem of clone's being conflicted with JobID as warning says..

@hemagx @MishimaHaruna
