### ISSUE TITLE
Guild Skill Error Message [Guild's Glory]?

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#3042]
**Describe the bug**
When you open Guild Skill tab a error message is shown.

**To Reproduce**
1. Open Guild Window
2. Go to Guild Skill tab
3. Error will pop up.. after clicking OK. it seems there's a blank skill in the last list of skill list.

**Expected behavior**
should show guild's glory? 

**Screenshots**
https://imgur.com/lbbow7X

**System specs (please complete the following information):**
 - OS: Ubuntu 18
 - Hercules Version Stable 9-19-21
 - Mode: Pre-re
 - Packet version: 2016 02 03

**Comment by MrKeiKun** [comment]
Isn't that a clientside issue?
im using pre-re grf
![image](https://user-images.githubusercontent.com/4362134/133907877-7517f740-1c5b-44e8-bd8f-997fe27f8bf6.png)
looks fine.
though not sure if **guild storage expansion** should be on Pre-RE? :)

**Comment by Mojacko** [comment]
Maybe its the Guild Storage Expansion pack. Im using the hercules offline pack as base grf.
This has the same Client side. but different version of Hercules. this one is older
![image](https://user-images.githubusercontent.com/7709489/133924967-e46bc9b2-9492-464b-ac98-ac6816d6d343.png)

this one is the latest
![image](https://user-images.githubusercontent.com/7709489/133924986-900e76f8-f47c-4d2a-8684-f0879b5e51b3.png)

**Comment by MrKeiKun** [comment]
particular file `db/guild_skill_tree.txt`
```
10000,1,0,0,0,0,0,0,0,0,0,0	//GD_APPROVAL#Official Guild Approval#
10001,1,10000,1,0,0,0,0,0,0,0,0	//GD_KAFRACONTRACT#Contract with Kafra#
10002,1,10000,1,0,0,0,0,0,0,0,0	//GD_GUARDRESEARCH#Guardian Research#
10003,3,0,0,0,0,0,0,0,0,0,0	//GD_GUARDUP#Strengthen Guardians#
10004,10,0,0,0,0,0,0,0,0,0,0	//GD_EXTENSION#Guild Extension#
10005,0,0,0,0,0,0,0,0,0,0,0	//GD_GLORYGUILD#Guilds Glory#
10006,5,0,0,0,0,0,0,0,0,0,0	//GD_LEADERSHIP#Great Leadership#
10007,5,0,0,0,0,0,0,0,0,0,0	//GD_GLORYWOUNDS#Glorious Wounds#
10008,5,10007,1,0,0,0,0,0,0,0,0	//GD_SOULCOLD#Cold Heart#
10009,5,10006,1,0,0,0,0,0,0,0,0	//GD_HAWKEYES#Sharp Gaze#
10010,1,10000,1,10004,2,0,0,0,0,0,0	//GD_BATTLEORDER#Battle Command#
10011,3,10000,1,10004,5,10010,1,0,0,0,0	//GD_REGENERATION#Regeneration#
10012,1,10011,1,0,0,0,0,0,0,0,0	//GD_RESTORE#Restoration#
10013,1,10000,1,10002,1,10004,5,10010,1,10011,1	//GD_EMERGENCYCALL#Urgent Call#
10014,1,0,0,0,0,0,0,0,0,0,0	//GD_DEVELOPMENT#Permanent Development#
10016,5,0,0,0,0,0,0,0,0,0,0	//GD_GUILD_STORAGE#Guild Storage Expansion#
```

check if `10016` is there and not commented.

**Comment by dastgirp** [comment]
It's clientside issue. Your offline pack doesn't have #10016 skill in skilldescript.lub,

If you don't need this skill, you can comment out from guild skill tree.

Closing the issue.
