### ISSUE TITLE
Damage Reduction Calculation

### ISSUE THREAD

**Issue by Samuel23** [HerculesWS/Hercules#3045]
**Describe the bug**
There seems to be a bug in our damage calculation.

**To Reproduce**
For example: Poo Poo Hat should just give 10% damage reduction but when applied, it seems to give more than 10%. So I made a test between hercules and rathena

So in the test both novice without poo poo hat at first test damage of asura strike then equipped poo poo hat after for the 2nd test damage

Rathena:
![screenrAthena001](https://user-images.githubusercontent.com/4675631/134755954-4c3e06f8-dcc2-412f-b34b-7a724312f353.jpg)

- 23,797 2nd damage with poo poo hat which is exactly 10% deduct from the first damage without the poo poo hat equipped

Hercules:
![InkedscreenFanfic Ragnarok Onl065_LI](https://user-images.githubusercontent.com/4675631/134756084-7474ee01-baa3-4644-b51a-b8c5af0202e1.jpg)
- 17,676 is way more than 10% deduction here from the first damage

**Expected behavior**
Exact calculation

**System specs (please complete the following information):**
 - OS: windows 10
 - Hercules Version [e.g. v2021.09.01]
 - Mode: pre-renewal
 - Packet version: 20180601
 - Client type: main

**Plugins used or source modifications**
Clean herc and rathena used

**Comment by MrKeiKun** [comment]
So this report is regarding `bSubRace` and Pre-Renewal right?
But i tested it on my side, looks perfectly fine...
![image](https://user-images.githubusercontent.com/4362134/134815286-0401c614-cc19-419b-90d7-dbe588fc7072.png)

I even applied debugs on `battle_cardfix`
```
[Debug]: Pre-Damage: 1600
[Debug]: Post-Damage: 1600
[Debug]: Pre-Damage: 1600
[Debug]: Post-Damage: 1440
```

**Comment by Samuel23** [comment]
Sorry very late reply here, i think i messed up my copy of clean hercules in this testing, retested it and it works fine. Sorry for the trouble.
