### ISSUE TITLE
Weird truncation error in DASDPDSU

### ISSUE THREAD

**Issue by electric-socket** [HerculesWS/Hercules#3089]
**Describe the bug**
Text documents extracted from a PDS and converted to ASCII using DASDPDSU is strangely truncated on the right at column 72. I am not sure if this would only occur in the Windows version of DASDPDSU.

**To Reproduce**
1. Have a copy of the TK4 MVS release.
2. Start up two MS-DOS windows (or open a terminal window in Linux).
2. Start Hercules in unattended mode, or run it as a background job in shell.
3. Switch to DOS window or shell command line.
4. Fire up a 3270 terminal
5. Logon to TK4, I used HERC02 as I don't need privileges (so you can verify what happens).
6. In the TSOAppls menu system, select 2 ENTER 2 ENTER (RPF, Edit)
7. On the EDIT screen, where it says Member= type **PCROSS** and press tab
8. in the field Dsname= type **PASCAL.PASSAMP** and press tab
9. in the field Volume= type **PUB000** and press enter
10. When the listing appears, use the F8 key to scroll to the next page until it reaches where it is showing line 173 (if you go too far, press F7 to page up).
11. When you can see that line, type **SCR** and push enter; the editor will scroll right.
12. The last few characters of this line, starting at byte 63, are   **\ (\*PARENTHESE\*\) (\*]**  (_sic_) with the "]" appearing right on column 80. The truncation occurs before this line, but it's much more obvious at this point.
13. Press F3 to exit back to the previous menu.
14. You'll be back to the Member= field, erase the previous item, type in **RNFDOC** and push enter
15. In the editor, page down to where line 53 occurs.
16. Type **SCR** to scroll right, then push enter.
17. The last few words on this line are **for the Cyber similiar to the RUNOFF**
18. Hit F3 several times until you're at READY.
19. You're finished with the terminal, now you need the DOS window (shell prompt)
20. move to the directory where the hercules directory is.
21. make a temporary directory and enter it.
22. type in: **./dasdpdsu <location_of_dasd_file_pub000.240> pascal.pascmp ascii** and press enter.
23. Use a text editor to look at files **pcross.mac** and **rnfdoc.mac**
24. Scroll to line 173 of **pcross.mac** . Notice how the line ends, with **\ (\*PARENTHE**
25. Now go to line 53. The line ends with **for the Cyber similiar to the** and everything after the e in "the" is truncated. It's even more obvious on further lines down the page, everything after column 72 is lost.

**Expected behavior**
Files should not be truncated.

**Screenshots**

**System specs (please complete the following information):**
 - OS: Windows 10 Pro version 20H2
 - Hercules Version 3.07 [Built  Apr 23, 2010]-  No source modifcations or plugins
 - 
**Additional context**
That's about it.
 - - - -
![DASDPDSU_Truncate2](https://user-images.githubusercontent.com/72189474/143729688-c192178a-79fb-4b01-b0f3-9bf8c36701b6.png)

![DASDPDSU_Truncate1](https://user-images.githubusercontent.com/72189474/143729689-60fe0867-8435-4787-b71c-67650072e78f.png)

![DASDPDSU_Truncate4](https://user-images.githubusercontent.com/72189474/143730303-1eb6c881-360c-44e0-b365-91c7f2523400.png)
![DASDPDSU_Truncate3](https://user-images.githubusercontent.com/72189474/143730304-76a7c9bd-0f8e-4967-a8a8-2b12b952e397.png)

**Comment by dastgirp** [comment]
Commented on wrong project. Closing this issue.
