### ISSUE TITLE
Mob Skill DB structure change

### ISSUE THREAD

**Issue by kisuka** [HerculesWS/Hercules#309]
Any thoughts on changing the structure of mob skill db to not be so redundant and to make use of constants?

So instead of this for example:
1001,SCORPION@NPC_FIREATTACK,attack,186,1,2000,0,5000,yes,target,always,,,,,,,,

it would be:
SCORPION,attack,NPC_FIREATTACK,1,2000,0,5000,yes,target,always,,,,,,,,

**Comment by EPuncker** [comment]
I agree as well lol

**Comment by Asheraf** [comment]
done in be90f6c69b6ac54ee83878f603cb9bf733d29d04
