### ISSUE TITLE
Map-server crashes without gdb log

### ISSUE THREAD

**Issue by carloshenrq** [HerculesWS/Hercules#3111]
**Describe the bug**

Hi guys, i've received this gdb stack error when i do `bt full`

```
Thread 1 "map-server" received signal SIGSEGV, Segmentation fault.
0x00002d000001d645 in ?? ()
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-164.el8.x86_64 libgcc-8.5.0-4.el8_5.x86_64 mariadb-connector-c-3.1.11-2.el8_3.x86_64 openssl-libs-1.1.1k-5.el8_5.x86_64 pcre-8.42-6.el8.x86_64 zlib-1.2.11-17.el8.x86_64
(gdb) bt full
#0  0x00002d000001d645 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb)
```

Have anyone else received this?

**Comment by 4144** [comment]
you not have any debug info.
probably hercules too old or used wrong configure or make files.
by default hercules add many debug info.

try use latest hercules and build it normally. then if it crash it may show correct stack.
