### ISSUE TITLE
mob_item_ratio affected by SC_CASH_RECEIVEITEM 

### ISSUE THREAD

**Issue by Vaans** [HerculesWS/Hercules#3151]
**Describe the bug**
Items that increase the item drop rate are affecting mob_item_ratio, for example bubble gum

**To Reproduce**
1. Go mob_item_ratio.txt
2. Assing a fixed rate drop to a item, example jellopy with 2% rate
3. Use SC_CASH_RECEIVEITEM with 200 or 300
4. The item drop is being double.

**Expected behavior**
As i know, the intention for this feature is to cap the item drop rate, no matter what bonus did you received

**Screenshots**
N/A

**System specs (please complete the following information):**
 - OS: Centos 7
 - Hercules Version v2022.06.01
 - Mode: pre-renewal
 - Packet version: 20190530
 - Client type: sak

**Plugins used or source modifications**
N/A

**Additional context**
N/A

**Comment by MrKeiKun** [comment]
hmm based on the file itself.

```
// Specific Item Drop Ratio Database
// Overrides for global item_rate* values from conf/battle/drops.conf
```
