### ISSUE TITLE
RODEX Bug (Items not reaching Player and Disappearing from mail)

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#3186]
**Describe the bug**
Rodex mark the mail as you receive the Item even if you did not actually get the item. And making the Mail Item gone.

**To Reproduce**
1. Get a about 93~96 items in your inventory
2. Must have about 20 Mail with items.
3. Try "retrieve all"
4. You will only get few items but the Items from Mail is gone too.

**Expected behavior**
Should not remove items from the mail if the player did not successfully receive the Items.

**Screenshots**
This is the screenshot of Bug.
I have 20 Mail with each having 1 Egg Item. 
[Image 1](https://i.imgur.com/alimy8K.png)
You can see in Image 1 that I only get 7 Eggs but in mail all Item is gone even though the Box icon is still showing.

I tried to Relog my char and open mail
[Image 2](https://i.imgur.com/tyhD7YR.png)

You can see that all mail have mark as Item received but my inventory still has only 7 Eggs.

**System specs (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Hercules Version v2022.12.07
 - Mode: Pre-renewal
 - Packet version: 2019-06-05fRagexe
 - Client type: [main]

**Plugins used or source modifications**
No Plugin Loaded

**Comment by Mojacko** [comment]
The same issue with [3009](https://github.com/HerculesWS/Hercules/issues/3009)

**Comment by dastgirp** [comment]
This happens because 
1. There's no inventory space left
2. Weight exceeds

There needs to be additional check while doing retrieve all to ensure there's no loss.

**Comment by Mojacko** [comment]
This only happens to "Retrieve all" button. but if trying to retrieve with single mail the weight checking is correct.
