### ISSUE TITLE
Storm Gust counter (sg_counter) does not refresh on Mob death

### ISSUE THREAD

**Issue by AcidMarco** [HerculesWS/Hercules#3196]
**Describe the bug**
Pre-renewal. When you are using Storm Gust skill on natural spawned monsters and the monsters die cause of Storm Gust hits, the counter (sg_counter) for this mob does not refresh. After respawn the monster can be freezed in 1-2 hits.

**To Reproduce**
1. Kill monsters with Storm Gust on one map
2. After first respawn they will start freeze in 1-2 hits

**Expected behavior**
As per mechanics the status has to be changed only after 3 hits.
Counter should be refreshed after monster death.

**Video**
I've create natural spot with script:
prt_in,33,111,0,0	monster	AGAV	1769,5,0,0,0
See the video below, on the 3rd hit the monsters die,
But after respawn the timer is not refreshed, and they
freeze after first Storm Gust skill.
https://youtu.be/-OEMXYlKLnw

**Additional context**
Amendments in 'skill.c' do not solve the issue.
I have found counter refresher in 'status.c', but seems it only work for BL_PC.

**Comment by Timokha7** [comment]
Tried many options in different variations. Have no clue how to fix it. I will highly appreciate if someone can find the solution based on source knowledge. All my nub attempts have failed.
