### ISSUE TITLE
I dont know how to coonect to server?

### ISSUE THREAD

**Issue by Boomgeek** [HerculesWS/Hercules#3213]
I cannot to find the client.exe and how to modify the client for point to my server 

Please help thank you 🙏

**Comment by csnv** [comment]
Please refer to the [forums](https://board.herc.ws/) for this type of questions. I also suggest you check both the [wiki](https://github.com/HerculesWS/Hercules/wiki) and the [archived wiki](https://wiki.herc.ws/wiki/Main_Page)

This page is for the project issues only.
