### ISSUE TITLE
Flee reduction doesn't match official/iRO Classic Wiki

### ISSUE THREAD

**Issue by Asonael** [HerculesWS/Hercules#3273]
**Describe the bug**
Flee reduction from multiple monsters is not calculated correctly to match official (via iRO wiki classic)

https://irowiki.org/classic/FLEE

Skill bonuses should be outside of the reduction of flee.
Expected behavior (from above): Actual Flee = Skill Bonus + [Level+ AGI + Item Bonus] * [1 - ((Mobs -2) * 0.1)]
Behavior on Hercules: Actual Flee = [Skill Bonus + Level+ AGI + Item Bonus] * [1 - ((Mobs -2) * 0.1)]

**To Reproduce**
Tested on 13 Kukre with 102 required FLEE for 95% dodge, reducing flee to 1. Every attack hits except lucky dodges. Should have 41 flee and dodge over 1/3rd of the attacks if Improve Dodge was calculated outside of flee reduction.

![image](https://github.com/HerculesWS/Hercules/assets/33134394/7c858c0a-00d1-4af5-a63d-f536f85762a0)

**Comment by csnv** [comment]
@skyleo is this something you can check in _your sources_?
