### ISSUE TITLE
Rogue Skill is Reset after copying Backstab from another Rogue

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#3289]
**Describe the bug**
Skills of rogue get reset after plagiarism acquire backstab from another rogue (not all skill is reset but most of it) and skill point is not even increase, making it incomplete skill or not in sync with your current job level

**To Reproduce**
1. Use 2 Rogue with atleast 6 pts to plagiarism. Rogue A will have backstab lv4 and rogue b will have backstab lv5
2. Use Level 5 backstab on Rogue A.
3. Reconnect the Rogue A.
4. You will notice your skill tab has many missing skill

**Expected behavior**
It should not reset the skills and messed up the job level to skill points

**Screenshots**
![image](https://github.com/HerculesWS/Hercules/assets/7709489/1d4f28af-b413-4aab-a645-fd1310ecee6d)

**System specs (please complete the following information):**
 - OS: [e.g. windows 10 version 1809, macOS 10.14]
 - Hercules Version [latest as of April 12, 2024]
 - Mode: [pre-renewal]
 - Packet version: [e.g. 20211117]
 - Client type: [RE]

**Plugins used or source modifications**
No plugin or modification in source except pre-renewal and client version

**Comment by Mojacko** [comment]
The bug also triggers on envenom. if you have higher level envenom and copied lower level (because of low level plagiarism) you will get lower level envenom and then try to use it. then copy new skill then reconnect. the envenom will get reset including all the skill pre-req envenom.

**Comment by skyleo** [comment]
Will submit a tested fix in the following days.
