### ISSUE TITLE
Char Server Crash from Guild Storage(?)

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#3301]
**Describe the bug**
I don't know what is causing it, but I got this message and then my char server crashed.
```
[Fatal Error]: WFIFOSET: Packet 0x3818 is too big. (len=69541, max=65535)
```

**To Reproduce**
Not sure

**Expected behavior**
Not crash

**Screenshots**

**System specs (please complete the following information):**
 - OS: [CentOS 8]
 - Hercules Version [v2024.05.04]
 - Mode: [pre-re]
 - Packet version: [e.g. 20160113]
 - Client type: [main]

**Plugins used or source modifications**
Have plugins but none are affecting guild storage.

**Additional context**

**Comment by sinju92** [comment]
are u change max item storage ?

**Comment by bWolfie** [comment]
MAX_GUILD_STORAGE is 600. I just discovered that some guild on my server somehow got more than 600 item in it.

**Comment by bWolfie** [comment]
Sorry, can close this ticket. I think it's okay now. I deleted some items from the gstorage and it should be fine.
