### ISSUE TITLE
Pre Renewal Grimtooth EDP

### ISSUE THREAD

**Issue by MatiasSW** [HerculesWS/Hercules#370]
As far as I remember, Grimtooth was affected by EDP on Pre Renewal, however on Hercules it is disabled on pre-renewal, not sure if someone got confused or this was a recent update? (Couldnt find much)

If anyone can confirm wether this is indeed a bug or a recent change it'd be great :)

https://github.com/HerculesWS/Hercules/blob/master/src/map/battle.c#L4874

**Comment by kyeme** [comment]
Please tag as fixed
https://github.com/HerculesWS/Hercules/commit/2ee1f3292ec7d7fe212bbac6bcab3ca88aae758e
