### ISSUE TITLE
Map server crash when new char with ALL_SKIL perm logs in

### ISSUE THREAD

**Issue by MatiasSW** [HerculesWS/Hercules#371]
So map server crashes when I login with all_skills, because of this: https://github.com/HerculesWS/Hercules/blob/master/src/map/clif.c#L4901

Pretty sure that sd->status.skill[id].lv was meant to be sd->status.skill[idx].lv

**Comment by MishimaHaruna** [comment]
Fixed in 7c8b7241066c7e0eb4e46d2a837253129ed886f7
