### ISSUE TITLE
Item Database Bugs

### ISSUE THREAD

**Issue by trickyloki3** [HerculesWS/Hercules#468]
Item ID **12191** uses invalid SC_ASPDPOTION0 and SC_SPEEDUP0 constants
> Fix
> sc_start SC_ATTHASTE_POTION1,600000,4;
> sc_start SC_MOVHASTE_HORSE,600000,0;

Item ID **12696** uses all the invalid SC_*FOOD constants
> Fix
> sc_start SC_FOOD_STR,10000,3;
> sc_start SC_FOOD_VIT,10000,3;
> sc_start SC_FOOD_INT,10000,3;
> sc_start SC_FOOD_DEX,10000,3;
> sc_start SC_FOOD_AGI,10000,3;
> sc_start SC_FOOD_LUK,10000,3;

Item ID **12746** missing semicolon on for the first autobonus script
> Fix
> **autobonus "{bonus2 bAddRace,RC_Boss,5;}",10000,1800000;**
> autobonus "{bonus2 bAddRace,RC_Angel,5;}",10000,1800000;
> autobonus "{bonus2 bAddEle,Ele_Holy,5;}",10000,1800000;

Item ID **12746** invalid SC_INCFLEE2 constant or not defined in const.txt
> Fix
> sc_start SC_PROTECT_MDEF,1800000,5;
> **sc_start SC_INCFLEE,1800000,10;**

Item ID **13272** invalid SC_CHANGEUNDEAD constant
> Fix
> sc_end SC_SILENCE;
> sc_end SC_BLOODING;
> sc_end SC_POISON;
> sc_end SC_CURSE;
> sc_end SC_ORCISH;
> **sc_end SC_PROPERTYUNDEAD;**
> heal 500,0;

Item ID **18601** has duplicated bonuses; bMagicAddRace
> Fix
> bonus bMdef,5;
> if(getrefine() > 5 && getrefine() <= 12) 
> 	bonus2 bMagicAddRace,RC_DemiHuman,(getrefine() - 5);
>     <REMOVED>
> if(getrefine() > 12) 
> 	bonus2 bMagicAddRace,RC_DemiHuman,7;
>     <REMOVED>

My compiler output:
>[warn]: src/script.c;translate_status;2420; failed to search const SC_ASPDPOTION0 in item 12191.
>[warn]: src/script.c;translate_status;2420; failed to search const SC_STRFOOD in item 12696.
>[warn]: src/script.c;evaluate_expression_recursive;3290; invalid token '}' in item 12746.
>[warn]: src/script.c;evaluate_expression;3026; failed to evaluate '5 } player' in item 12746.
>[warn]: src/script.c;translate_status;2420; failed to search const SC_INCFLEE2 in item 12752.
>[warn]: src/script.c;translate_status_end;2562; failed to search const SC_CHANGEUNDEAD in item >13272.
>[warn]: bonus duplicated on item id 18601; in block 0 and 0; see dump.txt.
>[warn]: bonus duplicated on item id 18601; in block 0 and 5; see dump.txt.
>[info]: compiled all 5048 items in 1 seconds.

**Comment by malufett** [comment]
@trickyloki3 
Can you do pull request?
Thank you and your effort is much appreciated.

**Comment by zackdreaver** [comment]
18601 should follow KRO desc not IRO :
MDEF +5
MATK +5%
Refined to +6, every refine increase magic damage by 1% and reduce Physical damage from Demihuman monster.

there are no limitation of refine level in description.
http://www.divine-pride.net/database/item/18601

**Comment by zackdreaver** [comment]
SC_INCFLEE2 is not exist,
maybe @malufett can add it in his current work?

btw i will add this in my next PR.

**Comment by malufett** [comment]
@zackdreaver SC_INCFLEE2 is SC_PLUSAVOIDVALUE...:D

**Comment by dastgir** [comment]
Argg.. Too many confusions

**Comment by zackdreaver** [comment]
lol how i suppose to know that

Btw, off topic,
@malufett 
i see some headgears with loc: 1 (which is low)
have script value = bonus bUnbreakableHelm,0;
will this make the upper headgears Indestructible?
or just the lower with this value?

**Comment by malufett** [comment]
@dastgir 
lol..but its easier if its about to covert coming from aegis...

@zackdreaver 
based on the src it protects EQP_HEAD_LOW, EQP_HEAD_MID, EQP_HEAD_TOP...

**Comment by zackdreaver** [comment]
ok i understand now,
so its safe to put that script.
thank you
