### ISSUE TITLE
Professor Job clone causes map-server crash

### ISSUE THREAD

**Issue by lordganja** [HerculesWS/Hercules#492]
Can someone reproduce this? Whenever a professor clone started casting skills it causes map server to crash. I can't specify what skill really causes the mapcrash. just try to use @evilclone and let the clone start using its skills.

**Comment by magimagica** [comment]
You should post this in bug tracker not this section,
read ind's post here
http://hercules.ws/board/topic/3731-issues-page/

**Comment by MishimaHaruna** [comment]
Recently, we started to silently accept bugs here as well, even though it's not written anywhere. (I personally find this bugtracker easier to use than the one integrated in the forums). Not all developers monitor the bugs here though, so your mileage may vary. I'll take care of this one as soon as I have tim, unless someone else does before.

**Comment by dastgir** [comment]
@lordganja Can't reproduce, possibly provide gdb report? or some more way so we can reproduce it?

**Comment by lordganja** [comment]
@magimagica Sorry, I thought it was supposed to be posted here. :)

@dastgir My bad, I think it's because of my custom mod on dispel skill, after I fix some and update it to the latest it works well now.. No more mapcrashes. Sorry for that. Closing this issue. .

**Comment by dastgir** [comment]
@lordganja
No problem, also issues can be posted here, it's accepted here too..

**Comment by lordganja** [comment]
Okay. Thanks @dastgir  :)
