### ISSUE TITLE
Incorrect use of Class?

### ISSUE THREAD

**Issue by Streusel** [HerculesWS/Hercules#504]
Should <Class>_Figure use Class or BaseClass?
Example item id 2770: if(Class==Job_Thief) bonus bAspdRate,3;
For those that need reminding, Class only checks for the actual class while BaseClass checks if the predecessor originally was of such a class, in this case thief.

**Comment by MishimaHaruna** [comment]
The Aegis special.sc (at least the one I could get my hands on) uses `GetPureJob`, which I believe to be equivalent to `BaseClass` (since it's used by i.e. `Wild_Rose_Card`).
The equivalent to `Class` would have been, instead, `get[VAR_JOB]`, to my understanding.

**Comment by Streusel** [comment]
Fixed in e4767041e80ee0b8ec567524f578ae49689b7938, closing issue.
