### ISSUE TITLE
Kafra Function

### ISSUE THREAD

**Issue by Streusel** [HerculesWS/Hercules#519]
I'm suggesting we use getarraysize(@wrpD$) instead of using a hardcoded value (magic number) in this line: https://github.com/HerculesWS/Hercules/blob/master/npc/kafras/functions_kafras.txt#L318
If anyone ever decides to add more teleport locations, they'll be surprised and it'll take a while to figure out what is supposedly going wrong.

**Comment by dastgir** [comment]
getarraysize(@wrpC$)
Since if we get arraysize of @wrpD$ , the cancel button will be left behind
