### ISSUE TITLE
Quest Skill using Error in Map-server

### ISSUE THREAD

**Issue by jump-ocz** [HerculesWS/Hercules#522]
Carzy Upload
Change Cart
Cart revolution
http://www.img.in.th/images/FaCip.jpg

**Comment by MishimaHaruna** [comment]
Compiled as renewal or pre-renewal? What do you have at line 179 of skill.c?

**Comment by jump-ocz** [comment]
renewal  i change only  mmo.h to packet 20150513  and compiled  
and change quest_skill_learn: yes   after login with novice  i'm use GM command 
1.@job 4076 
2.@blvl 175
3.@jlvl 60

and test skill 
Carzy Upload
Change Cart
Cart revolution

in game is normal not have any error but in map-server  having  error  like a pics on top

**Comment by MishimaHaruna** [comment]
This should be fixed as of bba4ce885b0667f92e0b3f2a26759059317a4c3d
