### ISSUE TITLE
Auction House can't talking with NPC

### ISSUE THREAD

**Issue by jump-ocz** [HerculesWS/Hercules#523]
Action House can't talking with NPC

http://www.img.in.th/images/9I60y3UhNb.jpg

**Comment by EPuncker** [comment]
maybe yout client doesn't support it, or you have not enabled it in features.conf

**Comment by emistry** [comment]
did you enabled this ??
[conf/battle/feature.conf#L29](https://github.com/HerculesWS/Hercules/blob/master/conf/battle/feature.conf#L29)
```
// Auction (Note 1)
// Feature became unstable on clients 2012 onwards (exact date not known),
// it has been fixed on clients 2013-05-15 onwards however.
feature.auction: off
```
