### ISSUE TITLE
Amatsu Dungeon Quest

### ISSUE THREAD

**Issue by Streusel** [HerculesWS/Hercules#525]
https://github.com/HerculesWS/Hercules/blob/master/npc/quests/quests_amatsu.txt
According to iRO it gives experience, I can't find any indication that the quest gives exp in our version.
http://irowiki.org/classic/Amatsu_Dungeon_Entrance_Quest
http://irowiki.org/wiki/Amatsu_Dungeon_Entrance_Quest
Are we missing something?

**Comment by MishimaHaruna** [comment]
Yep, I've heard some mentions of that as well. I'm not really sure whether it's in all official servers or only iRO. The script that comes with the 2013 ASB release doesn't have it:

```
				dropitem Fox_Tail 1
				getitem Lord's_Passable_Ticket 1
				setitem jap_mono 6
				dialog "[Ishida Yoshinaga]"
				dialog "Although it's nothing really precious,"
				dialog "I think it might be useful to you."
				dialog "You can sort out the details with my follower 'Jyuro'."
				close
```

**Comment by dastgir** [comment]
Neither I can find it on aegis I have(ep14.2)

**Comment by MishimaHaruna** [comment]
Has anyone tested it in any official servers just to make sure the irowiki info matches iRO at least? (and that doesn't match the other servers)

**Comment by dastgir** [comment]
Closing this, it seems it is iRO specific...
