### ISSUE TITLE
Temporal Boots & Enchants

### ISSUE THREAD

**Issue by ernestfegarido** [HerculesWS/Hercules#529]
no npc for this? :)

**Comment by Streusel** [comment]
Do you have any more information other than their name?

**Comment by emistry** [comment]
###### Item Bonus not available
http://irowiki.org/wiki/Enchantment#Temporal_Boots_.28Old_Glast_Heim.29_Enchants

**Comment by Asheraf** [comment]
this is already done

**Comment by hemagx** [comment]
Fixed in 114767ca4d5df9268b87f5d4be0836390209698f
