### ISSUE TITLE
Eden Quest Level 100-110

### ISSUE THREAD

**Issue by tsan79** [HerculesWS/Hercules#538]
When you do the Eden quest for for level 100-110, you may level up to beyond level 110.
And when that happens, it will display the following message. You're unable to close the box, leaving you only to relog, or use butterflywings.

![screenwoonrorenewal395](https://cloud.githubusercontent.com/assets/11470341/8014313/cc31d8cc-0c23-11e5-99fd-7c66e236c7dd.jpg)

Notes: We're 2 weeks behind on Hercules updates.
Hope I'm doing this issue things right.

Reference: https://github.com/HerculesWS/Hercules/blob/2944ddc520ba7035ce55ab3665c0d27c094a8fea/npc/re/quests/eden/100-110.txt

-SH

**Comment by MishimaHaruna** [comment]
`S_Hunting` seems to be missing a `return`.
