### ISSUE TITLE
Missing item in Gift Box

### ISSUE THREAD

**Issue by Streusel** [HerculesWS/Hercules#543]
It appears there might be 1 or 2 items missing in the https://github.com/HerculesWS/Hercules/blob/master/db/pre-re/item_group.conf file.
Gift Box (665) and Gift Box (644) is supposed to for instance have an Emperium.
Same appears to apply for the re db.

**Comment by Jedzkie** [comment]
@Streusel i confirm in Gift Box (644), but in 665 i can't confirm because i check in aegis and can't found emperium in Gift Box (665)
