### ISSUE TITLE
pet feed clients crashes bugs

### ISSUE THREAD

**Issue by jump-ocz** [HerculesWS/Hercules#545]
- @makeegg poring
- @hatch
- @item 531  (note: only 1)

if has only 1 pet food can feed no crashed but have one message "Feeding the pet. 13090996 '(null)' remaining"
If you have pet feed more than 1 client crashes
i testing on poring pet

**Comment by dastgir** [comment]
If you are using client >= 20141022, then it's a known issue.
May you tell which client you use?

**Comment by kyeme** [comment]
Client side issue:
on msgstringtable.txt

Find:
Feeding the pet. %d '%s' remaining#
 
Replace to:

Feeding the pet. %s '%d' remaining#

**Comment by dastgir** [comment]
Client side issue
