### ISSUE TITLE
New item script for reducement based on Monster's element (not elemental attack)

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#548]
Based on : 
http://herc.ws/board/tracker/issue-7769-tatacho-card-effect/

Hercules need new script for this reducement.
List items that affected : 
2684 Ring_Of_Wind
4442 Tatacho Card
4443 Aqua Elemental Card
4444 Draco Card
4445 Luciola Vespa Card
4447 Centipede Card
4448 Cornus Card
4449 Dark Shadow Card
5508 Shark_Hat
5509 Sting_Hat
5593 K_Rabbit_Bonnet
15008 Flame_Sprits_Armor__

**Comment by AnisotropicDefixation** [comment]
Also need AutoSpellOnSkill for offensive heals.

**Comment by zackdreaver** [comment]
@AnisotropicDefixation
You should create new thread for your issue

**Comment by zackdreaver** [comment]
*bumps
@MishimaHaruna @4144 @malufett 
anyone?

**Comment by iRagno** [comment]
This has been already introduced on rAthena:

https://github.com/rathena/rathena/commit/5a4cd7426ee67bc87a845651bedc55bce2ff4487

Would be possible to solve this?
