### ISSUE TITLE
Icewall and dead cells.

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#549]
If a piece of wall is destroyed, it will leave a permanent dead cell.

**Comment by MishimaHaruna** [comment]
This is unfortunately a known issue. To my understanding (the issue has been around for much longer than I), it's entirely clientside (the client forgets to mark those temporarily unwalkable cells as walkable again), and it can't be fixed until the client is fixed. If there's something I'm not aware of, please reply here and we'll reopen the issue.

Reference:
- http://herc.ws/board/tracker/issue-38-icewall-bugs/ (2007)
- http://herc.ws/board/tracker/issue-1204-icewall-causing-dead-cell/ (2008)
- http://herc.ws/board/tracker/issue-6055-cell-bug-after-ice-wall/ (2012)
- http://herc.ws/board/tracker/issue-7043-ice-wall-cell-bug/ (2013)

**Comment by AnisotropicDefixation** [comment]
Hmm, from what I read, it's supposed to be clientside and fixed with @refresh but that's not the case at all, a server reboot is needed.

**Comment by AnisotropicDefixation** [comment]
There has to be a way to help this is issue, it's just plain gamebreaking and forces you to disable the skill entirely.
