### ISSUE TITLE
Icons Disappear

### ISSUE THREAD

**Issue by Streusel** [HerculesWS/Hercules#550]
Client date 2012-04-10 14.2.9

1. Login to your character.
2. Add some buffs or even debuffs that have timers, like Blessing or Increase Agility.
3. Hatch/Get a pet. (Intimacy doesn't matter, although in this case it was neutral)
4. Walk around a bit, takes less than a minute.
5. Icons disappear!! The timer is still visible but the icon itself is gone, if you hover over the area where it should be it displays the buff info.

Could this be a client issue or a server issue?

**Comment by malufett** [comment]
can't reproduce....XD
