### ISSUE TITLE
OnSellItem doesnt return @sold_card[] value for named item.

### ISSUE THREAD

**Issue by emistry** [HerculesWS/Hercules#560]
Sample Script to test : http://pastebin.com/raw.php?i=4f6jV65E
_(Created a named item using **getitem2** or **getnameditem**)_

I believe the value checking work fine with both **countitem2** and **getinventorylist**

but not in **@sold_card[]**
![Preview](http://i.imgur.com/dYHAGDR.png)
As you can see from the picture: 
the **countitem2** and **getinventorylist**return positive result but not the **@sold_card**

The **@sold_card[]** should return these values.
```
@sold_card1[0]    -->  254
@sold_card2[1]    -->  0
@sold_card3[2]    -->  18928
@sold_card4[3]    -->  2
```

**Comment by MishimaHaruna** [comment]
Confirmed. We're currently only setting the `@sold_cardX` variables when the item is an equipment piece.

By the way, your script is incorrect. You should change this:

```
	OnSellItem:
		if ( @sold_nameid == .itemid ) {
			dispbottom sprintf( "using @sold_card[] %d - %d - %d - %d",
				@sold_card1[0],
				@sold_card2[1],
				@sold_card3[2],
				@sold_card4[3]
			);
		}
		end;
```

into:

```
OnSellItem:
	for (.@i = 0; @sold_nameid[.@i] != 0; ++.@i) { // Loop through the items, @sold_nameid is an array, and there may be more than one value
		dispbottom sprintf("using @sold_card[] %d - %d - %d - %d",
			@sold_card1[.@i],  // The array indices should be .@i (i.e. all 4 should have the same index), you used 1, 2, 3, 4 instead.
			@sold_card2[.@i],
			@sold_card3[.@i],
			@sold_card4[.@i]
		);
	}
	end;
```

**Comment by emistry** [comment]
Owh, that line... I was in hurry so I only made 1 item in the sell list. xD

**Comment by dastgir** [comment]
Fixed @ https://github.com/HerculesWS/Hercules/commit/3fbd2b3b3b8277ded2b8139139e62e32c3db3145
