### ISSUE TITLE
nj_kaensin knockback

### ISSUE THREAD

**Issue by Geniks** [HerculesWS/Hercules#561]
hi,

the skill crimson fire formation (a.k.a nj_kaensin) doesn't made any knockback while he should.

thanks

**Comment by Playtester** [comment]
It doesn't knock back on official servers.

**Comment by Geniks** [comment]
see that
https://www.inertiaro.com/forums/topic/3551-the-ninja-guide/ -> http://puu.sh/iF3oJ/ba76fa912a.png
and
http://z7.invisionfree.com/AfterTheAcademy/index.php?showtopic=30

**Comment by Playtester** [comment]
None of this information is from official servers. I added knockback because I was told it works like firewall. Now we have official video footage and are able too test ourselves so we can be a lot more official with our implementations. :-)

**Comment by malufett** [comment]
Working as Intendedd
