### ISSUE TITLE
White Wing Suit and Black Wing Suit drop rate

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#562]
Question,
- where do you guys know this 2 item's drop rate?

I see only 2 sites that mention its drop rate, which is : 

http://www.divine-pride.net/database/monster/1098 < white wing suit from anubis with drop rate 1% (is this even kRO's official? can't see any mention of its server) too high if i think for rare gear
http://ro.silk.to/mob/1098.html < white wing suit from anubis with drop rate 0.06 % (official jRO) seems normal for "rare" gears

http://www.divine-pride.net/database/monster/2773 < Black wing suit from Elusive Luciola Vespa with INSANE drop rate 90%, seriously? I know you got higher drop rate from "Champion Monster", but 90%? (this mob is not exist in jRO) The drop rate from normal Luciola Vespa is Okay (0.1%)

**Comment by emistry** [comment]
ro. gnjoy.com

**Comment by zackdreaver** [comment]
@emistry
show me the drop rate

**Comment by emistry** [comment]
http://herc.ws/board/tracker/issue-8477-wrong-monster-drop-the-giant-crossbow2/?gopid=24388#entry24388

they are not refer to divine-pride database.

**Comment by zackdreaver** [comment]
@Dasgir or any developer mind checking?

**Comment by Kenpachi2k13** [comment]
The drop chances were taken from http://kafra.kr back then.
DivinePride has updates the chances to:
- Anubis drops White Wing Suit with a chance of 0,5%.
- Elusive Luciola Vespa drops Black Wing Suits with a chance of 0,25%.

These chances match my Aegis data so I'll update our database accordingly.
