### ISSUE TITLE
Need info Stalker Reject Sword and Paladin Reflect Shield

### ISSUE THREAD

**Issue by Esux** [HerculesWS/Hercules#567]
Are these skills supposed to work like this "reflect damage cannot go higher than casters HP" and if so does it work that way for both skills in Hercules? Seems like it could be abused if it doesn't work that way.

**Comment by anacondaqq** [comment]
Stalker Reject Sword do not have limitations to reflect damage.
Paladin Reflect Shield have limitations.

**Comment by Esux** [comment]
I knew one of them was nerfed, wasn't sure which one. It seems most servers choose to nerf Reject Sword as well to prevent abuse.

Thanks for your help.
