### ISSUE TITLE
MVP's bonus exp log message on client

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#570]
On official, MVP's bonus EXP goes to "Public Log"
instead of "Experience Message Display"

But on Hercules, it goes to "Experience Message Display"
![screenhercules001](https://cloud.githubusercontent.com/assets/10024221/8357467/31089392-1b85-11e5-9f75-9f901e8a83b9.jpg)
![screenhercules002](https://cloud.githubusercontent.com/assets/10024221/8357469/39d48a8a-1b85-11e5-8e0b-d6ae703459e5.jpg)

The official should be : 
Congratulations! You are the MVP! Your reward EXP Points are 1980000 !!

nb: msgstringtable line between 146 - 147

**Comment by zackdreaver** [comment]
Here's proof...
http://bp2.blogger.com/_EPl8EHxxL9U/R_68d3d36GI/AAAAAAAAAA8/bsucYmPG3Bk/s1600-h/MVP2.JPG

**Comment by MishimaHaruna** [comment]
Are you positive this isn't an issue with your client? I don't have a way to test this, but in the screenshot you show (the `PUBLIC_LOG ON` one), it appears that you have received packets `ZC_MVP_GETTING_SPECIAL_EXP` and `ZC_MVP_GETTING_ITEM` (else those messages wouldn't be that color), but the client is not displaying the exp amount.

We're sending the value correctly as far as I know (check clif.c:7014 and mob.c:2493).

From your screenshot, I also see a missing exclamation point after "Tiger Skin" (line 145 of msgstringtable), unless it was removed.

**Comment by zackdreaver** [comment]
I've search for the cause of this issue via client side,
but still got no luck... so now i believe it might be server side.

nb:
i've tested using default msgstringtable from KRO,
even i've checked with many different patches through NEMO patcher, but still no resolution i found.

**Comment by Milchdealer** [comment]
This issue does not exist. It appears in both public and exp log. The Exp log because you receive exp and the public because it is special via an mvp kill.
![Public Log](http://i.imgur.com/XfJK2vR.jpg)
![Exp Log](http://i.imgur.com/5xIBZEY.jpg)

**Comment by MishimaHaruna** [comment]
Thank you @Milchdealer - as I suspected. That's what I also remember seeing on my side.

I'll close this now. Please reopen if there are news.

**Comment by zackdreaver** [comment]
@MishimaHaruna 
idk if this related, but they fix it
https://github.com/rathena/rathena/commit/9ca5dc40bd2c269af2f6041d3e79d157be5cdb1f

**Comment by MishimaHaruna** [comment]
the rAthena commit and issue referenced is unrelated. We're not affected by that bug

**Comment by zackdreaver** [comment]
Ok, i've made some test with old client date (2008-03-25Sakexe), same msgstringtable
seems like the issue doesn't exist, so its not related with server side
maybe it's related with the differ?
(well I only use NEMO patcher all this year.. havent test with other)

what do you think @MStr3am ?

![screenlocal000](https://cloud.githubusercontent.com/assets/10024221/11685500/19105f40-9eac-11e5-94c6-c002f6aab5d1.jpg)

**Comment by zackdreaver** [comment]
@MishimaHaruna 
how about this fix?
https://github.com/rathena/rathena/commit/85749e84b91087960e868e30a7a052b0c0cdce5b
