### ISSUE TITLE
RA_CAMOUFLAGE

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#571]
It's supposed to make you untargetable by targeted skills (area skills still affect you).

**Comment by csnv** [comment]
According to Irowiki:
> Camouflaged players cannot be targeted by normal attacks from players (Skills can still be used on the Ranger) and is revealed on hit. 

Can anybody confirm if it's skills or only normal attacks?

**Comment by AnisotropicDefixation** [comment]
8/22/2012 kRO patch:

Camouflage - Fixed a bug where a ranger in camouflage state could be targeted by single target skills.

As far as I know it still works like that over there.

**Comment by MishimaHaruna** [comment]
Tests on a somewhat recent Aegis show that both single-target and AoE skills can target a character in Camouflage status. I'll mark this as in need of confirmation (waiting for a test on a more recent Aegis server)
