### ISSUE TITLE
Status Icon Timer of  sc_monster_transform disappear after loading a map

### ISSUE THREAD

**Issue by Angelmelody** [HerculesWS/Hercules#580]
The status icon timer of sc_monster_transform dispears after changing map or re-login,
It should not be so and hope devs fix this bug thanks

**Comment by Milchdealer** [comment]
Are you still transformed and it's just the Icon disappearing?

**Comment by QQfoolsorellina** [comment]
icon doesn't disappear , but icon timer disappear

**Comment by QQfoolsorellina** [comment]
I report this bug for More than half a year but still no response form devs  ![4163931](https://cloud.githubusercontent.com/assets/2773211/8669441/42c53e20-2a47-11e5-9d5c-472870800751.gif)

http://herc.ws/board/tracker/issue-8382-status-icon-timer-disappear-after-loading-a-map/

**Comment by malufett** [comment]
this is the same with the other status icons which their timer is controlled via a variable(val3/val4)..this will be fixed when the redesign is created..

**Comment by QQfoolsorellina** [comment]
glad to hear that, thank you malufett

**Comment by QQfoolsorellina** [comment]
I wish that our devs would spend some time fixing this bug ....
![50722153222](https://cloud.githubusercontent.com/assets/2773211/8820357/49901e5a-3087-11e5-9429-7ab0e4f3457f.gif)

**Comment by Smokexyz** [comment]
I don't see an issue with this using 2013-08-07 client

**Comment by QQfoolsorellina** [comment]
@Smokexyz 
cuz you don't get what i mean

**Comment by Smokexyz** [comment]
you're right, i didn't read correctly, sorry.

**Comment by QQfoolsorellina** [comment]
@devs  any news about this bug

**Comment by dastgir** [comment]
Poor 'devs' user , who got notified xD
@malufett, when you will be free to merge the ScRedesign?

**Comment by Angelmelody** [comment]
@HerculesWS/developers
One year has passed , Any news about sc redesign?
