### ISSUE TITLE
 elemental damage issue

### ISSUE THREAD

**Issue by Miengo2** [HerculesWS/Hercules#583]
Bug with elemental damage My users are complaining that the damage should be double (200%) just ascended 8k damage I do my testing with this amon ra confirming

**Comment by AnisotropicDefixation** [comment]
If you're running renewal, element only applies to weapon attack.

**Comment by Miengo2** [comment]
No skill is affected? Or using endow? And if use elemental date, nor is it affected?

**Comment by AnisotropicDefixation** [comment]
You have two ATK parts, base and weapon, only weapon ATK gets element bonus in renewal, base ATK is always neutral so the damage boost isn't as big as before.
