### ISSUE TITLE
"Favorite" inventory tab.

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#587]
Stuff placed there shouldn't appear in the list when selling stuff to NPC.

**Comment by kyeme** [comment]
In official will not appear?

**Comment by AnisotropicDefixation** [comment]
Nope, that's the whole point of that tab.

**Comment by dastgir** [comment]
Any official video or something showing this?

**Comment by malufett** [comment]
nah...it isn't...can be sold like the other items
![image](https://cloud.githubusercontent.com/assets/3251821/8671629/623f65a2-2a59-11e5-92d1-9977a4b04062.png)

**Comment by dastgir** [comment]
Anything @AnisotropicDefixation

**Comment by AnisotropicDefixation** [comment]
I reported this due to a player mentioning that nothing in the tab was sellable on euRO official server, haven't tried myself, might have been their own change?

Hmm, maybe adding a switch for it would a good idea as it makes sense?

**Comment by hemagx** [comment]
@AnisotropicDefixation  euRO doesn't even have this update :x

**Comment by dastgir** [comment]
Maybe, the item he put in favorite was itself not sellable, and he thought it won't appear in npc list...
