### ISSUE TITLE
 update sql file failed

### ISSUE THREAD

**Issue by QQfoolsorellina** [HerculesWS/Hercules#588]
I tried to update 2015-07-02--18-14.sql today ,but got failed , Here is the err msg:

[Err] 1267 - Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='
[Err] CALL alter_if_not_exists('item_db', 'forceserial', 'ADD COLUMN', 'TINYINT(1) UNSIGNED DEFAULT NULL AFTER bindonequip') ;

Does anyone know how to fix this err?

**Comment by MishimaHaruna** [comment]
Do you have a custom character set in your item_db table or ragnarok database? What's the output of these MySQL queries (after selecting the ragnarok db):

```
SHOW FULL COLUMNS FROM item_db WHERE Collation IS NOT NULL;
SHOW TABLE STATUS WHERE NAME = 'item_db';
SHOW VARIABLES LIKE 'character_set_database';
SHOW VARIABLES LIKE 'collation_database';
```

**Comment by QQfoolsorellina** [comment]
<pre><code>
mysql> SHOW FULL COLUMNS FROM item_db WHERE Collation IS NOT NULL;
1146 - Table 'heragnarok.item_db' doesn't exist
</code></pre>

<pre><code>
mysql> SHOW TABLE STATUS WHERE NAME = 'item_db';
Empty set
</code></pre>

<pre><code>
mysql> SHOW VARIABLES LIKE 'character_set_database';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| character_set_database | utf8  |
+------------------------+-------+
1 row in set
</code></pre>

<pre><code>
mysql> SHOW VARIABLES LIKE 'collation_database';
+--------------------+-----------------+
| Variable_name      | Value           |
+--------------------+-----------------+
| collation_database | utf8_unicode_ci |
+--------------------+-----------------+
1 row in set
</code></pre>

**Comment by QQfoolsorellina** [comment]
I loaded  item_db.sql into my mysql database
<pre><code>
mysql> SHOW FULL COLUMNS FROM item_db WHERE Collation IS NOT NULL;
+----------------+-------------+-----------------+------+-----+---------+-------+---------------------------------+---------+
| Field          | Type        | Collation       | Null | Key | Default | Extra | Privileges                      | Comment |
+----------------+-------------+-----------------+------+-----+---------+-------+---------------------------------+---------+
| name_english   | varchar(50) | utf8_unicode_ci | NO   |     |         |       | select,insert,update,references |         |
| name_japanese  | varchar(50) | utf8_unicode_ci | NO   |     |         |       | select,insert,update,references |         |
| script         | text        | utf8_unicode_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| equip_script   | text        | utf8_unicode_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| unequip_script | text        | utf8_unicode_ci | YES  |     | NULL    |       | select,insert,update,references |         |
+----------------+-------------+-----------------+------+-----+---------+-------+---------------------------------+---------+
5 rows in set
</code></pre>
<pre><code>
mysql> SHOW TABLE STATUS WHERE NAME = 'item_db';
+---------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+
| Name    | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time | Collation       | Checksum | Create_options | Comment |
+---------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+
| item_db | MyISAM |      10 | Dynamic    | 6139 |             92 |      565664 | 281474976710655 |        52224 |         0 | NULL           | 2015-07-08 17:05:51 | 2015-07-08 17:05:53 | NULL       | utf8_unicode_ci | NULL     |                |         |
+---------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+
1 row in set
</code></pre>

**Comment by MishimaHaruna** [comment]
Curious. The script was supposed to inherit the database collation... Unless connection and database (or server) collations don't match...

How about these?
```
SHOW VARIABLES LIKE 'collation\_%';
SHOW VARIABLES LIKE 'character\_set\_%';
```

Also, does the script work now that you imported the item_db table?

**Comment by QQfoolsorellina** [comment]
<pre><code>
mysql> SHOW VARIABLES LIKE 'collation\_%';

+----------------------+-----------------+
| Variable_name        | Value           |
+----------------------+-----------------+
| collation_connection | utf8_general_ci |
| collation_database   | utf8_unicode_ci |
| collation_server     | utf8_unicode_ci |
+----------------------+-----------------+
3 rows in set
</code></pre>
<pre><code>
mysql> SHOW VARIABLES LIKE 'character\_set\_%';
+--------------------------+--------+
| Variable_name            | Value  |
+--------------------------+--------+
| character_set_client     | utf8   |
| character_set_connection | utf8   |
| character_set_database   | utf8   |
| character_set_filesystem | binary |
| character_set_results    | utf8   |
| character_set_server     | utf8   |
| character_set_system     | utf8   |
+--------------------------+--------+
7 rows in set
</code></pre>

script still doesn't work after imported  item_db table into mysql database,still got the same err msg

**Comment by dastgir** [comment]
```
DELIMITER $$

DROP PROCEDURE IF EXISTS alter_if_exists $$

CREATE PROCEDURE alter_if_exists(my_table TINYTEXT, my_column TINYTEXT, my_command TINYTEXT, my_predicate TEXT)
BEGIN
  set @dbname = DATABASE();
  IF NOT EXISTS (
    SELECT * FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = @dbname
        AND TABLE_NAME = my_table
        AND COLUMN_NAME = my_column
  )
  THEN
    SET @q = CONCAT('ALTER TABLE ', @dbname, '.', my_table, ' ',
      my_command, ' `', my_column, '` ', my_predicate);
    PREPARE STMT FROM @q;
    EXECUTE STMT;
  END IF;

END $$

CALL alter_if_exists('item_db', 'forceserial', 'ADD COLUMN', 'TINYINT(1) UNSIGNED DEFAULT NULL AFTER `bindonequip`') $$
CALL alter_if_exists('item_db2', 'forceserial', 'ADD COLUMN', 'TINYINT(1) UNSIGNED DEFAULT NULL AFTER `bindonequip`') $$

DROP PROCEDURE IF EXISTS alter_if_exists $$

DELIMITER ';'

INSERT INTO `sql_updates` (`timestamp`) VALUES (1435860840);
```
Try this?

**Comment by MishimaHaruna** [comment]
Or just skip the update, and only run:

```
INSERT INTO `sql_updates` (`timestamp`) VALUES (1435860840)
```

The script is only needed to update existing item_db tables, and re-importing the item_db makes this script unnecessary.
I'd still advise to either change your mysql client settings so that it uses the same collation as the database, or change the database collation, to avoid any future problems.
The difference between `utf8_general_ci` and `utf8_general_ci` is that, while the first is more accurate (it respects the Unicode standards), especially when calculating an alphabetical order, the latter is faster.

**Comment by QQfoolsorellina** [comment]
@dastgir  
 wow... I loaded your procedure script successfully :+1:  , 'COLLATE utf8_unicode_ci'  is very useful to me 

@MishimaHaruna 
  let me try....
