### ISSUE TITLE
unittalk script function and mobs.

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#589]
It doesn't looks like @mobid or $@mobid[0] or anything of the sort works, isn't it supposed to be able recall the previously used ID (spawned mob)? Works on rA.

**Comment by MishimaHaruna** [comment]
I'm not sure what `@mobid` or `$@mobid[0]` are about, but the expected use of unittalk (when used with monsters) is:

```
.@mobid = monster("prontera", 150, 150, "a Poring", PORING, 1);
if (.@mobid) {
    unittalk(.@mobid, "Hello, I'm a Poring.");
}
```

**Comment by AnisotropicDefixation** [comment]
So there's no way to link it to monster's GID?

**Comment by dastgir** [comment]
Isn't .@mob  mob GID?(in haru example)

**Comment by AnisotropicDefixation** [comment]
Here are some examples of what I'm having issues with, this is rA's OGH script.

//
OnEnable:
	enablenpc instance_npcname("#ghmemorialmob10");
	donpcevent instance_npcname("Gerhalt#ghinstance1")+"::OnDisable";
	monster instance_mapname("2@gl_k"),158,255,"Amdarais",2476,1,instance_npcname("#ghmemorialmob10")+"::OnMyMobDead";
	unittalk $@mobid[0],"Run away... run away from me...",1;
	initnpctimer;
	end
OnTimer6000:
	unittalk $@mobid[0],"I don't want... I don't want to kill anyone...",1;
	end;

//

monster .@map$,145,54,"Khalitzburg",2471,1,.@label$;
unittalk $@mobid[0],"Water... Someone give me water...",1;
monster .@map$,154,54,"Khalitzburg",2471,1,.@label$;
unittalk $@mobid[0],"Kkkrrrruughgh...",1;
//

How would one go around linking the correspondent unittalks to the specific mobs that have been spawned without interfering with anything else?

**Comment by MishimaHaruna** [comment]
Use the return value of the `monster()` function, save it to a variable, and use it?

**Comment by AnisotropicDefixation** [comment]
I'm not able to make this work outside of spawn case, tried everything already. Works just fine when attached to a monster spawn but nothing seems to work for label and ontimer events.
