### ISSUE TITLE
Client Crashes

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#592]
To reproduce
1. Make character name like Chingchangkun :)
2. Type @accinfo %Chingchangkun :)%
Boom client crash

Related issue: http://herc.ws/board/tracker/issue-8186-client-crashes-in-disguise-and-who/?gopid=22789#entry22789

Im using client 2013-12-23

**Comment by Milchdealer** [comment]
Found the mistake. It's unrelated to the previous one.
accinfo uses inter communication (between servers, in this case map->char) and for accinfo it uses SQL. The closing brackets is illegal in SQL ')' and can't be escaped properly
I'll think of a fix ~

**Comment by Milchdealer** [comment]
Should be fixt once they merge my Pull Request. You can already get the 1 line patch from the diff if you need it urgently.
