### ISSUE TITLE
bonus2 bSkillCooldown/SP_SKILL_COOLDOWN

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#593]
Looks like it has no effect whatsoever on skills with very long cooldowns, I haven't tested every value but everything with 1min+ gets no benefits.

**Comment by pengc2010** [comment]
I have checked this, since the skillcooldown.val is declared as short, it does not support a large value, that is the reason.
Change skillcooldown.val to int type in "pc.h" will fix this.

**Comment by Kenpachi2k13** [comment]
Was fixed in https://github.com/HerculesWS/Hercules/pull/2364 -> https://github.com/HerculesWS/Hercules/pull/2364/commits/8c04536cf64dd3a7c233d9631eceb23f7207ad9c
`close();`
