### ISSUE TITLE
Kagerou/Oboro Custom Skills

### ISSUE THREAD

**Issue by SoulBlaker** [HerculesWS/Hercules#594]
Whenever I add quests skills in this class it does not appear in the skill tree, already tested with other classes and appears normally.

**Comment by malufett** [comment]
better ask in the forums..:D

**Comment by SoulBlaker** [comment]
nobody answers

**Comment by Mysteries** [comment]
Even though Soul, the issues tracker isn't for support in any way. It's used to report bugs/issues.  You may bump your thread every 24 hours.

**Comment by SoulBlaker** [comment]
Asking not to support to reporting that tests all classes, will Skills for less tree with Kagerou&Oboro class.
