### ISSUE TITLE
Fix Quest List in 20150513 Clients

### ISSUE THREAD

**Issue by Triedge** [HerculesWS/Hercules#602]
in clif.c
Search:
```
void clif_quest_send_list(struct map_session_data *sd)
{
	int fd = sd->fd;
	int i;
#if PACKETVER >= 20141022
	int info_len = 15;
	int len = sd->avail_quests*info_len+8;
	WFIFOHEAD(fd,len);
	WFIFOW(fd, 0) = 0x97a;
#else
	int info_len = 5;
	int len = sd->avail_quests*info_len+8;
	WFIFOHEAD(fd,len);
	WFIFOW(fd, 0) = 0x2b1;
#endif
```
Change to:
```
void clif_quest_send_list(struct map_session_data *sd)
{
	int fd = sd->fd;
	int i;
#if PACKETVER >= 20150513
	int info_len = 5;
	int len = sd->avail_quests*info_len+8;
	WFIFOHEAD(fd,len);
	WFIFOW(fd, 0) = 0x2b1;
#elif PACKETVER >= 20141022
	int info_len = 15;
	int len = sd->avail_quests*info_len+8;
	WFIFOHEAD(fd,len);
	WFIFOW(fd, 0) = 0x97a;
#else
	int info_len = 5;
	int len = sd->avail_quests*info_len+8;
	WFIFOHEAD(fd,len);
	WFIFOW(fd, 0) = 0x2b1;
#endif
```

**Comment by MishimaHaruna** [comment]
This is more of a workaround than a fix, I don't think using the old packet is really what we want here, or is it?

**Comment by dastgir** [comment]
There's a new packet for quest list for clients > 2015

**Comment by Triedge** [comment]
if PACKETVER >= 20141022
    int info_len = 15;
    int len = sd->avail_quests*info_len+8;
    WFIFOHEAD(fd,len);
    WFIFOW(fd, 0) = 0x97a;

Crash in clients 20150513... 
set Active 2 quest.
close client.
enter to the game...
CRASH!

with old packet no crash.

**Comment by Triedge** [comment]
no merge? >.<

**Comment by dastgir** [comment]
Will Check this issue again soon..

**Comment by dastgir** [comment]
@Triedge 
I don't receive crashes,  can you specify which quest you used for testing?

**Comment by mirivlad** [comment]
@dastgir  i think this eden group quests)) any 2 quests from eden

**Comment by MishimaHaruna** [comment]
Is this still crashing (i.e. after be5c38f5bf7f316eebd301f91fde888dffd844e6)?

**Comment by dastgir** [comment]
That wouldn't work on 2015 clients, new packets are needed.

**Comment by dastgir** [comment]
This should be fixed in https://github.com/HerculesWS/Hercules/commit/be5c38f5bf7f316eebd301f91fde888dffd844e6
