### ISSUE TITLE
NPC get Mute Bubble.

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#603]
Related to this bug report ...
http://herc.ws/board/tracker/issue-7549-npc-get-mute-bubble/
## Step to Reproduce the issue

Make a NPC keep talking ....
![NPC get Mute Bubble](http://i.imgur.com/0bsy39V.png)

This issue, I not sure how it really happened and why could happen  ... 
it doesnt happen everytime ...
I tried repeat the process to try reproduce the issue, but it doesnt happen all the time...

GIT Version : latest from https://github.com/HerculesWS/Hercules/commit/19669457e600034cecad3cfba06c567a2f3fe5f3

_Haha ... exactly 2 years later (Today)... I posted same things again .. LOL_

**Comment by dastgir** [comment]
Maybe there was some auto mute on spam(I don't remember where we had that setting)

**Comment by QQfoolsorellina** [comment]
this?  client_accept_chatdori in client.conf

**Comment by ai4rei** [comment]
Option client_accept_chatdori is self-mute (client requests itself to be stopped from talking), the associated code seems fine, so it should not cause blabbering NPCs to the muted.

It would be nice to have the client version. For now you can assume, that that client marks any flooding unit in advance as muted, without waiting for the unit's client to get muted by itself.

Note, that the condition for the regular self-mute is repeating the same or very similar message few times, or flooding the chat with many lines within a short time interval.

**Comment by Emistry** [comment]
client: 
`2014-10-22bRagexe` or `2015-06-18aRagexe` (should be any of these if i recall correctly)

npc script: 
the script does repeat and spam the messages (random 1 from 10~30 message arrays) every 30s ~ 60s. However those message doesn't appear in the chatbox since I'm using the `showscript()` script command. 

The npc mute, does't happen to every NPC, and not every time manage to duplicate the issue. Sometime it does manage to duplicate the issue after I left the NPC keep spamming for whole night.

Not sure if the issue still exists today, didnt give it a test in latest version.

**Comment by ai4rei** [comment]
Whether or not in the chat window is irrelevant. Before I give one of those clients' code an angry glare, does the NPC use any kind of visual special effects, like `specialeffect()`?

**Comment by AnnieRuru** [comment]
from the screenshot,
seems like emistry using mob_avail.txt create a new mob ID, but using player's sprite

custom, but worth a try ...
testing ...

**Comment by Emistry** [comment]
@ai4rei I think no, doesn't recall if I used any `specialeffect()`
@AnnieRuru no, I was using these [Geffen Mage Sprites](http://nn.ai4rei.net/dev/npclist/?q=geffen_mage&qq=search) if I recall correctly. 

seem like I didnt have a copy for the script that I made last time, not sure what else was in the script other than just spamming the `showscript("message")` every 30s~60s and walking around the map.

**Comment by Kenpachi2k13** [comment]
Unable to reproduce. Tested with `npctalk()`, `showscript()`, NPC sprite, mob sprite, character sprite, walking and not walking NPC.

Client: `20180418`
Hercules: https://github.com/HerculesWS/Hercules/commit/c03722679a01e5f181c2138565e95a6b0981a124

`close();`
