### ISSUE TITLE
Error undefined function mergeitems()

### ISSUE THREAD

**Issue by asakapab0i** [HerculesWS/Hercules#605]
When starting the server:
Path: npc/other/item_merge.txt

**Comment by Milchdealer** [comment]
Can you please elaborate what is actually happening?

**Comment by emistry** [comment]
update your hercules ...
the script command has been added
https://github.com/HerculesWS/Hercules/blob/master/src/map/script.c#L19703

**Comment by asakapab0i** [comment]
Fixed recompiled the src.
