### ISSUE TITLE
Warg Dash Delay

### ISSUE THREAD

**Issue by Helheim90X** [HerculesWS/Hercules#608]
According to iRO: http://irowiki.org/wiki/Warg_Dash

This skills has a delay of 2 secs, in Hercules this is much less than 2 secs, please, check it and reset it to its official value.

**Comment by malufett** [comment]
hmm..as I remember it was added before,,,

**Comment by AnisotropicDefixation** [comment]
The cooldown was removed after rebalance.

**Comment by malufett** [comment]
ow..now I remember..thanks @AnisotropicDefixation

**Comment by Helheim90X** [comment]
Really? what year?
