### ISSUE TITLE
Cash shop total is not working

### ISSUE THREAD

**Issue by latheesan-k** [HerculesWS/Hercules#618]
I am currently using **2013-08-14aRagexe.exe** (so packet version **20130814**) with the latest git repo. On the cash shop, when you add items to the basket, the total is not updating, I just see **%s** like this:

![Cash Shop Bug](http://i.imgur.com/CpVCz7C.png)

**Comment by kyeme** [comment]
Maybe the msgstringtable.txt that are you using?

**Comment by latheesan-k** [comment]
I am using http://herc.ws/board/topic/901-basic-complete-renewal-data-english-folder/ english data dir with https://github.com/ROClientSide/Translation client side translation. Could this be why? Am I supposed to rename one of the msgstringtable.txt template and over-write the one that is supplied? There are a few version in the release.

**Comment by dastgir** [comment]
This doesn't belong to Hercules, rather its client side, please use forum for client side issues.
