### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#623]
Downloading latest and I can't compile, I got this error:

1>------ Skipped Build: Project: plugin-sample, Configuration: Debug Win32 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: mapcache, Configuration: Debug Win32 ------
3>------ Build started: Project: map-server, Configuration: Debug Win32 ------
4>------ Build started: Project: login-server, Configuration: Debug Win32 ------
5>------ Build started: Project: char-server, Configuration: Debug Win32 ------
2>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt
4>     Creating library ..\login-server.lib and object ..\login-server.exp
4>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt
5>     Creating library ..\char-server.lib and object ..\char-server.exp
5>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt
3>     Creating library ..\map-server.lib and object ..\map-server.exp
3>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt
========== Build: 0 succeeded, 4 failed, 3 up-to-date, 1 skipped ==========

Im using Hercules-10.sln 
Windows7 64bit

**Comment by 4144** [comment]
This error most time mean some thing wrong with temp files.
Try select "clean solution" or like this, forgot name.
Then select rebuild solution.

**Comment by kyeme** [comment]
Still getting the error :[

**Comment by kyeme** [comment]
I update my .NET Framework to 4.5 last week lol, I try to Upgrading to VS 2010 SP1
https://support.microsoft.com/en-us/kb/2757355
Sorry I don't know this is the common issue.

**Comment by kyeme** [comment]
Problem solve.
Thanks for your reply @4144 :D
