### ISSUE TITLE
Menblatt Card Script Effect

### ISSUE THREAD

**Issue by tsan79** [HerculesWS/Hercules#626]
The current #4593 Menblatt Card effect is:
bonus bLongAtkDef,readparam(bDex)/10
Reference: https://raw.githubusercontent.com/HerculesWS/Hercules/master/db/re/item_db.conf

On the contrary, The item information noted that:
"Long-ranged Attack Strength +1% for every 10 pure DEX."
Reference: http://www.divine-pride.net/database/item/4593/menblatt-card

Therefore I think the correct card effect should be:
bonus bLongAtkRate,readparam(bDex)/10

Cheers,
-SH

**Comment by Jedzkie** [comment]
This issue is now fixed. Thanks for the report.
