### ISSUE TITLE
RC_NonDemiPlayer and RC_NonDemiHuman is not working properly

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#630]
RC_NonDemiPlayer and RC_NonDemiHuman are still working on Human. It should not because of 'NON'

Example: Item with script "SubRace RC_NonDemiPlayer,50;" Resist should only work for Non-DemiHuman. The bug is, it will still give resist to Demi Human/Player.

This is a critical bug, please confirm  thank you.
Topic
http://herc.ws/board/topic/10234-bug-nondemiplayer/

**Comment by dastgir** [comment]
@MishimaHaruna @4144 
Wanna give a look in this?
it seems bAddRace and bSubRace aren't working for any value...

**Comment by MordekaiserGod** [comment]
I think its because players are also classified as RC_Nonboss. 

src/map/pc.c  line 2894 needs a check for RC_Nonboss. 

If I'm correct. Other bonus2 also needs changing.
