### ISSUE TITLE
About bAddRaceTolerance

### ISSUE THREAD

**Issue by dastgir** [HerculesWS/Hercules#631]
```
bonus2 bAddRaceTolerance,r,n;			+n% tolerance against race r (Renewal Only)
```

But the effect is only triggered on battle_calc_cardfix2
which have

```
tsd = BL_CAST(BL_PC, bl);
	sstatus = status->get_status_data(src);

	if ( tsd ) {
		if ( !(nk&NK_NO_CARDFIX_DEF) ) {
			// RaceAddTolerance
			damage -= damage * tsd->race_tolerance[sstatus->race] / 100;
			damage -= damage * tsd->race_tolerance[is_boss(src) ? RC_BOSS : RC_NONBOSS] / 100;
			if ( flag&BF_SHORT )
				damage -= damage * tsd->bonus.near_attack_def_rate / 100;
			else // SubRangeAttackDamage or bLongAtkDef
				damage -= damage * tsd->bonus.long_attack_def_rate / 100;
		}
		if ( flag&BF_LONG && tsd->sc.data[SC_GS_ADJUSTMENT] ) {
			damage -= 20 * damage / 100;
		}
	}
```
So In Short it only acts if tsd is found as player,
that means if the other race is RC_Player?

so why there's option of race in the bonus when its limited to player? or someone mind explain how it works?

**Comment by dastgir** [comment]
@malufett

**Comment by malufett** [comment]
"But the effect is only triggered on battle_calc_cardfix2" 
- cause its for renewal only

"So In Short it only acts if tsd is found as player,
that means if the other race is RC_Player?"
-tsd means target..why is mob can use card?

**Comment by dastgir** [comment]
@malufett 
```
tsd = BL_CAST(BL_PC, bl);
```
you cast it as BL_PC, so basically its only for player...

**Comment by malufett** [comment]
@dastgir 
yes this bonus meant only for players cause they are the only one can equip items..
and the attacking type is any...

**Comment by dastgir** [comment]
* without checking further code, just wondering *
What's default value of race_tolerance
Is it 0? (sd->race_tolerance[sstatus->race], I mean this)

**Comment by malufett** [comment]
yes it's 0...
