### ISSUE TITLE
bAddRace not increasing damage?

### ISSUE THREAD

**Issue by dastgir** [HerculesWS/Hercules#632]
@MishimaHaruna @4144 @malufett 
Wanna give a look in this?
it seems bAddRace aren't working for any value...
(Tested the bAddRace with Renewal.)
My Test Script:
```
bonus2 bAddRace,RC_Plant,500;
```
Then tested on Poring(and other plant races), damage remained same.
then I tested some other races, none worked.

**Comment by malufett** [comment]
with that bonus(3x)
![image](https://cloud.githubusercontent.com/assets/3251821/9170124/be6bdec0-3f92-11e5-88f7-58c82cd0c684.png)

w.o that bonus
![image](https://cloud.githubusercontent.com/assets/3251821/9170131/cafd5452-3f92-11e5-8b0a-65602fafc6fe.png)

**Comment by Paoly28** [comment]
baddrace only adds weapon/eqatk maybe you tested it unarmed.
