### ISSUE TITLE
Snap_dodge bug

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#638]
http://herc.ws/board/topic/10359-snap-dodge-bug/#entry61364

Hi,
I tried turning the setting ON and OFF on conf/battle/battle.conf
[code]
// Should the target be able of dodging damage by snapping away to the edge of the screen?
// Official behavior is "no"
snap_dodge: yes
[/code]
but the result are the same. Snap can't dodge all skill even my setting is yes or no.

please fix

**Comment by anacondaqq** [comment]
client date? revision? mechanic? Why are you do not post details? How is devs will fix it without enough data? This is a open source project, why are they must repeat issues and do your job? 
I think, if you recieve bugreport from your member, will are you ask for more details from him, or not?

**Comment by kyeme** [comment]
He mean that the snap dodge is not working (unofficial settings)

http://herc.ws/board/index.php?app=tracker&showissue=3510

He want this:
https://youtu.be/5qqfPvL1P6s

**Comment by zicaros** [comment]
any update ?

**Comment by jef924** [comment]
Bump!~

**Comment by vBrenth** [comment]
I'll give this another bump.

**Comment by Mysteries** [comment]
@vBrenth have you tried with the latest Hercules? Is anyone else able to confirm this as well? @HerculesWS/developers

**Comment by vBrenth** [comment]
Yep, can u send us where the fix commit is?

**Comment by vBrenth** [comment]
@Mysteries tested on the very latest hercules its still a bug :D

**Comment by vBrenth** [comment]
Still Bumping this one.

**Comment by vBrenth** [comment]
Any update on this one? Its been years.
