### ISSUE TITLE
Dispell skill is not working on @duel state

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#640]
SA_DISPELL skill is not working on @duel state ^^

**Comment by MishimaHaruna** [comment]
Could you elaborate a little more on this?

- Does it work between an user in duel and one outside duel? (intended not to work)
- Does it work between two users in the same duel? (intended to work)

**Comment by kyeme** [comment]
Does it work between two users in the same duel? (intended to work) <-- This is not working in latest. Sage class cannot dispell even if there is gemstone availabe.

**Comment by AnisotropicDefixation** [comment]
That's due to the skill being only usable on party members outside of PvP flagged maps.

[code]
if( sd && dstsd && !map_flag_vs(sd->bl.m)
					&& (sd->status.party_id == 0 || sd->status.party_id != dstsd->status.party_id) ) {
					// Outside PvP it should only affect party members and no skill fail message.
					break;
{
[/code]

Can just add a duel_group exception or something.
