### ISSUE TITLE
Map server crash

### ISSUE THREAD

**Issue by belfallen** [HerculesWS/Hercules#646]
![crash](https://cloud.githubusercontent.com/assets/5786514/9278353/80930ef2-42da-11e5-92f7-adb9d92f341a.png)

dont know the reason, random crash, maybe in script?

**Comment by 4144** [comment]
This look like known issue.
If kick player in OnLogin* script

**Comment by belfallen** [comment]
i don't have any script kick player in OnLogin scripts ...

**Comment by belfallen** [comment]
are you sure? i will check it again with my kick scriptcommand :( @4144

**Comment by belfallen** [comment]
tested, not crash.. hmm :(

**Comment by 4144** [comment]
If variable correct on screen, look like after player was deleted, may be kick or other way, script continue to working.
Somewhere on forums was bug about it, not sure is it present in github bt

**Comment by belfallen** [comment]
@4144 , :( any temp fix for this bug T_T, crash daily :(

**Comment by 4144** [comment]
no except disable this kind of scripts.

But may be in your server it related to other.
What plugins you using?
If crash happend again, can you show call stack?

**Comment by belfallen** [comment]
how to show call stack?

me only enable dbghelpplug plugin T_T

**Comment by 4144** [comment]
On screen small tab in "Output" panel, named "call stack"

**Comment by dastgir** [comment]
Closing this as no reply from @belfallen
