### ISSUE TITLE
MonsterDB

### ISSUE THREAD

**Issue by OverLordDev** [HerculesWS/Hercules#649]
[Warning]: mob_readdb_race2: Unknown race2 7.
[Error]: sv_readdb: Could not process contents of line 19 of "db/re/mob_race2_db
.txt".
[Warning]: mob_readdb_race2: Unknown race2 8.
[Error]: sv_readdb: Could not process contents of line 21 of "db/re/mob_race2_db
.txt".

**Comment by dastgir** [comment]
Update your source and recompile.
Probably you haven't updated the source...
