### ISSUE TITLE
npc/other/item_merge.txt

### ISSUE THREAD

**Issue by OverLordDev** [HerculesWS/Hercules#650]
[Error]: script error in file 'npc/other/item_merge.txt' line 61 column 4
    parse_line: expect command, missing function name or calling undeclared func
tion
    58:                         mes "Merge just heard your wish and let it be re
alised!";
    59:                         mes "Open your inventory to check the miracle!";

    60:                         close2;
*   61:                         mergeitem();
        ~~~~~~~~~~~~~~~~~~~~~~~~^
    62:                         end;
    63:                 case 2:
    64:                         mes "[Mergician]";

**Comment by dastgir** [comment]
Yet again , update your source and recompile...
