### ISSUE TITLE
HP/SP regen while overweight and sitting.

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#651]
Right now you don't regen HP/SP while overweight and sitting, should regen it at half the speed.

Tension Relax also doesn't work when overweight.

if (flag && regen->state.overweight)
    flag=0;

This line seems to be at fault and negates the blocks above that allows halved regen while sitting.

**Comment by MordekaiserGod** [comment]
>Right now you don't regen HP/SP while overweight and sitting, should regen it at half the speed.
This is false. It works are intended. Completely disable regeneration.

>Tension Relax also doesn't work when overweight.
This is a bug. When overweight 50%, Tension Relax should regen at 1x.  When you are not overweight, Tension Relax regens at 3x.

**Comment by AnisotropicDefixation** [comment]
I remember reading somewhere that in renewal HP/SP recovery while overweight but sitting was allowed allowed at a very slow rate, might be wrong.

Tension Relax is broken for sure though.

**Comment by Jedzkie** [comment]
This issue is already fixed. Closing now.
