### ISSUE TITLE
Cart Tornado formula is wrong

### ISSUE THREAD

**Issue by Historica** [HerculesWS/Hercules#659]
On Hercules this skill damage become insane when Genetic reach 149 or more total str. The current formula from repository take total str while in official it use base str.

Current repository battle.c
skillratio = 50 \* skill_lv + (sd ? sd->cart_weight : battle_config.max_cart_weight) / 10 / max(150 - strbonus, 1) + 50 \* (sd ? pc->checkskill(sd, GN_REMODELING_CART) : 5);

With that formula a 149 or more total str Genetic will get (250+10500+250)% skill ratio. This should be 150 minus base str like official so 130 base str Genetic will get (250+525+250)% skill ratio

**Comment by Smokexyz** [comment]
int strbonus = bst->str;
bst invokes base_status.

**Comment by Historica** [comment]
In game test with current formula. Lv 1 cart tornado with Lv 5 cart remodeling and full cart (10500/10500)

1 base str , 150 bonus str , 37883 damage
http://114.imagebam.com/download/087LO_XqzaOudG89z-nmgQ/43128/431270826/screenNTRO010.jpg

130 base str , 2558 damage
http://113.imagebam.com/download/4lKDpS8khuwIE-7i8VK0pw/43128/431272129/screenNTRO012.jpg

**Comment by MrKeiKun** [comment]
https://github.com/HerculesWS/Hercules/pull/2927 should fix this...
