### ISSUE TITLE
Land Protect... Skill doesn't work in maps (Against MVP bosses)

### ISSUE THREAD

**Issue by Helheim90X** [HerculesWS/Hercules#661]
Do the prove, with Amon RA, set a land, and walk into the view ratio of Amon Ra... meteor still causes Damage to the player... on Land Protector

**Comment by kyeme** [comment]
This http://herc.ws/board/tracker/issue-8693-land-protector-meteor-storm-bug/?gopid=25378#entry25378 ?

**Comment by Playtester** [comment]
Yeah, this is intentional behavior in both pre-renewal an renewal. LP doesn't protect you from damage, it only protects from AoE cells being placed on the cells.

If you can see the meteor then it will do full damage. Meteors prevented by LP will not even display.
