### ISSUE TITLE
No data for enriched ores in refine_db.txt

### ISSUE THREAD

**Issue by Smokexyz** [HerculesWS/Hercules#666]
There is no data for enriched ores in refine_db.txt and no support for it. Enriched ores use and have the same getequippercentrefinery() as normal ores. is this a known issue?

% of success for enriched ores should be - 

Upgrade	Lv. 1		Lv. 2		Lv. 3		Lv. 4		Armor
+4 -> +5	100%	100%	100%	90%		90%
+5 -> +6	100%	100%	90%		60%		60%
+6 -> +7	100%	90%		75%		60%		60%
+7 -> +8	90%		60%		30%		30%		30%
+8 -> +9	60%		30%		30%		30%		30%
+9 -> +10	20%		20%		20%		10%		10%

**Comment by emistry** [comment]
https://github.com/HerculesWS/Hercules/blob/master/npc/re/merchants/advanced_refiner.txt#L158

it's not 20% ... I dont think there really exist an evidence of "20%" bonus of refine rate in kRO.

refine_db.txt only used to set the base refine rate for all level of equipments

**Comment by hemagx** [comment]
in Aegis there's two tables for refine rates ( premium ores/ free ores ) also there's a third missing modifier in the success chance calculation

**Comment by Smokexyz** [comment]
Since it's just the success rate that changes, could we not just add Chance+1:ChancePremium+1:Bonus+1 in the refine_db.txt ?

**Comment by AnisotropicDefixation** [comment]
That's not how those ores work, what they do is reroll your refine once if the first attemp fails.

**Comment by Smokexyz** [comment]
Well, if Aegis has a second refine db for premium, I don't think that's how it works on official. Also is iRO that much different from kRO then?

**Comment by emistry** [comment]
suggest for overhaul of refine_db.txt for better control over refine rate ...
http://herc.ws/board/topic/5101-overhaul-refine-db/

the current one is way too hard to read when more and more modifier is added xD

**Comment by Smokexyz** [comment]
Good suggestion, added a PR on related - hope it's okay.
https://github.com/HerculesWS/Hercules/pull/671
