### ISSUE TITLE
Visual Studio 2015 Compile warnings

### ISSUE THREAD

**Issue by Angelmelody** [HerculesWS/Hercules#673]
1>------ Rebuild All started: Project: char-server, Configuration: Debug Win32 ------
2>------ Rebuild All started: Project: login-server, Configuration: Debug Win32 ------
3>------ Rebuild All started: Project: map-server, Configuration: Debug Win32 ------
1>  grammar.c
2>  grammar.c
3>  grammar.c
2>  libconfig.c
1>  libconfig.c
3>  libconfig.c
2>  scanctx.c
3>  scanctx.c
3>  scanner.c
1>  scanctx.c
1>  scanner.c
3>  strbuf.c
1>  strbuf.c
2>  scanner.c
2>  strbuf.c
3>  mt19937ar.c
1>  mt19937ar.c
2>  mutex.c
1>  conf.c
1>  core.c
3>  conf.c
3>  core.c
2>  thread.c
2>  account_sql.c
2>  HPMlogin.c
1>  console.c
3>  console.c
1>  db.c
3>  db.c
1>  ers.c
3>  des.c
2>  ipban_sql.c
3>  ers.c
1>  HPM.c
1>  malloc.c
2>  login.c
2>  loginlog_sql.c
3>  grfio.c
1>  mapindex.c
3>  HPM.c
3>  malloc.c
1>  mutex.c
3>  mapindex.c
3>  md5calc.c
1>  nullpo.c
1>  random.c
2>  conf.c
2>  core.c
3>  mutex.c
2>  console.c
2>  db.c
1>  showmsg.c
1>  socket.c
3>  nullpo.c
2>  ers.c
1>  sql.c
3>  random.c
3>  showmsg.c
3>  socket.c
1>  strlib.c
1>  sysinfo.c
3>  sql.c
3>  strlib.c
2>  HPM.c
3>  sysinfo.c
2>  malloc.c
2>  md5calc.c
1>  thread.c
2>  nullpo.c
1>  timer.c
2>  random.c
1>  utils.c
3>  thread.c
3>  timer.c
2>  showmsg.c
3>  utils.c
3>  atcommand.c
2>  socket.c
2>  sql.c
1>  HPMchar.c
1>  char.c
2>  strlib.c
3>  battle.c
1>  geoip.c
2>  sysinfo.c
2>  timer.c
1>  int_auction.c
1>  int_elemental.c
3>  battleground.c
1>  int_guild.c
1>  int_homun.c
1>  int_mail.c
2>  utils.c
3>  buyingstore.c
2>  mt19937ar.c
3>  channel.c
3>  chat.c
1>  int_mercenary.c
3>  chrif.c
3>  clif.c
1>  int_party.c
1>  int_pet.c
1>  int_quest.c
1>  int_storage.c
1>  inter.c
1>  loginif.c
1>  mapif.c
1>  pincode.c
3>  date.c
3>f:\code\herc\src\map\channel.c(633): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned char', possible loss of data
3>  duel.c
3>  elemental.c
3>  guild.c
3>  intif.c
3>f:\code\herc\src\map\clif.c(1953): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(2075): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>  irc-bot.c
3>f:\code\herc\src\map\clif.c(3623): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(3661): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
2>     Creating library ..\login-server.lib and object ..\login-server.exp
3>f:\code\herc\src\map\clif.c(5537): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(5590): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(5621): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(5638): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(5826): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(8047): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(8313): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(8343): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(8680): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(8688): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(9094): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data
3>f:\code\herc\src\map\clif.c(9128): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data
3>f:\code\herc\src\map\clif.c(9951): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(9960): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>  itemdb.c
3>f:\code\herc\src\map\clif.c(14920): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(16382): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\intif.c(147): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\clif.c(17951): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>  log.c
3>f:\code\herc\src\map\intif.c(175): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>  mail.c
3>f:\code\herc\src\map\intif.c(222): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\intif.c(260): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>f:\code\herc\src\map\intif.c(627): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
3>  map.c
3>  mapreg_sql.c
3>  homunculus.c
3>  HPMmap.c
1>     Creating library ..\char-server.lib and object ..\char-server.exp
3>  instance.c
3>  mercenary.c
3>  mob.c
3>  npc.c
3>  npc_chat.c
3>  party.c
3>  path.c
3>  pc.c
3>  pc_groups.c
3>  pet.c
3>  quest.c
3>  script.c
3>  searchstore.c
3>  skill.c
3>  status.c
3>  storage.c
3>  trade.c
3>  unit.c
3>  vending.c
2>  login-server.vcxproj -> F:\CODE\Herc\vcproj-14\..\login-server.exe
1>  char-server.vcxproj -> F:\CODE\Herc\vcproj-14\..\char-server.exe
3>     Creating library ..\map-server.lib and object ..\map-server.exp
3>  map-server.vcxproj -> F:\CODE\Herc\vcproj-14\..\map-server.exe
========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========

**Comment by QQfoolsorellina** [comment]
@MishimaHaruna 
bump...

**Comment by QQfoolsorellina** [comment]
up... fix these warnings...

**Comment by MishimaHaruna** [comment]
Visual Studio 2015 seems to be overly pedantic with size conversions. In a way, it's right, but I'm considering to just suppress that warning, since it'd get unmaintainable otherwise (I can't get other compilers to behave similarly)

**Comment by QQfoolsorellina** [comment]
Hm, I think I understand . I will ignore those warnings since those won't harm the server
