### ISSUE TITLE
Dragon Breath Damage

### ISSUE THREAD

**Issue by purityz** [HerculesWS/Hercules#679]
Old DB Formula:
{(Caster’s HP / 50) + (Caster’s MSP / 4)} x (Dragon Breath Skill Level x Caster’s Base Level / 150)} x Dragon Training This is Current formula on DB damage. 

New DB Formula:
{[(Caster's HP / 50) + ( Caster's MSP / 4)] × (Dragon Breath Skill Level × Base Level / 150)} × Dragon Training × Elemental modifier(1.25~2) × Ranged Damage(Expert Archer and so on)

**Comment by Smokexyz** [comment]
× (100 + Ranged Damage Modifers)% x (Elemental Modifiers)% x (100 + Racial Modifiers)%
this is added to the skill and also overall damage? or are they just specifying it for informative purposes that these modifiers are also taken into consideration, just not only or additionally added to DB.

**Comment by Smokexyz** [comment]
I don't think that those extra modifiers are exclusive to this skill. As i'm testing right now with
LongAtkRate: 0
HP:38657
MaxSP: 1861 
AddEle:0
AddRace:0
Output Damage: 18321

LongAtkRate: 7
HP: 38757
MaxSP: 1861 
AddEle: 25
AddRace: 0
Output Damage: 18351

with a 25% increase of damage on that particular race, there is no significant increase in damage. is this AddEle % increase not supposed to be added on all monsters of that element? Also LongAtkRate and AddRace?

**Comment by Kenpachi2k13** [comment]
Fixed in https://github.com/HerculesWS/Hercules/pull/1304.
