### ISSUE TITLE
WoE gear and consumable still work in instance

### ISSUE THREAD

**Issue by Historica** [HerculesWS/Hercules#686]
Vellum weapons
WoE / Siege armor sets
WoE potions (11547 11548 11549)

Shouldnt they disabled in instance ?

**Comment by Inzianity** [comment]
You can just set to disable those items by editing mapflag files.
But yeah, those should be fixed here so that whenever herc has an update that can overwrite stuff, the bugs won't recur.

**Comment by dastgir** [comment]
Afaik, They should be only enabled in woe
