### ISSUE TITLE
Vellum bow , WoE Arrow and WoE Quiver

### ISSUE THREAD

**Issue by Historica** [HerculesWS/Hercules#688]
item_combo_db.txt

1775:18113,{ bonus bLongAtkRate,70; }
1776:18113,{ bonus bLongAtkRate,40; }
1775:18114,{ bonus bLongAtkRate,50; }
1776:18114,{ bonus bLongAtkRate,20; }

I never found source that says Vellum Arbalest (18113) got combo effect with woe arrow. 
From googling several material only Vellum Crossbow (18814) got 70% and 40% combo effect.
While 50% and 20% is first release effect of crossbow and siege arrow in kRO (6/15/2011).

item_db.txt

	Id: 12677
	AegisName: "Siege_Arrow_Quiver_S"
	Name: "Siege Arrow Quiver S"
	Type: 2
	Buy: 2
	Weight: 100
	EquipLv: 130
	Script: <" getitem 1776,200; ">

Should be getitem 1775

	Id: 12678
	AegisName: "Siege_Arrow_Quiver_A"
	Name: "Siege Arrow Quiver A"
	Type: 2
	Buy: 2
	Weight: 100
	EquipLv: 95
	Script: <" getitem 1775,200; ">

Should be getitem 1776

**Comment by Jedzkie** [comment]
This issue is fixed already.
