### ISSUE TITLE
Impositio Manus

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#695]
Original topic: from Atemo https://github.com/rathena/rathena/issues/610

http://irowiki.org/wiki/Impositio_Manus

Lower levels of Impositio Manus will overwrite higher levels. For example, someone with level 5 IM activated will have +25 ATK from the skill, but if level 1 IM were used on them their ATK would drop to only +5. Therefore, this skill can be used offensively.
Confirmed on aegis.

**Comment by Smokexyz** [comment]
What's the issue here?

**Comment by iRagno** [comment]
Maybe RagEmu's fix could be applied?

**Comment by Jedzkie** [comment]
@MishimaHaruna is this good to merge now?
