### ISSUE TITLE
Invalid mob-class 2398

### ISSUE THREAD

**Issue by aleprincess** [HerculesWS/Hercules#702]
In a fresh emulator and latest version.

[Status]: Done reading '115' entries in 'db/pre-re/job_db.conf'.
[Status]: Done reading '34' entries in 'db/castle_db.txt'.
[Status]: Done reading '15' entries in 'db/guild_skill_tree.txt'.
[Warning]: pet_db reading: Invalid mob-class 2398, pet not read.
[Status]: Done reading '58' pets in 'pet_db.txt'.
[Status]: Done reading '0' pets in 'pet_db2.txt'.

pre-renewal edition

**Comment by aleprincess** [comment]
By the way, it is in pre-renewal version

**Comment by emistry** [comment]
The mob id doesnt exist in your mob_db.txt.
I dont think pre-renewal has mob with ID 2398.

**Comment by aleprincess** [comment]
Hmm ? 

I have checked the pet_db.txt

In the Line 120 has: // 14.2 Academy

https://github.com/HerculesWS/Hercules/commit/21564acf13fbfc10295e4b2e026c2d3b7ca07299

I think this bug has something related to that commited.

Thank you.

**Comment by aleprincess** [comment]
Confirmed. The bug started to show after this commited: https://github.com/HerculesWS/Hercules/commit/21564acf13fbfc10295e4b2e026c2d3b7ca07299

Just for PRE-RENEWAL version.

**Comment by dastgir** [comment]
Confirmed.. Will be fixed soon...

**Comment by aleprincess** [comment]
Thank you. :)

**Comment by kisuka** [comment]
As a temporary fix for you, disable that pet in your pet_db.txt

pet_db needs to be given re/pre support.
