### ISSUE TITLE
Scripting engine: pre-decrement operator

### ISSUE THREAD

**Issue by k-py** [HerculesWS/Hercules#705]
See the following test case:

```
prontera,156,180,4  script  test    81,{
    .@i = 2;
    while (.@i > 0 && callsub(PrintDebug, i)) --.@i;
    end;

PrintDebug:
    debugmes "i = " + getarg(0);
    return 1;
}
```

It leads to an infinite loop.

It works as expected after adding curly brackets:

```
prontera,156,180,4  script  test    81,{
    .@i = 1;
    while (.@i > 0 && callsub(PrintDebug, i)) {
        --.@i;
    }
    end;

PrintDebug:
    debugmes "i = " + getarg(0);
    return 1;
}
```

And this is a syntax error (maybe the expected behaviour?):

```
prontera,156,180,4  script  test    81,{
    .@i = -2;
    while (.@i < 0 && callsub(PrintDebug, i)) ++.@i;
    end;

PrintDebug:
    debugmes "i = " + getarg(0);
    return 1;
}
```

These examples also make it clear that logical operators are not short-circuited. That's probably how it has always worked, but it is disconcerting.

**Comment by MishimaHaruna** [comment]
This is a known issue. For the time being, please use curly brackets (it doesn't just happen with `while`, but also with `if`). There are also other very amusing cases where the parser gets it completely wrong, i.e.:

```
if (this_line_should_throw_an_error_but_it_does_not) < 1 {
    debugmes "Hello World";
}
```

About the short-circuiting of logical operators, yep, that's very true. It's on my wishlist for when I'll have time to take care of it (see the FIXME entries in `npc/dev/test.txt`)

**Comment by dastgirp** [comment]
Fixed https://github.com/HerculesWS/Hercules/pull/2077
