### ISSUE TITLE
crash client with quest Trick Dead (Academy)

### ISSUE THREAD

**Issue by Desground** [HerculesWS/Hercules#706]
how to get:
1)Take the quest dead trick
2)Relogin
Tested on 2014-10-22bRagexe and 2015-05-13aRagexe
[Info]: Git revision (src): '89e63d3c6131121d48079994e456af78efd4db37'
[Info]: Git revision (scripts): '89e63d3c6131121d48079994e456af78efd4db37'
[Info]: OS version: 'Windows 8 Enterprise (build 9200) [x86_64]' bug? I have installed windows 10.
[Info]: CPU: 'x86_64 CPU, Family 16, Model 5, Stepping 3 [4]'
[Info]: Compiled with Microsoft Visual C++ 2013 (v1800)

**Comment by kisuka** [comment]
At what point during the NPC dialog does it crash your client?

**Comment by Desground** [comment]
during the loading on 100%. only after the exit at the character selection and select again for that character.
sorry for my english.

**Comment by kisuka** [comment]
Make sure your client has all the needed files / is updated.

**Comment by Desground** [comment]
Client latest kro.

**Comment by Desground** [comment]
Sorry. the problem is not in the quest. problem in windows 10 crash occurs in all quests where has the time or whether it is time to complete the quest , or during restoration . Server can not determine the time in windows 10.

**Comment by kisuka** [comment]
Interesting. Might be an issue we need to look into.

**Comment by ErMaqui** [comment]
>>Info: OS version: 'Windows 8 Enterprise (build 9200) [x86_64]' bug? I have installed windows 10.
As Microsoft, if your app entitlement doesn't establish explicit compatibility with Windows 10, then, the OS identifies as Windows 8.

About the crash, did you try on a Linux Server? Maybe the crash are on the client itself...

**Comment by Desground** [comment]
does not seem that the fault of the client. in rathena not have such problems.

**Comment by MishimaHaruna** [comment]
There seems to be something wrong with the way Windows 10 (or Visual Studio 2015, I'm not sure which) handles the `time()` function.

@Desground can check if the following patch improves it in any way?

```
diff --git a/src/common/core.c b/src/common/core.c
index a0f16e7..1962d87 100644
--- a/src/common/core.c
+++ b/src/common/core.c
@@ -391,6 +391,7 @@ int main (int argc, char **argv) {
 		core->arg_v = argv;
 		core->runflag = CORE_ST_RUN;
 	}
+	time(NULL);
 	core_defaults();
 
 	iMalloc->init();// needed for Show* in display_title() [FlavioJS]
```

**Comment by Desground** [comment]
strange but the problem disappeared after I updated today Hercules. and
without time (NULL);

**Comment by Desground** [comment]
It is no longer happening. so close.
