### ISSUE TITLE
failed assertion error is back

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#708]
![asserterrormado](https://cloud.githubusercontent.com/assets/12475348/9727801/1c89df26-5603-11e5-9fbd-24c845dbdda4.jpg)

This happens when a player mounted on mado gear gets attacked by a normal attack (not skills).

This also throws errors with skill_get_ele and skill_get_delay functions.

**Comment by AnisotropicDefixation** [comment]
Looks good now, no idea what was causing this with get_skill_delay function though, I'll see if it happens again.

**Comment by MishimaHaruna** [comment]
Please let us know if it does. I didn't see anything related to `get_skill_delay` in the code path executed by normal attacks on mado gears.

**Comment by AnisotropicDefixation** [comment]
Just found another one, cast a bolt skill, use spellfist then hit the target, both cases usually trigger the warnings.

@MishimaHaruna
