### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#718]
When you're going to PM someone using the PM Box whose name is compose of 24 characters or more, theres a warning msg that will appear on the console.
![error_pm](https://cloud.githubusercontent.com/assets/4656578/9923834/16574d5c-5d2c-11e5-9813-c5f71d42a74b.jpg)
Im using 2015-05-13client

**Comment by hemagx** [comment]
that pretty normal ? the name should never be longer than 23 character

**Comment by dastgir** [comment]
Char name length 23 and a termination char,
Making it 24.
Also I wonder if >24 char name exist, since client would limit off the name.

**Comment by kyeme** [comment]
Opps, I mean any non existing name.
![1](https://cloud.githubusercontent.com/assets/4656578/9924067/5990d442-5d2e-11e5-863b-b93d2e48203e.jpg)

**Comment by dastgir** [comment]
Hmm.. This seems frustrating..
Maybe NULL character is not been added.

**Comment by kyeme** [comment]
~ Up ~

**Comment by MishimaHaruna** [comment]
If the client allows sending names longer than 23 characters (or in other words, can send names without a NULL terminator, then we can remove the warning message.

**Comment by Kenpachi2k13** [comment]
I did a some testing and Gravity's developers really are strange people.

The name field in the character creation windows as well as the name field in the chat box can hold a maximum of 24 characters.
When trying to create a character name with 24 characters you'll get an error message which tells you that you're limited to 23 characters.
But when trying to PM a character name with 24 characters you'll get the "There is no such character name or the user is offline." message.

In my opinion we should simply add a `NULL` terminator ourselves and remove the warning message.

**Comment by 4144** [comment]
probably 24 chars works some times, because packets placed in buffer, and in buffer often exists 0 code, this mean almost always 24 chars will not crash server or client, but may crash randomly if here not allowed 24 chars.
need check with disassembler each packet for check is it works with 24 or 23 chars

**Comment by Kenpachi2k13** [comment]
Hmm, we're not supporting names with more than 23 characters in any case.
I don't think we should start making exceptions now just to mimic an obvious bug of Gravity.

**Comment by MishimaHaruna** [comment]
Ok, since the character creation is limited to 23 (and we limit it to 23 nearly everywhere anyway), there's no point in supporting 24 in the whisper packet. Let's enforce a `'\0'` on the 24th character as a safety measure

**Comment by Kenpachi2k13** [comment]
After a closer look at the code of `clif_parse_WisMessage()` I think we really should allow 24 characters for whisper names.

1. The whisper name can contain "*NPC:*" and with a limit of 23 characters we're only able to whisper NPCs with names shorter than 20 characters. With a limit of 24 we get an additional character for the NPC's name.
2. It does not break anything to allow 24 characters.
