### ISSUE TITLE
Duplicated NPC with Const Sprite Name isnt visible.

### ISSUE THREAD

**Issue by emistry** [HerculesWS/Hercules#719]
Sample NPC Script : http://pastebin.com/raw.php?i=Z1VuS3r2

![Image](http://i.imgur.com/yYDBys4.jpg)

As you can see from the picture, several *duplicated* NPC with __Const NPC Name__ isnt visible. 

Error shown in Map server
![Image](http://i.imgur.com/J3Y8TIS.png)

__1_M_YOUNGKNIGHT__ isnt a custom npc const name.
https://github.com/HerculesWS/Hercules/blob/master/db/const.txt#L2476

**Comment by dastgir** [comment]
Npc name is at fault
The script you posted have extra space.
I.e 
npc#001<space><tab>CONSTANT.
eliminating the space will fix the error.

**Comment by emistry** [comment]
if that's the case, the error message should be change to something more related to the issue itself.

LOL .. i cant think of how the "spacing" name can relate to "no view data for class 1"

aren't it suppose to show : 
- invalid npc name (spacing/tab)

**Comment by MishimaHaruna** [comment]
The number parser is less strict than the constant parser, so it falls back to that (and matches the `001` part as `1`). It can certainly be made stricter (or removed, since it's deprecated), so that the error message would be about a syntax error, rather than an invalid id
