### ISSUE TITLE
market NPC console warning

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#720]
![marketerror](https://cloud.githubusercontent.com/assets/12475348/9947653/1d8c6ce0-5d9c-11e5-81d6-633accad7da9.jpg)

Happens for every item added to the list upon opening the shop, regardless of using Aegis name or ID. 

You can also move around and interact with other NPCs while the shop is open.

There's also something wrong with weight limits as it won't let you purchase more than a few items.

**Comment by AnisotropicDefixation** [comment]
I guess this kind of merchant NPC isn't really usable for now.

**Comment by MishimaHaruna** [comment]
Just to make sure, is this about the `NST_MARKET` shops?

If so, do you have any SQL errors (or warnings/errors of any kind on startup)? Any unexpected values (invalid item IDs) in your `npc_market_data_db` database table?

About the limited amount - are you positive it has something to do with the weight limit? How many items are in stock and how many are you trying to purchase?

**Comment by AnisotropicDefixation** [comment]
Yeah, NST_MARKET.

Nope, no errors.

It seems to be somewhat weight related as I can purchase more of light items that heavy ones. Let's say I can purchase only 2 Oridecons but 5 Fly Wings (not exact amounts, just an example).
I can't played with the stock amounts, just set them to 99999.

**Comment by dastgir** [comment]
I hope this isn't because you are using client which don't have market packets...

**Comment by AnisotropicDefixation** [comment]
Using 2014-01-15, which should have them according to packets.h since they were added with 2013-12-18, unless those were changed for newer clients? The only market entries are for  2013-12-18.
Wouldn't it just throw unknown packet error and disconnect if that was the case though?

**Comment by MishimaHaruna** [comment]
Could you provide a minimal example script that causes this to happen?

**Comment by AnisotropicDefixation** [comment]
prontera,159,167,4	trader	Aurora#paramk	91,{
OnInit:
	tradertype(NST_MARKET);
	sellitem 969,1000000,20; 			//Gold
	sellitem 7289,500000,20; 			//Peridot
	sellitem 7290,500000,20; 			//Phlogopite
	sellitem 7291,500000,20; 			//Agate
	sellitem 7292,500000,20; 			//Muscovite
	sellitem 7293,500000,20; 			//Rose Quartz
	sellitem 7294,500000,20; 			//Turquoise
	sellitem 7295,500000,20; 			//Citrin
	sellitem 7296,500000,20; 			//Pyroxene
	sellitem 7297,500000,20; 			//Biotite
	end;

OnWed0000:
OnMyResupply:
	if( shopcount(969) < 20 )
		sellitem 969,1000000,20;
	if( shopcount(7289) < 20 )
		sellitem 7289,500000,20;
	if( shopcount(7290) < 20 )
		sellitem 7290,500000,20;
	if( shopcount(7291) < 20 )
		sellitem 7291,500000,20;
	if( shopcount(7292) < 20 )
		sellitem 7292,500000,20;
	if( shopcount(7293) < 20 )
		sellitem 7293,500000,20;
	if( shopcount(7294) < 20 )
		sellitem 7294,500000,20;
	if( shopcount(7295) < 20 )
		sellitem 7295,500000,20;
	if( shopcount(7296) < 20 )
		sellitem 7296,500000,20;
	if( shopcount(7297) < 20 )
		sellitem 7297,500000,20;
	end;
}

It seems like the SQL warning no longer happens but you still can't purchase more than x amount of item, which is 5 in the case of stones in this script yet the whole stock of gold can be bought out.

**Comment by MishimaHaruna** [comment]
This seems to be a client issue rather than a server issue...

I tried the example script with a 20131223 client, and I can confirm the behavior you describe. I can buy the full stock of Gold, but not the rest of the items, which are limited to 5~6.

When I try to purchase more, just after dragging an item to the buy list, I see the msgstringtable line 2537 (I don't know what's the right message, but it shows that line). There's no interaction between client and server at that point though, the client just refuses to accept certain item IDs and accepts others, but it's entirely clientside...
As such, I believe there's nothing we can do.

**Comment by AnisotropicDefixation** [comment]
Now that I think about it, considering this type of NPC offers a limited stock, it would make sense to prevent people from buying it out in one go so that others get a chance too, maybe some packet is supposed to be sent?

**Comment by chatchanunn** [comment]
Hello, dev

I found some behavier about item weight and shoptype.

If charactor have weight == 0 , max_weight == 4000
and itemid == 501 (Red_Potion) weight 7 (70)

I can buy stuff about 80 ea (max_weight/itemid) not 571 ea for real weight ( max_weight/item_weight )

I try to find sourcecode in npc.c but not found something control that but I think you can do this.

So herc server read weight = itemid not real item weight.

Sometime, I think it may be bug about packet arrangement.

Sorry about my English.
