### ISSUE TITLE
Eden Group timer quest - client crashed

### ISSUE THREAD

**Issue by mirivlad** [HerculesWS/Hercules#722]
Greetings. I found a strange bug when making Eden Group quests. A character who took Eden quest timer - after the quest expires (apparently) no longer enter the game - after logging a character client crashes. The problem is solved by removing all input character quests from the database table where the values of `quests` field` time` nonzero.
If you do not understand written - inquire, translated by Google.

Приветствую. Обнаружил непонятный баг при принятии  квестов Эден Груп.  Персонаж который взял квест Эден с таймером - после того как время квеста истечет (видимо) перестает входить в игру - после логина такого персонажа клиент вылетает с ошибкой. Проблема входа решается удалением всех квестов персонажа из БД в таблице `quests` где значения поля `time` отличны от нуля.
Если не понятно написано - спрашивайте, переводил через гугл.

**Comment by dastgir** [comment]
Which client do you use?

**Comment by Desground** [comment]
Windows 10? У меня такой же баг был.

**Comment by mirivlad** [comment]
Клиент что на 7 что на 10 крашится. Сервер на убунте 32 бита.
18.09.2015 18:21 пользователь "Alexey" <notifications@github.com> написал:

**Comment by ErMaqui** [comment]
He's asking about ragnarok client version

**Comment by mirivlad** [comment]
Client version 2015-05-13aRagexe patched with Nemo

**Comment by mirivlad** [comment]
Updated: client crash not is not associated with quests at the time but is still a problem with Eden Group quests. 
What is causing the problem quest - is unclear.

**Comment by dastgir** [comment]
Don't use that client
Client >= 20141022 have issue of quest timers not been handled correctly.(because there's some new packets yet to be coded)

**Comment by mirivlad** [comment]
Well, i recompile server with 201402* packet version, and try game. Old prontera, no new sets for 100+ job T_T
And again crash client if have eden group quests >_<. On windows 7, 8.1, 10. Its only for me?

**Comment by MishimaHaruna** [comment]
This should be fixed as of be5c38f5bf7f316eebd301f91fde888dffd844e6 (if it isn't, please reopen)
