### ISSUE TITLE
Plugin addBattleConf

### ISSUE THREAD

**Issue by SamuelHercules** [HerculesWS/Hercules#723]
I have added battleconf settings into the plugin which is loaded perfectly.
 
The problem is, the value can't be detected by the script command getbattleflag
 
Although setbattleflag command can affect the custom battle_conf setting I have made with the plugin.

I have checked the getbattleflag and it seems to just check the battle_data which is limited to the list in battle.h? or is there a way getbattleflag can read custom battleconf settings added in a plugin?

Thanks!

**Comment by MishimaHaruna** [comment]
Confirmed. `getbattleflag` doesn't check for plugin-owned configuration settings.

**Comment by Samuel23** [comment]
bump?
