### ISSUE TITLE
Can't compile with VS2012

### ISSUE THREAD

**Issue by VeilsideGX** [HerculesWS/Hercules#726]
Using Hercules-11.sln, I'm getting a lot of errors. (VS2012)
![herc-error](https://cloud.githubusercontent.com/assets/5967371/9980227/f82805c6-5fc2-11e5-9384-adbcab476208.png)

This is a fresh copy of Hercules without any modification

**Comment by MishimaHaruna** [comment]
Confirmed. There is a C99 construct in `atcommand_stopattack`.

**Comment by VeilsideGX** [comment]
Thanks, hoping for sooner solution to this so I can test for further bugs.

**Comment by VeilsideGX** [comment]
Hi there's still an error when compiling. The clif.c is not yet fixed.
![err 1](https://cloud.githubusercontent.com/assets/5967371/10010695/6ba42b1a-6121-11e5-9cd2-35256f8bc887.png)

**Comment by MishimaHaruna** [comment]
Thank you, fixed in 6b135d6

**Comment by QQfoolsorellina** [comment]
@MishimaHaruna 
What about 2015 ?
https://github.com/HerculesWS/Hercules/issues/673

**Comment by VeilsideGX** [comment]
Thank you @MishimaHaruna
