### ISSUE TITLE
Summoned elemental attack monsters are MISS

### ISSUE THREAD

**Issue by idamonli** [HerculesWS/Hercules#727]
Magic attacks are damage.
but Ordinary attack without damage, is MISS .

**Comment by idamonli** [comment]
Tracking found  Damage battle_calc_weapon_attack 
return wd;
wd damage = 0
wd damage2 = 0

**Comment by pengc2010** [comment]
I think Hercules does not have the elemental spirit fully supported.
To temporarily solve this weird issue, in "status.c"
change
```javascript
	else if (bl->type == BL_HOM && watk->atk) {
		if (flag & 4) {
			max = min = status->get_matk(bl, 2);
		}
		else {
			min = watk->atk;
			max = watk->atk2;
		}
	}
```
to
```javascript
	else if (bl->type == BL_HOM && watk->atk && (flag & 4)) {
		max = min = status->get_matk(bl, 2);
	} 
	else {
		min = watk->atk;
		max = watk->atk2;
	}
```

It's not a solution, just make the elemental spirits looks better...
I don't know if the core devs have plan to implement the elemental spirits in the near future or not.
