### ISSUE TITLE
VIP System is outdated.

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#729]
Hi Haru, It seems our VIP System is outdated, and Also the Questlog System (rAthena commit: https://github.com/rathena/rathena/commit/039e1b65a3cae96d80b220f078814cac72846737). 

Thanks!

**Comment by dastgir** [comment]
Lol, we had that questlog thing from many months..

Though, we don't have proper VIP system.

**Comment by Smokexyz** [comment]
any details on this? so someone or I can get this done.

**Comment by dastgir** [comment]
rA have this: https://rathena.org/board/topic/89848-official-vip-system/ , see the features..

(Also , it could be good if we can have multiple VIP statuses?)
Like VIP 1- 12 char slot
VIP 2- 14 Char slot,
Though this is extra, the one on rA forum are official features

**Comment by hemagx** [comment]
i was actually thinking of work on this one ! :)

**Comment by Jedzkie** [comment]
@hemagx can we talk about this? I have informations about this.

**Comment by hemagx** [comment]
@Jedzkie Sure! talk to me on IRC ( Ema ) or send Private Message

**Comment by SamuelHercules** [comment]
bump? :D

**Comment by sgsilva** [comment]
bump?
