### ISSUE TITLE
Quest DB Drop Issues

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#733]
Is this inteded? If i set a Monster ID (ex: 1002), and set an item (ex: 501) All of its normal drops are disabled, even the 100% rate. Please check this. Thanks!

**Comment by dastgir** [comment]
If that happens, that is not intended

**Comment by MishimaHaruna** [comment]
Is this reproducible? If so, can you provide an example of quest DB modification that creates this problem on a clean Hercules?

**Comment by Ridley8819** [comment]
I can't reproduce this
