### ISSUE TITLE
SQL upgrades should specify their destination database

### ISSUE THREAD

**Issue by MishimaHaruna** [HerculesWS/Hercules#734]
While we support (and encourage) using different databases for main and logs, we don't differentiate between upgrades that affect the main database and those that affect the logs database.

The two types of upgrades should be separated (and kept track of separately, in each database).

**Comment by Kenpachi2k13** [comment]
Since we're not using different databases for main and logs anymore, this can be closed.

**Comment by 4144** [comment]
actually hercules can use separate databases. It not using them with default configs, but configs change is possible.
