### ISSUE TITLE
Error messages for server connections denied by network.conf are misleading

### ISSUE THREAD

**Issue by MishimaHaruna** [HerculesWS/Hercules#737]
When the `allowed` networks aren't correctly configured, the error messages are misleading and should be edited to reflect the actual error.

This is what currently happens:

```
[Status]: The login-server is ready (Server is listening on the port 6900).

[Info]: Connection request of the char-server 'Hercules' @ 192.168.1.72:6121 (account: 's1', pass: 'p1', ip: '192.168.1.72')
[Notice]: Authentication accepted (account: s1, id: 1, ip: 192.168.1.72)
[Notice]: Connection of the char-server 'Hercules' REFUSED.
[Info]: Closed connection from '192.168.1.72'.
```

```
[Status]: The char-server is ready (Server is listening on the port 6121).

[Info]: Attempt to connect to login-server...
[Status]: Connecting to 192.168.1.72:6900
[Error]: Can not connect to login-server.
[Error]: The server communication passwords (default s1/p1) are probably invalid.
[Error]: Also, please make sure your login db has the correct communication username/passwords and the gender of the account is S.
[Error]: The communication passwords are set in /conf/map-server.conf and /conf/char-server.conf
[Warning]: Connection to Login Server lost.
```

The login server says that authentication was accepted, then says the connection was refused, without showing any message about the reason. Ideally, we'd want the _authentication accepted_ message to be never shown in this case, and instead a message about the unauthorized IP should be printed.

The char server suggests that the problem might be an incorrect username/password pair, while this is not true. We could provide a proper error code to the character server, so that it can show the correct suggestion in this case.

This soft-depends on #736, in order to have a clean implementation.

**Comment by kyeme** [comment]
Sir why this not enable by default?

allowed: (
	"0.0.0.0:0.0.0.0",
	// "127.0.0.1:255.0.0.0", <-- this
)

**Comment by MishimaHaruna** [comment]
That's because it's unnecessary. The localhost network is included by default in the `trusted` stanza, and `allowed` automatically includes all the IPs in `trusted`
