### ISSUE TITLE
Client side stuck at trading

### ISSUE THREAD

**Issue by pengc2010** [HerculesWS/Hercules#740]
To reproduce it:
Try to trade with other players while talking with any npc.
The message box will disappear and you get stuck.

**Comment by kyeme** [comment]
I can't reproduce

**Comment by Jedzkie** [comment]
This is also present in official servers.

**Comment by Jedzkie** [comment]
This issue is already fixed by this commit: https://github.com/HerculesWS/Hercules/pull/1694 closing this now.
