### ISSUE TITLE
Missing packet at arrows de-equip

### ISSUE THREAD

**Issue by kontownik** [HerculesWS/Hercules#745]
Main problem: when I equip arrow it's good I got state change packet, but on de-equip I didn't get state 0.

rev. e6d9b557c979954d49f80d180696d0fa50ff1db0  Date:   Mon Aug 31 16:30:03 2015 +0800
packet version: 20130807

At equip I got:
[Network] Recv: PACKET_ZC_MSG_STATE_CHANGE4 {index: 695, AID: 2000001, state: 1, TotalMS: 9999, RemainMS: 9999…}

which is good but when I try to de-equip it...

[Network] Send: PACKET_CZ_REQ_TAKEOFF_EQUIP {index: 6}
[Network] Recv: PACKET_ZC_ACK_TAKEOFF_EQUIP_V5 {index: 6, wearLocation: 32768, result: true}

There should be additional packet like:
PACKET_ZC_MSG_STATE_CHANGE4 of index 695 with state 0

**Comment by kontownik** [comment]
none can confirm???

**Comment by kontownik** [comment]
bump

**Comment by MishimaHaruna** [comment]
Does aegis send that packet?

**Comment by Jedzkie** [comment]
@MishimaHaruna Aegis sends this packet.

**Comment by malufett** [comment]
this a renewal changed..where ammunition requirements are now being checked when changing states, equipment and job..confirmed in aegis..same with carts, bullets, equip and mounts...

**Comment by Jedzkie** [comment]
@malufett please reponse on my pm's senpai <3 <3 <3

**Comment by kontownik** [comment]
em my first post explains exactly whats missing (its logic that if we change state once we should change it again when it's off)
