### ISSUE TITLE
atcommand jobchange no longer lists jobs

### ISSUE THREAD

**Issue by theultramage** [HerculesWS/Hercules#759]
When I execute atcomand job/jobchange with no parameters, since https://github.com/HerculesWS/Hercules/commit/7064ec3fd365221a0aa4e891c7045032ff1bf0c2 it will print "You are unable to change your job" instead of listing the available job names and ids.

This is because the committer mistakenly changes a pointer check into a zero byte terminator check, which makes no sense in this context. The correct change (assuming null pointers really don't happen anymore) would have been to remove the check entirely and un-indent the whole block of code. The pointer check originated in https://github.com/HerculesWS/Hercules/commit/b4136dd3d4779d80df18f84929c576c8080cd7b8.

**Comment by VeilsideGX** [comment]
Yes this happens to me too..
