### ISSUE TITLE
[Client 2014-10-22b] Quest Issues

### ISSUE THREAD

**Issue by tmav94** [HerculesWS/Hercules#762]
You cant have more than 1 active quest on your character. If you got mora than this, you will get gravity error after re-enter in your character...

You can have how many quests do you want...but if you disconnect or re-log you will never enter without delete the values in mysql...

**Comment by belfallen** [comment]
confirm, recall @4144 @dastgir  @MishimaHaruna

**Comment by ossi0110** [comment]
2014-10-22b ragexe is way to unstable too use it on a live server , i rly recomend to use a exe below this date

**Comment by Desground** [comment]
confirm, but on client 2013-XX-XX error not.

**Comment by tmav94** [comment]
@ossi0110, sorry but i dont think so... 2014 clients works fine on my live server...The only problem that i found is it.

**Comment by ossi0110** [comment]
trust me @tmav94  its not stable give it some time and you will figure it out .

**Comment by dastgir** [comment]
There were some different packets, no idea if it was implemented...
And about 2014-10-22 , I wouldn't also tell it as stable, as it would crash on several occasions due to missing packet or w/e issue.

**Comment by Desground** [comment]
I have this error occurs only on Eden quest. Where you can take more than one quest.

**Comment by tmav94** [comment]
@Desground, you will get Gravity Error for get more than 1 quest in "Quest" Table (SQL);
Test it...if you get two quest you will get error, if you get only 1 you can play happy =D

I feel it's missing a little something in packet_db...

**Comment by Desground** [comment]
I only have to Eden quest appears error. On the other quests can take more than one without error.

**Comment by dastgir** [comment]
Please state which quests of Eden(quest Id if possible)
And we will check and fix if required.

**Comment by Desground** [comment]
All Eden Group Leveling Quests which can take more than one. If you take more than one quest. Or will show only one taken quest.In any case, if we continue to take the quests, you get an error.Correct you can only remove the quests in SQl. (checked only Client 2014-10-22b and 2015-05-13a).

**Comment by Desground** [comment]
After this update https://github.com/HerculesWS/Hercules/pull/811
bug not happen.
