### ISSUE TITLE
Frustration Item DB Id Limit

### ISSUE THREAD

**Issue by utofaery** [HerculesWS/Hercules#763]
Please do increase that limit or somehow ???

last I check anything beyond 32767 ??
Delete or erased on map changed or relog 

As of current version I haven't check yet,
since I am not with my desktop currently.

**Comment by ossi0110** [comment]
even if we increase the limit on the serverside , the client is still limited in the Item IDs

and current RE uses item IDs till 28000 , so you got more then 4000+ IDs free , what should be enough

**Comment by dastgir** [comment]
Nah nah nah....
Ossi, Haru was working on it...
Since 2012 I guess, it was changed as unsigned, supporting 65535 ids

**Comment by utofaery** [comment]
But why Ra4h3na use more than 32768 
without missing item deleted or erased?

Hercules hold so much promising stuff.
I really wanted to switch to hercules if  item dissappearing don't happens
Because i dont wanna upgrade my custom item db id
every time hercules upgrade.

**Comment by dastgirp** [comment]
Fixed in https://github.com/HerculesWS/Hercules/pull/2134
