### ISSUE TITLE
error occur for unitskillusepos script command.

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#768]
Sample Script : http://pastebin.com/raw.php?i=cjmDVb5A
## GIT Version

```
[Info]: Git revision (src): '4db986b93566d673c226971fa045f1dc99645242'
[Info]: Git revision (scripts): '4db986b93566d673c226971fa045f1dc99645242'
```
## Step to Reproduce :

Load the Sample Script given using by restart server / @reloadscript (First Error Shown) 
![Image](http://i.imgur.com/0CvStyT.png)

After that, execute @reloadscript ( second error below shown ) , you may try several times, it will show same result.
![Image](http://i.imgur.com/4ZThFxR.png)
Skill ID 85 = Lord of Vermillion.
## In-game Screenshot :

![Image](http://i.imgur.com/kx04Jwq.png)
The skill will continue cast by the NPC, but the error will not shown in map-server.
## Side Note :

Beside, somehow when I first try it, the map-server spam some other error from the core, I unable to reproduce the errors at the moment, but if I recall correctly, it's something related to nullpo reference I guess.
## Off-Topic :

It seem like NPC casting area skill is kinda useless... it's only 1 damage.. :-1:

**Comment by Ancyker** [comment]
In regard to the off topic bit, this command can be used with a monsters GID as well as a players GID (account ID/RID).

**Comment by emistry** [comment]
ya, but it become kinda useless if cast by NPC since NPC has no status build. only deal 1 damage.

**Comment by Kenpachi2k13** [comment]
This happens because the NPC's skill units can't be deleted when the NPC is unloaded.
The reason for this is the condition for calling `skill_clear_unitgroup()` in `npc_unload()`:
```
	if (nd->ud != NULL && nd->ud != &npc->base_ud)
		skill->clear_unitgroup(&nd->bl);
```
It's almost impossible to fulfil this condition since `nd->ud` always is `NULL` or `&npc->base_ud` if `unit_bl2ud2()` was never called for the NPC's `block_list` (for example `npcspeed()`).
