### ISSUE TITLE
Pin code different from aegis

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#769]
Repeated numbers (1111, 2222,...9999,) or sequential (1234, 5678, 0123, 6789, etc.) are not accept passwords for the system pin code. In addition to appearing a window with the msgstringtable line 1897

Also when you create the password for the first time a window appears with the msgstringtable line 1890

To change the password pops up a window with the msgstringtable line 1892.

When you enter the wrong pin code pops up a window with the msgstringtable line 1893.

Config oficial aegis:

```
SecondPWRestrictKeyTbl = 
{
    { [[0000]] }, 
    { [[1111]] }, 
    { [[2222]] }, 
    { [[3333]] }, 
    { [[4444]] }, 
    { [[5555]] }, 
    { [[6666]] }, 
    { [[7777]] }, 
    { [[8888]] }, 
    { [[9999]] }, 
    { [[0123]] }, 
    { [[1234]] }, 
    { [[2345]] }, 
    { [[3456]] }, 
    { [[4567]] }, 
    { [[5678]] }, 
    { [[6789]] }, 
    { [[7890]] }, 
};


--//////////////////////////////////////////////////////////////////////////////
-- Second Password를 사용하지 않는 IP 리스트를 등록합니다.
-- ex) 설정방법 : "{ [[192.168.5.50]] },"
--//////////////////////////////////////////////////////////////////////////////

SecondPWNoCheckIP = 
{
    { [[59.10.115.39]] },
    { [[59.10.115.28]] },
    { [[59.10.115.40]] },
};
```

**Comment by kyeme** [comment]
Welcome back Beret :D

I can confirm
Video: https://youtu.be/wTCWSoOyG60

http://herc.ws/board/tracker/issue-8435-pin-code-different-from-aegis/?gopid=24104#entry24104

**Comment by xBeret** [comment]
Thanks kyeme, let's fill this bug tracker xD

**Comment by Jedzkie** [comment]
Bump @MishimaHaruna
