### ISSUE TITLE
check weight is not working

### ISSUE THREAD

**Issue by aleprincess** [HerculesWS/Hercules#770]
https://github.com/HerculesWS/Hercules/blob/master/npc/merchants/refine.txt
Line 1044:
	if (checkweight(1201,1) == 0) {
		mes "- Wait a minute !! -";
		mes "- Currently you're carrying -";
		mes "- too many items with you. -";
		mes "- Please try again -";
		mes "- after you lose some weight. -";
		close;
	}

Even if you're carrying too many items, the npc wont use the "checkweight"

Thank you.

**Comment by dastgir** [comment]
It checks If there's weight of 1201 item ,if yes , the script proceeds

**Comment by aleprincess** [comment]
Oh alright thank you
