### ISSUE TITLE
Status point after raise

### ISSUE THREAD

**Issue by vykimo** [HerculesWS/Hercules#775]
If I die and I try to rise up my status points, it doesn't work as well.
But if i'm resurrected, I still cannot rise up status points... It looks like a bug with paquet, right? Or maybe it's only a problem with client?
Tell me more please
PS: Using 2015 client

**Comment by MishimaHaruna** [comment]
This sounds like a clientside issue. I'm not sure, though, if it's only because the client is expecting something we're not sending (it'd require a check in AEGIS in similar conditions with the same client version)

**Comment by hemagx** [comment]
After checking on Aegis, it seem like client bug, the client should be refreshed after death or it wont be able to raise points ( and this what happen in normal respawn )
