### ISSUE TITLE
clif.c:5409: 'mes' in function `clif_displaymessage'

### ISSUE THREAD

**Issue by Shyne** [HerculesWS/Hercules#776]
i dont know, just any sorcerer login my server, it will make map-server got crash A Signal.
I ran debug mode and i got that bug in my console.
P/S: Sorry my bad english
![screenshot 2015-10-08 12 13 28](https://cloud.githubusercontent.com/assets/2038294/10358377/dd9c6384-6db7-11e5-9006-c86cfabda9d8.png)

**Comment by 4144** [comment]
Probably you have corrupted mail table. May be at server start was error about broken db?
If yes try recover db with mysqladmin or other tools.

Can you rebuild server for better information about errors?
run
    make clean
    ./configure with your flags
    make
