### ISSUE TITLE
Unsupported Packet

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#779]
Is there anyone who can confirm if packet key 2015-05-13 client is not working? In my computer(win7) its working fine but if its compiled with CentOS 7 (I compiled many times) . its giving me an error when logging in
 "[Warning]: clif_parse: Received unsupported packet (packet 0x532a (0x0363), 19 bytes received), disconnecting session # 7."

Im using latest (rev. 20813)

**Comment by ossi0110** [comment]
yes the packet Keys Are Correct for this EXE

**Comment by dastgir** [comment]
It's fine, be sure to have packet obfuscation setting as 2  PACKETVER 20150513 And have recompiled the server...

**Comment by kyeme** [comment]
Same settings with my test server and CentOS,

conf/import/battle_conf.txt (im always use import folder)
packet_obfuscation: 2

in my mmo.h
PACKETVER 20150513

Compiled and run..

I can't connect in CentOS, but in my test server working w/o any error

I try to revert the revision and try again (Last week it's working fine)

**Comment by kyeme** [comment]
Ok problem solved. I rediff my client.

The weird thing is my previous client is working fine on my PC but not "unsupported packet" in Centos lol
