### ISSUE TITLE
plugin_load

### ISSUE THREAD

**Issue by aleprincess** [HerculesWS/Hercules#785]
I have to copile make all if i dont want to see this errors.

[Fatal Error]: HPM:plugin_load: failed to load 'plugins/HPMHooking_char.so' (error: plugins/HPMHooking_char.so: cannot open shared object file: No such file or directory)!
[Fatal Error]: HPM:plugin_load: failed to load 'plugins/HPMHooking_map.so' (error: plugins/HPMHooking_map.so: cannot open shared object file: No such file or directory)!

**Comment by dastgir** [comment]
Yes,
Use make all
or
make plugins

That will create these files,
If you don't use plugin altogether, you can disable plugin by editing conf/plugins.conf

**Comment by aleprincess** [comment]
So it isnt a bug?

**Comment by dastgir** [comment]
Nope, compiling plugin will fix it
