### ISSUE TITLE
The server provide english text only (msgstringtable.txt)

### ISSUE THREAD

**Issue by tmav94** [HerculesWS/Hercules#786]
Lagntype 1 (2013-08-07)
How to remove this issue? I diff my client to use ASCII and Arial for all langtypes and this is disturbin me...

**Comment by dastgir** [comment]
What you mean?

**Comment by kyeme** [comment]
He meant "Enable ACSII for all langtype" I think Neo remove this option..

**Comment by MStr3am** [comment]
I removed Enable Arial for all langtypes . Enable ASCII patch is still there.

**Comment by ossi0110** [comment]
change your langtype in the clientinfo.xml this will solve the problem
