### ISSUE TITLE
inconsistent whitespace in vcproj files after 3b89a135

### ISSUE THREAD

**Issue by theultramage** [HerculesWS/Hercules#792]
In https://github.com/HerculesWS/Hercules/commit/3b89a135dcde9779bd0537cd136a7c34cfadbe3f shennetsind added console.c and console.h to all projects, however they used tabs instead of spaces for indentation (probably from editing the files by hand). Microsoft switched to spaces starting with vs2010. Whenever a change is made to any of the projects using visual studio, it will correct this mistake, and by doing so introduce spurious whitespace changes.

**Comment by MishimaHaruna** [comment]
Interesting, thank you for the insight -- yes, they were edited by hand, most of us don't use Windows for development :x

**Comment by theultramage** [comment]
https://gist.github.com/theultramage/b83a3d64b230a762deab - patch, done by hand but should work.

**Comment by theultramage** [comment]
Oh, and vcproj-10/map-server.vcxproj and vcproj-11/map-server.vcxproj have a trailing newline at the end. Visual Studio, will, again, normalize this out if you hit the save button after changing something. Blame c0a502a3.
