### ISSUE TITLE
[Critical Bug] Refinement

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#800]
Defense and attack of upgraded equipment is not working.. Please confirm and let me know the temporary fix :(

I'm using pre-renewal

**Comment by kyeme** [comment]
@MishimaHaruna  @4144

**Comment by kyeme** [comment]
![ref_bug](https://cloud.githubusercontent.com/assets/4656578/10559248/caf93e96-751e-11e5-85dd-1d5898afb90f.jpg)

**Comment by dastgir** [comment]
I can confirm

**Comment by kyeme** [comment]
Thank you thank youuuuu.
