### ISSUE TITLE
mineffect

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#803]
The commit 75444c7 has been implemented incorrectly, the status applied is not the lesseffect, the correct status is mineffect.

Link Hercules: http://herc.ws/board/tracker/issue-7868-mineffect/

**Comment by xBeret** [comment]
bump

**Comment by xBeret** [comment]
bump @MishimaHaruna @4144

**Comment by xBeret** [comment]
@Kenpachi2k13 can you take a look?

**Comment by Kenpachi2k13** [comment]
@xBeret 
I had a look at it. The whole commit is pointless. Setting that flag has no relation to any state.
/mineffect is completely handled client side.
If the flag is set for a map, /mineffect will automatically be enabled when entering that map. (But you're still allowed to disable it again.)
Furthermore the client will re-apply the user's setting when leaving that map.
If the flag is not set, nothing happens.

Additionally I couldn't reproduce the issue reported in https://herc.ws/board/tracker/issue-7868-mineffect/. The state of /mineffect always persists after warping except it was disabled before warping and you warp to map where the `mineffect` flag is set (but it's re-applied when leaving that map). I used 2018-04-18bRagexeRE and 2019-08-02aRagexeRE for testing.

Based on this cognitions I'll change that code back to:
```c
p.flag.mineffect = map_flag_gvg(bl->m);
```
