### ISSUE TITLE
Shadow Item autobonus

### ISSUE THREAD

**Issue by byunjaeil** [HerculesWS/Hercules#806]
{
    Id: 24219
    AegisName: "Cold_Bolt_Shadow_Armor"
    Name: "Cold Bolt Shadow Armor"
    Type: 5
    Buy: 10
    Loc: 65536
    Script: <"
        if (getrefine()>=2) {
            autobonus "{ bonus3 bAutoSpell,14,(getrefine()/2),1000; }",(getrefine()*2)+100,100,BF_SHORT;
        }
    ">
},

I tried a variety of tests.
If you copy the option works identically on different items.

**Comment by MishimaHaruna** [comment]
Umm, what's the issue/question here?
