### ISSUE TITLE
The new refine system causes rates to be 100%

### ISSUE THREAD

**Issue by Nihadm89** [HerculesWS/Hercules#810]
As the title says, it applies to all refiners

**Comment by ossi0110** [comment]
cant confirm it 

i just tried it on latest Rev with 8 items , all items broke after +6 or +7

**Comment by Nihadm89** [comment]
The only updates I don't have are from the last 24 hours. I ended up reverting the refine commits and then everything was fine again. I don't see how anything in the last 24 hours could impact this.

**Comment by Nihadm89** [comment]
I'll poke around and figure it out. At least I know that a clean version works fine. Thanks

**Comment by Nihadm89** [comment]
Thx, figured it out. My conf files were messed up.
