### ISSUE TITLE
Warning when creating Instance

### ISSUE THREAD

**Issue by dastgir** [HerculesWS/Hercules#812]
```
[Warning]: npc_parseview: Use of numeric NPC view IDs is deprecated and may be removed in a future update. Please use NPC view constants instead. ID '111' specified in file 'INSTANCING', line '1'.
```

**Comment by Nihadm89** [comment]
This has also totally broken old glast heim. It doesn't load any npcs at all.

**Comment by dastgir** [comment]
False, it just warn, but loads npc

**Comment by Nihadm89** [comment]
Weird, that instance won't load any npc for me. And I'm using a clean version. All other instances work just fine. Dastgir can you confirm your old glast heim is working?

**Comment by dastgir** [comment]
@Nihadm89 
That's other issue I guess...

**Comment by Nihadm89** [comment]
Thanks for the fix.

**Comment by dastgir** [comment]
Thanks for the merge
