### ISSUE TITLE
Adding new skill gives error in console

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#814]
Hi!

I know this is not a support section, but i tried in 2 clean herc and still I failed.

I recently add the skill Return to Thanatos Skill from jRO. But seems it's not working in the latest version, i didn't tried any skill Id's other than the Official ID itself which is 3044. I already add the skill id in skill.h and also increase the MAX_SKILL in mmo.h, but still the server is not reading the skill. Here's the console error:

skill_db.txt
3044,0,0,4,0,0x1,0,1,0,no,0,0,0,none,0,		ALL_THANATOS_RECALL,Return to Thanatos

skill_castnodex_db.txt
3044,7,7	//ALL_THANATOS_RECALL

skill_cast_db.txt
3044,3000,0,0,0,0,300000

skill_require_db.txt
3044,0,0,1,0,0,0,99,0,0,none,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0	//ALL_THANATOS_RECALL#Return To Thanatos#

<img src="http://i58.tinypic.com/2mzoec.png">

**Comment by MishimaHaruna** [comment]
Increasing `MAX_SKILL` is not enough. You also need to modify the function `skill_get_index` to correctly map the new skill ID to an index of the `skill->dbs->db` array.
The function isn't as edit-friendly as it should, but it's like that for the time being. Keep in mind that you might need to increase the `MAX_SKILL` by more than just 1, depending on how you edit `skill_get_index` to map your new ID and how many gaps you leave not compacted.

**Comment by Jedzkie** [comment]
Thanks Haru!

**Comment by Jedzkie** [comment]
@MishimaHaruna haru, after I edit the skill_get_index part, the error is gone. But if i equip any items with adding this script 'skill ALL_THANATOS_RECALL,1;', the skill wont show, I already add the skill id in my lub files but it doesnt show. please help. thanks!
