### ISSUE TITLE
bonus bIgnoreDefRace,RC_DemiPlayer bug

### ISSUE THREAD

**Issue by belfallen** [HerculesWS/Hercules#815]
Bloody Roar : ItemID - 1265 effect not working

bonus bIgnoreDefRace,RC_DemiPlayer

bIngoreDefRace not work with RC_DemiPlayer, please check!

**Comment by AnisotropicDefixation** [comment]
SP_IGNORE_DEF_RACE
SP_IGNORE_MDEF_RACE
SP_DEF_RATIO_ATK_RACE
SP_ADDRACE2
SP_SUBRACE2

Weren't updated for the new RC_ constats and thus don't work.

**Comment by dastgir** [comment]
SP_ADDRACE2
SP_SUBRACE2
These are not needed, since they are RC2(race2) , which doesn't belong to RC_ constants..
However I noted several missing bonuses for elements too, and its added.
Thanks for reporting..
