### ISSUE TITLE
error in bonus items

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#819]
In hercules some bonus don't work like the aegis, seem a solution to work like.

Hercules is using a script entirely wrong, because when you use the item you are using an effect and not the skill as it is in the aegis,

for example the item:

```
    Inc_Agi_10_Scroll
```

script hercules:

```
Script: <"
    if(Hp>15) {
        skilleffect AL_INCAGI,0;
        sc_start SC_INC_AGI,240000,10;
        heal -15,0;
    }
">
```

script aegis:

```
item Inc_Agi_10_Scroll
    event OnConsume:
        SkillToMe AL_INCAGI 10
    return
```

Hercules is working totally wrong, needing extra code to function as the aegis.

I suggest create SkillToMe command, this command applies the skill the character who used the item, noting that if the skill is target it applies without needing to click on target to receive the skill.

**Comment by dastgir** [comment]
I agree, we need those commands.

**Comment by Ridley8819** [comment]
Bumping this :)

**Comment by iRagno** [comment]
What about `unitskilluseid(getcharid(CHAR_ID_ACCOUNT), AL_INCAGI, 10);`?

Makes the trick.

**Comment by Murilo-BiO** [comment]
@iRagno When using this item and `Guarana Candy` it shouldn't have cast time, it must be instantaneous.
