### ISSUE TITLE
item_db.conf bUseSPrate

### ISSUE THREAD

**Issue by byunjaeil** [HerculesWS/Hercules#821]
{
	Id: 2004
	AegisName: "Kronos"
	Name: "Kronos"
	Type: 4
	Buy: 20
	Weight: 1000
	Atk: 30
	Matk: 240
	Range: 1
	Job: 0x00010204
	Upper: 58
	Loc: 34
	WeaponLv: 4
	EquipLv: 50
	View: 23
	Script: <"
		bonus bInt,3+(getrefine()/2);
		bonus bMaxHP,300+(50*getrefine()/2);
		autobonus "{ bonus bMatkRate,12; bonus buseSPRate,20; }",1,5000,BF_MAGIC,"{ specialeffect2 EF_ENHANCE; }";
	">
},
...
[Error]: script_add_str: detected possible use of wrong case in a script. Found 'buseSPRate', probably meant to be 'bUseSPrate' (in 'autobonus').
...
buseSPRate -> bUseSPrate
Typing error.

**Comment by dastgir** [comment]
Fixed via https://github.com/HerculesWS/Hercules/commit/508543e1705b59e7e6ec959f6133147766dda804
