### ISSUE TITLE
Bound items comparison

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#822]
1. In Aegis, When dropping a Bounded item, there's no message showing 'This item cannot be dropped.', in Herc, there's a message.

2. in Aegis, When putting bound items in Storage, there's no message showing 'This item cannot be stored.', Instead it will show to you like you obtained the item, in Herc. there's a message.

<a href="http://tinypic.com?ref=2lo13dg" target="_blank"><img src="http://i62.tinypic.com/2lo13dg.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

3. in Aegis, When trading bound items, there's no message showing 'This item cannot be traded.', in Herc, there's a message.

4. In Aegis, When putting bound items in Cart, there's no message showing 'This item cannot be stored.' and 'You are over your weight limit.', Its like also in storage, It will show that you obtained the item again, in Herc, There's a message only.

Source: iRO Chaos

**Comment by MishimaHaruna** [comment]
Should we really mimic Aegis in cases like these, where they do worse than us?

**Comment by kyeme** [comment]
Right, in Official, there is no warning message when the item is non-storagable/droppabe/tradable/mail. It will be much better if we have a settings wherein we can enable or disable the warning message.

**Comment by Jedzkie** [comment]
@MishimaHaruna We are aiming to totally copy the configuration and the system of aegis. This is not a bug or something that breaks the mechanics of the game, this is the behavior of official servers.

**Comment by dastgir** [comment]
We do aim for totally copying aegis and their behavior only IF they are not having any flaw/bug.
In this case, I would agree with Haru..

**Comment by MishimaHaruna** [comment]
Accurate emulation or being an Aegis clone (i.e. including flaws and bugs) has never been a goal of this project, otherwise we'd have designed things differently in many situations (i.e. we'd have designed the scripting system to load the unmodified scripts from Aegis). Instead, from my point of view, whenever it makes sense, we aim to improve the user (and developer) experience.

**Comment by xBeret** [comment]
Show the item was obtained is interesting because it shows the player that the item may not go to the warehouse and that are in your inventory, many aegis systems use it, even when the player take an inventory item is blocked the drop and try to play on the floor appears that the item was obtained

**Comment by MishimaHaruna** [comment]
But the item was not obtained, you had it to begin with. The obtained message is misleading.

**Comment by Jedzkie** [comment]
@MishimaHaruna Hmmm what if we add a configuration that allows the developer to use the behavior of aegis? Isn't it ok?

**Comment by xBeret** [comment]
Is not misleading. Test the server aegis to view when you add an item in storage he goes to storage more verification of aegis know you're over the limit then sends the item to the inventory, so it shows the item obtained

**Comment by dastgir** [comment]
Aegis sends obtain packet, but item was never deleted to begin with, also the user would not know whats happening...

Also waste of 1 packet...

**Comment by Nihadm89** [comment]
I much prefer the message system. It seems like it would be effort put into something that isn't even an improvement, to me at least.

**Comment by dastgir** [comment]
Maybe its time to close this, since our system is better.
