### ISSUE TITLE
Storage behavior in Aegis

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#823]
If you have 30,000 piece of arrow or other stackable items, the system will show a message 'You cannot carry more than 30,000 of one kind of item.' and the system also show that you will newly obtained that item. Source is iRO.

See picture below

<a href="http://tinypic.com?ref=kapg5z" target="_blank"><img src="http://i61.tinypic.com/kapg5z.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by dastgir** [comment]
Same as #822, I think we have a better system than aegis

**Comment by xBeret** [comment]
Show the item was obtained is interesting because it shows the player that the item may not go to the warehouse and that are in your inventory, many aegis systems use it, even when the player pick up the item from the inventory and try to play on the floor appears that the item was obtained

**Comment by dastgir** [comment]
Maybe its time to close this, since our system is better. (Same as discussed via #822)

**Comment by Murilo-BiO** [comment]
Actually, there's a bug with our system:
When trying to move the item to storage or cart and the attempt fails, we can't grab the item anymore and we need to close storage or doing re-login. Maybe adding the `clif->additem` will fix it in client side...
