### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#826]
[Warning]: mob_read_db: drop item Black_Treasure_Chest not found in monster 1841
[Warning]: mob_read_db: drop item Black_Treasure_Chest not found in monster 1842
[Warning]: mob_read_db: drop item Black_Treasure_Chest not found in monster 1843
[Warning]: mob_read_db: drop item Black_Treasure_Chest not found in monster 1844

[Warning]: mob_read_db: drop item Crushed_Pumpkin not found in monster 1926
[Warning]: mob_read_db: drop item Worn_Fabric not found in monster 1927
[Warning]: mob_read_db: drop item Token_Bag not found in monster 2033

-Renewal

**Comment by Jedzkie** [comment]
Confirmed, currently fixing it. Thanks!

**Comment by dastgir** [comment]
They are commented in item_db2

**Comment by Kenpachi2k13** [comment]
Fixed in 02546a4 and d983a27.
`close();`
