### ISSUE TITLE
clif.c Memory leaks found

### ISSUE THREAD

**Issue by byunjaeil** [HerculesWS/Hercules#831]
./athena-start stop
(i'm using clean clif.c)

Memory manager: Memory leaks found at 2015/10/28 09h53m49s (Exported rev '').
0001 : clif.c line 15494 size 230 address 0x0x7f35ff9e9d6c
0002 : clif.c line 15494 size 230 address 0x0x7f35ff9e9e7c
0003 : clif.c line 15494 size 230 address 0x0x7f35ff9e9f8c
0004 : clif.c line 15494 size 230 address 0x0x7f35ff9ea09c
0005 : clif.c line 15494 size 230 address 0x0x7f35ff9ea1ac
0006 : clif.c line 15494 size 230 address 0x0x7f35ff9ea2bc
[Warning]: Memory manager: Memory leaks found and fixed.

**Comment by Jedzkie** [comment]
@4144 @MishimaHaruna
