### ISSUE TITLE
Songs

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#835]
Original Topic: http://herc.ws/board/tracker/issue-8639-songs/?gopid=25023#entry25023

I've noticed something wrong with Clown/Gypsy songs (example Poem of Bragi) are not updated continuously.

Example: A Wizard casts a skill ( storm gust ) with Poem of Bragi effect inside Clown skill diameter. When the clown RECAST the song the wizard will stop after the 20 secs effect of the last casted Poem of Bragi. What should happen is.. it should be continuous the Wizard shouldn't have delays even after the song was re-casted.

Inshort:
In official if you are inside the area of Clown, it is impossible for you to run out of Poem of Bragi effect,. after 20 secs Poem of Bragi effect should just update again and again.

Bug Video:
https://youtu.be/R8mIAv_TRL8

**Comment by kyeme** [comment]
@csnv 
I've already tested this on iRO wherein it automatically updates the song whenever you are inside of the song range.

**Comment by kyeme** [comment]
@csnv

**Comment by csnv** [comment]
@kyeme Can you check apple of Idun? I need to know if it's refreshed with fully HP or if it's resetted back to normal and get's healed again.

A video would be wonderful, as I want to check if the automatic heal works when it's reduced effect.

**Comment by kyeme** [comment]
I can say, it refreshed with fully HP
here https://youtu.be/YyW3hpFLJ6o

**Comment by csnv** [comment]
@kyeme you need to step outside of the song effect and then come back. Otherwise you never reset the effect, you stay with the large effect of 3 minutes.
Please check it with fully HP, so we can know if the max HP get's reseted after the first 20 second effect runs out, and with empty HP to know if the song heals the target while still in the 20 second effect.
Thanks a lot!

**Comment by kyeme** [comment]
Ok, I will check tomorrow. :D

**Comment by kyeme** [comment]
@csnv  
Video: https://www.youtube.com/watch?v=VvqlaYCRmSc&feature=youtu.be

From you previous reply on bug tracker, yes you are correct, there's a 3 seconds delay on Iduns Apple. Sorry I didn't notice it.

**Comment by csnv** [comment]
Great, thanks a lot Kyeme.

So, it goes as following:
Every song has a 20 second effect as soon as you step out of it, while you cannot override the effect with another song.
But as soon as the song effect expires, the new song effect will be applied except for Apple of Idun which has a 3 second delay.
Also, apple of idun keeps healing even if the status change of the last song is still alive.

And also apple of idun has a bug that it keeps healing endlessly, gotcha.
