### ISSUE TITLE
Constants in item_db.conf

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#838]
I just noticed that if there is a typo in "Script: <" ">" part (example: "Script:<" getitem Empty_Bottles,100; ">, it doesn't read by the server, unless I use it. If i use @reloaditemdb or restart the server, there's no error in console If i have a misspelled words.

Thanks

**Comment by dastgir** [comment]
Yes, because constant and player variable are same, so it assumes that it's a player variable... And when you use it, server actually processes the value , so that time it catches the error.

This is design flaw, which is discussed many times.

**Comment by MishimaHaruna** [comment]
And, I'd like to point out, any attempts to fix this flaw have been boycotted by the community and developers.

**Comment by AnnieRuru** [comment]
why not just use the "" symbol ?
```
{
	Id: 12004
	AegisName: "Arrow_Container"
	Name: "Quiver"
	Type: 2
	Buy: 2
	Weight: 250
	BuyingStore: true
	Script: <" getitem "Arrow",500; dispbottom "1"; ">
},
```
it works
I added dispbottom to confirmed no error thrown and the dispbottom shows properly

**Comment by dastgir** [comment]
The problem is typo on constants are not recognized...
getitem Red_Potion,1;
and
getitem RedPotion,1;

2nd one is missing _ and it don't show the error, because server assumes its a player variable...

**Comment by MishimaHaruna** [comment]
Bu using the "", you not only slow down the script (strings are slower to process and use more memory), but don't improve the situation at all. A typo in a string is just like a typo in a constant, it can't be detected at parse time.
