### ISSUE TITLE
mob_db2.conf inherit "Mode" issue

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#843]
mob_db2.conf

{
	Id: 1002
	Inherit: True
	SpriteName: "PORING"
	Mode: {
	}
},

settings above will remove all mode of PORING

and please see my suggestion master @MishimaHaruna  http://herc.ws/board/topic/10913-mob-db-file-structure-overhaul/?p=64694

**Comment by MishimaHaruna** [comment]
Yes, this is intended, similarly to the Drops case.
It'll need similar add/remove semantics in order to allow altering the list instead of replacing.
