### ISSUE TITLE
OSX 10.11.1 error with gcc5 + sanitize.

### ISSUE THREAD

**Issue by Smokexyz** [HerculesWS/Hercules#852]
`
Hercules xyz$ ==3997==AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_malloc_mac.cc:103 "((!asan_init_is_running)) != (0)" (0x0, 0x0)
    <empty stack>

==3998==AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_malloc_mac.cc:103 "((!asan_init_is_running)) != (0)" (0x0, 0x0)
    <empty stack>

==3999==AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_malloc_mac.cc:103 "((!asan_init_is_running)) != (0)" (0x0, 0x0)
    <empty stack>
`

When starting ./athena-start with a clean checkout having compiled with GCC5 and flag --enable-sanitize=full on OSX 10.11.1.

**Comment by MishimaHaruna** [comment]
I can reproduce this (OS X 10.11.1, GCC 5.2).
It seems like a bug in the sanitizer, described here by the llvm developers: https://llvm.org/bugs/show_bug.cgi?id=13794

I don't believe there's anything we can do until they fix it
