### ISSUE TITLE
Skill is blocked until the server restart

### ISSUE THREAD

**Issue by pengc2010** [HerculesWS/Hercules#854]
Hi, I have encountered some timer_do_delete error, when this happens to skill_blockpc_end, the player cannot use a certain skill (have seen it on RA_ARROWSTROM and SR_RAISINGDRAGON) until the server restart.
I have no idea how to reproduce it, it just randomly happens once per a few days, and there will be an error message like

```
timer_do_delete error: function mismatch 00606501 (unit_walktoxy_timer) != 00603824 (skill_blockpc_end)
```

My version is d2e3acb.
Since it is really rare, happens once ~ twice per week with tens of online players, so I cannot test it myself with the latest version, but I have not seen any changes related to this issue recently.
This problem makes the player very frustrated, and I have to restart the whole server to help him/her. 
Any idea about how to solve or track this issue will be greatly appreciated.

**Comment by emistry** [comment]
you can temporary fix it using @cddebug command.

**Comment by dastgir** [comment]
Maybe something related to http://herc.ws/board/tracker/issue-8402-serious-problem-with-skill-that-cant-be-cast-or-used/

**Comment by pengc2010** [comment]
thx for this info, it is really helpful

**Comment by Kenpachi2k13** [comment]
Can't be reproduced and no new info or reports for years.
`close();`
