### ISSUE TITLE
Pre-re loading miss lots of files

### ISSUE THREAD

**Issue by Nyliar** [HerculesWS/Hercules#859]
Hello,

I've upgraded my server to the last version two days ago. From now, there was lots and lots of error in official scripts loading.
Actually, some files are missing, but are still read in pre-re mob. Here's a list I've been able to set up, hoping it doesn't miss any:

pre-re/item_db.txt
pre-re/mob_db.txt
pre-re/job_db1.txt
pet_db.txt

**Comment by dastgir** [comment]
They don't read item/mob .txt
They read item_db.conf , mob_db.conf

It's suggested that you do clean rebuild..
If it still exist, it may be due to some incorrect merge while you were updating the server.
