### ISSUE TITLE
Pre-Renewal: When Talking to NPC

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#862]
On Ofifcial pre-renewal you can use usable items and self skills (Energy Coat, Sight etc..) while talking to NPC.

**Comment by dastgir** [comment]
Kinda buggy behavior?
I can't think any good reason to allow it...

**Comment by kyeme** [comment]
For example, in a situation that you accidentally clicked a npc and there are mobs, in pre-renewal official you can still use pots

**Comment by MishimaHaruna** [comment]
I agree with kyeme, that's a more than valid reason to allow it (and I don't believe it'd break anything).

**Comment by AnisotropicDefixation** [comment]
On a side note, would it be possible to block interaction with any other NPC as long as you are already in a dialogue or have a buying/selling window/cash shop open? Maybe have it as a .conf option.

**Comment by AnnieRuru** [comment]
https://github.com/HerculesWS/Hercules/blob/master/doc/script_commands.txt#L5042
we already allow to change equipment during npc dialog (allow by default)
so just need to add 'allow to use pots and self buff skills'
or ... maybe a bitmask

**Comment by Aeromesi** [comment]
+1 for this

**Comment by kyeme** [comment]
@Kenpachi2k13

**Comment by Kenpachi2k13** [comment]
Are all usable item types affected by this or only specific ones? (For example only items of type `IT_HEALING`.)

**Comment by kyeme** [comment]
All items including IT_HEALING, IT_USABLE, IT_DELAYCONSUME, IT_CASH are allowed to use.
https://github.com/rathena/rathena/commit/be2428b83200756316adc54bf58b208268ba35c6

**Comment by Kenpachi2k13** [comment]
Okay, I'll have a look at it.
