### ISSUE TITLE
long variable name cause server crash

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#865]
while I was amazed by the long variable name `@Queue_Destination_Map$` <- *yes it still works*
so I test this
```
prontera,159,184,5	script	asdakjdshas	1_F_MARIA,{
	.@1234567890123456789012345678901234567890$ = "ok";
	dispbottom .@1234567890123456789012345678901234567890$; // it works ?!?!?!
//	a1234567890123456789012345678901234567890$ = "ok"; // server crash if uncomment
	end;
OnInit:
	$a1234567890123456789012345678901234567890$ = "ok"; // after this line load once, then comment this line and @reloadscript will server crash
	announce $a1234567890123456789012345678901234567890$, bc_all;
	end;
}
```
it looks like everywhere,
documentation and wiki told us that variable names cannot longer than 23 characters
but it seems the server doesn't mind how long the variable name ... 

BUT
the problem comes when it needs to save into sql
currently almost all fields use `VARCHAR(32)`, which is 32 characters long
unlike what we have been told all the time

so the server crash when we save the variable name length more than 32
```
[SQL]: DB error - Data too long for column 'key' at row 1
[Debug]: at d:\ragnarok\hercules\src\char\inter.c:588 - REPLACE INTO `char_reg_str_db` (`char_id`,`key`,`index`,`value`) VALUES ('150000','a1234567890123456789012345678901234567890$','0','ok')
```

so, fix all variable name length at 23 or 32 ?

**Comment by MishimaHaruna** [comment]
I think that on the long term (maybe as part of the script language syntax/variables revamp), we should consider removing this length restriction. For now, throwing an error is good.
