### ISSUE TITLE
Item usable with delayed consumption (Type 11)

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#888]
On Official the number of item should be lessen upon clicking or using it on the target . However when clicking it, the number of item doesnt change until it is successfuly casted on the target.

Bug tracker: http://herc.ws/board/tracker/issue-5966-item-usable-with-delayed-consumption-item-scroll/?gopid=10219#entry10219

**Comment by kyeme** [comment]
Type:
	0	Healing item.
	2	Usable item.
	3	Etc item
	4	Weapon
	5	Armor/Garment/Boots/Headgear
	6	Card
	7	Pet egg
	8	Pet equipment
	10	Ammo (Arrows/Bullets/etc)
	11	Usable with delayed consumption (item is lost from inventory
		after selecting a target, for use with skills and pet lures)
	18	Another delayed consume that requires user confirmation before
		using item.

Type 11 is very wrong, on official it will consume immediately

**Comment by AnnieRuru** [comment]
you do know that type 11 has been abused by our custom scripts as a infinite usage right ?

I remember long time ago there was a discussion (I forgot which forum already)
that a fix is done on the itemskill/pet script command rather than fix the itemtype itself

**Comment by hemagx** [comment]
@kyeme it's official behavior but does it actually hurt to keep it this safe way ? i remember losing a lot because this non-logical behavior, unless it break someone it would be better keep it this way.

**Comment by AnnieRuru** [comment]
we can always use battle config to set an unofficial way, like
itemskill_on_consumption: yes
yes = official behaviour
no = stay like this

**Comment by hemagx** [comment]
For this one i'm not sure if it's just how kRO wanted it or just bug and they felt lazy to fix, however we have so many stuff that are based on the logical stuff with no option to do the aegis way.
anyway, though we're emulator i believe we should follow "Logic" as long as it doesn't do a real break for the game.

**Comment by kyeme** [comment]
Agree with AnnieRuu, make a configuration so we can choose official or unofficial way.

**Comment by hemagx** [comment]
after checking item 12622 i don't think this change is possible, I'm going to check how Aegis do it.

**Comment by hemagx** [comment]
After testing, seems like we've understood item type 11 in wrong way, it doesn't mean to delayed usage but Restricted usage.
those items are not supposed to be used while siting/mounting, however the reason some of the type 11 are delayed after consume it seem to be hard coded but doesn't seem to be the main reasons of type 11.
to keep item after usage you should use KeepAfterUse option instead of type 11.

**Comment by hemagx** [comment]
@MishimaHaruna please check this.

**Comment by xBeret** [comment]
Bump.

**Comment by kyeme** [comment]
Fixed @ https://github.com/HerculesWS/Hercules/pull/2616
Thanks~
