### ISSUE TITLE
Hp displayed when dead

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#889]
On iro/euro the client display 1 hp when you have died (on rathena -> 0 hp).

Image on left, with rathena ; offi on right

![image](https://cloud.githubusercontent.com/assets/4656578/11316087/41e0b504-9039-11e5-9abe-6ba0f27cd10b.png)

Credits to @Atemo 
https://github.com/rathena/rathena/issues/758

**Comment by kyeme** [comment]
Novice:
Official iRO: Half of your HP
Hercules:  0 HP

![novice hp](https://cloud.githubusercontent.com/assets/4656578/11316140/52753556-903a-11e5-9b41-a761b901569c.jpg)

**Comment by AnnieRuru** [comment]
I remember this bug very clearly,
when the player die, the player should show the hp when re-spawn

that's why it is 1 for non-novice job (respawn as 1 hp)
and hp as 1/2 max hp for novice (respawn as 1/2 max hp)
