### ISSUE TITLE
Warnig when compiling in visual studio 2015

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#890]
The emulator is with warning when compiling in visual studio 2015.

    Ex: channel.c line 633 initializing': conversion from 'size_t' to 'unsigned char', possible loss of data
        clif.c line 1932 '=': conversion from 'size_t' to 'uint16', possible loss of data
         

There are more warning, but I will not list all here.

**Comment by MishimaHaruna** [comment]
Related: #673
