### ISSUE TITLE
Arrow Crafting / Produce Item 

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#891]
I cant be sure if its my db but these are the issue im getting:
Pre-Renewal compile
latest git

1. When using Arrow Craft, a list of available material is there but when u chose, it dont give the arrow and material was not reduced.
2. All forge weapons and potion become unnamed.

Can u confirm?

**Comment by ossi0110** [comment]
Hello rlacson7

are you using the Extended Vending Plugin from @dastgir ?

if yes Disable it and recompile your server and test it


the plugin got some bugs  what blocks skills and do weird stuff

**Comment by tlacson7** [comment]
You are exactly right. Im using that Extended Vending Plugin. I will try removing it and chk. THANK YOU FOR THAT INFO :)

**Comment by tlacson7** [comment]
Confirmed. It was Extended Vending System. Its okay now. Thanks again

**Comment by tlacson7** [comment]
That costume system also prevent produce item to fetch make name. Fyi

**Comment by dastgir** [comment]
Thats custom plugins, please report at respective plugin thread to get its bug solved. Thanks.
