### ISSUE TITLE
trying to write readparam allow constant

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#899]
about readparam to allow reading Hp, BaseJob etc
https://github.com/rathena/rathena/commit/e112fc1c500feb5c705fdb5990f142c507fd384a
I found this on rathena github, so I attempt to pull request but ...
http://upaste.me/90fe22128a9016ec3
it seems that hercules script engine will recognize BaseJob and so on as C_INT, no C_PARAM
so the way rathena did it cannot simply copy paste into hercules, hercules parse them as C_INT

again, I give up on this one .... maybe someone else can figure out how
```
prontera,155,185,5	script	kjsdfsjdf	1_F_MARIA,{
	dispbottom readparam(abcd) +" "+ abcd;
	dispbottom readparam(abcde) +" "+ abcde;
	dispbottom readparam(BaseJob) +" "+ BaseJob;
	dispbottom readparam(bLuk) +" "+ bLuk;
//	dispbottom readparam(BankVault) +" "+ BaseJob;
//	dispbottom readparam(BaseJob) +" "+ BaseJob;
//	dispbottom readparam(bLuk) +" "+ bLuk;
//	dispbottom readparam(bCritical) +" "+ bCritical;
//	dispbottom readparam(bAtk) +" "+ bAtk;
//	dispbottom readparam(bAtk2) +" "+ bAtk2;
//	dispbottom readparam(BankVault) +" "+ BankVault;
	end;
OnPCDieEvent:
	dispbottom readparam(Hp) +" "+ Hp;
}
```

**Comment by dastgir** [comment]
Why do we need readparam when they can be accessed directly?

**Comment by AnnieRuru** [comment]
because readparam can be use to read other player's stat without using attachrid

**Comment by dastgir** [comment]
We should state it works for bLuk-bStr , I see no reason for adding optional char name(Yes , we don't have it),
We don't have additional params, because rA recently gone through adding those char_id/name optional parameter to many commands..

Or maybe we can add char_Id/account_id field to some important commands...

**Comment by AnnieRuru** [comment]
> We don't have additional params, because rA recently gone through adding those char_id/name optional parameter to many commands..

personally, I think we should do that too
if you up for it, I can pull request to mimic them

... erm, char_id ? we should go for account_id instead

.... hmm ... but Haru recently say its no good to add them ... in this pull request ... #858

**Comment by hemagx** [comment]
I don't know Haru point yet. But what I can see is if so many commands in
script got account id value it well do loop for each command to get the sd
while attachrid does it once

**Comment by AnnieRuru** [comment]
yeah exactly
`script->rid2sd(st)` should be faster than `map->nick2sd` or `map->id2sd`

**Comment by MishimaHaruna** [comment]
My point against those optional parameters is that commands already have a mess of optional parameters, and we'd end up with a very awkward syntax, different for each command.
Another point against adding it is that checking whether the command failed because the target character if offline or doesn't exist, is going to get very ugly (leading to poor scripting practice of just skipping on the check).

I'd like to address this with the next-generation script syntax I've been wanting to implement for a while (but unfortunately, I don't have an ETA yet, it's still at a very early stage of design). My goal was to have 'objects', such as characters, mobs, NPCs, etc, exposed to the script engine through variables, so that you could do something like this (pseudocode, not the actual syntax):

```
var $me = getpc("Haru");
if ($me != null) {
    mes("Hello, I'm a " + $me.Name + ". Nice to meet you.");
    mes("My level is "+ $me.BaseLevel +" / "+ $me.JobLevel);
} else {
    mes("Have you seen a Haru?");
}
```

Now, to get back to the current issue, things like `readparam(Hp)` can't work, because `Hp` is replaced with its value (the player's HP) before being passed to `readparam` What you're looking for is a constant that we don't have (not sure why), but if we had it, it'd be `bHp` (similarly to `bAgi`, `bStr`, etc, to match the `enum status_point_types` defined in map.h and used by the `pc_readparam` function). I haven't tested it, but I'd be surprised if `readparam(5)` wouldn't work. Of course, it shouldn't be used with a hardcoded 5, since the enum may change at any time, and your scripts would break in a very painful way.

**Comment by AnnieRuru** [comment]
readparam(5) would work, but its not a good practice to use number, better use a constant
and constant doesn't work with readparam in hercules except bStr-bLuk

Haru, I think you missed the point,
in `script.c`, when it parse the `db/const.txt` constant file,
it did read the type 0 as C_INT
and the type 1 as C_PARAM
but when I am trying to read the data of script_getdata(st,2),
it return C_INT as opposed to the one rathena can do
it should return C_PARAM if it is Hp, MaxHp, BaseExp ... with `reference_toparam(data)`

**Comment by dastgir** [comment]
Because Hp is variable too? So it gives preference to variable first? Thus its not read as param?

(Both have same name)

**Comment by MishimaHaruna** [comment]
I'll verify why it returns C_INT, I'm not really sure. My concern is, do we want that behavior? It sounds like it's more of an issue than a benefit.

One would expect that the three below are equivalent (and they are):
```
readparam(bStr);
readparam(.@param = bStr);
.@param = bStr; readparam(.@param);
```

But these wouldn't:
```
readparam(Hp);
readparam(.@param = Hp);
.@param = Hp; readparam(.@param);
```

I'd rather add a separate set of `bHp`, `bSp`, `bWeight`, `bWhatever` constants.

**Comment by AnnieRuru** [comment]
>I'd rather add a separate set of bHp, bSp, bWeight, bWhatever constants.

that is what I'm trying to say
IF ...  the Hp, MaxHp, BaseLevel can be identify as C_PARAM
then we don't have to declare another sets of constants
just use them, they can return the value from the constant file by using `data->u.num`

I link again how rathena did it
https://github.com/rathena/rathena/commit/e112fc1c500feb5c705fdb5990f142c507fd384a
though I already link it on my 1st post

rathena script engine can detect Hp, MaxHp, BaseLevel as C_NAME
but hercules script engine detect them as C_INT
and C_INT is the same as using numbers, which is pointless

**Comment by MishimaHaruna** [comment]
Well, the implementation is trivial:

```
diff --git a/npc/MOTD.txt b/npc/MOTD.txt
index 99bd8c7..b3638ac 100644
--- a/npc/MOTD.txt
+++ b/npc/MOTD.txt
@@ -12,4 +12,13 @@
 -	script	HerculesMOTD	-1,{
 	message strcharinfo(0),"Welcome to Hercules! Enjoy! Please report any bugs you find.";
 	end;
+OnInit:
+	debugmes "a:" + Hp; // Well, works.
+	debugmes "b:" + readparam(Hp); // Would work (but do we want this?)
+	debugmes "d:" + readparam((Hp)); // Would still work, semantically very incorrect since '(Hp)' is an expression, and I'd expect it to be evaluated into an int before being passed -- right now it doesn't happen, but that's because of another bug.
+	debugmes "e:" + readparam(1+Hp-1); // Wouldn't of course work (expression result should be equivalent to the one above, but it isn't).
+	debugmes "f:" + readparam /* Hello */ (Hp); // Would work, but very awkward. '(Hp)' isn't an expression here.
+	debugmes "g:" + readparam(.@bHp = Hp); // Wouldn't work.
+	debugmes "h:" + readparam(.@foo = 5); // Already works. And if bHp was defined as a constant, it'd look like: readparam(.@foo = bHp);
+	debugmes "i:" + readparam(.@foo); // Already works.
 }
diff --git a/src/map/script.c b/src/map/script.c
index cfc7ed0..e8fdf41 100644
--- a/src/map/script.c
+++ b/src/map/script.c
@@ -2620,10 +2620,12 @@ struct script_code* parse_script(const char *src,const char *file,int line,int o
 TBL_PC *script_rid2sd(struct script_state *st) {
 	TBL_PC *sd;
 	if( !( sd = map->id2sd(st->rid) ) ) {
-		ShowError("script_rid2sd: fatal error ! player not attached!\n");
-		script->reportfunc(st);
-		script->reportsrc(st);
-		st->state = END;
+		//ShowError("script_rid2sd: fatal error ! player not attached!\n");
+		//script->reportfunc(st);
+		//script->reportsrc(st);
+		//st->state = END;
+		sd = pc->get_dummy_sd();
+		sd->battle_status.hp = 4500; // Hello, I'm a hack because Haru doesn't feel like starting a RO client right now :)
 	}
 	return sd;
 }
@@ -7706,13 +7709,21 @@ BUILDIN(disableitemuse)
 BUILDIN(readparam) {
 	int type;
 	TBL_PC *sd;
+	struct script_data *data = script_getdata(st, 2);
 
-	type=script_getnum(st,2);
 	if( script_hasdata(st,3) )
 		sd=map->nick2sd(script_getstr(st,3));
 	else
 		sd=script->rid2sd(st);
 
+	script_reportdata(data);
+
+	if (data_isreference(data) && reference_toparam(data)) {
+		type = reference_getparamtype(data);
+	} else {
+		type = script_getnum(st, 2);
+	}
+
 	if(sd==NULL) {
 		script_pushint(st,-1);
 		return true;
```

But using those same constants would be semantically wrong... See the snippets in my previous post, those inconsistencies would be really awkward to me.

So the question stands: **do we want this**? I'd say we'd better define bXXX constants for the stuff we need. Constant-like parameters will go away with the next generation syntax, if they become properties of the character object, so I wouldn't invest in them now, at all.

**Comment by AnnieRuru** [comment]
ok I just knew about the `script_reportdata` function

the result will tell a thousand words
exact same script
```
prontera,155,185,5	script	kjsdfsjdf	1_F_MARIA,{
	dispbottom readparam(BaseJob) +"";
	dispbottom readparam(bLuk) +"";
	dispbottom readparam(20) +"";
	dispbottom readparam(Hp) +"";
}
```
and put the `script_reportdata(data)` command in both emulator inside BUILDIN(readparam)

in hercules
[Debug]: Data: number value=20
[Debug]: Data: number value=18
[Debug]: Data: number value=20
https://github.com/AnnieRuru/customs/blob/master/screenshots/screenRuru_Server013.jpg

in rathena
[Debug]: Data: param name='BaseJob' type=119
[Debug]: Data: number value=18
[Debug]: Data: number value=20
https://github.com/AnnieRuru/customs/blob/master/screenshots/screenRuru_Server007.jpg
______________________________________________

so ...
1. fix the parameter to return C_NAME in hercules, so it can return data->type correctly

2. fix the documentation so that readparam only accept bStr-bLuk

3. or declare a new bunch of bWhatever constants

**Comment by AnnieRuru** [comment]
ok Haru you are right, closing this one
I found the solution
