### ISSUE TITLE
some plugin doesn't work anymore on latest GIT

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#909]
```
[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): '1e2f24a2fcb13b8a2fe06f4cc829670303760929'
[Info]: Git revision (scripts): '1e2f24a2fcb13b8a2fe06f4cc829670303760929'
[Info]: OS version: 'Windows 7 Ultimate Service Pack 1 (build 7601) [x86]'
[Info]: CPU: 'x86 CPU, Family 6, Model 23, Stepping 10 [2]'
[Info]: Compiled with Microsoft Visual C++ 2010 (v1600)
[Info]: Compile Flags: N/A
[Info]: Server supports up to '4096' concurrent connections.
[Status]: HPM: Loaded plugin 'HPMHooking' (0.2).
[Status]: HPM: Loaded plugin 'DC_DONTFORGETME' (0.0).
[Status]: HPM: Loaded plugin 'sendmail' (2.0).
[Status]: HPM: Loaded plugin 'setbgid' (1.5).
[Warning]: HPMDataCheck:movespeed: 'npc_chat_interface' size mismatch 1 != 36
[Fatal Error]: HPM:plugin_load: 'plugins/movespeed.dll' failed DataCheck, out of
 sync from the core (recompile plugin)!

Map-Server has terminated abnormally.
Restarting in 15 seconds, press Ctrl+C to cancel.
```
though I don't think there is a problem with my plugin,
all problem starts with this commit https://github.com/HerculesWS/Hercules/commit/60dc92a6f2367fe6d75b0e7e6227d4fa5baaa60b
I have to revert my hercules test server before that one, everything works fine

unless, there is something change again in recent plugin format
https://github.com/AnnieRuru/customs/blob/master/plugin/movespeed.c

@QQfoolsorellina
not really, most of my plugin that uses hook are broken

**Comment by Samuel23** [comment]
@AnnieRuru did you recompile the hook plugins?

**Comment by AnnieRuru** [comment]
of course
https://github.com/AnnieRuru/customs/blob/master/screenshots/recompile%20already.png

**Comment by AnnieRuru** [comment]
ALL right
now IF I say, src\plugin\sample.c is not working, this should be convincing right ?
```
[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): '1e2f24a2fcb13b8a2fe06f4cc829670303760929'
[Info]: Git revision (scripts): '1e2f24a2fcb13b8a2fe06f4cc829670303760929'
[Info]: OS version: 'Windows 7 Ultimate Service Pack 1 (build 7601) [x86]'
[Info]: CPU: 'x86 CPU, Family 6, Model 23, Stepping 10 [2]'
[Info]: Compiled with Microsoft Visual C++ 2010 (v1600)
[Info]: Compile Flags: N/A
[Info]: Server supports up to '4096' concurrent connections.
[Status]: HPM: Loaded plugin 'HPMHooking' (0.2).
[Fatal Error]: HPM:plugin_load: failed to load 'plugins/sample.dll' (error: The
specified module could not be found.
)!

Map-Server has terminated abnormally.
Restarting in 15 seconds, press Ctrl+C to cancel.
```

**Comment by MishimaHaruna** [comment]
The sample plugin was updated in 1e2f24a with a missing predefined macro. As such, all third party plugins will need a similar update to their VS project...  This is unfortunate, but it's pretty much the only viable way that Visual Studio allows. (unless we decide to switch to CMake to generate the VS projects, which would be a good idea, but has some drawbacks)

The problem with the sample plugin you're showing is a different issue - is the .dll there? Did the compilation fail perhaps?

**Comment by AnnieRuru** [comment]
compile success
https://github.com/AnnieRuru/customs/blob/master/screenshots/sample_compile_ok.png
it just keep crashing the server

actually you are right, there seems to be 2 different issues here
when I revert my hercules test server to this commit
https://github.com/HerculesWS/Hercules/commit/aad6eaea82053f629cbbe204aa83db5fd4b557a4
all my custom plugins load fine, but sample plugin fail
```
[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): 'aad6eaea82053f629cbbe204aa83db5fd4b557a4'
[Info]: Git revision (scripts): 'aad6eaea82053f629cbbe204aa83db5fd4b557a4'
[Info]: OS version: 'Windows 7 Ultimate Service Pack 1 (build 7601) [x86]'
[Info]: CPU: 'x86 CPU, Family 6, Model 23, Stepping 10 [2]'
[Info]: Compiled with Microsoft Visual C++ 2010 (v1600)
[Info]: Compile Flags: N/A
[Info]: Server supports up to '4096' concurrent connections.
[Status]: HPM: Loaded plugin 'HPMHooking' (0.2).
[Status]: HPM: Loaded plugin 'SC_ANYTHING' (0.1).
[Status]: HPM: Loaded plugin 'sendmail' (2.0).
[Status]: HPM: Loaded plugin 'setbgid' (1.5).
[Status]: HPM: Loaded plugin 'movespeed' (1.1).
[Status]: HPM: Loaded plugin 'fixedaspd' (1.1).
[Status]: HPM: Loaded plugin 'noitem' (1.3).
[Status]: HPM: Loaded plugin 'getmemberaid' (1.3).
[Status]: HPM: Loaded plugin 'AuraSet' (1.4a).
[Status]: HPM: Loaded plugin 'OnPCStatCalcEvent' (1.0).
[Status]: HPM: Loaded plugin 'OnPCUseSkillEvent' (1.1).
[Fatal Error]: HPM:plugin_load: failed to load 'plugins/sample.dll' (error: The
specified module could not be found.
)!

Map-Server has terminated abnormally.
Restarting in 15 seconds, press Ctrl+C to cancel.
```
.... com'on nobody load the sample.c  plugin ...

ok let's just focus on the sample.c plugin then
I try uncomment some lines in the sample.c plugin and tell you which specific line causes the error
this can take awhile

**Comment by AnnieRuru** [comment]
ahahahaha .... the default sample.c ...
yes ... it compile as plugin_sample.dll, but the server asked for sample.dll ...
so this is a ... bug ? in the `vcproj-10` folder ... maybe

after I correct the position, yeah, it can load on that older commit

but the char_server.exe and login_server.exe spam this error
`[Error]: HPM:AddHook: unknown Hooking Point 'pc->dropitem'!`
`[Error]: HPM:AddHook: unknown Hooking Point 'pc->dropitem'!`
yes it show twice

_________________________________________________________

now, on latest GIT
.... shit the sample.c is working fine on latest GIT

AHHHH !!!
the problem is when include npc.h
`#include "map/npc.h"`
add this line in sample.c, then it fail

**Comment by MishimaHaruna** [comment]
> ahahahaha .... the default sample.c ...
> yes ... it compile as plugin_sample.dll, but the server asked for sample.dll ...
> so this is a ... bug ? in the vcproj-10 folder ... maybe

Hmm indeed, we have an inconsistency here... On Windows we're adding the `plugin` prefix to the plugin dlls, while on the other platforms we don't... For the time being, to load it, you have to specify the full name in the config file (or as command line argument)... I think we're going to edit the project files to remove the `plugin-` part from the names.

The reason why it loads on the old commit is that you probably have a sample.dll in your plugins folder (not sure how it got there, the output name from the project file wasn't modified since 2013 from what I see). Try deleting all the .dll you have inside your plugins folder when you switch to an older or newer commit to test (not Hercules/src/plugins, but Hercules/plugins), and rebuilding the plugins you want to try.

---

> but the char_server.exe and login_server.exe spam this error
> [Error]: HPM:AddHook: unknown Hooking Point 'pc->dropitem'!
> [Error]: HPM:AddHook: unknown Hooking Point 'pc->dropitem'!
> yes it show twice

Yep, that's normal... it's because the sample plugin tries to hook into map-server functions without checking if it's been loaded by the map server. It's an easy fix (but even if it stays like that, it won't break anything, other than showing the error messages)

---

```
AHHHH !!!
the problem is when include npc.h
#include "map/npc.h"
add this line in sample.c, then it fail
```

That should only happen if the plugin's vcxproj doesn't have `PCRE_SUPPORT` in its PreprocessorDefinitions (I added it in commit 1e2f24a2fcb13b8a2fe06f4cc829670303760929). Can you verify that you have it?

**Comment by AnnieRuru** [comment]
>The reason why it loads on the old commit is that you probably have a sample.dll in your plugins folder (not sure how it got there, the output name from the project file wasn't modified since 2013 from what I see). Try deleting all the .dll you have inside your plugins folder when you switch to an older or newer commit to test (not Hercules/src/plugins, but Hercules/plugins), and rebuilding the plugins you want to try.

nonono, I changed the path name
I noticed in the Output File field is
`$(OutDir)$(TargetName).dll`
I changed to
`$(OutDir)\sample.dll`

this just proved nobody (on windows) has bother to load the sample.c plugin since 2013 ... until today ... hahaha
__________________________________________________
>Yep, that's normal... it's because the sample plugin tries to hook into map-server functions without checking if it's been loaded by the map server. It's an easy fix (but even if it stays like that, it won't break anything, other than showing the error messages)

normal ?? O.O
yeah the best method to fix this that I can think of, is allowing an optional argument
`addHookPre("pc->dropitem",my_pc_dropitem_pre);`
this will hook to all 3 server types
`addHookPre("pc->dropitem",my_pc_dropitem_pre, SERVER_TYPE_MAP);`
this only hook to map-server.exe
________________________________________________
>That should only happen if the plugin's vcxproj doesn't have PCRE_SUPPORT in its PreprocessorDefinitions (I added it in commit 1e2f24a). Can you verify that you have it?

I thought windows should compile PCRE by default ....
map-server has this
`WIN32;_WIN32;__WIN32;_DEBUG;PCRE_SUPPORT;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_DEPRECATE;FD_SETSIZE=4096;LIBCONFIG_STATIC;YY_USE_CONST;%(PreprocessorDefinitions)`
and plugin-HPMHooking_map has this
`_DEBUG;WIN32;_WINDOWS;_USRDLL;PCRE_SUPPORT;HPMHOOKING_MAP;%(PreprocessorDefinitions)`
yes on older commit, PCRE_SUPPORT; doesn't show up, on latest GIT it shows up

just note that, on latest git, (with all plugin not loaded) I can still play with activatepset
https://www.eathena.ws/board/index.php?showtopic=274000
```
prontera,159,183,5	script	idsfsd	1_F_MARIA,{
	end;
L_1:
	npctalk "It's a "+ $@p2$;
	end;
OnInit:
	defpattern 1, "[^:]+: (\\|\\d{2})?(cat!).$", "L_1";
	activatepset 1;
	end;
}
```
https://github.com/AnnieRuru/customs/blob/master/screenshots/screenRuru_Server017.jpg

**Comment by AnnieRuru** [comment]
found out the problem
its our windows problem

after I add PCRE_SUPPORT; to the sample.c plugin, the error is gone

**from now on, all windows should compile with PCRE_SUPPORT;**
now, have to update the wiki
http://herc.ws/wiki/Building_HPM_Plugin_for_MSVC

**Comment by AnnieRuru** [comment]
now that PCRE_SUPPORT is enable for plugin right ?
I try to resolve this topic
http://herc.ws/board/topic/4855-port-preg-match-from-rathena/
with this plugin
http://upaste.me/0c9f2215492dc4909
when compile, windows compiler show this message
```
1>------ Build started: Project: zzz, Configuration: Debug Win32 ------
2>------ Skipped Build: Project: plugin-sample, Configuration: Debug Win32 ------
2>Project not selected to build for this solution configuration 
1>  zzz.c
1>     Creating library ..\plugins\zzz.lib and object ..\plugins\zzz.exp
1>zzz.obj : error LNK2001: unresolved external symbol _libpcre
1>..\plugins\\zzz.dll : fatal error LNK1120: 1 unresolved externals
========== Build: 0 succeeded, 1 failed, 17 up-to-date, 1 skipped ==========
```
then try another method
http://upaste.me/7dcf22155a1953c44
```
1>------ Build started: Project: zzz, Configuration: Debug Win32 ------
2>------ Skipped Build: Project: plugin-sample, Configuration: Debug Win32 ------
2>Project not selected to build for this solution configuration 
1>  zzz.c
1>     Creating library ..\plugins\zzz.lib and object ..\plugins\zzz.exp
1>zzz.obj : error LNK2001: unresolved external symbol __imp__pcre_free
1>zzz.obj : error LNK2019: unresolved external symbol __imp__pcre_exec referenced in function _buildin_regexp
1>zzz.obj : error LNK2019: unresolved external symbol __imp__pcre_study referenced in function _buildin_regexp
1>zzz.obj : error LNK2019: unresolved external symbol __imp__pcre_compile referenced in function _buildin_regexp
1>..\plugins\\zzz.dll : fatal error LNK1120: 4 unresolved externals
========== Build: 0 succeeded, 1 failed, 17 up-to-date, 1 skipped ==========
```
I noticed there is no libpcre in this file
https://github.com/HerculesWS/Hercules/blob/master/src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
since the libpcre->... function is define from npc_chat.c right ?

yes, I also can't hook to npc_chat->...

**Comment by hemagx** [comment]
@AnnieRuru
as temporary solution hook pcre.lib temporary same old way before it get interfaced and use functions directly, should work untested but compile-able on windows

**Comment by AnnieRuru** [comment]
erm, I don't understand what you mean ...
can give an ~~untested~~ example ?

**Comment by hemagx** [comment]
okay so ~
seems like the compiler can't link the pcre lib, even on correct settings so i just did it like how i did it for Odin Manner before plugin support it ( Thanks to haruna for telling me how back then! ).
for MSVC :
Linker -> General -> Additional Library Directories:
 ..\3rdparty\mysql\lib;..\3rdparty\zlib\lib;..\3rdparty\pcre\lib;%(AdditionalLibraryDirectories)

Linker -> Input -> Additional Dependencies: 
put pcre.lib in it

for GCC: ( NOT SURE THIS STILL  CORRECT FOR GCC I HAVE NO LINUX
Add the follow in the end of src/plugins/makefile.in

../../plugins/manner@DLLEXT@: pluginname.c $(ALL_H)
    @echo "    CC    $<"
    @$(CC) -lpcre @DEFS@ @CFLAGS@ @CPPFLAGS@ @LDFLAGS@ @SOFLAGS@ -o $@ $<

and it should compile and you can access all functions directly 
pcre_compile, pcre_free, etc ~

**Comment by AnnieRuru** [comment]
ok then ... temporary solution then

so 2 issues remain here
1. on windows compiled as `plugin-sample.dll`, but the server ask for `sample.dll`
2. try fix that 'pc->dropitem' hook error message with `if ( SERVER_TYPE == SERVER_TYPE_MAP )` stuff

**Comment by MishimaHaruna** [comment]
1. Is there any known reason why we have the `plugin-` prefix on all plugin dlls on windows? If not, I'll just drop it.

2. Done in d1458c6

**Comment by AnnieRuru** [comment]
nope, no problem at all
so just change the `plugin-sample` into `sample`, since it makes thought it doesn't work ... for a moment
