### ISSUE TITLE
1 damage from all monsters.

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#911]
Git Version : 056541d6da7b322ee53f533205aa128cc2841f93 ( Date: 22 November 2015 )

![Image of Yaktocat](http://i.imgur.com/G5xLPiN.gif)

btw, I noticed that every 2 levels will increase the def/mdef. 
![Image of Yaktocat](http://i.imgur.com/sogx1TR.png)

From what I recall, i didnt apply any plugins or any custom src mod.
the only changes I made would probably just custom script commands and the client date.

**Comment by AnnieRuru** [comment]
1 damage from all monster, can't reproduce, maybe you have OnPCStatCalcEvent ? lol, just asking
custom patches should be detectable .. tortoisegit should show the red !

but that every 2 levels increase def, every 4 levels increase mdef, I also having it
maybe its official ?

**Comment by dastgir** [comment]
I talked to emistry, he said he have no custom script/mod installed... So its really weird :x

**Comment by AnnieRuru** [comment]
in the screenshot I saw, that rune knight learned asura strike, storm gust, fire bolt,
try also revert the conf setting ?

**Comment by emistry** [comment]
even normal group also same =D
and nope, i didnt use OnPCStatCalcEvent.

**Comment by AnnieRuru** [comment]
then try dual client
login 2 characters, when `@pvpon` did they do 1 damage to each other too ?

if only receive 1 damage from monsters, maybe your mob_db.conf parse incorrectly ...

**Comment by Jedzkie** [comment]
Maybe it affect the gm all skills?

**Comment by Emistry** [comment]
doesnt seem like happen when updated to latest client, i guess it's safe to assume the bug no longer exist or failed to reproduce.
