### ISSUE TITLE
SECURE NPC TIMEOUT

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#916]
@MishimaHaruna @4144 @AnnieRuru @dastgir this system has been disabled due to known bugs, can someone check this and do a fix so that we can use this system again? Thanks!

http://herc.ws/board/tracker/issue-8048-secure-npc/

http://herc.ws/board/tracker/issue-7695-secure-npctimeout-bug/

**Comment by AnnieRuru** [comment]
http://herc.ws/board/tracker/issue-8048-secure-npc/
this bug is confirmed

http://herc.ws/board/tracker/issue-7695-secure-npctimeout-bug/
cannot reproduce this one with my own stylist npc

**Comment by Jedzkie** [comment]
@MishimaHaruna @4144

**Comment by hemagx** [comment]
purr :3 *scratch the guy who assigned me*
but okay, will check it.

**Comment by Jedzkie** [comment]
@hemagx :)

**Comment by hemagx** [comment]
@Jedzkie please check second bug, if not produce able, tried here with no luck.

**Comment by Jedzkie** [comment]
@hemagx cannot reproduce the 2nd bug now.

**Comment by AnnieRuru** [comment]
I just test again, while it works
`#define NPC_SECURE_TIMEOUT_INPUT 9`
with this script
```
prontera,150,180,4	script	asdf	1_F_MARIA,{
	mes "asdadas";
	next;
	input .@asdasd$;
	mes "asdada";
	close;
}
```
1. click the npc
2. click next;
3. when the input box show up, wait 10 seconds
4. the npc box got a close button pops up, click on it
5. now the npc chat box gone, input something
`[Debug]: npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not asdf (id=1100000
09).`
though I think this debug message can be ignore though
since its completely valid code

**Comment by hemagx** [comment]
@AnnieRuru  can you please open another issue for this bug?

**Comment by AnnieRuru** [comment]
its not really a bug, just some annoying debug message
if you don't feel like fixing it, can leave it out though
since it is a completely valid code

**Comment by hemagx** [comment]
it is bug, the server should ignore this request completely and not even debug it.
going to check it.

**Comment by dastgir** [comment]
client wants mes before input, isn't it?

**Comment by AnnieRuru** [comment]
correct
because step 4 already close the npc dialog, but the input box is still there

**Comment by hemagx** [comment]
okay i tried to see if Aegis sends anything else while doing this, well i can't see anything, also i don't think remove the debug message is good idea either.
if anyone got other ideas, please reopen.

**Comment by bgamez23** [comment]
please re-open this. the old bug has been resurrected after removing it. Ind put it on purpose to avoid a bug for npc without dialog box.

bug report.
http://herc.ws/board/tracker/issue-7272-secure-npctimeout-bug-for-those-npc-who-have-no-dialog-window/

https://github.com/HerculesWS/Hercules/commit/adc2e6ea9778e34945722f8f7d89e10cd9a4b972

**Comment by hemagx** [comment]
@bgamez23 okay, i will check the packets Aegis sends and see if we miss something, if not, then i believe ind workaround was wrong, cause i'm sure "AEGIS doesn't clean the script this way" or maybe it should be sent in certain cases.

**Comment by bgamez23** [comment]
okay no problem with that.
