### ISSUE TITLE
[Guild] Guildmaster can't change his own TAX exp

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#932]
Git hash: bb3afb0340c2046192c6e601b3ea450b68d41d3b (20151210)
Mode: Renewal
Client date: 20150513
Console error:
![guildddddd](https://cloud.githubusercontent.com/assets/10024221/11746361/6f03d4a4-a050-11e5-9e7f-fecc96f8c31f.jpg)

**Comment by 4144** [comment]
You not build your server on latest sources.
You have latest sources in local directory, but server binaries is not based on it

**Comment by 4144** [comment]
After rebuild you may trigger other issue.
This issue fixed in latest commit. This mean you should pull sources from git.

**Comment by zackdreaver** [comment]
uh ok,
maybe i forgot to compile with latest source,
brb checking

**Comment by zackdreaver** [comment]
Ok, it seems fixed in latest commit
thanks @4144
