### ISSUE TITLE
Close not move

### ISSUE THREAD

**Issue by playgron** [HerculesWS/Hercules#938]
Click any NPC > Click the Cancel button > Pick any npc that have close; menu > Pick Close / Exit menu that using close; } > You cannot move

Is this a bug ? I can explain it in video if you guys don't understand.

**Comment by Emistry** [comment]
if you display the menu without display any npc dialog.
Example:
```
select( "menu 1","menu 2" );
close;
```
 you will get stucked.

Example:
```
mes "any message";
select( "menu 1","menu 2" );
close;
```
 you will not get stucked.

**Comment by playgron** [comment]
Thank you Emistry for the explanation I tried and it's work.

Problem solved how to close this thread? my first time using github.

**Comment by dastgir** [comment]
Closed.

**Comment by Emistry** [comment]
but i think it could be label as bug too...

what if i want to create just a menu for players to select without provide any npc dialogs beforehand?

**Comment by 4144** [comment]
This is client bug
