### ISSUE TITLE
Tombstone of Lord Of Death

### ISSUE THREAD

**Issue by will21** [HerculesWS/Hercules#94]
The tombstone of Lord Of Death in niflheim map is not working. I already set the monster.conf in mvp_tomb_enabled to yes. Please confirm. Thank you

**Comment by Ragno1** [comment]
This may not be the best reference, but people on Warp Portal forums said Lord of the Dead doesn't leave a Gravestone:

https://forums.warpportal.com/index.php?/topic/128929-missing-mvp-tomb/#entry1480193

From the comments, it seems to be the same for all mvps with special summon by a npc, not naturally spawned.

**Comment by MishimaHaruna** [comment]
Ok, thank you very much! We can then close this for the time being.
