### ISSUE TITLE
item#5574 Well-Chewed Pencil [0] 

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#948]
A popular snack while taking tests. It makes one look more studious but, it's days may be numbered if it stays in somebody's mouth any longer.
HIT + 3.
[+ Model Training Hat]
DEX + 2, DEF + 2.

Item Script:
{ bonus bdex,2; bonus bHitRate,3; },{},{}

I think this need to be change

**Comment by Jedzkie** [comment]
Fixed in https://github.com/HerculesWS/Hercules/commit/718fc08805d6d91eb732b6a51472e8ae78aa1892

we are not following Ratemyserver's descriptions and item scripts. Dex +2 is in kRO database.

**Comment by zackdreaver** [comment]
DEX +2 in kRO database? really?
http://ro.gnjoy.com/guide/runemidgarts/itemview.asp?itemSeq=2&ID=5574

**Comment by Jedzkie** [comment]
Aegis @zackdreaver 
item Pencil_In_Mouth
	event OnStartEquip:
		AddExtParam User VAR_DEXAMOUNT 2
		AddExtParam User VAR_HITSUCCESSVALUE 3
	return
	event OnFinishEquip:
		SubExtParam User VAR_DEXAMOUNT 2
		SubExtParam User VAR_HITSUCCESSVALUE 3
	return

**Comment by Jedzkie** [comment]
@hemagx if @zackdreaver is right, please correct me. I'm just following aegis's special.sc.

**Comment by zackdreaver** [comment]
that's euRO aegis db

**Comment by hemagx** [comment]
@Jedzkie please correct it to follow
Combo item :
	Pencil_In_Mouth
	Cap_Of_Concentration

Combo Effect :
		AddExtParam User VAR_DEXAMOUNT 2
		AddExtParam User VAR_ITEMDEFPOWER 2

//kRO
item Pencil_In_Mouth
	event OnStartEquip:
		AddExtParam User VAR_HITSUCCESSVALUE 3
	return
	event OnFinishEquip:
		SubExtParam User VAR_HITSUCCESSVALUE 3
	return

**Comment by Jedzkie** [comment]
Fixed in https://github.com/HerculesWS/Hercules/commit/ba7302ea729060c76348256c6ad10309b9c094da
