### ISSUE TITLE
 Fire Pillar

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#970]
Official: Fire Pillar not required gemstone
Please confirm thanks :)
Source: pRO Sakray, iRO, RWC Test Server

**Comment by AnisotropicDefixation** [comment]
Damage formula is also wrong and it shouldn't be attackable.

**Comment by MishimaHaruna** [comment]
It used to require them (pretty sure I saw plenty of vids on youtube), when was it changed?

**Comment by zackdreaver** [comment]
the gemstone requirement only on pre-renewal : 
"1 Blue Gemstone for LV 6-10"

**Comment by kyeme** [comment]
My source is from renewal :[

**Comment by Jedzkie** [comment]
@zackdreaver iRO wiki maybe outdated, i tried this in iRO and RWC Aegis, and there's no required gemstone to cast this skill.

**Comment by AnnieRuru** [comment]
add component database because all you have to do is edit `skill_require_db.txt` file =/
