### ISSUE TITLE
rA Merge

### ISSUE THREAD

**Issue by dastgir** [HerculesWS/Hercules#972]
https://github.com/rathena/rathena/commit/5fe81455b07caca715f05f824e1c3300197c2dc1

Just putting it here, if someone wishes to do it before I could(probably few days later)

**Comment by dastgir** [comment]
https://github.com/rathena/rathena/compare/b53eacd7b24e...22a1cc017415

**Comment by Ragno1** [comment]
Maybe this was solved on a7d49b6?
