### ISSUE TITLE
Prevent Logout Official Behavior

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#981]
Hi,

In Official servers, if you login to the game, you can character select immediately, unless no one attacks you or hit you.

In Herc, if you login to the game, you must wait 10 secs in able to character select.

Reference Video:

https://www.youtube.com/watch?v=nfMnMxO3PXk&feature=youtu.be

**Comment by kyeme** [comment]
I can confirm this :dancers:

**Comment by Emistry** [comment]
```
// Prevent logout of players after being hit for how long (in ms, 0 disables)?
prevent_logout: 10000
```
it's based on this settings
https://github.com/HerculesWS/Hercules/blob/master/conf/battle/player.conf#L114-L115

**Comment by kyeme** [comment]
Base on what I've tested on Official Server, when you've login, you're able to logout IF you have waited for 2secs before you do the "Character Select". But if you havent waited for atleast 2secs and immediately clicked Character Select on Game Option, youre not be able to logout.

(I'm not sure for that 2secs interval I'm a bit lag on iRO when ive tested this. So kindly help if what is the exact interval. Thanks)

**Comment by Jedzkie** [comment]
This feature is now implemented. Closing this issue.
