### ISSUE TITLE
Wedding at 2014-10-22 Client

### ISSUE THREAD

**Issue by Legend95** [HerculesWS/Hercules#984]
Hello! I've tried to test out what seems to be the problem why i can't use wedding dress costume sprite...
I opened up itemdb under renewal folder and i found out that there's no "OnEquipScript: <" changebase Job_Wedding; ">" on item id 2338 (wedding_dress).
I tried to add that line but it doesn't work.
while using @costume wedding seems to be working fine.

Please do fix :)
Thanks and have a nice day~
More power to Hercules!

**Comment by Jedzkie** [comment]
@Legend95 is this what you talking about? https://github.com/HerculesWS/Hercules/blob/master/db/item_db2.conf#L574

**Comment by Legend95** [comment]
woah! thanks @Jedzkie written 3 days ago and I never knew about this :)
