### ISSUE TITLE
changecharsex bug

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#985]
Related: http://herc.ws/board/tracker/issue-8504-changesex/?gopid=24468#entry24468

Can anyone confirm this?

Step 1: make gypsy/clown and use the command 'changecharsex'
Step 2: Login again and you will get the error "first character of profession is more than .. ..."
![4](https://cloud.githubusercontent.com/assets/4656578/11893081/9243b238-a5a8-11e5-8c9d-b593ec013cbb.jpg)

Im using 2015-05-13 client and 2014 10 22

**Comment by kyeme** [comment]
@MishimaHaruna @dastgir

**Comment by kyeme** [comment]
Hmmm tested on clean sql and I did not get this error. Why :(

**Comment by kyeme** [comment]
~ * UP * ~

**Comment by kyeme** [comment]
Can anyone confirm this? Thank you

**Comment by kyeme** [comment]
@MishimaHaruna

**Comment by MishimaHaruna** [comment]
When you say two accounts, you mean two accounts or two characters in the same account? (how can two separate accounts have a similar interaction effect otherwise?)

**Comment by kyeme** [comment]
You need 2 accounts to reproduce the bug.

Account # 1: make Clown, use changecharsex
Account # 2: make Clown, use changecharsex <--- boom error

**Comment by kyeme** [comment]
@MishimaHaruna master

**Comment by kyeme** [comment]
~Up~

**Comment by Kenpachi2k13** [comment]
This happens when `@changecharsex` is used before the new job is saved to the database. Steps to reproduce:

1. Create character.
2. Use `@job 4020` to change job to Clown.
3. Use `@changecharsex`.

Now `char_change_sex_sub()` is called with `class` 0 (Novice) and thus can't change the job to Gypsy.
