### ISSUE TITLE
Storm Gust Crash

### ISSUE THREAD

**Issue by playgron** [HerculesWS/Hercules#986]
Whenever player use storm gust on beelzebub monster on my server map server will crashed.

Any help? I just opened the server now having trouble with map crash. with SG skill

And the error:
[Error]: Server received crash signal! Attempting to save all online characters! Segmentation fault

**Comment by Jedzkie** [comment]
What versiion of herc? What settings? Do you have custom changes in your source code?

**Comment by dastgir** [comment]
Provide coredump? That would help alot ...

**Comment by playgron** [comment]
I just tried go to orc dungeon 02 , using skill SG which 1 hit kill monster , server didnt crash, I lower my int so the SG can hit like 2-3 times , the server disconnected. I just downloaded hercules version like 7 days ago im not sure what the version is. about 7 days ago.

can you tell me how to use coredump? thank you.

**Comment by Jedzkie** [comment]
Prenewal or renewal?

**Comment by playgron** [comment]
prerenewal

**Comment by dastgir** [comment]
Coredump(gdb) guide:http://herc.ws/wiki/GDB

**Comment by playgron** [comment]
im still trying to use the gdb please be patient im new to gdb :s 
And while im installing gdb , then after 5 minutes , this error actually shows up idk what this is , but didnt crash the server
![hm](https://cloud.githubusercontent.com/assets/6842560/11897494/c28380f8-a5c2-11e5-82c1-d7c651675591.png)

**Comment by playgron** [comment]
Server keep crashing again now even without SG skills , I dont have any modification inside , weird.

**Comment by dastgir** [comment]
The error you showed up above, was fixed a week ago, please update to have that error fixed

**Comment by playgron** [comment]
okay im gonna update everything and try again

**Comment by playgron** [comment]
I found the problem. I add this to my status.c

case SC_FREEZE:
			//Undead are immune to Freeze/Stone
			if (undead_flag && !(flag&SCFLAG_NOAVOID))
				return 0;
			//CUSTOM
                        // Players that have luk above or equal 260 are immune to Freeze
			if( type == SC_FREEZE && sd->battle_status.luk >= 260 )
				return 0;
			// Players that have luk above or equal 230 have freeze timer reduced to 2s
			if( type == SC_FREEZE && sd->battle_status.luk >= 230 && tick > 3000 )
				tick = 3000; // is in ms
			if( type == SC_FREEZE && sd->battle_status.luk >= 200 && sd->battle_status.luk < 230 && tick > 5000 )
				tick = 5000;
			if( type == SC_FREEZE && sd->battle_status.luk >= 170 && sd->battle_status.luk < 200 && tick > 7000 )
				tick = 7000;
			if( type == SC_FREEZE && sd->battle_status.luk >= 140 && sd->battle_status.luk < 170 && tick > 9000 )
				tick = 9000;
			if( type == SC_FREEZE && sd->battle_status.luk >= 100 && sd->battle_status.luk < 140 && tick > 13000 )
				tick = 13000;


Can u help me fixing that ? making the map crash

**Comment by theultramage** [comment]
My guess is that your src edit is assuming that 'sd' exists, and does not check for null. In case the thing being frozen is a monster. Enclosing the whole thing in a ```if( sd != NULL ) {``` block should do the trick.
