### ISSUE TITLE
SP_ATK_RATE and SP_ADDRACE issues

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#988]
SP_ATK_RATE doesn't do anything.
SP_ADDRACE doesn't work with RC_All, RC_Boss and RC_NonBoss.

Could be related to the recent RC implementation update?

**Comment by dastgir** [comment]
https://github.com/HerculesWS/Hercules/pull/971
See comments of that, pretty much the calculations are messed up,
For 10% increase in db,
Renewal does 1% extra damage while pre-renewal does 20% damage
@Michieru @malufett @MishimaHaruna

**Comment by AnisotropicDefixation** [comment]
Could be the case for SP_ATK_RATE but SP_ADDRACE works fine for specified races so masks are still messed up.

**Comment by malufett** [comment]
with SP_ATK_RATE I don't see any problem..
![image](https://cloud.githubusercontent.com/assets/3251821/11914182/a5816e88-a6b3-11e5-99fb-238900dbf1b9.png)
![image](https://cloud.githubusercontent.com/assets/3251821/11914183/b6ff3d02-a6b3-11e5-97a2-c87a8082d185.png)
Take note SP_ATK_RATE only increase weapon atk damage...

**Comment by malufett** [comment]
also SP_ADD_RACE is working fine..
![image](https://cloud.githubusercontent.com/assets/3251821/11914221/1804cca6-a6b5-11e5-85d2-eaaee0086e43.png)

**Comment by kyeme** [comment]
@malufett welcome back master!!!

**Comment by dastgir** [comment]
So that's weapon atk :x

**Comment by malufett** [comment]
@kyeme 
lols..actually @Jedzkie bugging me about this..so I a pay time and visit..:D
anyway soon I'll be..
@dastgir 
yep..:)
always take into consideration in RE thare are always 3 factor in physical damage..base, weapon and equipment attack...unlike in PRE its just all the summation of factor before applying mods..
