### ISSUE TITLE
[PRE] Refine not showing + error

### ISSUE THREAD

**Issue by playgron** [HerculesWS/Hercules#990]
Refine from blacksmith not showing and + , only "Upgrade has been completed successfully" or "Upgrade has failed" , and weapon +2 can destroyed.

Please fix this

**Comment by playgron** [comment]
WeaponLevel4: {
	StatsPerLevel: 700
	RandomBonusStartLevel: 5
	RandomBonusValue: 1300
	Rates: {
		Lv5: {
			Chance: 60
		}
		Lv6: {
			Chance: 40
		}
		Lv7: {
			Chance: 40
		}
		Lv8: {
			Chance: 20
		}
		Lv9: {
			Chance: 20
		}
		Lv10: {
			Chance: 10
		}
	}
}

But when my player trying to refine using blacksmith refine skill , weapon from +1 can be destroyed. no safe. please fix

**Comment by playgron** [comment]
Youtube video for more explanation: https://youtu.be/4Y5Av3AKN9s

**Comment by Jedzkie** [comment]
report 1:

That is Aegis Behavior,

![screenmichiro003](https://cloud.githubusercontent.com/assets/4826387/11913830/53543070-a6ac-11e5-9164-de0a43d04b4e.jpg)

If the item fails, it shows like this, not Upgrade has failed. We need change it in future updates

![screenmichiro004](https://cloud.githubusercontent.com/assets/4826387/11913834/6e6f8a1c-a6ac-11e5-95c6-2684c28bc5ae.jpg)

report 2:

maybe your job level is 1? Please give us more information.

**Comment by Jedzkie** [comment]
@hemagx :D :D :D :D :D :D :D :D :D :+1:

**Comment by playgron** [comment]
@Jedzkie Job level was 42 , so we have to be max job lvl to be able to safe refine ? 

and for the report 1 I was hoping the blacksmith skill everytime you use it , it shows the weapon refine +.

**Comment by Jedzkie** [comment]
That behavior is from eathena, we here in hercules are following  official behavior.

**Comment by playgron** [comment]
@Jedzkie thanks , closed
