### ISSUE TITLE
Monster Rare Drop Announcement

### ISSUE THREAD

**Issue by MishimaHaruna** [HerculesWS/Hercules#994]
Originally reported by @kyeme 

Related to http://herc.ws/board/tracker/issue-7858-monster-rare-drop-announcement/
Related to commit 2761bb0af9ddfa8bd14cefa9b6e1b33b2940e7be

The linked commit hardcodes some item IDs into the source. Those values should be instead read from a configuration/db file.

Rather than adding a separate configuration file, I suggest that we add a field to the Item Database.

**Comment by hemagx** [comment]
@MishimaHaruna thank you for opening issue, gosh almost forgot it.
